### PR TITLE
format pipelinerun_test.go

### PR DESCRIPTION
**Pull request by jbpratt**
# Changes

/kind cleanup

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [x] [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Release notes block below has been filled in or deleted (only if no user facing changes)

# Release Notes

```release-note
NONE
```

this will make it a bit easier to continue work on #4610

reproduce these changes with:

`gofmt -w pkg/reconciler/pipelinerun/pipelinerun_test.go`

Signed-off-by: jbpratt <jbpratt78@gmail.com>

### CODE REVIEW

**Comment by afrittoli** [comment]
I wonder why this was not picked up by the usual build test... perhaps we run it on modified files only? @vdemeester ?

**Review by afrittoli — COMMENTED** [review]
/approve

**Comment by jbpratt** [comment]
@afrittoli @vdemeester  I'm afraid a lot of files are picked up as not formatting when executing the formatter, but I didn't want to open a PR this big :fearful: (gofmt version `v0.2.1`)
```
❯ gs
On branch main
Your branch is up to date with 'origin/main'.
nothing to commit, working tree clean
❯ gofmt -w .
❯ gs
On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
1	modified:   cmd/entrypoint/runner_windows.go
2	modified:   cmd/entrypoint/subcommands/cp.go
3	modified:   cmd/entrypoint/subcommands/cp_test.go
4	modified:   cmd/entrypoint/subcommands/decode_script_test.go
5	modified:   cmd/entrypoint/subcommands/step_init.go
6	modified:   cmd/entrypoint/subcommands/subcommands_test.go
7	modified:   cmd/entrypoint/waiter_test.go
8	modified:   cmd/workingdirinit/main.go
9	modified:   hack/tools.go
10	modified:   pkg/apis/pipeline/v1alpha1/param_types_test.go
11	modified:   pkg/apis/pipeline/v1alpha1/pipeline_conversion_test.go
12	modified:   pkg/apis/pipeline/v1alpha1/pipeline_types.go
13	modified:   pkg/apis/pipeline/v1alpha1/pipelinerun_defaults_test.go
14	modified:   pkg/apis/pipeline/v1alpha1/pipelinerun_types_test.go
15	modified:   pkg/apis/pipeline/v1alpha1/pipelinerun_validation_test.go
16	modified:   pkg/apis/pipeline/v1alpha1/run_types_test.go
17	modified:   pkg/apis/pipeline/v1alpha1/task_validation.go
18	modified:   pkg/apis/pipeline/v1alpha1/taskrun_validation_test.go
19	modified:   pkg/apis/pipeline/v1alpha1/workspace_validation_test.go
20	modified:   pkg/apis/pipeline/v1beta1/implicit_params_test.go
21	modified:   pkg/apis/pipeline/v1beta1/openapi_generated.go
22	modified:   pkg/apis/pipeline/v1beta1/param_context.go
23	modified:   pkg/apis/pipeline/v1beta1/pipeline_types_test.go
24	modified:   pkg/apis/pipeline/v1beta1/pipeline_validation_test.go
25	modified:   pkg/apis/pipeline/v1beta1/pipelinerun_types_test.go
26	modified:   pkg/apis/pipeline/v1beta1/pipelinerun_validation_test.go
27	modified:   pkg/apis/pipeline/v1beta1/resource_types.go
28	modified:   pkg/apis/pipeline/v1beta1/resource_types_test.go
29	modified:   pkg/apis/pipeline/v1beta1/resultref.go
30	modified:   pkg/apis/pipeline/v1beta1/task_validation.go
31	modified:   pkg/apis/pipeline/v1beta1/task_validation_test.go
32	modified:   pkg/apis/pipeline/v1beta1/taskrun_validation_test.go
33	modified:   pkg/apis/pipeline/v1beta1/workspace_validation_test.go
34	modified:   pkg/apis/resource/v1alpha1/cluster/cluster_resource_test.go
35	modified:   pkg/apis/resource/v1alpha1/git/git_resource.go
36	modified:   pkg/apis/resource/v1alpha1/pipeline_resource_types.go
37	modified:   pkg/apis/resource/v1alpha1/pipelineresource_validation_test.go
38	modified:   pkg/apis/resource/v1alpha1/pullrequest/pull_request_resource_test.go
39	modified:   pkg/apis/resource/v1alpha1/storage/artifact_pvc.go
40	modified:   pkg/apis/resource/v1alpha1/storage/gcs.go
41	modified:   pkg/apis/validate/metadata_test.go
42	modified:   pkg/artifacts/artifact_storage_test.go
43	modified:   pkg/artifacts/artifacts_storage.go
44	modified:   pkg/credentials/dockercreds/creds.go
45	modified:   pkg/credentials/dockercreds/creds_test.go
46	modified:   pkg/credentials/gitcreds/basic.go
47	modified:   pkg/credentials/gitcreds/creds_test.go
48	modified:   pkg/credentials/gitcreds/ssh.go
49	modified:   pkg/credentials/initialize.go
50	modified:   pkg/credentials/initialize_test.go
51	modified:   pkg/entrypoint/entrypointer_test.go
52	modified:   pkg/git/git.go
53	modified:   pkg/git/git_test.go
54	modified:   pkg/internal/limitrange/transformer_test.go
55	modified:   pkg/pipelinerunmetrics/metrics.go
56	modified:   pkg/pipelinerunmetrics/metrics_test.go
57	modified:   pkg/pod/entrypoint_lookup_impl_test.go
58	modified:   pkg/pod/entrypoint_lookup_test.go
59	modified:   pkg/pod/entrypoint_test.go
60	modified:   pkg/pod/pod_test.go
61	modified:   pkg/pod/script_test.go
62	modified:   pkg/pod/status.go
63	modified:   pkg/pod/status_test.go
64	modified:   pkg/pullrequest/disk.go
65	modified:   pkg/pullrequest/disk_test.go
66	modified:   pkg/pullrequest/scm.go
67	modified:   pkg/reconciler/events/cloudevent/cloud_event_controller_test.go
68	modified:   pkg/reconciler/events/cloudevent/cloudevent_test.go
69	modified:   pkg/reconciler/events/cloudevent/interface.go
70	modified:   pkg/reconciler/events/event_test.go
71	modified:   pkg/reconciler/pipeline/dag/dag_test.go
72	modified:   pkg/reconciler/pipelinerun/affinity_assistant.go
73	modified:   pkg/reconciler/pipelinerun/pipelinerun.go
74	modified:   pkg/reconciler/pipelinerun/pipelinerun_test.go
75	modified:   pkg/reconciler/pipelinerun/resources/apply.go
76	modified:   pkg/reconciler/pipelinerun/resources/apply_test.go
77	modified:   pkg/reconciler/pipelinerun/resources/conditionresolution.go
78	modified:   pkg/reconciler/pipelinerun/resources/conditionresolution_test.go
79	modified:   pkg/reconciler/pipelinerun/resources/input_output_steps_test.go
80	modified:   pkg/reconciler/pipelinerun/resources/pipelineref_test.go
81	modified:   pkg/reconciler/pipelinerun/resources/pipelinerunresolution.go
82	modified:   pkg/reconciler/pipelinerun/resources/pipelinerunresolution_test.go
83	modified:   pkg/reconciler/pipelinerun/resources/pipelinerunstate_test.go
84	modified:   pkg/reconciler/pipelinerun/resources/pipelinespec_test.go
85	modified:   pkg/reconciler/pipelinerun/resources/resultrefresolution_test.go
86	modified:   pkg/reconciler/pipelinerun/resources/validate_params_test.go
87	modified:   pkg/reconciler/run/run_test.go
88	modified:   pkg/reconciler/taskrun/resources/apply.go
89	modified:   pkg/reconciler/taskrun/resources/apply_test.go
90	modified:   pkg/reconciler/taskrun/resources/image_exporter.go
91	modified:   pkg/reconciler/taskrun/resources/input_resource_test.go
92	modified:   pkg/reconciler/taskrun/resources/output_resource.go
93	modified:   pkg/reconciler/taskrun/resources/output_resource_test.go
94	modified:   pkg/reconciler/taskrun/resources/taskref_test.go
95	modified:   pkg/reconciler/taskrun/resources/taskresourceresolution.go
96	modified:   pkg/reconciler/taskrun/resources/taskresourceresolution_test.go
97	modified:   pkg/reconciler/taskrun/resources/taskspec_test.go
98	modified:   pkg/reconciler/taskrun/taskrun_test.go
99	modified:   pkg/reconciler/taskrun/validate_resources.go
100	modified:   pkg/reconciler/volumeclaim/pvchandler_test.go
101	modified:   pkg/taskrunmetrics/metrics.go
102	modified:   pkg/taskrunmetrics/metrics_test.go
103	modified:   pkg/termination/write.go
104	modified:   pkg/workspace/apply_test.go
105	modified:   pkg/workspace/validate_test.go
106	modified:   test/artifact_bucket_test.go
107	modified:   test/cancel_test.go
108	modified:   test/cluster_resource_test.go
109	modified:   test/conformance_test.go
110	modified:   test/controller_test.go
111	modified:   test/custom_task_test.go
112	modified:   test/dag_test.go
113	modified:   test/duplicate_test.go
114	modified:   test/embed_test.go
115	modified:   test/entrypoint_test.go
116	modified:   test/examples_test.go
117	modified:   test/git_checkout_test.go
118	modified:   test/helm_task_test.go
119	modified:   test/hermetic_taskrun_test.go
120	modified:   test/ignore_step_error_test.go
121	modified:   test/init_test.go
122	modified:   test/kaniko_task_test.go
123	modified:   test/ko_test.go
124	modified:   test/multiarch_utils.go
125	modified:   test/path_filtering.go
126	modified:   test/path_filtering_test.go
127	modified:   test/pipelinefinally_test.go
128	modified:   test/pipelinerun_test.go
129	modified:   test/pullrequest/e2e_test.go
130	modified:   test/registry_test.go
131	modified:   test/remote.go
132	modified:   test/retry_test.go
133	modified:   test/secret.go
134	modified:   test/serviceaccount_test.go
135	modified:   test/start_time_test.go
136	modified:   test/status_test.go
137	modified:   test/taskrun_test.go
138	modified:   test/tektonbundles_test.go
139	modified:   test/timeout_test.go
140	modified:   test/v1alpha1/artifact_bucket_test.go
141	modified:   test/v1alpha1/cancel_test.go
142	modified:   test/v1alpha1/cluster_resource_test.go
143	modified:   test/v1alpha1/duplicate_test.go
144	modified:   test/v1alpha1/embed_test.go
145	modified:   test/v1alpha1/entrypoint_test.go
146	modified:   test/v1alpha1/git_checkout_test.go
147	modified:   test/v1alpha1/init_test.go
148	modified:   test/v1alpha1/kaniko_task_test.go
149	modified:   test/v1alpha1/pipelinerun_test.go
150	modified:   test/v1alpha1/registry_test.go
151	modified:   test/v1alpha1/retry_test.go
152	modified:   test/v1alpha1/secret.go
153	modified:   test/v1alpha1/sidecar_test.go
154	modified:   test/v1alpha1/start_time_test.go
155	modified:   test/v1alpha1/status_test.go
156	modified:   test/v1alpha1/taskrun_test.go
157	modified:   test/v1alpha1/timeout_test.go
158	modified:   test/v1alpha1/wait_example_test.go
159	modified:   test/v1alpha1/wait_test.go
160	modified:   test/v1alpha1/workingdir_test.go
161	modified:   test/v1alpha1/workspace_test.go
162	modified:   test/wait_example_test.go
163	modified:   test/windows_script_test.go
164	modified:   test/windows_test.go
165	modified:   test/workingdir_test.go
166	modified:   test/workspace_test.go
167	modified:   third_party/github.com/hashicorp/golang-lru/simplelru/lru_interface.go
168	modified:   tools/tools.go
```

**Comment by vdemeester** [comment]
@jbpratt which version of go/gofmt are you using ? the only `diff` I get running `gofmt` is the `//go:build !ignore_autogenerated` because of the new go build tag format. 
But yes, we do run `gofmt` only on changed files, because we did run it once for all before enabling it.

**Comment by afrittoli** [comment]
> @afrittoli @vdemeester I'm afraid a lot of files are picked up as not formatted when executing the formatter, but I didn't want to open a PR this big 😨 (gofmt version `v0.2.1`)

Uhm, we do run `gofmt` on every PR so perhaps a different version of `gofmt` or `golang` changed the default?
We should only make this kind of changes if they are enforced by CI... I thought it was only this file that maybe was missed, but if everything would be changed then we need to see if we want this change or not?

**Comment by jbpratt** [comment]
@vdemeester @afrittoli okay maybe this is just an issue we will see when bumping to to `1.18`? I know we are still running latest 1.17 for the tekton projects.

```
pipeline main [$!]
❯ go version
go version go1.18 linux/amd64

pipeline main [$!]
❯ gofmt --version
v0.2.1
```

**Comment by jbpratt** [comment]
And yes, to your point @afrittoli if this doesn't line up with CI then we can drop it and I can manage for now :smiley:

**Comment by vdemeester** [comment]
@jbpratt where is your `gofmt` coming from ? 

```
$ gofmt -h
usage: gofmt [flags] [path ...]
  -cpuprofile string
        write cpu profile to this file
  -d    display diffs instead of rewriting files
  -e    report all errors (not just the first 10 on different lines)
  -l    list files whose formatting differs from gofmt's
  -r string
        rewrite rule (e.g., 'a[b:len(a)] -> a[b:]')
  -s    simplify code
  -w    write result to (source) file instead of stdout
```

The CI is using the `gofmt` binary shipped with the go version (aka [this one](https://pkg.go.dev/cmd/gofmt)), and it doesn't have a `--version` flag.

**Comment by jbpratt** [comment]
Maybe I'm losing my mind, I think I am, I'm sorry I don't want you guys to go on a wild goose chase due to formatting. Oh god, I am, I'm so sorry, let's close this up. I'm using [`gofumpt`](https://github.com/mvdan/gofumpt) and could have swore I unset things. My sincere apologies :crying_cat_face:

**Comment by vdemeester** [comment]
> Maybe I'm losing my mind, I think I am, I'm sorry I don't want you guys to go on a wild goose chase due to formatting. Oh god, I am, I'm so sorry, let's close this up. I'm using [`gofumpt`](https://github.com/mvdan/gofumpt) and could have swore I unset things. My sincere apologies crying_cat_face

No worries 😛 the mystery is solved 👼🏼

**Pull request closed without merging**
