### PR TITLE
Add @lbernick to pipeline approvers list

### PR DESCRIPTION
**Pull request by dibyom**
# Changes
Lee was already added as a Pipelines maintainer in https://github.com/tektoncd/community/pull/694
This PR updates the Pipelines OWNERS file to reflect that

/kind misc

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [ ] [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [ ] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [ ] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [ ] Release notes block below has been filled in
(if there are no user facing changes, use release note "NONE")

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by jerop — APPROVED** [review]
Welcome @lbernick 🎉

**Review by afrittoli — COMMENTED** [review]
/lgtm

**Pull request merged**
