### PR TITLE
Add Image attribute to StepState and SidecarState

### LINKED ISSUE #6970: Improve ImageID
### Feature request

A [ContainerStatus](https://pkg.go.dev/k8s.io/api/core/v1#ContainerStatus) struct contains the attributes `Image` and `ImageID`. Their description is somewhat vague:
```
// Image is the name of container image that the container is running.
// The container image may not match the image used in the PodSpec,
// as it may have been resolved by the runtime.
// More info: https://kubernetes.io/docs/concepts/containers/images.
Image [string](https://pkg.go.dev/builtin#string) `json:"image" protobuf:"bytes,6,opt,name=image"`
// ImageID is the image ID of the container's image. The image ID may not
// match the image ID of the image used in the PodSpec, as it may have been
// resolved by the runtime.
ImageID [string](https://pkg.go.dev/builtin#string) `json:"imageID" protobuf:"bytes,7,opt,name=imageID"`
```

Tekton reports the value of `ImageID` in [StepState](https://github.com/tektoncd/pipeline/blob/82a405a1abf44afc8c1c58387285749af86cee1b/pkg/pod/status.go#L236) and [SideCar](https://github.com/tektoncd/pipeline/blob/82a405a1abf44afc8c1c58387285749af86cee1b/pkg/pod/status.go#L249).

In some cases the registry/repo reported in `ContainerStatus.ImageID` is different than the registry/repo reported in `ContainerStatus.Image`. [OCPBUGS-8428](https://issues.redhat.com/browse/OCPBUGS-8428) contains a reproducer. (It's an OpenShift issue, but the underlying behavior comes from CRI-O). TL;DR: If the image was previously pulled on the node by a different image reference, the registry/repo of that image reference may get reported in ImageID.

The value of `ContainerStatus.Image` contains the right registry/repo, but may contain a tag instead of a digest. The value of `ContainerStatus.ImageID` contains the right digest, but may contains the wrong registry/repo.

I propose Tekton computes the value of `StepState.ImageID` and `SideCar.ImageID` by leveraging the information on both `ContainerStatus.ImageID` and `ContainerStatus.Image`.

### Use case

I want to write a policy that evaluates the SLSA Provenance generated by Tekton Chains to allow/disallow usage of certain registries in Task Steps. Today, this policy is nondeterministic as the registry/repo value is affected by the runtime state of the node.

### PR DESCRIPTION
**Pull request by lcarva**
# Changes

This change exposes the `ContainerStatus.Image` attribute to `StepState` and `SidecarState`. Previously, the only information about the container image was the `ContainerStatus.ImageID` attribute. This, however, may not always contain a valid image reference. For example, cri-o may use an internal ID instead. Conversely, the `ContainerStatus.Image` attribute will contain the image reference provided when creating the Pod.

Resolves #6970

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) if any changes are user facing, including updates to minimum requirements e.g. Kubernetes version bumps
- [x] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [x] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings). See some examples of [good release notes](https://github.com/tektoncd/community/blob/main/standards.md#good-release-notes).
- [x] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
v1.StepState and v1.SidecarState structs now include the Image attribute which is populated from ContainerStatus.ImageID
```

### CODE REVIEW

**Comment by lcarva** [comment]
Not sure if this needs a doc update. I didn't find anything for the existing `ImageID` attribute.

**Review by khrm — COMMENTED** [review]
I think you forgot to run hack scripts.

**Comment by khrm** [comment]
`[update-codegen.sh](https://github.com/tektoncd/pipeline/blob/main/hack/update-codegen.sh)` Running this resolve build issues.

**Comment by lcarva** [comment]
I'm gonna hold off on this for now. I'm seeing `Image` having unexpected values when using a `kind` cluster.

**Pull request closed without merging**
