### PR TITLE
[TEP-0137] Rename customrun package

### PR DESCRIPTION
**Pull request by afrittoli**
# Dependencies:

- [x] #6883

Once dependencies are merged, the PR will contain 1 commit only

# Changes

The pkg/reconciler/customrun package contains a controller that
today sends cloudevents for CustomRuns. In the context of TEP-0137,
this controller will be repurposed to send events for all resources,
so the current name does not make sense anymore.

Renaming the package to "notifications", because the "events" and
"cloudevents" names are already used elsewhere and we don't want
a mass API rename for this. We might consolidate the code further
as a follow-up. The new name is also more future-proof, as the
controller may in future handle other kinds of non-cloudevents
type of notifications.

When renaming I realised that the customrun controller was being
started as part of the main controller as well as an independent
one. This PR fixes that bug as well.

Signed-off-by: Andrea Frittoli <andrea.frittoli@uk.ibm.com>

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [x] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) if any changes are user facing, including updates to minimum requirements e.g. Kubernetes version bumps
- [x] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [x] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings). See some examples of [good release notes](https://github.com/tektoncd/community/blob/main/standards.md#good-release-notes).
- [x] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
The `CustomRun` events controller has been moved to the `pkg/reconciler/notifications` package.
```

/kind misc

### CODE REVIEW

**Review by lbernick — APPROVED** [review]

**Review by wlynch — COMMENTED** [review]
/lgtm

One question though - would this break downstream customrun implementations? Should we leave behind a simple package that type aliases to the new package?

If this is truly only for cloudevent notifications, you may also want to add a `doc.go` with some documentation calling this out.

**Comment by afrittoli** [comment]
> /lgtm
> 
> One question though - would this break downstream customrun implementations? Should we leave behind a simple package that type aliases to the new package?
> 
> If this is truly only for cloudevent notifications, you may also want to add a `doc.go` with some documentation calling this out.

Thanks @wlynch - it looks like the un-approve didn't work, so I'll address your comments as a follow-up.
The package is exclusively used to provide the ability to send cloud events for `CustomRuns`, it's not something that custom run controller implementors would use. 

If you prefer I can introduce an alias; in https://github.com/tektoncd/pipeline/pull/6889 however I started restructuring that package in preparation for "TEP-0137", so I'm not sure an alias would be very helpful (or alternatively I will have rework that PR and the following one to keep the old methods around).

**Pull request merged**
