### PR TITLE
Move several packages into internal

### PR DESCRIPTION
**Pull request by lbernick**
# Changes
This commit moves several packages in pkg/ into pkg/internal. This reduces the Pipelines API surface by ensuring these packages can't be imported and relied on by clients, as we only intend for pkg/apis and pkg/client to be imported outside of Pipelines. Other packages that contain exported functions used outside of pkg/ will be refactored in a later commit.

/kind cleanup

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- n/a Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- n/a Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [x] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [x] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
Several packages have been moved into pkg/internal and can no longer be imported.
```

### CODE REVIEW

**Comment by lbernick** [comment]
part 1 of https://github.com/tektoncd/pipeline/issues/5679

/assign @dibyom @vdemeester @wlynch

**Review by vdemeester — CHANGES_REQUESTED** [review]
Note that today, other tektoncd component might depend on those, for example the cli, or the operator, or triggers or even chains. I think for each package we want to move we need to see if it make sense or not to be "public" (and exported) or not. 

For example, `github.com/tektoncd/pipeline/pkg/pod` is used by `results` (`tektoncd` org) in `experimental` (notifiers and task-loops) and in `buildkit-tekton` (external, in my own repositories). In `results` the code that uses it looks like : 

```go
        case pod.ReasonCouldntGetTask, pod.ReasonFailedResolution, pod.ReasonFailedValidation, pod.ReasonExceededResourceQuota, pod.ReasonExceededNodeResources, pod.ReasonCreateContainerConfigError, pod.ReasonPodCreationFailed:
                return rpb.RecordSummary_FAILURE
        case pod.ReasonPending:
                return rpb.RecordSummary_UNKNOWN
```

Those "reason" do make sense to be public, maybe in another package or not, but they are definitely useful.
In `buildkit-tekton`, the code is more "involved", for example `pod.IsContainerStep(c.Name)`, but it's still valuable to export this kind of functions. `buildkit-tekton` also uses `github.com/tektoncd/pipeline/pkg/substitution` (at least the exported ones) because it is useful to re-use (to be able to perform substitution à-la-tekton) and that package is also probably used in some custom task or resolvers I wrote. 
`github.com/tektoncd/pipeline/pkg/workspace` is used in `pipeline-in-pod` for example. `github.com/tektoncd/pipeline/pkg/list` is used in triggers, in catlin, in results, in operator, in chains, in buildkit-tekton and in some resolvers I wrote as well.

**Comment by lbernick** [comment]
Thanks for pointing this out! This change was probably a bit too hasty. Is there a good way to find out which functions are in use by other projects? (I know we can look at package importers on pkg.go.dev, but doesn't tell us which functions/consts are in use.) Maybe a good place to start would be moving the reasons out of the pod package and into apis, and make the rest of the pod package internal? Going to close this out for now.

**Comment by vdemeester** [comment]
> Is there a good way to find out which functions are in use by other projects? (I know we can look at package importers on pkg.go.dev, but doesn't tell us which functions/consts are in use.) 

Not that I know of. Looking into package importers on pkg.go.dev helps us a bit at least.

> Maybe a good place to start would be moving the reasons out of the pod package and into apis, and make the rest of the pod package internal? 

I think it's gonna be both. There is probably a lot of things that needs to move in `pkg/apis`, and some in very specific, non internal package. I think we need to investigate and look into this as time goes.

**Pull request closed without merging**
