### PR TITLE
[WIP] Remove Artifacts Package

### PR DESCRIPTION
**Pull request by JeromeJu**
# Changes
This commit cleans up the artifacts package.
It prepares for the removal storage resources to mitigate dependencies.

/kind cleanup

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [ ] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [ ] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [ ] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [ ] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [ ] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by JeromeJu** [comment]
I have been trying to cleanup the artifacts first before moving the entire chunk of storage resources.

Some questions I encountered during the cleanup:
- It feels that the output_resources paths are affected by the removal of such setup for pvc, shall we remove them along with the artifacts package?

**Comment by lbernick** [comment]
I think artifacts are probably required for the storage resource to work correctly, so removing artifacts before removing storage resources would put us in an unreleasable state.

**Comment by JeromeJu** [comment]
> I think artifacts are probably required for the storage resource to work correctly (although haven't looked into this thoroughly), so removing artifacts before removing storage resources would put us in an unreleasable state.

Thanks for the instant replies. If this is not preferred then let's remove both storage resources and artifacts in one shot.

**Comment by afrittoli** [comment]
Given that this is already a large PR, I'm not sure we should bundle it with more changes, but I agree with @lbernick that we must first delete the remaining PipelineResources and then this.

**Pull request closed without merging**
