### PR TITLE
Deprecate ClusterTasks

### LINKED ISSUE #4476: Where should we take `ClusterTasks` next?
### Feature request

We've discussed the possible future of `ClusterTasks` in our API Working Group but haven't created an issue for it yet as far as I can see. The intention for this issue is to act as the focal point for discussion around the feature, its future, and where we see it going within the context of Tekton Pipelines' other features.

### Background

`ClusterTask` is a CRD that Tekton Pipelines provides that is the cluster-scoped equivalent of a `Task`. It shares all of the same fields as a `Task` but can be referenced regardless of the namespace that a `TaskRun` is executing in. By contrast a `Task` can only be referred to by a `TaskRun` in the same namespace.

While `ClusterTask` has been part of the codebase for a long time it's unclear precisely how much use it actually sees in practice. In our own dogfooding of Tekton Pipelines we don't currently leverage the resource but it does get exercised by unit and integration testing.

There have been some requests for a cluster-scoped `Pipeline` (https://github.com/tektoncd/pipeline/issues/1876, https://github.com/tektoncd/pipeline/issues/4432) and as part of those discussions there have definitely been a number of messages in support of `ClusterTasks` too. At the same time Tekton has introduced support for Bundles (an OCI image with Tasks and Pipelines, stored in a registry) that seems to provide a lot of the same benefit as cluster-scoped Task / Pipeline resources (accessible regardless of the namespace that a TaskRun or PipelineRun is executing in). More recently we've also been making moves to expand the number of places that Tekton Pipelines can access Tasks and Pipelines from, such as git repositories.

### Next Steps

- [ ] Solicit feedback from the community on usage of `ClusterTask`
- [ ] Present the results from this feedback to the API WG
- [ ] Assess overlap of `ClusterTasks` with other features Tekton Pipelines is pursuing
- [ ] ... figure out the next next steps ...

### PR DESCRIPTION
**Pull request by lbernick**
This commit marks ClusterTasks as deprecated, planned for the next Pipelines release.
Closes #4476.

/kind misc

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [x] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- n/a Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [x] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [x] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
Action required: ClusterTasks are deprecated. Please use the cluster resolver instead.
```

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
/cc @tektoncd/core-maintainers

**Review by jerop — APPROVED** [review]

**Comment by lbernick** [comment]
Thanks Andrea!
/hold until RR PR is resolved

**Comment by lbernick** [comment]
/hold cancel
since we've promoted remote resolution to beta

**Review by jerop — COMMENTED** [review]
/lgtm

**Pull request merged**
