### PR TITLE
Bump github.com/cloudevents/sdk-go to v2.5.0

### PR DESCRIPTION
**Pull request by dlorenc**
# Changes

This updates the cloudevents dependency from v2.1.0 to v2.5.0. This is over a year
old and catches us up quite far.

There was one manual change in the cloud_event_controller_test.go file. CloudEvents
changed the string representation of an event, which our tests looked for. This
matches the change to their upstream test: github.com/cloudevents/sdk-go/pull/639.

Signed-off-by: Dan Lorenc <lorenc.d@gmail.com>

/kind cleanup

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [X] [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [X] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [X] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [X] Release notes block below has been filled in or deleted (only if no user facing changes)

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by dlorenc** [comment]
cc @n3wscott to double check the test change

**Review by n3wscott — COMMENTED** [review]
/lgtm

Sorry, there was a string change in the sdk around 2.2

**Comment by mattmoor** [comment]
Looks like you need to run `./hack/update-deps.sh` to ensure the patch to apimachinery is applied.

**Review by vdemeester — APPROVED** [review]

**Pull request merged**
