### PR TITLE
Take -version into account in the controller ☕️

### LINKED ISSUE #3338: Missing version in pod annotations
# Expected Behavior
The annotation in the pod shows the version of pipeline it was created by

# Actual Behavior

```
apiVersion: v1
kind: Pod
metadata:
  annotations:
    pipeline.tekton.dev/release: ""
```

# Steps to Reproduce the Problem

1. Install latest Tekton (v0.17.0)
2. Run a task `k create -f https://raw.githubusercontent.com/tektoncd/pipeline/master/examples/v1beta1/taskruns/task-result.yaml`

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

 ```
$ k version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-21T14:51:23Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-14T07:30:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:

```
$ tkn version
Client version: 0.12.1
Pipeline version: v0.17.0
Triggers version: v0.8.1
```

It looks like things are a bit mixed up with versions.
If I look at the deployment:
```
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: default
    app.kubernetes.io/name: controller
    app.kubernetes.io/part-of: tekton-pipelines
    app.kubernetes.io/version: v0.17.0
    pipeline.tekton.dev/release: v0.17.0
    version: v0.17.0
```

and in the pod template:
```
      labels:
        app: tekton-pipelines-controller
        app.kubernetes.io/component: controller
        app.kubernetes.io/instance: default
        app.kubernetes.io/name: controller
        app.kubernetes.io/part-of: tekton-pipelines
        app.kubernetes.io/version: v0.17.0
        pipeline.tekton.dev/release: v0.17.0
        version: v0.17.0
    spec:
      containers:
      - args:
        - -version
        - devel
```

The `version` arg is supposed to be used by the taskrun controller to set the version annotation on the taskrun and thus on the pod.

/kind bug

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

Closes #3338 

Set the `version.PipelineVersion` properly in the controller main so
that we annotate the object with the version (instead of a blank string).

Signed-off-by: Vincent Demeester <vdemeest@redhat.com>

/cc @afrittoli @pritidesai @dlorenc @sbwsg 
/kind bug

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [x] Release notes block has been filled in or deleted (only if no user facing changes)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) to build and release this image.

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md) are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes) must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS) and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes) must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS), and they must first be added [in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

# Release Notes

```release-note
Correctly set the release annotation on TaskRun based on the currently running pipeline instance version
```

### CODE REVIEW

**Review by afrittoli — COMMENTED** [review]
Nice, thank you!
/approve

**Comment by pritidesai** [comment]
build failure 😞 

```
[/home/prow/go/src/github.com/tektoncd/pipeline/test/taskrun_test.go:118:47: undeclared name: pod /home/prow/go/src/github.com/tektoncd/pipeline/test/taskrun_test.go:120:73: undeclared name: pod /home/prow/go/src/github.com/tektoncd/pipeline/test/taskrun_test.go:120:96: undeclared name: pod]"
```

**Comment by chmouel** [comment]
/lgtm

Looking Good! 🤙🏽

**Pull request merged**
