### PR TITLE
fix(substition): fix configmap and secret volume param substition

### LINKED ISSUE #3070: Variable substitution doesn't work in configmap/secret items from volume
# Expected Behavior

The variable in configmap/secret items will be substituted.

# Actual Behavior

I set the variable substition in configmap items but it didn't work, and the pod created failed since the items key and path can not found.

# Steps to Reproduce the Problem

1. Create a task with configmap volume.

# Additional Info

- Kubernetes version:

  **Output of `kubectl version`:**

   ```Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"e6503f8d8f769ace2f338794c914a96fc335df0f", GitTreeState:"clean", BuildDate:"2020-07-04T15:01:15Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"} ```

- Tekton Pipeline version:

  **Output of `tkn version` or `kubectl get pods -n tekton-pipelines -l app=tekton-pipelines-controller -o=jsonpath='{.items[0].metadata.labels.version}'`** devel from master

### PR DESCRIPTION
**Pull request by FogDong**
# Changes

fix(substition): fix configmap and secret volume param substition

Fix #3070 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [x] Release notes block has been filled in or deleted (only if no user facing changes)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) to build and release this image.

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md) are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes) must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS) and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes) must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS), and they must first be added [in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

# Release Notes
     fix(substition): fix configmap and secret volume param substition

### CODE REVIEW

**Comment by sbwsg** [comment]
This is great, thanks!  Could you also update `docs/variables.md` to include these new entries?  We have the following already:

```
| `Task` | `spec.volumes[].configmap.name` |
| `Task` | `spec.volumes[].secret.secretname` |
```

So I suggest also adding this:

```
| `Task` | `spec.volumes[].configmap.items[].key |
| `Task` | `spec.volumes[].configmap.items[].path |
| `Task` | `spec.volumes[].secret.items[].key |
| `Task` | `spec.volumes[].secret.items[].path |
```

**Comment by sbwsg** [comment]
Looks like extra spaces causing the build errors:

```
=============================
==== RUNNING BUILD TESTS ====
=============================
-------------------------------------------
---- Checking go code style with gofmt ----
-------------------------------------------
diff -u pkg/reconciler/taskrun/resources/apply_test.go.orig pkg/reconciler/taskrun/resources/apply_test.go
--- pkg/reconciler/taskrun/resources/apply_test.go.orig	2020-08-07 14:14:29.678540289 +0000
+++ pkg/reconciler/taskrun/resources/apply_test.go	2020-08-07 14:14:29.679540367 +0000
@@ -144,7 +144,7 @@
 						Name: "$(inputs.params.FOO)",
 					},
 					Items: []corev1.KeyToPath{{
-						Key: "$(inputs.params.FOO)",
+						Key:  "$(inputs.params.FOO)",
 						Path: "$(inputs.params.FOO)",
 					}},
 				},
@@ -155,7 +155,7 @@
 				Secret: &corev1.SecretVolumeSource{
 					SecretName: "$(inputs.params.FOO)",
 					Items: []corev1.KeyToPath{{
-						Key: "$(inputs.params.FOO)",
+						Key:  "$(inputs.params.FOO)",
 						Path: "$(inputs.params.FOO)",
 					}},
 				},
```

**Comment by FogDong** [comment]
@sbwsg Thank you for ur help ❤!  Still not able to open the detail page because of the bad network...😭

**Comment by FogDong** [comment]
Well I guess I have to fix the build check tomorrow, the network problem is killing me 😑

**Comment by FogDong** [comment]
PTAL @sbwsg 😉

**Pull request merged**
