### PR TITLE
Fix typo in auth.md

### PR DESCRIPTION
**Pull request by dtkachenko**
# Changes

Fixed typo in auth configuration example

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

# Release Notes

```
release-note
```

### CODE REVIEW

**Comment by vdemeester** [comment]
@dtkachenko you're gonna need to sign the CLA :pray: :angel:

**Comment by dlorenc** [comment]
> @dtkachenko you're gonna need to sign the CLA 🙏 👼

Any chance you can sign the CLA @dtkachenko ?

**Comment by dlorenc** [comment]
I'm going to close this out for now, feel free to reopen if you can sign the CLA!

**Pull request closed without merging**
