### PR TITLE
Don't install golangci-lint with curl|bash, use go install, introduce the tools folder

### PR DESCRIPTION
**Pull request by smaftoul**
# Changes

Fix for #4214

In Makfile, change the `$(BIN)/golangci-lint` target to install `golangci-lint` with `go install` rather than with `curl [...] | bash`.
As suggested in #4214, it introduces a `/tools` folder with its  `go.mod` and `go.sum` in order to track the tools.
I think, as part of another PR, we could move other tools needed to build to the same way of installing.

```
$ grep ": PACKAGE" Makefile
$(BIN)/ko: PACKAGE=github.com/google/ko
$(BIN)/ram: PACKAGE=go.sbr.pm/ram
$(BIN)/golint: PACKAGE=golang.org/x/lint/golint
$(BIN)/ineffassign: PACKAGE=github.com/gordonklaus/ineffassign
$(BIN)/staticcheck: PACKAGE=honnef.co/go/tools/cmd/staticcheck
$(BIN)/dupl: PACKAGE=github.com/mibk/dupl
$(BIN)/errcheck: PACKAGE=github.com/kisielk/errcheck
$(BIN)/goimports: PACKAGE=golang.org/x/tools/cmd/goimports
``` 

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [ ] [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [ ] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [ ] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including functionality, content, code)
- [ ] Release notes block below has been filled in or deleted (only if no user facing changes)

# Release Notes

### CODE REVIEW

**Comment by imjasonh** [comment]
This change looks good to me, if anything it makes me want to move more tooling dependencies into `tools.go` and make it more standard across the Makefile. Not that that needs to be done in this PR, but if you're interested that could be useful followup work.

**Comment by smaftoul** [comment]
@imjasonh sure, once this PR merged, I may move other tools to this go.mod , and remove the `PACKAGE=...` in the Makefile.

**Comment by nikhil-thomas** [comment]
✅ lgtm

**Review by vdemeester — APPROVED** [review]

**Comment by smaftoul** [comment]
Anything left to do here ? I'm waiting the merge to move other go tools to the same installation method.

**Comment by sbwsg** [comment]
I'm going to try closing and reopening to see if that retriggers the check-pr-has-kind-label checker.

/close

**Comment by sbwsg** [comment]
hm. at least from first glance it does not appear that closing and reopening has retriggered the label check.  @smaftoul can you rebase on latest main and force-push?  That should hopefully get things moving again 🤞

**Comment by smaftoul** [comment]
@sbwsg thanks !
I will probably start another PR to move other tools to the same installation method

**Pull request merged**
