### PR TITLE
metric type handling changed to reflect documentation

### PR DESCRIPTION
**Pull request by zeidlermicha**
# Changes
In the documentation of the metrics it is written, that one can set histogram **or** lastvalue for the type of the duration metric. This PR actually allows to set either type for taskrun and pipelinerun duration metrics. Until now it was only possible to set lastvalue for the taskrun and pipelinerun level. 

Additionally the constants inside the switch statement were changed to reflect the correct type constant for the pipelinerun duration type

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) if any changes are user facing, including updates to minimum requirements e.g. Kubernetes version bumps
- [ ] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [ ] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [ ] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including functionality, content, code)
- [ ] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [ ] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings). See some examples of [good release notes](https://github.com/tektoncd/community/blob/main/standards.md#good-release-notes).
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by khrm** [comment]
@zeidlermicha We can only set LastValue for `pipelinerun` or `taskrun` tags. It's because the histogram doesn't make sense when we use those tag. We have only one count even if we use `*run` level. If the documentation isn't clear, we should update the documentation.

In addition to using a histogram with `*run` not providing any benefits, the Prometheus backend is affected quite negatively if we use histogram + run level.

**Review by khrm — COMMENTED** [review]
@zeidlermicha We can only set LastValue for `pipelinerun` or `taskrun` tags. It's because the histogram doesn't make sense when we use those level. We have only one count even if we use *run level. If the documentation isn't clear, we should update the documentation.

In addition to using a histogram with *run not providing any benefits, the Prometheus backend is affected quite negatively if we use histogram + run level.

**Comment by jerop** [comment]
/close

@zeidlermicha thank you for the contribution

closing based on feedback from @khrm above

feel free to reopen if you revisit this work

**Pull request closed without merging**
