### PR TITLE
Use a fixed version for helm

### LINKED ISSUE #943: TestHelmDeployPipelineRun is failing "a lot"
It is either flaky or something change in the image we use that makes the test fail on all PRs

```
I0604 07:01:08.915] --- FAIL: TestHelmDeployPipelineRun (95.57s)
I0604 07:01:08.916]     init_test.go:101: Create namespace arendelle-lpdmr to deploy to
I0604 07:01:08.916]     init_test.go:113: Verify SA "default" is created in namespace "arendelle-lpdmr"
I0604 07:01:08.916]     helm_task_test.go:230: Creating tiller service account
I0604 07:01:08.916]     helm_task_test.go:286: Creating Cluster Role binding tiller-6hb2d for helm
I0604 07:01:08.917]     helm_task_test.go:286: Creating Cluster Role binding default-tiller-pj2hh for helm
I0604 07:01:08.917]     helm_task_test.go:286: Creating Cluster Role binding default-tiller-c6wwv for helm
I0604 07:01:08.917]     helm_task_test.go:62: Creating Git PipelineResource go-helloworld-git
I0604 07:01:08.917]     helm_task_test.go:67: Creating Image PipelineResource go-helloworld-image
I0604 07:01:08.917]     helm_task_test.go:72: Creating Task create-image-task
I0604 07:01:08.917]     helm_task_test.go:77: Creating Task helm-deploy-task
I0604 07:01:08.917]     helm_task_test.go:82: Creating Pipeline helm-deploy-pipeline
I0604 07:01:08.917]     helm_task_test.go:87: Creating PipelineRun helm-deploy-pipeline-run
I0604 07:01:08.918]     helm_task_test.go:94: Error waiting for PipelineRun helm-deploy-pipeline-run to finish: pipeline run helm-deploy-pipeline-run failed!
I0604 07:01:08.918]     artifact_bucket_test.go:53: build logs {"level":"warn","ts":1559631657.6882505,"logger":"fallback-logger","caller":"logging/config.go:65","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/test\" is not a valid GitHub commit ID"}
I0604 07:01:08.918]         {"level":"info","ts":1559631657.6889648,"logger":"fallback-logger","caller":"creds-init/main.go:40","msg":"Credentials initialized."}
I0604 07:01:08.918]     artifact_bucket_test.go:53: build logs {"level":"warn","ts":1559631591.789462,"logger":"fallback-logger","caller":"logging/config.go:65","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/test\" is not a valid GitHub commit ID"}
I0604 07:01:08.918]         {"level":"info","ts":1559631591.7898474,"logger":"fallback-logger","caller":"creds-init/main.go:40","msg":"Credentials initialized."}
I0604 07:01:08.918]     helm_task_test.go:104: PipelineRun execution failed; helm may or may not have been installed :(
```

/area testing

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

helm v3 being out, this test may fail because the latest image and the
behavior change. So let's be more explicit on the version.

Hopefully fixes #943

Signed-off-by: Vincent Demeester <vdemeest@redhat.com>

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ :no_good_man: ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ :no_good_man: ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by vdemeester** [comment]
> I0604 12:14:00.689] --- PASS: TestHelmDeployPipelineRun (214.57s)

:tada:

**Comment by vdemeester** [comment]
> I0604 12:20:41.965] 2019/06/04 12:20:41 main.go:312: Something went wrong: failed to prepare test environment: --provider=gke boskos failed to acquire project: resource not found

ahah damn :sweat_smile:

**Comment by chmouel** [comment]
nice one 👍

**Pull request merged**
