### PR TITLE
Add third_party/VENDOR-LICENSE file back

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

It got cleaned-out unintentionnaly :'D

cc @afrittoli @dlorenc 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ :no_good_man: ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ :no_good_man: ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by afrittoli** [comment]
+1

**Comment by abayer** [comment]
/lgtm

Yeah, that seems to vanish/get massively rewritten regularly. It's weird.

**Comment by vdemeester** [comment]
> Yeah, that seems to vanish/get massively rewritten regularly. It's weird.

`./hack/update-codegen.sh` (and/or `./hack/update-deps.sh`) does this, but I feel it removes the content before failing to re-add in some cases (I had the same problem on `NixOS`)

**Comment by bobcatfish** [comment]
silly question, but what is `third_party/VENDOR-LICENSE` for??

**Pull request merged**
