### PR TITLE
Release v0.11.x results cherry pick

### PR DESCRIPTION
**Pull request by bobcatfish**
# Changes

This PR "cherry picks" several fixes for results into the release branch:
* https://github.com/tektoncd/pipeline/pull/2471
* https://github.com/tektoncd/pipeline/pull/2393
* https://github.com/tektoncd/pipeline/pull/2354 <-- @sbwsg I ended up including this after all but it _was_ a bug so seems reasonable?

I put air quotes around cherry pick because in order to pull in the fixes without adding more features (specifically pipelineresults), I had to manually update some of the cherry picked commits and in one case create my own (if #2465 wasn't enough to teach me the value of separating refactoring from feature/bug changes then this exercise certainly was!) Because so much of this was manual, it's a bit iffy, but I feel good about our existing test coverage to make sure I didn't make anything worse. However if we don't feel good about adding this to the release, our other options I think are:

1. cherry pick WITH pipelineresults (its a pretty innocuous feature, maybe okay to just include it)
2. wait for the 0.12 release (these bugs are pretty severe imo and we want ppl to be able to actually use results to im not super happy about this one, on the other hand 0.12 should be next week) 

cc @vdemeester @othomann 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [n/a] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) to build and release this image.

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md) are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes) must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS) and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes) must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS), and they must first be added [in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

# Release Notes

```
Adds fixes for:
* Conditions and task results https://github.com/tektoncd/pipeline/issues/2336
* Mixing results and param substitution https://github.com/tektoncd/pipeline/pull/2393
* Handling results correctly in embedded specs https://github.com/tektoncd/pipeline/issues/2463
* Allowing result names to contain underscores https://github.com/tektoncd/pipeline/issues/2464

```

### CODE REVIEW

**Comment by vdemeester** [comment]
So, if I was a pain in the *** I would say, we shouldn't push feature in a bugfix release :stuck_out_tongue_closed_eyes:. If we were in a `1.x` or with a `v1` API, this would definitely be a no-go. That said, I'm kinda fine with it for now (I'm trying to find a *show-stopper* on this but… can't come up with anything).

**Comment by bobcatfish** [comment]
> So, if I was a pain in the *** I would say, we shouldn't push feature in a bugfix release 😝. 

@vdemeester which feature do you mean? (want to make sure I get this right one we are 1.0+)

I think the only potential "feature" this patch is support for results replacement in conditions - it could be argued that was a bug as well depending on how you look at it, but if that's the feature you're talking about i see what you mean. (i would have been willing to go back and try harder to removed it also, should have included that as an option 🤔 )

But if that's not what you mean, I don't think this includes any (other) features?

**Comment by vdemeester** [comment]
@bobcatfish ah lol, my bad. I thought this added a new field in the API — I made that assumption and I browse the source code too quickly to figure out that wasn't the case. 

Forget I've said anything.

**Comment by bobcatfish** [comment]
haha kk, no worries @vdemeester :D 🤣

**Pull request merged**
