### PR TITLE
Add details about deprecating feature flags `enable-custom-task` and `custom-task-version`

### PR DESCRIPTION
**Pull request by XinruZhang**
# Changes

Prior to this PR, the deprecation doc only contains the deprecation about the `v1alpha1.Run`, didn't mention related feature flag deprecation. This commit adds details about the feature flag deprecation

/kind documentation

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [x] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [ ] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [x] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [x] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
Deprecation Notice: the feature flag `custom-task-version` will be removed in release v0.47.0.
```

### CODE REVIEW

**Comment by XinruZhang** [comment]
/assign @vdemeester 
cc @abayer @jerop

**Comment by vdemeester** [comment]
Sorry, wrong button 🙀 😅

**Review by jerop — COMMENTED** [review]
/lgtm

**Pull request merged**
