### PR TITLE
Replace Pod Update() with Pod Patch() to update Pod in place

### PR DESCRIPTION
**Pull request by ywluogg**
# Changes

Replace Pod Update() with Pod Patch() to update Pod in place to solve the issue that when Pod gets updated when the entrypoint tries to update the Pod's annotations.

Closes [#3310](https://github.com/tektoncd/pipeline/issues/3310)

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [ ] Release notes block has been filled in or deleted (only if no user facing changes)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) to build and release this image.

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md) are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes) must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS) and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes) must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS), and they must first be added [in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

# Release Notes

### CODE REVIEW

**Comment by ImJasonH** [comment]
I think we can simplify this change. The patch we're trying to make is, effectively, "add the annotation `tekton.dev/ready: READY`" -- this value isn't dependent on any aspect of the Pod's current state, we're just saying "whatever the current state is, add this annotation key+value".

In that case, the patch can be expressed as:

```
[{
  "op": "add",
  "path": "/metadata/annotations/tekton.dev~1ready",
  "value":"READY"
}]'
```

(I found [this helpful SO question](https://stackoverflow.com/questions/55573724/create-a-patch-to-add-a-kubernetes-annotation) to explain the `~1` part)

Like we do with [generating the patch to cancel a TaskRun](https://github.com/tektoncd/pipeline/blob/025f57a04754902df665cec6d51c388a070a4c6c/pkg/reconciler/pipelinerun/cancel.go#L37), these patch bytes can be generated once at init, and [reused for all future patches](https://github.com/tektoncd/pipeline/blob/025f57a04754902df665cec6d51c388a070a4c6c/pkg/reconciler/pipelinerun/cancel.go#L60), along the lines of:

```go
if _, err := kubeclient.CoreV1().Pods(pod.Namespace).Patch(ctx, pod.Name, types.JSONPatchType, updateReadyPatchBytes, metav1.PatchOptions{}, ""); err != nil {
  return err
}
```

This avoids having to consider any aspect of the current state of the Pod -- you don't have to copy over existing annotations, or any Pod fields, you're just telling k8s to blindly apply this patch to the object, whatever its current state is.

**Comment by vdemeester** [comment]
@ywluogg thanks for the PR. Looks like it has been fixed by @ImJasonH in #3494, so I'll close this one.

**Pull request closed without merging**
