### PR TITLE
Remove deprecated `TaskRun.Status.ResourceResults.ResourceRef` field

### PR DESCRIPTION
**Pull request by abayer**
# Changes
See #2694.

The `TaskRun.Status.ResourceResults.ResourceRef` field was only ever used for its own `Name` field, and as part of #2694, a new field, `TaskRun.Status.ResourceResults.ResourceName` was added to replace `...ResourceRef.Name` with a more semantically appropriate field. This change finishes the work by removing the deprecated `TaskRun.Status.ResourceResults.ResourceRef`.

This has been scheduled for removal since April 2021.

/kind cleanup

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [x] [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [x] [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Release notes block below has been filled in
(if there are no user facing changes, use release note "NONE")

# Release Notes

```release-note
Removes deprecated `TaskRun.Status.ResourceResults.ResourceRef` field; use `TaskRun.Status.ResourceResults.ResourceName` instead.
```

### CODE REVIEW

**Comment by abayer** [comment]
cc @lbernick

**Review by lbernick — APPROVED** [review]
Thanks Andrew! Could you add a bit more context to the commit message and PR description (from the linked issue), stating that ResourceRef and ResourceName contain the same info but "resourceRef" doesn't make semantic sense? Also, you have a typo in the PR name (should be "deprecated")

**Review by jerop — APPROVED** [review]
@abayer this was deprecated a long time ago and is overdue for removal, but wondering if we should send out an email to tekton-dev@ and tekton-users@ about the removal in the next release just in case someone is still using it and needs to migrate off it before the next release?

**Comment by abayer** [comment]
@lbernick Done, I hope. =)

**Comment by abayer** [comment]
@lbernick @jerop Ok, should be good and ready for an lgtm, hopefully!

**Review by jerop — COMMENTED** [review]
🎉 

/lgtm

**Comment by afrittoli** [comment]
It looks like, even if not used, `resourceRef` was set in the status, and now the webhook does not allow deleting resources with a `resourceRef`:

```yaml
    request-pr-docs-reviewer-wjfgm-clone-repo:
      pipelineTaskName: clone-repo
      status:
        completionTime: "2022-07-04T08:57:17Z"
        conditions:
        - lastTransitionTime: "2022-07-04T08:57:17Z"
          message: All Steps have completed executing
          reason: Succeeded
          status: "True"
          type: Succeeded
        podName: request-pr-docs-reviewer-wjfgm-clone-repo-pod
        resourcesResult:
        - key: url
          resourceRef: {}
          value: https://github.com/tektoncd/pipeline
```

and 

```shell
$ tkn pr delete request-pr-docs-reviewer-wjfgm -n tekton-ci
Are you sure you want to delete PipelineRun(s) "request-pr-docs-reviewer-wjfgm" (y/n): y
Error: failed to delete PipelineRun "request-pr-docs-reviewer-wjfgm": admission webhook "validation.webhook.pipeline.tekton.dev" denied the request: decoding request failed: cannot decode incoming old object: json: unknown field "resourceRef"
```

I filed https://github.com/tektoncd/pipeline/issues/5317 to track the issue

**Pull request merged**
