### PR TITLE
Update v1alpha1 status types to inline fields

### LINKED ISSUE #1590: Use Knative's {Type}StatusFields Pattern
# Expected Behavior
I would like to be able to embed Tekton's Status in my own CRD (e.g., for a TaskRun).

# Actual Behavior
I have to recreate Tekton's Status type because I can't embed it due to the included `duck.Status`.

# Additional Info
Knative-Serving solves this by creating a new Type that doesn't embed the `knative.dev/pkg/apis/duck/v1beta1.Status`.

An example of it is their [`ServiceStatus`](https://github.com/knative/serving/blob/e695abb86f319abd7095bb508cebbbf5238d27dc/pkg/apis/serving/v1/service_types.go#L93)

Notice that it embeds both the `ConfigurationStatusFields` and the `RouteStatusFields`.

I would be happy to contribute towards this if this is something we want to do.

### PR DESCRIPTION
**Pull request by poy**
# Changes

Splits up the status types into two structs:

* XXXStatus
* XXXStatusFields

This first inlines both knative's duck status type and the
XXXStatusFields. The second stores all the fields that were originially
in XXXStatus. This is advantageous as downstream users can now embed a
the XXXStatusFields if their CRDs manage a Tekton object.

This pattern is demonstrated in Knative (e.g., Serving). Moving to this
pattern does not change the JSON/YAML structure in anyway, however it
does change how status objects have to be instantiated in Go.

fixes #1590

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) to build and release this image.

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md) are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes) must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS) and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes) must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS), and they must first be added [in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

# Release Notes

```
Describe any user facing changes here, or delete this block.

Examples of user facing changes:
- API changes
- Bug fixes
- Any changes in behavior

```

### CODE REVIEW

**Comment by vdemeester** [comment]
/hold
Let's merge this after 0.9.0 release (planned this week)

**Comment by ImJasonH** [comment]
/hold

This change looks good to me, but we're going to hold off on this until after the v0.9 release cut, which is next week. I'm not concerned about the breaking-ness of this change since it only affects integrators using the Go structs directly.

**Comment by poy** [comment]
@vdemeester Squashed.

**Pull request merged**
