### PR TITLE
Update to latest knative.dev/pkg

### PR DESCRIPTION
**Pull request by mattmoor**
This pulls in some code-generation changes, and I wanted to make sure it didn't break Tekton.

/kind cleanup

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [ ] [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [ ] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [ ] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [ ] Release notes block below has been filled in or deleted (only if no user facing changes)

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by mattmoor** [comment]
cc @n3wscott who reviewed the upstream change to PKG

**Comment by n3wscott** [comment]
/lgtm

This is updating the codegen from knative/pkg updates from https://github.com/knative/pkg/pull/2210.

**Comment by mattmoor** [comment]
/retest

Looks like a flake

**Pull request merged**
