### PR TITLE
Try reducing "Invalid log format" errors

### PR DESCRIPTION
**Pull request by sbwsg**
# Changes

Over in [another PR](https://github.com/tektoncd/pipeline/pull/4108) I was seeing a lot of "Invalid log format for pod" errors in the build-log on gcs, that looked to be coming from logstream.

After chatting with mattmoor it seems like the values we've got in our config-logging needed to be updated. This PR matches those values to [knative serving](https://github.com/knative/serving/blob/d0d882feafa7ba4accee9baf525cab34ac88522a/config/core/configmaps/logging.yaml#L51-L63) (updated in PR https://github.com/knative/serving/pull/10273) to see if that potentially reduces the messages.

/kind misc

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Release notes block below has been filled in or deleted (only if no user facing changes)

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by sbwsg** [comment]
Strange, I am seeing a similar thing here to #4108 : a lot of messages with form `E0806 19:57:18.814159   26295 round_tripper.go:61] CancelRequest not implemented by *genericclioptions.CommandHeaderRoundTripper`

**Comment by sbwsg** [comment]
/hold

I'll investigate those `CommandHeaderRoundTripper` messages on Monday

**Comment by sbwsg** [comment]
Possible source of the messages: https://github.com/kubernetes/client-go/blob/master/discovery/cached/disk/round_tripper.go#L54-L63

**Comment by sbwsg** [comment]
/hold cancel

The roundtripper-related error messages don't appear to be showing up anymore. 🤷

**Comment by bobcatfish** [comment]
@sbwsg  is there any source we can point at in the commit message / pr description that explains why these specific changes need to be made?

but other than that nit:

/approve

**Comment by pritidesai** [comment]
Are we expecting any format change in log messages? I don't think so, the controller logs are still the same:

```
{"level":"info","ts":"2021-08-11T05:36:39.195Z","logger":"tekton-pipelines-controller","caller":"controller/controller.go:548","msg":"Reconcile succeeded","commit":"c291d75","knative.dev/controller":"github.com.tektoncd.pipeline.pkg.reconciler.pipelinerun.Reconciler","knative.dev/kind":"tekton.dev.PipelineRun","knative.dev/traceid":"2fd1700f-3ea6-4ffa-ba6e-574e4d444991","knative.dev/key":"default/pipelinerun-qrfqr","duration":0.0030967}
```

**Comment by sbwsg** [comment]
/hold

That's a good point @pritidesai - those log messages look like they use the "old" field names that I'm replacing in this commit.

**Comment by sbwsg** [comment]
What's weird is that in [our integration tests that also use this change](https://tekton-releases.appspot.com/build/tekton-prow/pr-logs/pull/tektoncd_pipeline/4108/pull-tekton-pipeline-alpha-integration-tests/1425244134502830080/?log#log)  I _do_ see a change to the logging format:

```
stream.go:254: D 00:05:25.762 tekton-pipelines-controller-cb9f7b8dc-fqp2q [github.com.tektoncd.pipeline.pkg.reconciler.pipelinerun.Reconciler] [arendelle-2kh56/pipeline-run-timeout-hzmuvadh] Adding to queue arendelle-2kh56/pipeline-run-timeout-hzmuvadh (delay: 4.999925833s, depth: 0)
```

**Comment by sbwsg** [comment]
Is it possible we're using two completely different log message formats somehow?  I have no idea where these field names get set up.

**Comment by sbwsg** [comment]
OK, a bit more investigation later and it appears (at the very least) that we do have two `zapcore.EncoderConfig` objects in our `vendor` directory that have completely different keys for these log messages:

[vendor/github.com/blendle/zapdriver/encoder.go](https://github.com/tektoncd/pipeline/blob/main/vendor/github.com/blendle/zapdriver/encoder.go#L33-L47) uses the format I'm updating our configuration to here. "timestamp", "severity", etc.

[vendor/go.uber.org/zap/config.go](https://github.com/tektoncd/pipeline/blob/main/vendor/go.uber.org/zap/config.go#L96-L113) uses the format I'm replacing. "ts", "level", etc.

It looks like both of these encoder configs might be affecting different messages emitted by our application in different scenarios? I'll need more time to look in to it so won't be able to get this PR moving for a while.

Both packages were touched by the [Bump knative to release-0.20](https://github.com/tektoncd/pipeline/pull/3605) PR in January but haven't been touched since then. fyi @vdemeester and @mattmoor in case they've seen anything like this before.

**Comment by vdemeester** [comment]
> Is it possible we're using two completely different log message formats somehow? I have no idea where these field names get set up.

I am afraid that is a highly likely possibility 😅

**Comment by sbwsg** [comment]
I'm unlikely to get to this any time in the near future. Closing for now.

**Pull request closed without merging**
