### PR TITLE
Skip TestStorageTaskRun if GCP_SERVICE_ACCOUNT_KEY_PAT is not defined

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

This fails locally or under system that do not use/connect to GCP. We
are already doing this check on another test 👼

Signed-off-by: Vincent Demeester <vdemeest@redhat.com>

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [.] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ :no_good_man: ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by sbwsg** [comment]
Hrm.  @bobcatfish and I removed that check in 2997814d5af44e75a9d so that the test would run in prow (see issue https://github.com/tektoncd/pipeline/issues/821 for background).  Indeed it was skipped in the integration run for this PR: https://tekton-releases.appspot.com/build/tekton-prow/pr-logs/pull/tektoncd_pipeline/904/pull-tekton-pipeline-integration-tests/1131840926604333056/

I'm wondering if we should tag it or have an environment variable like "REQUIRES_GCP" or something as a guard?

**Comment by vdemeester** [comment]
@sbwsg wait, is `GCP_SERVICE_ACCOUNT_KEY_PATH` not set on the PRs CI ? 

> Hrm. @bobcatfish and I removed that check in [2997814](https://github.com/tektoncd/pipeline/commit/2997814d5af44e75a9d5e9865d05a8222235c3d4) so that the test would run in prow (see issue #821 for background). Indeed it was skipped in the integration run for this PR: https://tekton-releases.appspot.com/build/tekton-prow/pr-logs/pull/tektoncd_pipeline/904/pull-tekton-pipeline-integration-tests/1131840926604333056/
> 
> I'm wondering if we should tag it or have an environment variable like "REQUIRES_GCP" or something as a guard?

Yeah, we definitely need better "skipping" mechanisms for those case — and a check on the CI to make sure we don't skip any :angel:

**Comment by sbwsg** [comment]
> wait, is GCP_SERVICE_ACCOUNT_KEY_PATH not set on the PRs CI ?

I don't think so - I believe the way it works (when we didn't have the Skip check) is that the test task container falls back on some default credentials baked into the cluster by GCP when that env var is missing.

I'll give the guard idea a bit more thought and put something together.

**Pull request merged**
