### PR TITLE
[master] Auto-update dependencies

### PR DESCRIPTION
**Pull request by mattmoor**
Produced via:
  `./hack/update-deps.sh --upgrade && ./hack/update-codegen.sh`
/assign ImJasonH vdemeester
/cc ImJasonH vdemeester

### CODE REVIEW

**Comment by vdemeester** [comment]
@mattmoor hum, why the only changes are on the `third_party` folder :thinking: (and none on `go.sum`, `go.mod`, …)

**Comment by mattmoor** [comment]
@vdemeester sorry I filter most of these mails, so I didn't see your comment.  I see changes to `go.*`, but I'd guess there were differences when you looked because someone didn't run things properly and it made it into HEAD?

**Comment by vdemeester** [comment]
@mattmoor that's what's worrying me a bit… it *should* have shown in the CI (if those file were missing in a PR)… This might mean we have a *bad* check somewhere :stuck_out_tongue_closed_eyes: 

/lgtm

**Comment by vdemeester** [comment]
/cc @bobcatfish @afrittoli @sbwsg @dibyom 
@mattmoor might conflict with #2846 but is independent right ?

**Comment by mattmoor** [comment]
@vdemeester I really like the check we have here: https://github.com/vmware-tanzu/sources-for-knative/blob/master/.github/workflows/go-verify.yml

**Comment by mattmoor** [comment]
Also, yes it will conflict :)

**Pull request closed without merging**
