### PR TITLE
Fix Windows image entrypoint paths for parity with Linux

### PR DESCRIPTION
**Pull request by aiden-deloryn**
# Changes

Tekton expects to find the entrypoint binary in `/ko-app/entrypoint`
which is equivalent to `C:\ko-app\entrypoint` on Windows. See
`pkg/pod/entrypoint.go:orderContainers()`. Currently entrypoint is
stored in `C:\ProgramData\tektoncd\pipeline\entrypoint.exe` causing
this to break on Windows. To avoid the need for platform-specific
logic in the controller, and for parity with Linux, this change
updates 'entrypoint' and 'nop' images for Windows to store binaries
in `C:\ko-app\`.

/kind bug

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [ ] [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Release notes block below has been filled in or deleted (only if no user facing changes)

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by sbwsg — APPROVED** [review]

**Comment by imjasonh** [comment]
/lgtm

FWIW https://github.com/google/ko/pull/374 builds images with entrypoint configured to `c:\ko-app\entrypoint`, so this should be compatible when we start actually building Windows images with ko 👍

**Pull request merged**
