### PR TITLE
Add @dibyom as an OWNER! 🙌

### PR DESCRIPTION
**Pull request by bobcatfish**
# Changes

@dibyom has been contributing significant work including variable path
resource substitution https://github.com/tektoncd/pipeline/pull/877 and
his continued work on one of our oldest and most sought after features:
conditional execution (https://github.com/tektoncd/pipeline/pull/27)!

He has also reviewed 44+ PRs in the Pipelines repo:
https://tekton.devstats.cd.foundation/d/46/pr-reviews-by-contributor?orgId=1&var-period=d&var-repo_name=tektoncd%2Fpipeline&var-reviewers="dibyom"

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [n/a] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [n/a] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) and [TaskRun](../tekton/publish-run.yaml) to build and release this image

### CODE REVIEW

**Comment by bobcatfish** [comment]
Adding a hold here so the other owners can review ( @ImJasonH @vdemeester @afrittoli @dlorenc @abayer ):

/hold

**Comment by abayer** [comment]
That is a very creepy cat. I apologize.

**Comment by ImJasonH** [comment]
/lgtm

:tada:

**Pull request merged**
