### PR TITLE
Update knative.dev/pkg to 0.13, fix breaking Convertible change

### PR DESCRIPTION
**Pull request by mattmoor**
Fixes: https://github.com/tektoncd/pipeline/issues/2125

### CODE REVIEW

**Comment by vdemeester** [comment]
/hold
I would looove to get https://github.com/tektoncd/pipeline/pull/2035 in before doing that :angel: :pray:

**Comment by mattmoor** [comment]
@vdemeester rebased!

**Comment by mattmoor** [comment]
@vdemeester needs `/ok-to-test` and `/lgtm` 😉

**Comment by vdemeester** [comment]
/ok-to-test
(I was waiting for someone else to write the lgtm :stuck_out_tongue:)

**Comment by mattmoor** [comment]
> I was waiting for someone else to write the lgtm

Aha!  Are there people I should poke?

**Comment by sbwsg** [comment]
/hold

Do we need this to go in before 0.11?  If not I'd prefer to pause merging of a 174 file change until we cut the release tomorrow.

**Comment by mattmoor** [comment]
I'm not in a rush, I mainly want the ability to validate this through CI.

**Comment by sbwsg** [comment]
:+1: alright cool, cheers!  i'll remove the hold as soon as I finish the release in the morning.

**Comment by mattmoor** [comment]
@vdemeester I'm guessing you have something relying on map ordering in `resultrefresolution_test.go` 🤔 

I'll dig a bit if I get a chance, I've been in meetings like all day 😭

**Comment by mattmoor** [comment]
Alright this now has a set of fixes for various breakages from pkg as well as a fix for a map iteration bug in tekton.

**Comment by mattmoor** [comment]
I wanted to ping this now that your release seems to be cut.  LMK if I should change anything.

**Pull request merged**
