### PR TITLE
ChildReference status helper functions should support both CustomRuns and Runs

### LINKED ISSUE #5933: ChildReference -> actual object status helper functions aren't handling v1alpha1.Runs.
When I added support for `CustomRun`s to the reconciler, I switched the logic in `pkg/status` to use `CustomRun` instead of `Run`...but we want to support both `CustomRun`s _and_ `Run`s, with `Run`s still the default for now. So we need to add back in support for `v1alpha1.Run` in the relevant functions.

This should get backported to v0.43.x.

cc @piyush-garg @vinamra28 since this is what's causing the tests in https://github.com/tektoncd/cli/pull/1838 to fail

/kind bug

### PR DESCRIPTION
**Pull request by abayer**
# Changes

fixes #5933

I updated `pkg/status` to support `CustomRun`s early in the work for supporting `CustomRun`s in the `PipelineRun` reconciler, but forgot to add back support for `Run`s as well when we moved to the reconciler supporting both, depending on a feature flag. This broke https://github.com/tektoncd/cli/pull/1838. This change brings back support for `Run`s in the status helper functions, alongside the support for `CustomRun`s.

/kind bug

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [x] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [x] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
Status helper functions now properly support both CustomRuns and Runs.
```

### CODE REVIEW

**Comment by abayer** [comment]
cc @piyush-garg @vinamra28

**Review by vdemeester — APPROVED** [review]

**Review by vinamra28 — COMMENTED** [review]
/lgtm

**Pull request merged**
