### PR TITLE
Add Tep 75&76 to install doc

### PR DESCRIPTION
**Pull request by Yongxuanzhang**
# Changes

Tep 75&76 are implemented in release v0.38.0, so need to add them into
the install doc's alpha feature section.

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [x] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [ ] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [ ] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [ ] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [ ] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [x] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by lbernick — APPROVED** [review]
looks like the release links are in the wrong column

**Comment by Yongxuanzhang** [comment]
> looks like the release links are in the wrong column

Thanks, Just fixed! I will remember to preview the format!

**Comment by abayer** [comment]
/hold

Temporarily holding due to Prow batching problems.

**Pull request merged**
