### PR TITLE
Results Lifecycle

### PR DESCRIPTION
**Pull request by chitrangpatel**
This document walks a developer through how the results are stored
by the tasks and extracted by the taskrun reconciler.

# Changes

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [ ] [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [ ] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [ ] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [ ] Release notes block below has been filled in
(if there are no user facing changes, use release note "NONE")

# Release Notes

```release-note
Documenting the results lifecycle.

```

### CODE REVIEW

**Comment by chitrangpatel** [comment]
/assign @dibyom  
cc @chuangw6 @Yongxuanzhang

**Comment by Yongxuanzhang** [comment]
I think overall this looks correct! 

1. Are you planning to include how we handle larger results in this doc once it is merged?
2. I wonder if it makes sense to include how results used in pipeline? It may consist of 1) How results are referred in another task (the reference will add a link to our tasks DAG), 2) How pipeline level results are emitted

**Comment by chitrangpatel** [comment]
> I think overall this looks correct!
> 
> 1. Are you planning to include how we handle larger results in this doc once it is merged?
Yes, once its merged, I can add to it.

> 2. I wonder if it makes sense to include how results used in pipeline? It may consist of 1) How results are referred in another task (the reference will add a link to our tasks DAG), 2) How pipeline level results are emitted

I'm not super familiar with the referencing of results so feel free to add to it once this PR is merged. I would like to know how that works.

> 3. Maybe add some reference to results section to other docs, or in other parts link to this doc as a reference for developers
I agree.

**Pull request merged**
