### PR TITLE
Add links to v0.15.1 docs

### PR DESCRIPTION
**Pull request by sbwsg**
# Changes

We tag each release so that future generations can see how Pipelines'
documentation looked at a given point in time.

This commit adds a reference to the 0.15.1 documentation from our
README.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [x] Release notes block has been filled in or deleted (only if no user facing changes)

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by dlorenc** [comment]
whoops, /kind documentation

**Comment by vdemeester** [comment]
@dlorenc the comments needs to be alone on a line :stuck_out_tongue_closed_eyes:

**Pull request merged**
