### PR TITLE
Exclude tags from being reported by knative.dev/test-infra/tools/go-ls-tags tool

### PR DESCRIPTION
**Pull request by cardil**
# Changes

Fixes https://github.com/knative/pkg/issues/2643
Fixes https://github.com/knative/actions/issues/86

/kind bug

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [ ] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [ ] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [ ] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [ ] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [ ] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by imjasonh** [comment]
This feels like an abstraction violation. Why should this repo need to maintain a file so that tests in some other repo don't fail? People adding new build tag scenarios to Tekton might (even "should") have no idea that some remote test could be affected by it.

Can this be maintained in knative/pkg instead? Or, should we just disable knative's failing downstream test of Tekton?

**Comment by cardil** [comment]
> Can this be maintained in knative/pkg instead? Or, should we just disable knative's failing downstream test of Tekton?

Ofc it is violation. That's the purpose of the downstream test.

The downstream test benefit Tekton because you are using knative/pkg. If someone refactors something from knative/pkg that you are using, it will not pass the downstream test. So, it saves you from upstream breaking changes.

So, I'd say your call...

**Comment by cardil** [comment]
Worth adding that knative/pkg doesn't have tags, so you always rely on latest commit being merged. That's why there is this downstream test in the first place.

**Comment by vdemeester** [comment]
> Worth adding that knative/pkg doesn't have tags, so you always rely on latest commit being merged. That's why there is this downstream test in the first place.

We do not rely on the last commit though, most of the time, we "rely" on the *versionned* branches (release-*).

**Comment by cardil** [comment]
@vdemeester said:

> _We do not rely on the last commit though, most of the time, we "rely" on the versionned branches (release-*)._

If so, maybe we can remove the downstream test for tektoncd/pipeline?

**Comment by vdemeester** [comment]
> @vdemeester said:
> 
> > _We do not rely on the last commit though, most of the time, we "rely" on the versionned branches (release-*)._
> 
> If so, maybe we can remove the downstream test for tektoncd/pipeline?

Probably yes.

**Comment by dibyom** [comment]
I don't think this PR is necessary anymore since the downstream tests got removed. Feel free to reopen if that's not the case

/close

**Pull request closed without merging**
