### PR TITLE
fix build uncorrect status

### PR DESCRIPTION
**Pull request by zouyee**
Fixes https://github.com/knative/build/issues/599

## Proposed Changes

* adjust object timestamp.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

# Release Notes

```
NONE
```

### CODE REVIEW

**Comment by dlorenc** [comment]
Thanks for the PR! I left one comment about grammar in the logging message, otherwise this looks good to me. Would you also mind adding a bit more to the commit message explaining the change and how we get into this state?

**Comment by zouyee** [comment]
@dlorenc got it.

**Comment by dlorenc** [comment]
> @dlorenc got it.

Sorry, somehow I never sent the comment itself. Just sent!

**Comment by dlorenc** [comment]
/lgtm /approve

Thanks!

**Pull request merged**
