### PR TITLE
bump deps - k8s to 1.19.7

### PR DESCRIPTION
**Pull request by dprotaso**
Bumped K8s, Knative, GGCR deps

`replace` block was removed since we don't need it anymore

/kind cleanup

```release-notes
NONE
```

### CODE REVIEW

**Review by ImJasonH — COMMENTED** [review]
/ok-to-test

**Comment by dprotaso** [comment]
blah folder casing changed - one sec

**Comment by dprotaso** [comment]
codegen

**Comment by dprotaso** [comment]
so weird - I run it locally with no diff

**Comment by dprotaso** [comment]
lol i'm running it in the wrong repo
```
-  Ref:     ref("github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1.Step"),
+ Ref:     ref("knative.dev/build-pipeline/pkg/apis/pipeline/v1beta1.Step"),
```

**Comment by dprotaso** [comment]
rebased

**Review by ImJasonH — APPROVED** [review]

**Comment by vdemeester** [comment]
@dprotaso one *very* naive question : why is it needed now (as compared to when knative 0.21 is released 😝) ?
Otherwise, looks good 😉

**Comment by dprotaso** [comment]
I was doing this to drop the `replace` blocks in in https://github.com/mattmoor/mink which pulls in tekton

If you prefer to be more conservative with your knative/pkg adoption I can close the PR and re-open it when 0.21 ships

**Comment by vdemeester** [comment]
> I was doing this to drop the `replace` blocks in in https://github.com/mattmoor/mink which pulls in tekton
> 
> If you prefer to be more conservative with your knative/pkg adoption I can close the PR and re-open it when 0.21 ships

Honestly that's ok, from time to time we do bump non tagged version of knative/pkg. As long as we have a issue in the our 0.21 to make sure we bump knative to the released version, I am fine merging this.

/lgtm
/hold

/cc @jerop @sbwsg to make sure the release captain agree with this as this make us have to wait for knative/* to be release as 0.21. Please remove the hold if you are ok with it 😉

**Review by jerop — COMMENTED** [review]
> /cc @jerop @sbwsg to make sure the release captain agree with this as this make us have to wait for knative/* to be release as 0.21. Please remove the hold if you are ok with it 😉

we agreed in the owners meeting on monday to wait for knative 0.21 (~ 15th Feb) then do our release a few days later

https://github.com/tektoncd/pipeline/issues/3324 is in our next release milestone ([comment](https://github.com/tektoncd/pipeline/issues/3324#issuecomment-766949309))

/hold cancel

**Comment by vdemeester** [comment]
thx @jerop 🤗

**Comment by dprotaso** [comment]
Fixes #3324

**Pull request merged**
