### PR TITLE
Refactored Steps and Sidecars to container_validation

### LINKED ISSUE #7442: Refactor Steps and Sidecars to container_validation
Now that we have [container_validations](https://github.com/tektoncd/pipeline/blob/532591101c08d7f6103c3dd7cd005ef1a5c3f8cb/pkg/apis/pipeline/v1/container_validation.go), we shall move the [`Sidecars`](https://github.com/tektoncd/pipeline/blob/d7f8c99bafb05af8d273746915b72c370d80e9e3/pkg/apis/pipeline/v1/task_validation.go#L152) and [`Steps` validation ](https://github.com/tektoncd/pipeline/blob/d7f8c99bafb05af8d273746915b72c370d80e9e3/pkg/apis/pipeline/v1/task_validation.go#L325) which are previously under [task_validation](https://github.com/tektoncd/pipeline/blob/main/pkg/apis/pipeline/v1/task_validation.go) to this file since they are more tied with [container types ](https://github.com/tektoncd/pipeline/blob/d7f8c99bafb05af8d273746915b72c370d80e9e3/pkg/apis/pipeline/v1/container_types.go#L24)rather than [Task types](https://github.com/tektoncd/pipeline/blob/d7f8c99bafb05af8d273746915b72c370d80e9e3/pkg/apis/pipeline/v1/task_types.go#L99).

/kind cleanup

### PR DESCRIPTION
**Pull request by professorabhay**
# Changes

Moved Steps and Sidecars functions to container_validation

closes #7442 

```release-note
NONE
```

### CODE REVIEW

**Comment by professorabhay** [comment]
Hey, @JeromeJu!
Kindly take a look and let me know what else you want to see. 😊

**Comment by JeromeJu** [comment]
Thanks @professorabhay 
/assign

/ok-to-test
/kind cleanup

**Comment by Dhruval7878** [comment]
@professorabhay hey , i think tests are failing because you should import time and fmt packages in import statement and removing unused package like time and k8s.io/pkg/validation should do

**Comment by afrittoli** [comment]
@professorabhay are you still working on this?

**Pull request closed without merging**
