### PR TITLE
Attempt to fix another structured-merge-diff failures.

### PR DESCRIPTION
**Pull request by mattmoor**
# Changes

Drop the pointer on the inline field to avoid panics in `structured-merge-diff` in CLI.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [ ] Release notes block has been filled in or deleted (only if no user facing changes)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) to build and release this image.

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md) are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes) must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS) and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes) must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS), and they must first be added [in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

# Release Notes

```release-note
action required: Drop pointers from inline struct when embedding TaskSpec in v1beta1
```

### CODE REVIEW

**Comment by mattmoor** [comment]
/assign @ImJasonH @vdemeester 

This is another issue I hit pulling the latest pipelines into CLI, but with this change it's passing: https://github.com/tektoncd/cli/pull/1198

The meat of this change is the diff in `pkg/apis/pipeline/v1beta1/pipeline_types.go` which drops the pointer from:
```go
      TaskSpec `json:",inline,omitempty"`
```

From a serialization perspective, I'd expect these to be virtually identical because every field of `TaskSpec` is itself `omitempty`.

**Review by vdemeester — COMMENTED** [review]
/lgtm

**Pull request merged**
