### PR TITLE
Fix release pipeline to handle #1122

### PR DESCRIPTION
**Pull request by afrittoli**
Since #1122, we do not treat outputs that were inputs as well in any
special way, meaning that the output folder will be empty unless we
copy the input to the output.

Fix the release pipeline to handle that.

Fixes: #1325

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) and [TaskRun](../tekton/publish-run.yaml) to build and release this image

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md)
are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes)
must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS)
and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes)
must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS),
and they must first be added
[in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

# Release Notes

```
Describe any user facing changes here, or delete this block.

Examples of user facing changes:
- API changes
- Bug fixes
- Any changes in behavior

```

### CODE REVIEW

**Comment by bobcatfish** [comment]
Just a quick note that the release pipeline (afaik - maybe this is changed now?) should be running against v0.3.1 of Tekton (https://github.com/tektoncd/pipeline/tree/master/tekton#install-tekton) - tho it's good to be ready for this change later!

**Comment by dibyom** [comment]
Do the nightly and release jobs run on the same cluster?

**Comment by afrittoli** [comment]
> Do the nightly and release jobs run on the same cluster?

I'm not sure if they do, but at least I could verify that Tekton in the prow cluster in `tekton-releases` runs on version 0.3.1. Which means I should not update the release pipeline before running the release.

We could perhaps have a parameter added to the publish Task to conditionally handle the change introduced #1122, so that the pipeline may work both on pre and post v0.7.0.

BTW the only way I cound find out the version of Tekton was to compare the image sha from the controller pod in the cluster with the sha from the 0.3.1 release file on github. Is there any better way to find out about the version of Tekton that runs in the cluster?

**Comment by dibyom** [comment]
+1 I like the parameter idea. Though it would have been cool to have a conditional that checks the version of Tekton and then runs the right task :)

**Pull request merged**
