### PR TITLE
Refactor LimitRange package

### PR DESCRIPTION
**Pull request by lbernick**
# Changes

This commit separates logic for calculating a "virtual" limitrange from all limitranges
present in a namespace from logic for setting pod compute resources based on the virtual limitrange,
and adds tests. This makes it much easier to add tests for scenarios with multiple limitranges
and multiple containers, because each component can be tested separately.

No functional changes.

/kind cleanup

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- n/a [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [x] [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Release notes block below has been filled in
(if there are no user facing changes, use release note "NONE")

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by lbernick** [comment]
@vdemeester @skaegi PTAL

**Review by skaegi — APPROVED** [review]
Looks good and more cleanly separates the tests.

**Review by skaegi — APPROVED** [review]

**Comment by skaegi** [comment]
/lgtm
good catch

**Pull request merged**
