### PR TITLE
fix: move getFeatureFlagsBaseOnAPIFlag from custom_task_test to another file

### LINKED ISSUE #7269: move getFeatureFlagsBaseOnAPIFlag from custom_task_test to another file
The [getFeatureFlagsBaseOnAPIFlag](https://github.com/tektoncd/pipeline/blob/8123d6332245008983aabe1dc910a63bd2c6f261/test/custom_task_test.go#L729) is used in multiple tests, and when developers want to introduce a new feature flag, they need to change this functions as well. 

It's not clear since the helper function is in `custom_task_test` and also cause confusions to reviewers. We should move it to another file

### PR DESCRIPTION
**Pull request by Dhruval7878**
fixes #7269 

/kind cleanup

# Changes

Changed the location of function and removed some imports.

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [x] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) if any changes are user facing, including updates to minimum requirements e.g. Kubernetes version bumps
- [ ] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [ ] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [ ] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings). See some examples of [good release notes](https://github.com/tektoncd/community/blob/main/standards.md#good-release-notes).
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by jerop — COMMENTED** [review]
/ok-to-test

**Comment by jerop** [comment]
@Dhruval7878 thank you for the contribution and welcome to Tekton

/meow

Please sign the CLA 🙏🏾

**Comment by Dhruval7878** [comment]
@jerop Hey, I've just signed the CLA.

**Comment by Dhruval7878** [comment]
Hey !!
What's the status of my PR ?

**Comment by Dhruval7878** [comment]
> Hey !! What's the status of my PR ?

@jerop

**Review by khrm — COMMENTED** [review]
/ok-to-test

**Review by khrm — COMMENTED** [review]
I think we should move this from some place else instead of test.

**Comment by Dhruval7878** [comment]
I'm facing issues with this task, and I'm not sure why it's failing. Any assistance or guidance would be greatly appreciated.

**Comment by Yongxuanzhang** [comment]
Hi @Dhruval7878 could you rebase the PR? I will help to approve it

**Comment by Dhruval7878** [comment]
> Hi @Dhruval7878 could you rebase the PR? I will help to approve it

Sure,  but I would like to know why I'm not assignee any longer?

**Comment by Yongxuanzhang** [comment]
> > Hi @Dhruval7878 could you rebase the PR? I will help to approve it
> 
> Sure, but I would like to know why I'm not assignee any longer?
> 
> I'm newbie to such things and I would really appreciate if you help me to be on the trail.

You're assignee of this issue: https://github.com/tektoncd/pipeline/issues/7269
The assignee of this PR is the one who's responsible for reviewing it

**Comment by Dhruval7878** [comment]
> > > Hi @Dhruval7878 could you rebase the PR? I will help to approve it
> > 
> > 
> > Sure, but I would like to know why I'm not assignee any longer?
> > I'm newbie to such things and I would really appreciate if you help me to be on the trail.
> 
> You're assignee of this issue: #7269 The assignee of this PR is the one who's responsible for reviewing it

okay I got it
So help me , like how to rebase this PR ..

**Comment by Yongxuanzhang** [comment]
> > > > Hi @Dhruval7878 could you rebase the PR? I will help to approve it
> > > 
> > > 
> > > Sure, but I would like to know why I'm not assignee any longer?
> > > I'm newbie to such things and I would really appreciate if you help me to be on the trail.
> > 
> > 
> > You're assignee of this issue: #7269 The assignee of this PR is the one who's responsible for reviewing it
> 
> okay I got it So help me , like how to rebase this PR ..

Usually you need to create another branch in your forked reop: https://github.com/Dhruval7878/pipeline
And your forked main branch can sync with upstream main. Then you can rebase your working branch with:
`git rebase -i main`

**Comment by Yongxuanzhang** [comment]
> > > > Hi @Dhruval7878 could you rebase the PR? I will help to approve it
> > > 
> > > 
> > > Sure, but I would like to know why I'm not assignee any longer?
> > > I'm newbie to such things and I would really appreciate if you help me to be on the trail.
> > 
> > 
> > You're assignee of this issue: #7269 The assignee of this PR is the one who's responsible for reviewing it
> 
> okay I got it So help me , like how to rebase this PR ..

You could search some basic git commands to get familiar with them, and learn how to use

**Comment by Dhruval7878** [comment]
> > > > > Hi @Dhruval7878 could you rebase the PR? I will help to approve it
> > > > 
> > > > 
> > > > Sure, but I would like to know why I'm not assignee any longer?
> > > > I'm newbie to such things and I would really appreciate if you help me to be on the trail.
> > > 
> > > 
> > > You're assignee of this issue: #7269 The assignee of this PR is the one who's responsible for reviewing it
> > 
> > 
> > okay I got it So help me , like how to rebase this PR ..
> 
> Usually you need to create another branch in your forked reop: https://github.com/Dhruval7878/pipeline And your forked main branch can sync with upstream main. Then you can rebase your working branch with: `git rebase -i main`

oke thankss !!

**Pull request closed without merging**
