### PR TITLE
Keep PipelineResource.status field for backward compatibility 👾

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

They are not used, and shouldn't be there, but client that have
previous version of this struct would fail targeting the API.

This is a *partial* revert of #1640, as it doesn't reintroduce the
`UpdateStatus` generation.

Follow-up on #1762 for `PipelineResource` :angel: 
/cc @dibyom @bobcatfish 

Signed-off-by: Vincent Demeester <vdemeest@redhat.com>

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) to build and release this image.

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md) are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes) must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS) and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes) must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS), and they must first be added [in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

### CODE REVIEW

**Comment by bobcatfish** [comment]
/lgtm
/approve

Thanks for taking care of this @vdemeester !!

Do we have a follow up issue to remove this in v1alpha2?

**Comment by vdemeester** [comment]
@bobcatfish well, I didn't migrate Pipeline yet so… I don't really need to do it for v1alpha2 :stuck_out_tongue_closed_eyes:

**Comment by bobcatfish** [comment]
> @bobcatfish well, I didn't migrate Pipeline yet so… I don't really need to do it for v1alpha2 :stuck_out_tongue_closed_eyes:

hmm I'm not sure what you mean? Maybe I'm not making sense, what I'm trying to say is that we're readding this and #1762 b/c it's a backwards incompatible change but we _do_ want to remove these fields eventually, right? So I just want to make sure we don't forget.

**Comment by vdemeester** [comment]
> > @bobcatfish well, I didn't migrate Pipeline yet so… I don't really need to do it for v1alpha2 stuck_out_tongue_closed_eyes
> 
> hmm I'm not sure what you mean? Maybe I'm not making sense, what I'm trying to say is that we're readding this and #1762 b/c it's a backwards incompatible change but we _do_ want to remove these fields eventually, right? So I just want to make sure we don't forget.

Yeah, we do want to remove them, in `v1alpha2`/`v1beta1` ; but as I did not yet port those, I don't have anything to remove yet, I just need to remember removing that. You totally make sense :angel:

**Pull request merged**
