### PR TITLE
Set better pipelinerun generate name for sample: pipelinerun-with-par…

### PR DESCRIPTION
**Pull request by vincent-pli**
People can not know where the case come from just base the name "pr-xxxx", confuse people when try make integration-test works, like this:
```
pipelinerun-echo-greetings                               Succeeded   True      2020-05-04T23:49:40Z
pipelinerun-with-params                                  Succeeded   True      2020-05-04T23:49:36Z
pipelinerun-with-taskspec-to-echo-good-morning           Succeeded   True      2020-05-04T23:49:38Z
pipelinerun-with-taskspec-to-echo-greetings              Succeeded   True      2020-05-04T23:49:39Z
pipelinerun-with-taskspec-to-echo-message                Succeeded   True      2020-05-04T23:49:38Z
pr-d4t4v                                                 Succeeded   Unknown   2020-05-04T23:49:35Z
pr-different-path-7f2cc                                  Succeeded   True      2020-05-04T23:49:34Z
```

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) to build and release this image.

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md) are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes) must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS) and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes) must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS), and they must first be added [in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

# Release Notes

```
Describe any user facing changes here, or delete this block.

Examples of user facing changes:
- API changes
- Bug fixes
- Any changes in behavior

```

### CODE REVIEW

**Comment by ImJasonH** [comment]
Please update the Release Notes section of your PR, or remove it if this change is not visible to users.

**Comment by sbwsg** [comment]
This file was removed in https://github.com/tektoncd/pipeline/pull/2546/files

So I think we can probably close this for now?

**Comment by sbwsg** [comment]
/close

Feel free to reopen if there's still more to do here!

**Pull request closed without merging**
