### PR TITLE
Remove experimental disable resolution controller flag

### PR DESCRIPTION
**Pull request by sbwsg**
# Changes

In commits 5681ce99232cffebc42b4a097514bc0a3e14a6e5 and
5fa4348bdbb7f28280bcfd518f6025c94670e420 we introduced a controller flag to
disable resolution of `taskRefs` and `pipelineRefs`. This was intended to support an
[experimental controller](https://github.com/tektoncd/experimental/pull/806) that could externalize resolution of these refs. Tests
and documentation for this flag were added as well.

The experimental flag ultimately never realized its purpose and the
experimental controller was written to only support PipelineRuns started in
PipelineRunPending state. This commit removes the code, tests and docs
surrounding this flag and its behaviour.

# Submitter Checklist

- [x] [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [x] [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Release notes block below has been filled in or deleted (only if no user facing changes)

# Release Notes

```release-note
An experimental controller flag was added in Pipelines v0.28.0 to disable resolution of taskrefs and pipelinerefs. This flag has now been removed.
```

/kind misc

### CODE REVIEW

**Comment by lbernick** [comment]
still getting used to permissions on this repo 😅 anyway, looks good

**Review by vdemeester — APPROVED** [review]

**Review by jerop — COMMENTED** [review]
`TaskRun "isolated-workspaces-p446k-test-isolation" failed to finish within "1m0s"`

/test pull-tekton-pipeline-alpha-integration-tests

**Comment by jerop** [comment]
thanks @sbwsg! 

/lgtm

**Comment by sbwsg** [comment]
test/v1alpha1 TestPipelineTaskTimeout 1m5s

/test pull-tekton-pipeline-alpha-integration-tests

**Pull request merged**
