### PR TITLE
Add docs and examples for Windows

### PR DESCRIPTION
**Pull request by aiden-deloryn**
# Changes

A new markdown file has been added to document Windows usage in Tekton.

Some examples have been added to demonstrate how to schedule TaskRuns
and PipelineRuns on a Windows node using node selectors and node
affinity constraints.

/kind documentation

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [x] [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [ ] [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [ ] Release notes block below has been filled in or deleted (only if no user facing changes)

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by vdemeester — COMMENTED** [review]
/ok-to-test

**Comment by dlorenc** [comment]
The examples actually get run as part of tests, we probably don't have a Windows node in our test clusters to run these on.

**Comment by aiden-deloryn** [comment]
@dlorenc Aren't the examples under `taskruns/no-ci/` and `pipelineruns/no-ci/` supposed to be skipped for tests?

It seems the failed tests are due to linting / white-space errors:

```
./examples/v1beta1/pipelineruns/no-ci/windows-node-selectors.yaml
  17:10     error    trailing spaces  (trailing-spaces)

./examples/v1beta1/pipelineruns/no-ci/windows-node-affinity.yaml
  17:10     error    trailing spaces  (trailing-spaces)

./examples/v1beta1/taskruns/no-ci/windows-node-affinity.yaml
  24:9      error    wrong indentation: expected 6 but found 8  (indentation)
```

**Comment by vdemeester** [comment]
> @dlorenc Aren't the examples under `taskruns/no-ci/` and `pipelineruns/no-ci/` supposed to be skipped for tests?
> 
> It seems the failed tests are due to linting / white-space errors:
> 
> ```
> ./examples/v1beta1/pipelineruns/no-ci/windows-node-selectors.yaml
>   17:10     error    trailing spaces  (trailing-spaces)
> 
> ./examples/v1beta1/pipelineruns/no-ci/windows-node-affinity.yaml
>   17:10     error    trailing spaces  (trailing-spaces)
> 
> ./examples/v1beta1/taskruns/no-ci/windows-node-affinity.yaml
>   24:9      error    wrong indentation: expected 6 but found 8  (indentation)
> ```

They don't run as part of the test (not applied to the cluster, …), but they still get "validated" by the linters 😝

**Comment by aiden-deloryn** [comment]
> They don't run as part of the test (not applied to the cluster, …), but they still get "validated" by the linters 😝

That does appear to be the case. Thanks for the confirmation 😄 

The tests succeeded after I fixed the linting errors. Please let me know if there is anything else I need to change.

**Review by vdemeester — APPROVED** [review]

**Comment by bobcatfish** [comment]
I always love more docs :D 

/lgtm

image

**Pull request merged**
