### PR TITLE
Use git resolver to fetch the github-release pipeline

### PR DESCRIPTION
**Pull request by chuangw6**
# Changes

/kind cleanup

Prior, the release cheat sheet uses tkn command to start the github `release-draft` pipeline that was previously applied to the cluster. However, this is easy to get aged in the dogfooding cluster.

This commit suggests to use a PipelineRun that will use git resolver to fetch the latest `tekton/resources/release/base/github_release.yaml` from the plumbing repo.

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by chuangw6** [comment]
/hold

until https://github.com/tektoncd/plumbing/pull/1440 is merged.

**Comment by chuangw6** [comment]
cc @tektoncd/core-maintainers PTAL

**Review by jerop — COMMENTED** [review]
/close

closing because we didn't agree on this change in https://github.com/tektoncd/pipeline/pull/6712

**Pull request closed without merging**
