### PR TITLE
example code for "Speed Up Container Image Builds in Tekton Pipelines" blog post

### PR DESCRIPTION
**Pull request by ggalloro**
This is example code for "Speed Up Container Image Builds in Tekton Pipelines" blog post.

It's referenced by the article in https://github.com/tektoncd/website/pull/571

# Release Notes
```
NONE
```

### CODE REVIEW

**Comment by JeromeJu** [comment]
Thanks @ggalloro , we might need the block for release note in the PR message:
"```release-note
NONE
```"

**Comment by ggalloro** [comment]
> Thanks @ggalloro , we might need the block for release note in the PR message: "```release-note"
> 
> ```
> NONE
> ```

Added in the PR message.

**Comment by dibyom** [comment]
@ggalloro it looks like these files are also included in the website/ repo as well. To me, that seems like a better location anyway. Do we still need to add the example code here?

**Comment by ggalloro** [comment]
@AlanGreene recommended me to put code example in the website repo so i did it, so no need to add this here too I think.

**Pull request closed without merging**
