### PR TITLE
Porting go e2e test to v1beta1

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

Migrate e2e go tests to use `v1beta1` and moving the current ones to their own package (`test/v1alpha1`).

It also has small refactoring :upside_down_face: 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) to build and release this image.

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md) are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes) must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS) and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes) must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS), and they must first be added [in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

### CODE REVIEW

**Comment by vdemeester** [comment]
Yay e2e are green, I'll finish the rest tomorrow (and it will automatically fix `build-tests`)

**Comment by vdemeester** [comment]
It is green :tada:

**Comment by sbwsg** [comment]
I'm going to lgtm as well as approve this one despite its size.  I've read through and feel pretty confident that this can go in, especially given that the blast radius is 99% testing and tests are passing.  I'm also very eager to get the 0.11-rc3 release train moving.

/lgtm

**Pull request merged**
