### PR TITLE
Remove deprecated `PipelineRunSpecStatusCancelledDeprecated`

### LINKED ISSUE #4611: TEP-0058: Graceful Termination - Promotions and Deprecation
In [TEP-0058: Graceful Termination](https://github.com/tektoncd/community/blob/main/teps/0058-graceful-pipeline-run-termination.md), we deprecated `PipelineRunCancelled` and added:
- `StoppedRunFinally` - To "stop" (i.e. let the tasks complete, then execute finally tasks) a Pipeline
- `CancelledRunFinally` - To "cancel" (i.e. interrupt any executing non finally tasks, then execute finally tasks)
- `Cancelled` - Same as today's `PipelineRunCancelled` - i.e. interrupt any executing tasks without running finally tasks

The above was released in [v0.25](https://github.com/tektoncd/pipeline/releases/tag/v0.25.0) in June 2021. 

The new fields are still in [alpha](https://github.com/tektoncd/pipeline/blob/302895b5a1ca45c02a85a9822201643c159fe02c/docs/install.md#alpha-features), so this issue tracks promoting them to beta. This issue also tracks deprecation and removal of `PipelineRunCancelled`.

### PR DESCRIPTION
**Pull request by abayer**
# Changes

Fixes #4611.

We deprecated the original cancelled status (with the value `PipelineRunCancelled`) in #3915, and we're now at the time for it to be removed in favor of the value `Cancelled`.

An email will be sent to tekton-dev@ alerting people to this change once it merges.

/kind cleanup

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [x] [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [x] [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Release notes block below has been filled in
(if there are no user facing changes, use release note "NONE")

# Release Notes

```release-note
Deprecated `PipelineRunCancelled` status string removed; use `Cancelled` instead.
```

### CODE REVIEW

**Comment by abayer** [comment]
/hold

This is on top of #5005 (which removes most of `v1alpha1`), so as to avoid dealing with the messier usage of `PipelineRunCancelled` in `v1alpha1`, so it's on hold until that has merged.

**Comment by vinamra28** [comment]
> /cc @vinamra28 @tektoncd/cli-maintainers do we feel confident this won't be a huge deal for cli ? I think we supported this only recently 🙃

@vdemeester yep, CLI can handle this easily.

**Review by lbernick — APPROVED** [review]
/hold

since the deprecation table states that this won't be removed until July 12 (and also until this is rebased)

**Comment by abayer** [comment]
@lbernick Since there won't be a release between now and July 12, this should be mergeable now.

**Review by vinamra28 — COMMENTED** [review]
/lgtm

**Comment by jerop** [comment]
thanks @abayer!

/lgtm

**Pull request merged**
