### PR TITLE
remove hashicorp kms libraries from trusted resources

### PR DESCRIPTION
**Pull request by Yongxuanzhang**
# Changes
This commit removes hashicorp kms libraries to unblock other tekton developers, details in #6015. In tep-91 we pulled in hashicorp kms libraries, and by running hack/update-codegen.sh it will copy the code into third_party directory. This will cause failures to ci jobs since it uses internal pkg. This is a short term solution to unblock other pipeline developers. Long term goal is to exclude checking third_party in our ci.

/kind misc

Signed-off-by: Yongxuan Zhang yongxuanzhang@google.com

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [ ] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [ ] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
remove hashicorp kms libraries from trusted resources, so trusted resources don't support hashivault kms
```

### CODE REVIEW

**Comment by lbernick** [comment]
thanks @Yongxuanzhang -- what's the expected impact of not supporting hashivault for trusted resources? Will this be added back in later?

**Comment by Yongxuanzhang** [comment]
> thanks @Yongxuanzhang -- what's the expected impact of not supporting hashivault for trusted resources? Will this be added back in later?

Currently we support loading kms from azure, aws, gcp and hashivault, so this means we will remove hashivault from our supported kms libraries. 
Since trusted resources is alpha feature and we may don't have users yet. I think the impact is minimized. 
We can add it back when we figure out how to exclude running third_party unit tests, on licenses or it is a feature request from users.

**Comment by lbernick** [comment]
> Currently we support loading kms from azure, aws, gcp and hashivault, so this means we will remove hashivault from our supported kms libraries. Since trusted resources is alpha feature and we may don't have users yet. I think the impact is minimized. We can add it back when we figure out how to exclude running third_party unit tests, on licenses or it is a feature request from users.

I'd like to unblock https://github.com/tektoncd/pipeline/pull/6342 and this sounds reasonable to me, but I don't love the idea of removing a feature we plan to add back later. Can anyone from the security wg comment on whether this is the right way to go or whether it makes sense to address the issue with hashicorp libraries directly?

Also, it seems like the problem described in https://github.com/tektoncd/pipeline/issues/6015 isn't that we run unit tests on code in third_party; it seems like the problem is that there are security vulnerabilities detected by CodeQL. Maybe this is a signal that we should not import this library until the vulnerabilities are resolved?

**Comment by Yongxuanzhang** [comment]
> > Currently we support loading kms from azure, aws, gcp and hashivault, so this means we will remove hashivault from our supported kms libraries. Since trusted resources is alpha feature and we may don't have users yet. I think the impact is minimized. We can add it back when we figure out how to exclude running third_party unit tests, on licenses or it is a feature request from users.
> 
> 
> 
> I'd like to unblock https://github.com/tektoncd/pipeline/pull/6342 and this sounds reasonable to me, but I don't love the idea of removing a feature we plan to add back later. Can anyone from the security wg comment on whether this is the right way to go or whether it makes sense to address the issue with hashicorp libraries directly?
> 
> 
> 
> Also, it seems like the problem described in https://github.com/tektoncd/pipeline/issues/6015 isn't that we run unit tests on code in third_party; it seems like the problem is that there are security vulnerabilities detected by CodeQL. Maybe this is a signal that we should not import this library until the vulnerabilities are resolved?

Yes that's a good suggestion. I will bring this up tobthe wg and see if there are other ways.  

Vulnerabilities from CodeQL are just part of the problem iirc. Their libraries will fail the unit tests since we run go test./...

**Comment by lbernick** [comment]
> Yes that's a good suggestion. I will bring this up tobthe wg and see if there are other ways.

Thanks!

> Vulnerabilities from CodeQL are just part of the problem iirc. Their libraries will fail the unit tests since we run go test./...

I'm not seeing the unit test failures you're describing, can you point me to an example? Unit tests pass in https://github.com/tektoncd/pipeline/pull/6342

**Comment by Yongxuanzhang** [comment]
> > Yes that's a good suggestion. I will bring this up tobthe wg and see if there are other ways.
> 
> Thanks!
> 
> > Vulnerabilities from CodeQL are just part of the problem iirc. Their libraries will fail the unit tests since we run go test./...
> 
> I'm not seeing the unit test failures you're describing, can you point me to an example? Unit tests pass in #6342

Oh indeed! This these libraries are not blocking unit tests/build tests anymore, maybe they have fixed it upstream. 
For the CodeQL warning, maybe we could turn them off? Is it a block for ci?

**Pull request closed without merging**
