### PR TITLE
Fix StepAction support in Cluster resolver

### PR DESCRIPTION
**Pull request by AverageMarcus**
# Changes

Fix StepAction support in Cluster resolver

Fixes https://github.com/tektoncd/pipeline/issues/8381

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [x] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) if any changes are user facing, including updates to minimum requirements e.g. Kubernetes version bumps
- [x] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] [pre-commit](https://github.com/tektoncd/pipeline/blob/main/DEVELOPMENT.md#install-tools) Passed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [x] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings). See some examples of [good release notes](https://github.com/tektoncd/community/blob/main/standards.md#good-release-notes).
- [x] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
Fix StepAction support in Cluster resolver
```

### CODE REVIEW

**Review by afrittoli — COMMENTED** [review]
Thanks! 
I'm not too familiar with this section of the codebase, but in principle it looks good to me. I think this qualifies as a feature rather than a bug - the documented support today is for task and pipeline, this adds step action, which makes sense. Would you mind updating the docs as part of this PR? https://github.com/tektoncd/pipeline/blob/main/docs/cluster-resolver.md

**Review by vdemeester — APPROVED** [review]
Oh waw, how did I miss that 😮‍💨 .
@afrittoli I would consider this as a bug, as it is supposed to be implemented (it's just that this part of the validation was missing 😱 )

**Comment by afrittoli** [comment]
> Oh waw, how did I miss that 😮‍💨 . @afrittoli I would consider this as a bug, as it is supposed to be implemented (it's just that this part of the validation was missing 😱 )

Well it matches the current docs https://github.com/tektoncd/pipeline/blob/main/docs/cluster-resolver.md... but I'm also ok to merge this and update the docs in a separate PR as long as they go out in the same release

**Comment by vdemeester** [comment]
> > Oh waw, how did I miss that 😮‍💨 . @afrittoli I would consider this as a bug, as it is supposed to be implemented (it's just that this part of the validation was missing 😱 )
> 
> Well it matches the current docs https://github.com/tektoncd/pipeline/blob/main/docs/cluster-resolver.md... but I'm also ok to merge this and update the docs in a separate PR as long as they go out in the same release

oh waw I missed a lot of things 🤦🏼 my PR got merged too quickly 🎃 😓

**Comment by AverageMarcus** [comment]
I can update the docs too, give me a moment. :)

**Comment by vdemeester** [comment]
@afrittoli I think we should backport this to 0.65. The reason is that it appears in the [changelog of `v0.63.0`](https://github.com/tektoncd/pipeline/releases/tag/v0.63.0) as a new feature supported, which… doesn't work (hence the initial `kind/bug`). How does that sound ?

**Comment by afrittoli** [comment]
Sounds good to me, feel free to change the label back if you prefer. I thought the feature label would give it more prominence in the release notes, but we can highlight it as a bug fix too

**Pull request merged**
