### PR TITLE
Update resources.md

### PR DESCRIPTION
**Pull request by jonjohnsonjr**
Apologies for the pedantry. The image spec is a different thing from the image layout.

### CODE REVIEW

**Comment by bobcatfish** [comment]
image

**Comment by dlorenc** [comment]
This is the most @jonjohnsonjr pr ever

**Comment by jonjohnsonjr** [comment]
> This is the most @jonjohnsonjr pr ever

Words have meaning!

**Comment by bobcatfish** [comment]
amazing

**Pull request merged**
