### PR TITLE
docs: Added instructions on how to access the git repo by  github token

### PR DESCRIPTION
**Pull request by digimonster**
Added instructions on how to access the git repo by  github token

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) to build and release this image.

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md) are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes) must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS) and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes) must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS), and they must first be added [in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

# Release Notes

```
Describe any user facing changes here, or delete this block.

Examples of user facing changes:
- API changes
- Bug fixes
- Any changes in behavior

```

### CODE REVIEW

**Comment by dibyom** [comment]
@digimonster would you mind signing the CLA. Otherwise
/lgtm

**Comment by digimonster** [comment]
@googlebot I signed it!

**Comment by digimonster** [comment]
@googlebot I fixed it.

**Comment by digimonster** [comment]
@googlebot I fixed it.

**Comment by digimonster** [comment]
@googlebot I fixed it.

**Comment by digimonster** [comment]
@googlebot I fixed it.

**Comment by digimonster** [comment]
@dibyom  @vdemeester Sorry to keep you waiting. I have signed the CLA.

**Comment by popcor255** [comment]
@digimonster I think you need to pull from master again, since there seems to be changes from your initial PR.

**Comment by vdemeester** [comment]
removed lgtm temporarly to unblock the merge queue
@digimonster can you rebase/force-push to force the EasyCLA check to run ? :angel:

**Comment by bobcatfish** [comment]
@digimonster do you still want to go ahead with this? It looks like we're nearly ready to merge!

**Comment by sbwsg** [comment]
I'm closing for now but please feel free to reopen @digimonster if you want to push it over the finish line!

**Pull request closed without merging**
