### PR TITLE
Remove bobcatfish and lbernick from OWNERS 😿

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

@bobcatfish and @lbernick are not working on tektoncd anymore, thus it
doesn't make sense to keep them as OWNERS in the project.

Thank you both for everything you did on the project 🤗.

Signed-off-by: Vincent Demeester <vdemeest@redhat.com>

/kind misc
/meow sad

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) if any changes are user facing, including updates to minimum requirements e.g. Kubernetes version bumps
- [ ] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] [pre-commit](https://github.com/tektoncd/pipeline/blob/main/DEVELOPMENT.md#install-tools) Passed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [ ] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings). See some examples of [good release notes](https://github.com/tektoncd/community/blob/main/standards.md#good-release-notes).
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by vdemeester** [comment]
@chitrangpatel I think `pull-tekton-pipeline-go-coverage-df` is not required (look at the tide check) so I think we are fine with it being 🔴

**Comment by chitrangpatel** [comment]
Thank you @bobcatfish, @lbernick !!!
/approve

**Comment by lbernick** [comment]
❤️

**Comment by afrittoli** [comment]
Sad PR :(
/lgtm

**Comment by vdemeester** [comment]
```
repository 'https://github.com/$(tasks.split-full-repo-name.results.repoOwner)/$(tasks.split-full-repo-name.results.repoName).git/' not found
```
🤔

**Comment by vdemeester** [comment]
@tektoncd/plumbing-maintainers there is an issue with the reports of the tekton-powered jobs. `pull-tekton-pipeline-go-coverage-df` is still running but the check is marked as successful already.

**Comment by vdemeester** [comment]
(It did succeed this time though)

**Pull request merged**
