### PR TITLE
Replace hardcoded value

### PR DESCRIPTION
**Pull request by pavanstarmanwar**
# Changes

- [x] Update code to replace hardcoded values for `alpha` and `beta`

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [ ] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [ ] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]

**Review by jerop — COMMENTED** [review]
/ok-to-test

**Comment by pritidesai** [comment]
Thank you @pavanstarmanwar for the fix!

Please make sure to only include one commit which is related here in this PR - https://github.com/tektoncd/pipeline/pull/6122/commits/b1d6382e7dc0b88560d382845d6cd43ccc83f4fe

The additional [commit](https://github.com/tektoncd/pipeline/pull/6122/commits/19965469e8a4f011597b9a46ca1bba2f26e6d847) is part of the other PR #6121.

Also, please make sure to submit the checklist in the PR description. Thanks!

**Comment by pritidesai** [comment]
thank you @pavanstarmanwar 👍 
/lgtm

**Pull request merged**
