### PR TITLE
Rewrite the "Pod Templates" documentation for clarity and flow.

### PR DESCRIPTION
**Pull request by sergetron**
# Changes

Rewrites the "Pod Templates" documentation for clarity and flow.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [X] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [X] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [X] Release notes block has been filled in or deleted (only if no user facing changes)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) to build and release this image.

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md) are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes) must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS) and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes) must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS), and they must first be added [in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

# Release Notes

 ```release-note
NONE
 ```

### CODE REVIEW

**Comment by sergetron** [comment]
Needs approval - pretty please?

**Comment by sbwsg** [comment]
Would you be open to rewriting the table HTML as markdown?  https://github.github.com/gfm/#tables-extension-

We use the markdown syntax, for example, in https://github.com/tektoncd/pipeline/blob/master/docs/variables.md

**Comment by sergetron** [comment]
If there's a strong feeling against HTML tables, I can convert it to
markdown no problem. From my experience, markdown tables tend to get really
messy if you need more than a line of text or nested/bulleted content,
which is why I normally go for simple HTML that's understood by most
renderers.

**Comment by sbwsg** [comment]
If you think the HTML tables are best for this then 👍 . Is it possible to use markdown for, e.g. the \<a\> links if the content is in an HTML table?  If we're sticking with raw HTML then I'd also suggest making the header \<td\>s into \<th\>s instead, which should allow you to drop the \<b\> tags in those cells since \<th\>s are typically bolded by default in stylesheets and/or the user agent.  Additionally suggest wrapping the top row in a \<thead\> rather than \<tbody\>.

**Comment by sergetron** [comment]
From my experience working on past projects, Markdown tables are only good
for very simple 2-3 column layouts with 1-2 lines of text per cell. Beyond
that, especially if you want to do things like bulleted lists, hyperlinks,
code formatting, and so on, they fall apart.

And you're totally right, <td> and <tbody> makes a lot more sense than what
I did, let me update those.

**Comment by sergetron** [comment]
*<th> instead of <td> that is!

**Comment by sergetron** [comment]
All fixed.

**Comment by sergetron** [comment]
Needs re-LGTM please!

**Pull request merged**
