### PR TITLE
Add Configuration for Metrics Cardinality Simplification

### PR DESCRIPTION
**Pull request by khrm**
Number of metrics produced can be reduced by controlling the depth or the level using configmap. Available levels are namespace, run pipelinerun/taskrun or pipeline/task. Also, type of metrics can be changed from histogram to prometheus gauge/opencensus last value. Doing this will reduce the load on metrics databases. Implementation of https://github.com/tektoncd/community/pull/466
 

# Changes

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [x] [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [ ] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Release notes block below has been filled in or deleted (only if no user facing changes)

# Release Notes

```release-note
Metrics tags/labels type on taskrun/pipelinerun and task/pipeline can be eliminated metrics using configmap. Also, the type of metrics for duration - histogram or gauge/last value, can also be configured.
```

### CODE REVIEW

**Comment by khrm** [comment]
/test pull-tekton-pipeline-integration-tests


/test pull-tekton-pipeline-alpha-integration-tests
--


<br class="Apple-interchange-newline">

**Review by vdemeester — APPROVED** [review]

**Pull request merged**
