### PR TITLE
Refactor TaskParam and PipelineParam.

### PR DESCRIPTION
**Pull request by EliZucker**
# Changes
_Taken directly from commit message:_

Make a new `ParamSpec` type and place it in its own file along with the
already existing `Param` type. `ParamSpec` replaces `TaskParam` and
`PipelineParam`.

`TaskParam` and `PipelineParam` are identical types, and with future
features including array/string parameters, consolidating
parameter-related code in `param_types.go` makes sense for better
code-reusability and logical structure.

Additionally, I think "ParamSpec" is a better name; `TaskParam` and
`PipelineParam` currently represent a name and description (with
potentially more information in the future such as whether the parameter
is an array or string), while the `Param` type represents the parameter
value itself. Previously, it was not as intuitive that `Param` contains
the actual parameter value, not `TaskParam` or `PipelineParam`.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added) **(no functionality changes)**
- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing) **(no user facing changes)**
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

# Release Notes

N/A

### CODE REVIEW

**Comment by EliZucker** [comment]
For context, I'm currently implementing a way for arrays to be accepted as parameters (#207), and I believe these changes will help improve code reusability for that feature. 

Either way, though, I still think that this is a good organizational change; almost everyone I have interacted with while trying to implement the feature had trouble keeping track of the difference between `Param` and `TaskParam` and their different purposes (and the same could be said for `Param`/`PipelineParam`).

**Comment by bobcatfish** [comment]
Thanks for the quick, well contained clean up @EliZucker !

If that test failure is a flake ( 🤞 ) then:

/lgtm
/meow space

**Comment by bobcatfish** [comment]
```
I0702 22:49:22.940] ERROR: tests timed out
I0702 22:49:22.940] >> Checking test results for taskrun
I0702 22:49:23.576] ERROR: test demo-pipeline-run-1-build-skaffold-app-fmxs7=SucceededUnknown but should be succeededtrue
I0702 22:49:23.577] ERROR: test demo-pipeline-run-1-deploy-web-q9w9w=SucceededFalse but should be succeededtrue
```

v interesting! 🤔 seems consistent anyway, looks like a real problem!

**Pull request merged**
