### PR TITLE
Fix controller create taskRun all the time after create task failed.

### PR DESCRIPTION
**Pull request by llhhbc**
When pipeline has multi taskRun, controller will create taskRun again and again if one taskRun create failed.

Signed-off-by: longhui.li <lilonghui123456@163.com>

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [ ] Release notes block has been filled in or deleted (only if no user facing changes)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) to build and release this image.

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md) are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes) must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS) and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes) must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS), and they must first be added [in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

# Release Notes

### CODE REVIEW

**Comment by pritidesai** [comment]
Thanks @llhhbc can you please explain your use case when you are running into this kind of failure? This is by design until `pipelinerun` eventually time out. Will help to troubleshoot if you can provide the errors you are running into.

**Comment by llhhbc** [comment]
> Thanks @llhhbc can you please explain your use case when you are running into this kind of failure? This is by design until `pipelinerun` eventually time out. Will help to troubleshoot if you can provide the errors you are running into.

@pritidesai  I have a pipelinerun that has 4 taskrun, but one taskrun name has upper case word. It will failed when create taskRun, then the pipelinerun controller will create all taskrun again.  In minitues, It will create so many taskrun that the system resource has reach the limit.

**Comment by llhhbc** [comment]
This is a bug fix for pipelinerun create taskrun again and again after create one taskrun failed. For example: I have a pipeline with 4 task,  then the pipelinerun controller will create 4 taskrun, but the third one create failed, but first and two is create success. And it will repeat this action again and again. Then my k8s will have many taskrun objects.

**Comment by sbwsg** [comment]
@llhhbc can you [create a bug report](https://github.com/tektoncd/pipeline/issues/new?assignees=&labels=kind%2Fbug&template=bug-report.md) for this?  I would like to see an example PipelineRun that reproduces the problem.  I'm not able to reproduce the behaviour described here running a Pipeline with a failing Task but I might be missing something.  A PipelineRun that reproduces the problem would make this much easier to verify and help debug.

In the report please include:
- What platform you are running on (bare metal / GKE / OpenShift etc)
- What k8s version you are running
- What Tekton Pipelines version your are using
- A short PipelineRun with embedded Pipeline spec that reproduces the problem for you

**Comment by llhhbc** [comment]
> @llhhbc can you [create a bug report](https://github.com/tektoncd/pipeline/issues/new?assignees=&labels=kind%2Fbug&template=bug-report.md) for this? I would like to see an example PipelineRun that reproduces the problem. I'm not able to reproduce the behaviour described here running a Pipeline with a failing Task but I might be missing something. A PipelineRun that reproduces the problem would make this much easier to verify and help debug.
> 
> In the report please include:
> 
> * What platform you are running on (bare metal / GKE / OpenShift etc)
> * What k8s version you are running
> * What Tekton Pipelines version your are using
> * A short PipelineRun with embedded Pipeline spec that reproduces the problem for you

I have create a bug report issue, any question welcome to ask.
ref https://github.com/tektoncd/pipeline/issues/3678

**Comment by sbwsg** [comment]
Thanks for opening the issue @llhhbc!  As noted by @pritidesai in that issue you're running quite an old version of Pipelines (0.10) and you're using v1alpha1 objects. This issue is already caught in the latest version of Pipelines because we've added validation for it.

I'm going to close this PR because it looks like the best step forward is to upgrade the version you're using.  If we need to discuss further then let's continue in the issue you opened.

**Pull request closed without merging**
