### PR TITLE
Add @chitrangpatel as an pipelines maintainer

### PR DESCRIPTION
**Pull request by dibyom**
# Changes

Chitrang has been a regular contributor to pipelines contributing many features such as sidecar logs, propagated params and workspaces, as well as the ongoing work around step reusability!

Reviews: https://github.com/tektoncd/pipeline/pulls?q=is%3Apr++reviewed-by%3Achitrangpatel+-author%3Achitrangpatel

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) if any changes are user facing, including updates to minimum requirements e.g. Kubernetes version bumps
- [ ] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [ ] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [ ] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including functionality, content, code)
- [ ] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [ ] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings). See some examples of [good release notes](https://github.com/tektoncd/community/blob/main/standards.md#good-release-notes).
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by pritidesai — APPROVED** [review]
thanks @chitrangpatel for all the contributions and hard work, very exciting 🎉

**Review by Yongxuanzhang — APPROVED** [review]
🎉 congrats!!

**Review by jerop — APPROVED** [review]
/meow

**Pull request merged**
