### PR TITLE
Uncomment tests in v1 task_validation_test.go

### PR DESCRIPTION
**Pull request by lbernick**
# Changes
This commit uncomments tests that were accidentally commented out.
No functional changes.

/kind bug

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- n/a Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [x] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- n/a Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- n/a Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by Yongxuanzhang — COMMENTED** [review]
Thanks for raising this PR! I also feel confused when working on ArrayOrString renaming. https://github.com/tektoncd/pipeline/pull/5304
Do you mind rebasing from main and renaming NewArrayOrString method? It is also renamed

**Comment by lbernick** [comment]
> Do you mind rebasing from main

Done

> and renaming NewArrayOrString method?

I don't see this in v1?

**Comment by Yongxuanzhang** [comment]
> > Do you mind rebasing from main
> 
> Done
> 
> > and renaming NewArrayOrString method?
> 
> I don't see this in v1?

It should be this one https://github.com/tektoncd/pipeline/blob/8413f854c11723ce2e0917284e4424ad4d4a9b5b/pkg/apis/pipeline/v1/param_types.go#L265-L276

**Pull request merged**
