### PR TITLE
Put workspace-in-sidecar example into no-ci

### PR DESCRIPTION
**Pull request by sbwsg**
# Changes

The workspace-in-sidecar example has been a relatively
consistent flake in our CI suite. The issue https://github.com/tektoncd/pipeline/issues/4169
was created in August describing this problem and
there have been relatively regular reports related to the
example since then. To a first approximation I've found 31
individual instances of the test's failure since May across
24 separate Pull Requests.

Attempts to reduce the flakiness of this example have not
been successful yet. So in order to reduce the amount of noise
in our CI (and hopefully increase overall trust in the suite)
this commit moves the example into the no-ci folder, preventing
its execution, while we continue to try and figure out why it
is so flakey.

Just to reiterate here: there's no intention to ignore
the workspace-in-sidecar example's flakiness. I'm still looking into it. But
the overall noise it adds to our CI results, I would argue, messes with the confidence
we place in the suite.

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [x] [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Release notes block below has been filled in or deleted (only if no user facing changes)

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by sbwsg** [comment]
Here's a [permanent link to the failed test run output](https://tekton-releases.appspot.com/build/tekton-prow/pr-logs/pull/tektoncd_pipeline/4380/pull-tekton-pipeline-alpha-integration-tests/1461082316183965697/).

Failed Test: `test/v1alpha1 TestSidecarTaskSupport/A_sidecar_that_runs_forever_is_terminated_when_Steps_complete`

Ran for `10m12s` according to the test runner. The TaskRun under test has its timeout field set to `1m`, so that's quite a disparity.

The test runner reported the following:

```
    sidecar_test.go:100: Creating Task "sidecar-test-task-0"
    sidecar_test.go:105: Creating TaskRun "sidecar-test-task-run-0"
    sidecar_test.go:129: Error waiting for Pod "sidecar-test-task-run-0-pod" to terminate both the primary and sidecar containers: timed out waiting for the condition
    sidecar_test.go:150: Sidecar container has a nil Terminated status but non-nil is expected.
    sidecar_test.go:158: Either the primary or sidecar containers did not terminate
```

Both the sidecar and steps are reported as successful in the captured TaskRun, and both have a non-nil `terminated` field:

```
        status:
          completionTime: "2021-11-17T21:34:31Z"
          conditions:
          - lastTransitionTime: "2021-11-17T21:34:31Z"
            message: All Steps have completed executing
            reason: Succeeded
            status: "True"
            type: Succeeded
          podName: sidecar-test-task-run-0-pod
          sidecars:
          - container: sidecar-sidecar-container
            imageID: docker-pullable://gcr.io/tekton-prow-6/tpipeline-e2e-img/nop-8eac7c133edad5df719dc37b36b62482@sha256:acb6b4cd4957beee021d31a3ac1d533ecd4f3f35085a8881068a57e63953a14d
            name: sidecar-container
            terminated:
              containerID: docker://5e9c5e88e389caac2efad56790b50fb1bcfe3c575ec96fe68b10b33005e4fde7
              exitCode: 0
              finishedAt: null
              message: Sidecar container successfully stopped by nop image
              reason: Completed
              startedAt: null
          startTime: "2021-11-17T21:34:22Z"
          steps:
          - container: step-primary
            imageID: docker-pullable://busybox@sha256:e7157b6d7ebbe2cce5eaa8cfe8aa4fa82d173999b9f90a9ec42e57323546c353
            name: primary
            terminated:
              containerID: docker://55fb66dd40f5d695ea7378f1ed51d5eb895e37fe9cc117e3868f18ed6951ef61
              exitCode: 0
              finishedAt: "2021-11-17T21:34:30Z"
              reason: Completed
              startedAt: "2021-11-17T21:34:30Z"
```

The creation timestamp on the TaskRun is `2021-11-17T21:34:20Z` so it looks like it took about 10 seconds from creation to termination, at least as far as the cluster-under-test was concerned.

**Review by afrittoli — COMMENTED** [review]
/approve

**Review by vdemeester — COMMENTED** [review]
/lgtm

**Pull request merged**
