### PR TITLE
Add Restful API document

### PR DESCRIPTION
**Pull request by anxinyf**
Issue: https://github.com/tektoncd/pipeline/issues/2055

# Changes
Add Restful API document

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) to build and release this image.

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md) are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes) must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS) and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes) must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS), and they must first be added [in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

# Release Notes

```
The document is for describing Pipeline restful API.
```

### CODE REVIEW

**Comment by mattmoor** [comment]
cc @ahmetb wrote a tool that generates docs from `./pkg/apis`

**Comment by anxinyf** [comment]
Actually, I have a swagger yaml, include Pipeline, Triggers and Dashboard, like this:

image

**Comment by bobcatfish** [comment]
@anxinyf  this looks great!

One thing that would stop us from merging this as-is however is that if we make any API changes, we'll have to change the doc that you are adding as well, and folks (including me) tend to have a hard time trying to remember to update that kind of thing manually. Since it's such an important reference doc, and something we'd want to version so that we can have versions for each release, it's important that we add automation to easily generate this and keep it up to date.

@mattmoor mentioned above a tool that can do this, I think the ideal scenario would be something like adding logic that runs on every PR (maybe like update-docs.sh or something?) that generates these docs, and we flag PRs that need an update (like we do with [update-codegen.sh](https://github.com/tektoncd/pipeline/blob/master/DEVELOPMENT.md#iterating)).

What do you think?

/hold

**Comment by anxinyf** [comment]
Yes! if so, that would be great. :D

This PR could be closed.

**Pull request closed without merging**
