### PR TITLE
Promote `onerror` Tasks to beta

### PR DESCRIPTION
**Pull request by chitrangpatel**
# Changes

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [x] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) if any changes are user facing, including updates to minimum requirements e.g. Kubernetes version bumps
- [x] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] [pre-commit](https://github.com/tektoncd/pipeline/blob/main/DEVELOPMENT.md#install-tools) Passed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [x] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings). See some examples of [good release notes](https://github.com/tektoncd/community/blob/main/standards.md#good-release-notes).
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
Promote Ignore Task Failure to Beta
```
/kind feature

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
cc @afrittoli @JeromeJu

**Comment by pritidesai** [comment]
Thanks a bunch @chitrangpatel for this promotion. We are planning to utilize this feature in our deployment. While we are experimenting with this feature, we ran into the following limitation. 

* Not able to access task's status (specifically reason) in `finally` tasks

`tkn` describes the list of taskRuns as expected:

```
🗂  Taskruns

 NAME                                                  TASK NAME       STARTED         DURATION   STATUS
 ∙ pipelinerun-with-failing-task-8lz7x-finish          finish          4 minutes ago   4s         Succeeded
 ∙ pipelinerun-with-failing-task-8lz7x-echo-fail       echo-fail       4 minutes ago   4s         Failed
 ∙ pipelinerun-with-failing-task-8lz7x-echo-continue   echo-continue   4 minutes ago   4s         Failed(FailureIgnored)
```

But in a finally task, how to distinguish between a failed task and a task with failure ignored.

At the time of designing `onError` feature at the `step` level, [the step exit code is made available to subsequent steps](https://github.com/tektoncd/pipeline/blob/main/docs/tasks.md#accessing-steps-exitcode-in-subsequent-steps). Similarly, we are looking for a way to classify a task which failed but with `FailureIgnored`.

**Comment by vdemeester** [comment]
@pritidesai we probably want to create a follow-up issue for this 👼🏼

**Comment by pritidesai** [comment]
> @pritidesai we probably want to create a follow-up issue for this 👼🏼

https://github.com/tektoncd/pipeline/issues/8110

Would this require a TEP? 😸

**Comment by chitrangpatel** [comment]
> > @pritidesai we probably want to create a follow-up issue for this 👼🏼
> 
> #8110
> 
> Would this require a TEP? 😸

I don't think a TEP will be required here since it's not adding new fields. It's providing access to existing fields via substitutions so I think we can probably justify it over an issue and implement it.

**Pull request merged**
