### PR TITLE
Migrate Propagated Workspaces to Stable

### PR DESCRIPTION
**Pull request by chitrangpatel**
[Issue 6107](https://github.com/tektoncd/pipeline/issues/6107) Migrate Propagated Workspaces to Stable

Prior to this, propagated workspaces was hidden behind the beta feature gate. This feature is now a stable feature.

# Changes

- Removed alpha/beta API fields  
# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [x] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [x] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [x] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
Propagated workspaces is now a stable feature.
```

### CODE REVIEW

**Comment by chitrangpatel** [comment]
cc @pritidesai @jerop

**Review by jerop — APPROVED** [review]
/hold 

@tektoncd/core-maintainers please take a look

**Review by vdemeester — APPROVED** [review]

**Review by jerop — COMMENTED** [review]
thanks for the review @vdemeester!

/lgtm
/unhold

**Pull request merged**
