### PR TITLE
Fix little typo

### PR DESCRIPTION
**Pull request by tomfrenken**

### CODE REVIEW

**Comment by tomfrenken** [comment]
@googlebot I signed it!

**Comment by tomfrenken** [comment]
@googlebot I signed it!

**Comment by tomfrenken** [comment]
@googlebot I signed it!

**Comment by sbwsg** [comment]
@tomfrenken i'm not sure exactly how the CLA bot works but right now when I tell it to scan this PR I get the following error message:

```
tomfrenken | 54979414+tomfrenken@users.noreply.github.com | need_sender_cla
```

When you signed the CLA did you use this email address?  It's the email used in the author line of your commit.

**Comment by afrittoli** [comment]
> @tomfrenken i'm not sure exactly how the CLA bot works but right now when I tell it to scan this PR I get the following error message:
> 
> ```
> tomfrenken | 54979414+tomfrenken@users.noreply.github.com | need_sender_cla
> ```
> 
> When you signed the CLA did you use this email address? It's the email used in the author line of your commit.

Thanks @sbwsg - I was just chatting with @tomfrenken on slack about the same issue - the email address in the commit message needs to be fixed.

**Comment by tomfrenken** [comment]
Alright, thank y'all for your help with my Google bot odyssey - should work now, just needs the lgtm label back

**Pull request merged**
