### PR TITLE
Sorted linters -- because neatness counts.

### PR DESCRIPTION
**Pull request by bendory**
# Changes

This PR simply sorts the enabled linters for neatness.

There are no functional changes in this PR.

/kind cleanup

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [N/A] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [N/A] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [N/A] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [N/A] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by Yongxuanzhang** [comment]
/lgtm thanks!
One more thought, I noticed that we have added a ref link in the yaml file. Just wonder if it makes sense to add some docs around https://github.com/tektoncd/pipeline/blob/main/DEVELOPMENT.md to tell developers how to run these check locally? So they don't need to fail until they open the PR

**Comment by bendory** [comment]
#5899

**Comment by bendory** [comment]
> One more thought, I noticed that we have added a ref link in the yaml file. Just wonder if it makes sense to add some docs around https://github.com/tektoncd/pipeline/blob/main/DEVELOPMENT.md to tell developers how to run these check locally? So they don't need to fail until they open the PR

Great idea!
Added #5900

**Comment by bendory** [comment]
oops!

/assign lbernick

**Review by lbernick — APPROVED** [review]

**Pull request merged**
