### PR TITLE
TEP0152 - Complete V1 conformance test suite

### PR DESCRIPTION
**Pull request by JeromeJu**
# Changes
This PR consists of the V1 `REQUIRED` fields for v1 conformance.

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [x] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) if any changes are user facing, including updates to minimum requirements e.g. Kubernetes version bumps
- [x] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] [pre-commit](https://github.com/tektoncd/pipeline/blob/main/DEVELOPMENT.md#install-tools) Passed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [ ] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings). See some examples of [good release notes](https://github.com/tektoncd/community/blob/main/standards.md#good-release-notes).
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by chitrangpatel** [comment]
For clarity and easy to read, I would suggest moving the yamls to individual files under `testdata` folder or something. 
And then add something that reads those yamls and runs the test. That would make it easy to parse and read (atleast to know which cases we have covered) and add more tests in the future.

**Comment by JeromeJu** [comment]
> For clarity and easy to read, I would suggest moving the yamls to individual files under `testdata` folder or something. And then add something that reads those yamls and runs the test. That would make it easy to parse and read (atleast to know which cases we have covered) and add more tests in the future.

Adding some outputs for the offline discussion we had - this is not done as fof the case of this PR mainly because we are having customized inputs for the YAML (which, potentially, could cause invalid YAML error with '%s' inputs in the files if we separate them out in different files).

cc @tektoncd/core-maintainers @tektoncd/core-collaborators  PTAL 🙏

**Comment by JeromeJu** [comment]
cc @tektoncd/core-maintainers can i have a lgtm?

**Review by vdemeester — APPROVED** [review]
/lgtm

**Pull request merged**
