### PR TITLE
Move resolution of Pipeline Results to end of completed/successful reconcile

### PR DESCRIPTION
**Pull request by sbwsg**
Fixes https://github.com/tektoncd/pipeline/issues/3667

# Changes

We currently resolve Pipeline Results on the first reconcile _after_ a PipelineRun is completed.
This is bad because the resolution can fail. When that happens we overwrite the Succeeded condition
of the PipelineRun which means we're losing the final status info. It also means there's a
bit of time where the PipelineRun is in one completed state only to have it change to a different
completed state, potentially confusing any services watching PipelineRun conditions.

This commit moves the resolution of Pipeline Results to the end of a reconcile when the PipelineRun
is put into a Succeeded/True condition. The benefit of this is that we don't have to look up
the Pipeline data to compute the results since it's already available to us. This removes the
part of result resolution that could fail and means that we don't have to clobber the PipelineRun's
final state.

/kind bug

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [x] Release notes block has been filled in or deleted (only if no user facing changes)

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by sbwsg** [comment]
Unit tests have succeeded but looks like it hasn't been picked up by prow.  Trying again.

/test tekton-pipeline-unit-tests

**Review by vdemeester — APPROVED** [review]

**Comment by pritidesai** [comment]
thanks @sbwsg for the fix 👍 
/lgtm

**Pull request merged**
