### PR TITLE
Add examples for some resolvers

### PR DESCRIPTION
**Pull request by abayer**
# Changes

Note that there's no bundles resolver example at all for Pipeline, because I can't find a publicly available bundle containing a Pipeline. Also, the cluster resolvers for both Pipeline and Task are in `no-ci`, since they require an existing `Pipeline`/`Task` in another namespace in the cluster, and I didn't feel comfortable adding a new namespace to those examples. The hub resolver example for `Pipeline` is in `no-ci` because it's using https://github.com/tektoncd/catalog/blob/main/pipeline/buildpacks/0.2/buildpacks.yaml, which requires various tasks already be present.

For the moment, the git resolver example for `Pipeline` is also in `no-ci`, but the new file ./test/resolvers_yaml/pipeline-in-git.yaml is intended to be used in an updated git resolver example once this is merged and can be referenced in the example.

Also fixes a mistake I made in `docs/hub-resolver.md`.

/kind misc

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [x] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [x] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by abayer** [comment]
> would you mind also adding an example of how to replace a clustertask with the cluster resolver [here](https://github.com/tektoncd/pipeline/blob/main/docs/migrating-v1beta1-to-v1.md#todo-add-example-after-5404-is-merged)?

oops! I forgot about that, will do.

**Review by vdemeester — APPROVED** [review]

**Review by jerop — APPROVED** [review]
thanks for adding these examples @abayer!

/lgtm

**Pull request merged**
