### PR TITLE
Keep securitycontext fields simple in e2e

### PR DESCRIPTION
**Pull request by piyush-garg**
This will make securitycontext fields to be simple and easy in e2e so that tests can be run on different platform like openshift where runasUser 65532 and 2000 etc can fail, here we are just checking the conversion of fields so simple configuration will also do the job

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) if any changes are user facing, including updates to minimum requirements e.g. Kubernetes version bumps
- [ ] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [ ] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [ ] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including functionality, content, code)
- [ ] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [ ] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
Keep securitycontext fields simple in e2e
```

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]

**Comment by lbernick** [comment]
Related: https://github.com/tektoncd/pipeline/issues/3452 and https://github.com/tektoncd/pipeline/pull/6515
I wonder if we can also use `runAsNonRoot` instead of `runAsUser` for the pipelinerun controller and pod init containers?

@piyush-garg I'm looking at https://docs.openshift.com/container-platform/3.11/admin_guide/manage_scc.html to figure out which securitycontext fields are and aren't accepted and it's a bit unclear; it seems like `runAsUser` needs to match any `securityContextConstraints` defined, which is an openshift concept? Do you know if any other security context fields cause trouble on openshift or just this one?

Also, a release note that might be a bit clearer could be "allow e2e tests to run on openshift"

**Comment by lbernick** [comment]
@vdemeester we don't currently set security context for init containers but I was trying to add it in https://github.com/tektoncd/pipeline/pull/6515

**Comment by vdemeester** [comment]
> @vdemeester we don't currently set security context for init containers but I was trying to add it in #6515

ah right 🙃

**Comment by piyush-garg** [comment]
@lbernick Can you please take a look and merge this PR

**Comment by lbernick** [comment]
/lgtm

@piyush-garg can you please address the feedback on the release notes?

**Comment by piyush-garg** [comment]
> /lgtm
> 
> @piyush-garg can you please address the feedback on the release notes?

done, updated the release notes. Thanks for merging.

**Pull request merged**
