### PR TITLE
update cloudevents dependency and clean up deps

### PR DESCRIPTION
**Pull request by tariq1890**
# Changes

Why make this change? I am trying to work on a project that depends on kubernetes-test-infra which depends on this project in turn. In an effort to smooth out dep graphs in a clean way, I figured this PR would be a good first step instead of sledgehammering my way through `replace` directives.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) to build and release this image.

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md) are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes) must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS) and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes) must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS), and they must first be added [in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

# Release Notes

```
Describe any user facing changes here, or delete this block.

Examples of user facing changes:
- API changes
- Bug fixes
- Any changes in behavior

```

### CODE REVIEW

**Comment by tariq1890** [comment]
@sbwsg Fixed the failing unit tests.

**Comment by tariq1890** [comment]
@sbwsg Can this be merged?

**Comment by afrittoli** [comment]
Hi @tariq1890 - thanks for your patch. 
The patch looks ok, would you mind adding a bit of context for this change to the PR description?

**Comment by tariq1890** [comment]
@afrittoli @vdemeester @sbwsg I have updated the description.

**Comment by afrittoli** [comment]
Thanks for the extra context :)
/lgtm

**Comment by tariq1890** [comment]
When can we expect the next release of pipeline?

**Comment by sbwsg** [comment]
We're working on the next release but have a couple of PRs outstanding before we're ready to cut it.  The plan right now is to have it released this week.  We'll see how that goes!

**Pull request merged**
