### PR TITLE
Move over Resolution's reconciler-related code, update existing code to point to it

### PR DESCRIPTION
**Pull request by abayer**
# Changes

Part of #4710

This removes the dependency on the tektoncd/resolution repository, without making any changes to the code yet.

/kind misc

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [ ] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [x] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by abayer** [comment]
(I just force-pushed solely to change the date on the commit, because I like my commit dates to reflect when the PR was updated/created, not when I first authored the commit I ended up cherry-picking over to the PR branch)

**Review by jerop — APPROVED** [review]
thanks @abayer!

/lgtm

**Comment by jerop** [comment]
`TestSendKubernetesEvents` failed, is it a flake?

/test tekton-pipeline-unit-tests

**Comment by abayer** [comment]
> `TestSendKubernetesEvents` failed, is it a flake?

Yup - not as common as the cloud events ones were/are, but it shows up now and again.

**Pull request merged**
