### PR TITLE
Cherry-picks for Release v0.32.1

### PR DESCRIPTION
**Pull request by sbwsg**
# Changes

Cherry-picks for the v0.32.1 release of Tekton Pipelines.

No conflicts during picks on this release, woo!

### Patches, Oldest -> Newest
d8425c2 - @vdemeester label propagation patch
ef5a83c - @wlynch implicit params taskref patch
4186dc9 - @wlynch implicit params pipelinespec patch
ed1440f - @sbwsg golang images patch

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [x] [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Release notes block below has been filled in or deleted (only if no user facing changes)

# Release Notes
```release-note
NONE
```

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]

**Comment by sbwsg** [comment]
Unit tests failed with

```
pkg/reconciler/pipelinerun TestReconcile_InvalidPipelineRuns/invalid-pipeline-mismatching-parameter-types 0.18s
go run hack/e2e.go -v --test --test_args='--ginkgo.focus=pkg\/reconciler\/pipelinerun\sTestReconcile\_InvalidPipelineRuns\/invalid\-pipeline\-mismatching\-parameter\-types$'
          }
          }
    pipelinerun_test.go:1429: error in test pipeline-mismatching-param-type: received 2 events but 3 expected. Found events: []string{"Normal Started ", "Warning Failed PipelineRun foo/pipeline-mismatching-param-type parameters have mismatching types with Pipeline foo/a-pipeline-with-array-params's parameters: parameters have inconsistent types : [some-param]"}
```

This doesn't reproduce for me locally. Retrying.

/test tekton-pipeline-unit-tests

**Comment by sbwsg** [comment]
Sidecar integration test failed.  Retrying

/test pull-tekton-pipeline-integration-tests

**Pull request merged**
