### PR TITLE
adding unit tests for pipelineTaskList.Deps

### PR DESCRIPTION
**Pull request by pritidesai**
# Changes

Adding unit tests to validate `pipelineTaskList.Deps()` returning correct dependencies.

Changing `orderingDeps()` to avoid calling `resourceDeps()` and checking for duplicates since `pipelineTaskList.Dep()` returns a unique set of dependencies (using `sets`) for all `pipelineTask`s.

/kind misc

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [x] Release notes block has been filled in or deleted (only if no user facing changes)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) to build and release this image.

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md) are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes) must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS) and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes) must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS), and they must first be added [in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by jerop — COMMENTED** [review]
thanks for adding these tests @pritidesai!

given that you also fixed the check for uniqueness of deps, maybe we can add a test that has duplicate deps and validate that the elements in the deps list are unique...

**Comment by pritidesai** [comment]
> given that you also fixed the check for uniqueness of deps, maybe we can add a test that has duplicate deps and validate that the elements in the deps list are unique...

Good point @jerop, it had a [check](https://github.com/tektoncd/pipeline/pull/3597/files#diff-d9fe4959d0bc55f36760776722610fc295cbbc08c19692a404d4154869805696R104) where the same task (`task-1`) was specified in `runAfter` and also in `inputs`. I have added a separate test on uniqueness.

**Comment by bobcatfish** [comment]
Looks like this might be more instances of https://github.com/tektoncd/pipeline/issues/2656

/test pull-tekton-pipeline-integration-tests

**Review by jerop — APPROVED** [review]

**Review by vdemeester — APPROVED** [review]

**Comment by pritidesai** [comment]
`lgtm` please 🙏

**Pull request merged**
