### PR TITLE
Fix issue for upload of pullrequest resource

### PR DESCRIPTION
**Pull request by vincent-pli**
Seems the PR instance not `Unmarshal` from pr.json on the dist when uploading
fix issue: #1714 

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) to build and release this image.

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md) are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes) must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS) and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes) must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS), and they must first be added [in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

# Release Notes

```
Describe any user facing changes here, or delete this block.

Examples of user facing changes:
- API changes
- Bug fixes
- Any changes in behavior

```

### CODE REVIEW

**Comment by afrittoli** [comment]
Thanks! Is this a follow-up to https://github.com/tektoncd/pipeline/pull/1685/commits/c87aa7912f31daa85aaacb187cb09fe74dd498e2?

/assign @wlynch

**Comment by wlynch** [comment]
> Thanks! Is this a follow-up to [c87aa79](https://github.com/tektoncd/pipeline/commit/c87aa7912f31daa85aaacb187cb09fe74dd498e2)?
> 
> /assign @wlynch

I think this is aiming to solve the same issue as https://github.com/tektoncd/pipeline/pull/1693. It looks like there was a mix up when cherrypicking that commit for `v0.9.1`, since it relied on other changes post-v.0.9.0 release cut (the code for `v0.9.1` looks significantly different from master - in particular, `pkg/pullrequest` is completely missing).

@ImJasonH @afrittoli To solve #1704 I think we need to pick other [pullrequest-init commits](https://github.com/tektoncd/pipeline/commits/master/cmd/pullrequest-init) into the latest release. In particular:
* d478e7d Add gitlab support to the PR resource.
* 780d9bd Handle error opening missing pull-request parts.

I'm fine with proceeding with this change, but we should probably undo the changes made in #1693.

**Comment by vincent-pli** [comment]
@wlynch 
I hit the same issue with branch `master`, seems there are so many background.
Feel free to close this pr if it's duplicated, thanks.

**Comment by afrittoli** [comment]
> > Thanks! Is this a follow-up to [c87aa79](https://github.com/tektoncd/pipeline/commit/c87aa7912f31daa85aaacb187cb09fe74dd498e2)?
> > /assign @wlynch
> 
> I think this is aiming to solve the same issue as #1693. It looks like there was a mix up when cherrypicking that commit for `v0.9.1`, since it relied on other changes post-v.0.9.0 release cut (the code for `v0.9.1` looks significantly different from master - in particular, `pkg/pullrequest` is completely missing).
> 
> @ImJasonH @afrittoli To solve #1704 I think we need to pick other [pullrequest-init commits](https://github.com/tektoncd/pipeline/commits/master/cmd/pullrequest-init) into the latest release. In particular:
> 
>     * [d478e7d](https://github.com/tektoncd/pipeline/commit/d478e7d6d576d2e309c6a42ecf8da75c536df681) Add gitlab support to the PR resource.
> 
This is a rather large patch, but I guess it would be difficult to cherry-pick more changes without it?

>     * [780d9bd](https://github.com/tektoncd/pipeline/commit/780d9bd23a90ddf5282f737a4b42aa1253f62d4a) Handle error opening missing pull-request parts.
> 
> 
> I'm fine with proceeding with this change, but we should probably undo the changes made in #1693.

As per @vincent-pli comment, #1693 does not fix the upload issue even on master, and this patch works on top of #1693. Do we still need to revert #1693 then? If so it might be good to include the revert in this PR.

**Comment by ImJasonH** [comment]
Is this fix still needed with the changes at head and in v0.9.2?

**Pull request closed without merging**
