### PR TITLE
golang format tools

### PR DESCRIPTION
**Pull request by mattmoor**
Produced via:
  `gofmt -s -w $(find -path './vendor' -prune -o -type f -name '*.go' -print))`
  `goimports -w $(find -name '*.go' | grep -v vendor)`
/assign ImJasonH
/cc ImJasonH

### CODE REVIEW

**Comment by ImJasonH** [comment]
/hold

The robot needs to ignore third_party. If I close this it'll just open another one.

**Comment by vdemeester** [comment]
also, why is it back ? :stuck_out_tongue_closed_eyes:

**Comment by mattmoor** [comment]
Huh, I thought I changed this.  Maybe I didn't redeploy?

It's back because @ImJasonH asked for it!

**Comment by mattmoor** [comment]
Running it again, at a minimum I updated the PR description to match my update 🤔

**Pull request closed without merging**
