### PR TITLE
Pick up the cloudevents v2 RC1

### PR DESCRIPTION
**Pull request by mattmoor**
/assign @vdemeester @ImJasonH

### CODE REVIEW

**Comment by mattmoor** [comment]
@vdemeester I'm guessing the failure mails I saw were your infamous CI breakage? 🤣

**Comment by vdemeester** [comment]
> @vdemeester I'm guessing the failure mails I saw were your infamous CI breakage? :rofl: 

ahah I don't know what failure your are talking about :rofl: :robot: :sweat_smile:

**Comment by vdemeester** [comment]
@mattmoor needs a rebase :sweat_smile:

**Comment by mattmoor** [comment]
rebased

**Comment by vdemeester** [comment]
I think this needs https://github.com/tektoncd/plumbing/pull/352 to have the integration tests green :crossed_fingers:

**Comment by dibyom** [comment]
/hold

(Trying to get this out of merge pool so other blocked PRs can be merged)

**Comment by dibyom** [comment]
Cancelling hold once https://github.com/tektoncd/pipeline/pull/2444 is merged

**Pull request closed without merging**
