### PR TITLE
Update knative/pkg to v0.23 and k8s.io to v0.20.7

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

Bump k8s.io and knative dependencies to v0.20.7 and v0.23.0 respectively, taking latest fixes and features in.

/kind misc

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [ ] [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Release notes block below has been filled in or deleted (only if no user facing changes)

# Release Notes

```release-note
Bump k8s.io and knative dependencies to v0.20.7 and v0.23.0 respectively, taking latest fixes and features in.
```

### CODE REVIEW

**Comment by sbwsg** [comment]
It looks like this has regenerated openapi / swagger specs with new package names (they've dropped the `github.com/` prefix).

Otherwise the dep updates look good to me.

**Comment by vdemeester** [comment]
> It looks like this has regenerated openapi / swagger specs with new package names (they've dropped the `github.com/` prefix).

Arg, all the time it hits me..

**Comment by vdemeester** [comment]
/retest
The build job is green but reporting red.. and the other one seems to be a flaky cluster provisionning...

**Review by pradeepitm12 — COMMENTED** [review]
/lgtm

**Pull request merged**
