### PR TITLE
Support multiple secrets of type dockercfg and dockerconfigjson

### PR DESCRIPTION
**Pull request by SaschaSchwarze0**
# Changes

In the [documentation](https://github.com/tektoncd/pipeline/blob/master/docs/auth.md#understanding-credential-selection), Tekton explicitly claims to support this use case:

> For example, a `Run` might require access to multiple private Git and Docker repositories. 

Support is provided through the `Secret`s associated with the `TaskRun`s `ServiceAccount`. The implementation of the credentials code for Docker authentication already supported many credentials provided as basic-auth `Secret`s, also in combination with credentials defined in exactly one `Secret` of type dockercfg and/or dockerconfigjson. I am lifting the limitations on non basic-auth secrets. The Tekton code already creates Pod containers with multiple `-docker-config` arguments, but the consuming code only accepted one and therefore only honored the last item. One may argue whether this is a feature or fixes a bug.

/kind feature

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [X] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [X] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [X] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [X] Release notes block has been filled in or deleted (only if no user facing changes)

-> Docs linked from above is already good enough = it had not mentioned that only one Secret had been supported.

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md) are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes) must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS) and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes) must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS), and they must first be added [in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

# Release Notes

```release-note
Adds support for multiple secrets of type dockercfg or dockerconfigjson
```

### CODE REVIEW

**Comment by sbwsg** [comment]
/ok-to-test

/approve

Thanks for this!

**Comment by SaschaSchwarze0** [comment]
> [CLA Not Signed](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/8049964/146641150/3659?version=1)

Quick update on that: is in progress. I expect to get the approval of the responsible IBMer managing this today.

**Comment by SaschaSchwarze0** [comment]
Received the CLA approval with this statement:

> If you had previously submitted one or more pull requests to Continuous Delivery Foundation (CDF) that had failed, you should close and re-open the pull request to force a recheck by the EasyCLA system.

Based on that, I'll close this one and will try to re-open it.

**Comment by sbwsg** [comment]
The kind job looks like it's stuck.  I'm going to flip the labels to try and bring it back to life.

**Comment by SaschaSchwarze0** [comment]
Hi @sbwsg, anything else you need from me for this pull request?

**Comment by sbwsg** [comment]
> Hi @sbwsg, anything else you need from me for this pull request?

At this point we're waiting for someone else to review & lgtm it on top of my approve.

**Review by vdemeester — APPROVED** [review]
/meow
/lgtm

**Pull request merged**
