### PR TITLE
fix: poor Tekton controller performance impacted by redundant state calculation…

### PR DESCRIPTION
**Pull request by rafalbigaj**
Tekton controller performance is impacted by redundant existing and desired resource state difference calculation.

The state comparison using `kmp.SafeDiff(existing.Status, desired.Status)` in the `reconcilerImpl.updateStatus` method is costly and performed for debug logging purposes.
Issue: https://github.com/tektoncd/pipeline/issues/6193
Related knative.dev/pkg issue: https://github.com/knative/pkg/issues/2677

/kind Bug

# Changes

- knative.dev/pkg module bumped to `v0.0.0-20230215234751-2f55fe00c5a1`
- Reconcilers code regenerated to include poor performance fix

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [X] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [X] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [X] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [X] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [X] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [X] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [X] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by rafalbigaj** [comment]
CPU total usage and memory usage observed on the original code:
image

CPU total usage and memory usage observed after applying the fix:
image


Observed improvements:
- CPU total usage reduction: 60%
- Memory usage reduction: 44%

**Comment by pritidesai** [comment]
thank you @rafalbigaj for identifying such issue and proposing the fix for it.

This PR is essentially upgrading the knative/pkg like you mentioned in the PR description.

@vdemeester has a PR #6062 to upgrade knative/pkg which didnt make it in 0.45.

PR #6062 and this PR is upgrading the knative pkg which requires bumping kubernetes min version to 1.24. This knative pkg has fix for a significant performance bottleneck but with it changes kubernetes min version. With this, is it possible to cherrypick or backport this to any of our previous releases?

@vdemeester do you mind changing your PR #6062 to change knative.dev/pkg to `v0.0.0-20230215234751-2f55fe00c5a1` instead of `v0.0.0-20230117181655-247510c00e9d`? PR #6062 has all the necessary doc. updates as well. 

Or @rafalbigaj you want to bring in the doc updates from @vdemeester's PR which is easier for both of you. Thanks!

**Comment by vdemeester** [comment]
> @vdemeester do you mind changing your PR #6062 to change knative.dev/pkg to `v0.0.0-20230215234751-2f55fe00c5a1` instead of `v0.0.0-20230117181655-247510c00e9d`? PR #6062 has all the necessary doc. updates as well.

Ideally, we only track released version of knative/pkg, so we would need to wait for a 1.10 (or a backport?) — otherwise anyone running `./hack/upgrade-dependency.sh --upgrade` would overwrite that dependency and go back to 1.9.

**Comment by pritidesai** [comment]
> > @vdemeester do you mind changing your PR #6062 to change knative.dev/pkg to `v0.0.0-20230215234751-2f55fe00c5a1` instead of `v0.0.0-20230117181655-247510c00e9d`? PR #6062 has all the necessary doc. updates as well.
> 
> Ideally, we only track released version of knative/pkg, so we would need to wait for a 1.10 (or a backport?) — otherwise anyone running `./hack/upgrade-dependency.sh --upgrade` would overwrite that dependency and go back to 1.9.

Thank you @vdemeester 👍 I am not aware of the knative release cycle and possibility of integrating to a commit level. Whom can we involve from the Knative community to understand if the backporting of [this](https://github.com/knative/pkg/issues/2677) fix into 1.9 is possible?

**Comment by psschwei** [comment]
@pritidesai no prob, just cherry picked it into v1.9

**Comment by pritidesai** [comment]
thanks a bunch @psschwei for responding back while you are on vacation, appreciate it 🙏 

@rafalbigaj do you want to update this PR to bring the latest commit from knative 1.9? I have a list of changes [here](https://github.com/tektoncd/pipeline/compare/main...pritidesai:pipeline:cherrypick-knative-1.9?expand=1).

After chatting with @vdemeester offline, I have updated the controllers in 0.41 to bring in this fix (PR #6201). I will create similar PRs for the subsequent releases (0.42 through 0.45). We might create a patch for each of the releases.

**Comment by pritidesai** [comment]
I have PR to update `main` with the latest knative/pkg 1.9: https://github.com/tektoncd/pipeline/pull/6256
Closing this PR.

/close

**Pull request closed without merging**
