### PR TITLE
Upgrade all dependent package

### LINKED ISSUE #1313: Upgrade all dependent package
# Expected Behavior

Use the latest dependent package.

# Actual Behavior

Still use the older version package.

# Steps to Reproduce the Problem

For example, the version of `cloud.google.com/go` package is `v0.45.1` but we still use `v0.37.2`; and the version of `github.com/Azure/azure-sdk-for-go` is `v33.2.0` but we still use `v21.4.0`; and so on. So, we should upgrade these third-party packages.

# Additional Info

NO.

### PR DESCRIPTION
**Pull request by thinkerou**
# Changes

Upgrade all dependent third-party package.

Because some third-party have released many version, we still use the older version.

Closes #1313 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [n/a] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [n/a] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) and [TaskRun](../tekton/publish-run.yaml) to build and release this image

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md)
are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes)
must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS)
and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes)
must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS),
and they must first be added
[in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

# Release Notes

```
Describe any user facing changes here, or delete this block.

Examples of user facing changes:
- API changes
- Bug fixes
- Any changes in behavior

```

### CODE REVIEW

**Comment by afrittoli** [comment]
Hi - thank you for this PR!

Could you please provide a bit more context in the commit message / PR description - seee https://github.com/tektoncd/community/blob/master/standards.md#commit-messages; and possibly link an associated github issue?

**Comment by thinkerou** [comment]
@afrittoli thank your reply, I have updated, please review again, thanks!

**Comment by vdemeester** [comment]
@thinkerou @afrittoli fwiw I did the same using [`sec`](https://github.com/vdemeester/sec) : https://github.com/tektoncd/pipeline/compare/master...vdemeester:bump-deps

**Comment by afrittoli** [comment]
If we decide to upgrade dependencies - even with no specific need - we should at least do that at the beginning of a release cycle.

**Comment by thinkerou** [comment]
> @thinkerou @afrittoli fwiw I did the same using [`sec`](https://github.com/vdemeester/sec) : [master...vdemeester:bump-deps](https://github.com/tektoncd/pipeline/compare/master...vdemeester:bump-deps)

@vdemeester should I close the pr? thanks!

**Comment by thinkerou** [comment]
```
vendor/k8s.io/kubernetes/pkg/credentialprovider/config.go:63:22: undefined: os.UserHomeDir
```
`UserHomeDir` require go1.12+

We are using go version is `go1.12.1` (https://github.com/tektoncd/pipeline/blob/master/tekton/ko/Dockerfile#L4)?

**Comment by vdemeester** [comment]
@thinkerou right, let's close this one and go with the `sec` one (as it splits the updates :angel:). I am wondering if we want to automate that (I think knative did automate that).

We are still using 1.12 indeed. We may want to update soonish indeed.

Thanks for the PR :hugs: 

/close

**Pull request closed without merging**
