### PR TITLE
change tutorial to getting-started

### PR DESCRIPTION
**Pull request by popcor255**
# Changes

Change tutorial to getting started doc.
The docs in [tektoncd/triggers](https://github.com/tektoncd/triggers/tree/master/docs/getting-started) is pretty similar in content to the tutorial.md in this repo. Since, no other repo has a tutorial.md. I would like to re-purpose this for the getting-started guide. There are some updates that still need to made. I plan to make those changes later today in a different pr.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) to build and release this image.

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md) are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes) must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS) and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes) must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS), and they must first be added [in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

# Release Notes

```
Describe any user facing changes here, or delete this block.

Examples of user facing changes:
- API changes
- Bug fixes
- Any changes in behavior

```

### CODE REVIEW

**Comment by AlanGreene** [comment]
This content is referenced as a tutorial in a number of places, so are you proposing to change this?

At a minimum, the existing links in README.md, DEVELOPMENT.md, docs/install.md and docs/README.md will need to be updated to point to the new filename.

**Comment by popcor255** [comment]
> This content is referenced as a tutorial in a number of places, so are you proposing to change this?
> 
> At a minimum, the existing links in README.md, DEVELOPMENT.md, docs/install.md and docs/README.md will need to be updated to point to the new filename.

I understand that there are other references. Thank you for letting me know. I will double check the other repos to make sure there are not other references. When I said, " Since, no other repo has a tutorial.md". Im referring to the other projects such as triggers, cli, and dashboard. If we want to automate the website there should be some level of consistency. I think I should bring this up in an issue before trying to make this change.

**Pull request closed without merging**
