### PR TITLE
[release-v0.41.x] fix CI for LTS release

### PR DESCRIPTION
**Pull request by pritidesai**
# Changes

In PR #6201, we identified a failure with our CI system. Beta integrations tests are failing in PR #6201.  Our CI system has been updated to run beta tests but the code base in `release-v0.41.x` was not updated with necessary changes to run beta tests successfully. We discovered a list of PRs which needs to be cherry picked into `release-0.41.x` branch  for the tests to work.

Cherry picking the following PRs:

- https://github.com/tektoncd/pipeline/pull/5726
- https://github.com/tektoncd/pipeline/pull/5737
- https://github.com/tektoncd/pipeline/pull/6031

Go build was [failing](https://prow.tekton.dev/view/gs/tekton-prow/pr-logs/pull/tektoncd_pipeline/6213/pull-tekton-pipeline-build-tests/1628619442676043776#1:build-log.txt%3A2330) after cherry-picking these PRs:

```
/home/prow/go/src/github.com/tektoncd/pipeline is out of date. Please run hack/update-codegen.sh.

```

This PR has these commits along with the changes from `./hack/update-codegen.sh`.

/kind misc

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [ ] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [x] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
Fixing Tekton CI for release-v0.41.x
```

### CODE REVIEW

**Comment by pritidesai** [comment]
all tests are successful except `build` 😞

**Comment by pritidesai** [comment]
build is failing for such whitespace difference https://github.com/tektoncd/pipeline/commit/905ab3600072839de68d28d5fdb8adbbe08d04d2#diff-3f510508862df8900929bb0330c1bff4eae3555261a4b30b5cb0546f152d2c00L8 :(

**Comment by lbernick** [comment]
> build is failing for such whitespace difference [905ab36#diff-3f510508862df8900929bb0330c1bff4eae3555261a4b30b5cb0546f152d2c00L8](https://github.com/tektoncd/pipeline/commit/905ab3600072839de68d28d5fdb8adbbe08d04d2#diff-3f510508862df8900929bb0330c1bff4eae3555261a4b30b5cb0546f152d2c00L8) :(

@pritidesai what go version are you using? this should be fixed now (https://github.com/tektoncd/pipeline/issues/5771)

**Comment by pritidesai** [comment]
Do we require a specific version of Go such that `update-codegen.sh` generates valid resources? @Yongxuanzhang I noticed you recently [updated](https://github.com/tektoncd/pipeline/commit/c53681d7f58e066b0a26c2936621207d4ed2fcf2) some of the whitespaces which might be needed for the build in this PR.  What go version are you using?

**Comment by lbernick** [comment]
Hm I'm not sure if you need to cherrypick that PR but you might need to re-run `update-codegen` with go 1.19. I'm a bit confused because @abayer recently made it so that the go version for linting would be the same one defined in the pipelines repo (rather than the ci job in the plumbing repo) in https://github.com/tektoncd/pipeline/pull/5944

**Comment by pritidesai** [comment]
> Hm I'm not sure if you need to cherrypick that PR but you might need to re-run `update-codegen` with go 1.19. I'm a bit confused because @abayer recently made it so that the go version for linting would be the same one defined in the pipelines repo (rather than the ci job in the plumbing repo) in #5944

thanks @lbernick not sure why #5944 is not effective here?

I have been asking new contributors (@EmmaMunley and @pavanstarmanwar) to go by the version in `go.mod`. But looks like our CI is upgraded to run with `1.19`. I think its time we upgrade our go.mod to `1.19`, thoughts? Knative is still `1.18` if it at all plays any role here.

**Comment by lbernick** [comment]
Go 1.18 is past its EOL so I think it makes sense to upgrade.

**Comment by Yongxuanzhang** [comment]
> Do we require a specific version of Go such that `update-codegen.sh` generates valid resources? @Yongxuanzhang I noticed you recently [updated](https://github.com/tektoncd/pipeline/commit/c53681d7f58e066b0a26c2936621207d4ed2fcf2) some of the whitespaces which might be needed for the build in this PR. What go version are you using?

I'm using 1.20, I think if the version is >=1.19 it should be ok

**Comment by pritidesai** [comment]
🎉  finally all tests succeed now 🎉 

Looking for `lgtm` please , thanks! 🙏

**Comment by Yongxuanzhang** [comment]
/lgtm
Thanks!

**Comment by pritidesai** [comment]
This PR fixes the beta integration failures in a branch. The same fix is needed in release-v0.42 to fix the failure discovered in this dependency update PR - https://github.com/tektoncd/pipeline/pull/6202

/cherry-pick release-v0.42.x

**Pull request merged**
