### PR TITLE
Change `TaskRef` to string instead of a struct with just one field.

### PR DESCRIPTION
**Pull request by tejal29**
Addresses one of the redundancy for #138 
Right now, the `TaskRef` struct only declares field `Name`.
Defining a struct for a just 1 field makes yaml longer.
In attempt to make the pipleine config concise, this PR remoes `TaskRef` and replaces it with a string.
In future if we decide to add other fields like APIVersion, we can write reference it as "<taskname>:<version>".
Right now APIVersion is not declared and used at all, so removing it.

### CODE REVIEW

**Comment by bobcatfish** [comment]
I'm not sure we should go ahead with this - it does simplify the yaml but it also:

1) Isn't the format a k8s reference is supposed to be in (not sure if that's important or not!)
2) Will get in the way of duck typing later on, for which we would need to in fact add at least a `type` field to the reference (more important probably)

I don't feel like I'm even approaching being an expert on this topic tho so maybe @dlorenc @ImJasonH @jonjohnsonjr could chime in?

Re. [the kubernetes conventions](https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md#references-to-related-objects):

> References to specific objects, especially specific resource versions and/or specific fields of those objects, are specified using the ObjectReference type (or other types representing strict subsets of it).

**Comment by shashwathi** [comment]
@tejal29 : 

Object references are made in a separate struct because it needs API version and reference name. In TaskRef struct looks like API Version is missing, I would recommend adding that to struct and hold on to current yaml structure instead of removing the reference struct.

Ref: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.10/#objectreference-v1-core
If this change is implemented that you cannot refer to an object with API version, I agree there are no multiple versions now but in future it might be the case.
WDYT?

**Comment by pivotal-nader-ziada** [comment]
agree with @shashwathi and @bobcatfish, if we remove the struct, then we can't have an API version in the future

**Comment by bobcatfish** [comment]
kk sounds like we probably want to leave this as it is for now then. @tejal29 you also mentioned possibly encoding the version (and I guess eventually type) in the name field as well, but I think that makes this _more_ complicated in the long run - we have to start requiring strings of a certain format and parsing strings vs. trusting the fields

**Comment by tejal29** [comment]
How about we call it taskName https://github.com/kubernetes/community/blob/master/contributors/devel/api-conventions.md#object-references
> Object references should either be called fooName if referring to an object of kind Foo by just the name (within the current namespace, if a namespaced resource), or should be called fooRef, and should contain a subset of the fields of the ObjectReference type.

@shashwathi  an @pivotal-nader-ziada,  how are we going to support `Task` with different versions? 
They would probably belong to [`ObjectMeta`](https://github.com/kubernetes/apimachinery/blob/ed135c5b96450fd24e5e981c708114fbbd950697/pkg/apis/meta/v1/types.go#L93:6) but most of the fields there are read only
Why not use something which is more user friendly now?

**Comment by bobcatfish** [comment]
> how are we going to support Task with different versions?

I'm not sure about versions, but probably different types in the long run, as per [knative duck typing](https://docs.google.com/document/d/16j8C91jML4fQRQPhnHihNJUJDcbvW0RM1YAX2REHgyY/edit#heading=h.n8a530nnrb).

> Why not use something which is more user friendly now?

It doesn't seem significantly more user friendly - we're talking about one level of indentation:

image

The cost would be that if we change this later, we need to either support both (confusing for a user) or introduce a breaking change (bad for a user).

I'd rather stick with the k8s standard for object references.

**Comment by tejal29** [comment]
hmm but `fooName` is Kubernetes Object Reference std

**Comment by bobcatfish** [comment]
> hmm but `fooName` is Kubernetes Object Reference std

Oh I see what you're saying, `fooName` is better than `fooRef` if we flatten this.

So then I think it comes down to two questions:

1. Do we do this for all our references? I'd prefer to be consistent if we can
2. How likely we think we are to want to support different kinds of `Types` for those references?

If the answer to (2) is not very likely, then let's change all the `fooRefs` to `fooName`! My gut feeling is that this is limiting our options in the future with the API, but it's definitely simpler now.

Maybe we can see what @shashwathi or @pivotal-nader-ziada think now as a tie breaker.

**Comment by bobcatfish** [comment]
@tejal29 do you mind if we close this for now?

**Pull request closed without merging**
