### PR TITLE
Add Description to ResourceDeclaration

### PR DESCRIPTION
**Pull request by toshi0607**
# Changes

Add Description to ResourceDeclaration

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) to build and release this image.

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md) are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes) must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS) and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes) must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS), and they must first be added [in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

# Release Notes

```
we can see description in task resource
```

# test

kaniko.yaml
```kaniko.yaml
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: kaniko
spec:
  inputs:
    params:
      - name: DOCKERFILE
        description: Path to the Dockerfile to build.
        default: ./Dockerfile
      - name: CONTEXT
        description: The build context used by Kaniko.
        default: ./
      - name: EXTRA_ARGS
        default: ""
      - name: BUILDER_IMAGE
        description: The image on which builds will run
        default: gcr.io/kaniko-project/executor:v0.13.0
    resources:
      - name: source
        type: git
        description: description for git  # added

  outputs:
    resources:
      - name: image
        type: image
        description: description for image # added

  steps:
    - name: build-and-push
      workingdir: /workspace/source
      image: $(inputs.params.BUILDER_IMAGE)
      # specifying DOCKER_CONFIG is required to allow kaniko to detect docker credential
      # https://github.com/tektoncd/pipeline/pull/706
      env:
        - name: DOCKER_CONFIG
          value: /builder/home/.docker
      command:
        - /kaniko/executor
        - $(inputs.params.EXTRA_ARGS)
        - --dockerfile=$(inputs.params.DOCKERFILE)
        - --context=/workspace/source/$(inputs.params.CONTEXT)  # The user does not need to care the workspace and the source.
        - --destination=$(outputs.resources.image.url)
      securityContext:
        runAsUser: 0
```

apply
```
$ kubectl apply -f kaniko.yaml
```

describe
```
$ kubectl describe task kaniko
Name:         kaniko
Namespace:    default
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration:
                {"apiVersion":"tekton.dev/v1alpha1","kind":"Task","metadata":{"annotations":{},"name":"kaniko","namespace":"default"},"spec":{"inputs":{"p...
API Version:  tekton.dev/v1alpha1
Kind:         Task
Metadata:
  Creation Timestamp:  2020-01-13T03:44:32Z
  Generation:          1
  Resource Version:    33618597
  Self Link:           /apis/tekton.dev/v1alpha1/namespaces/default/tasks/kaniko
  UID:                 0259500c-35b7-11ea-b47e-42010a9200b8
Spec:
  Workspaces:  <nil>
  Inputs:
    Params:
      Default:      ./Dockerfile
      Description:  Path to the Dockerfile to build.
      Name:         DOCKERFILE
      Type:         string
      Default:      ./
      Description:  The build context used by Kaniko.
      Name:         CONTEXT
      Type:         string
      Default:
      Name:         EXTRA_ARGS
      Type:         string
      Default:      gcr.io/kaniko-project/executor:v0.13.0
      Description:  The image on which builds will run
      Name:         BUILDER_IMAGE
      Type:         string
    Resources:
      Description:  description for git
      Name:         source
      Type:         git
  Outputs:
    Resources:
      Description:  description for image
      Name:         image
      Type:         image
  Steps:
    Command:
      /kaniko/executor
      $(inputs.params.EXTRA_ARGS)
      --dockerfile=$(inputs.params.DOCKERFILE)
      --context=/workspace/source/$(inputs.params.CONTEXT)
      --destination=$(outputs.resources.image.url)
    Env:
      Name:   DOCKER_CONFIG
      Value:  /builder/home/.docker
    Image:    $(inputs.params.BUILDER_IMAGE)
    Name:     build-and-push
    Resources:
    Security Context:
      Run As User:  0
    Working Dir:    /workspace/source
Events:             <none>
```

# issue
https://github.com/tektoncd/pipeline/issues/1389

### CODE REVIEW

**Comment by chmouel** [comment]
/ok-to-test

Addin a unit/yaml test should be pretty easy, isnt it ?

**Comment by toshi0607** [comment]
@chmouel Thank you for review! Are you referencing `run_yaml_tests` and is what I have to do adding fields to `example/taskruns/optional-resources` (and fixing conflicts) ?

**Comment by chmouel** [comment]
yes, i mean adding a taskrun example with a pipelineresource which has a description in this directory : 

https://github.com/tektoncd/pipeline/tree/3ae789c25831b3240721437d6570b58097cd55d9/examples/taskruns

CI will run those example to make sure it can supports it.

**Comment by toshi0607** [comment]
@chmouel Thank you! added

**Comment by toshi0607** [comment]
I'm sorry, failed to squash. I created new PR
https://github.com/tektoncd/pipeline/pull/1875

**Comment by vdemeester** [comment]
/close
Let's discuss in the other one then :sweat_smile:

**Pull request closed without merging**
