### PR TITLE
Remove PodSecurityPolicy ✂️

### LINKED ISSUE #4112: PodSecurityPolicy deprecated in Kubernetes 1.21
# Expected Behavior
The released deployment manifest doesn't have deprecated resources listed in it.

# Actual Behavior
PodSecurityPolicy tekton-pipelines is listed in the deployment manifest which is a deprecated resource as of 1.21.

# Steps to Reproduce the Problem

1. Download the latest release yaml (tested with 0.26.0)

# Additional Info

- Kubernetes version: 1.21

  **Output of `kubectl version`:**
N/A

- Tekton Pipeline version:

0.26.0

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

PodSecurityPolicy is being deprecated in Kubernetes 1.21, and isn't
being exercised by our CI. Let's just remove it from the payload (the
`release.yaml` file).

Closes #4112 

Signed-off-by: Vincent Demeester <vdemeest@redhat.com>

/kind cleanup
/cc @tektoncd/core-collaborators 

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [ ] [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Release notes block below has been filled in or deleted (only if no user facing changes)

# Release Notes

```release-note
The PodSecurityPolicy shipped by Tekton is now removed as it is being deprecated in Kubernetes >= 1.21. See https://kubernetes.io/blog/2021/04/06/podsecuritypolicy-deprecation-past-present-and-future/ for more info
```

### CODE REVIEW

**Review by sbwsg — APPROVED** [review]

**Comment by afrittoli** [comment]
I don't see the rush for this TBH? Tekton min k8s version is 1.18, and PSP is not deprecated until 1.21.
We may have users that rely on the PSP in our release, and just removing it could break them.
We could al least give a few releases of notice?

Looking at https://kubernetes.io/blog/2021/04/06/podsecuritypolicy-deprecation-past-present-and-future/ a k8s replacement is not available yet, and PSP will still be available for a while. The alternative available today is admission controllers - so we could document that, or link to the k8s docs about that.

**Comment by vdemeester** [comment]
The corresponding issue is in 0.28 milestone, so I added it there. 
@afrittoli do you think we should/could move this to 0.29 or 0.30 instead ? 🤔

**Comment by sbwsg** [comment]
We should probably figure out what user migration for this would look like - can we document the best next step as part of release notes? At the moment it's not totally clear what those steps would look like.

Maybe moving back to 0.30 is a good idea, and giving one release of notice for 0.29 that this is going away?

**Comment by jerop** [comment]
@tektoncd/core-maintainers, it seems we're not ready to move ahead with this so considering moving it to the next milestone - maybe we can give a deprecation notice for in this release as @sbwsg suggested above?

**Review by jerop — COMMENTED** [review]
@tektoncd/core-maintainers, it seems we're not ready to move ahead with this so considering moving it to the next milestone - maybe we can give a deprecation notice for in this release as @sbwsg suggested above?

**Comment by dibyom** [comment]
>  maybe we can give a deprecation notice for in this release as @sbwsg suggested above?

Sounds good to me!

**Comment by dibyom** [comment]
/hold 
based on discussions in the pipeline wg, we are figuring out how to migrate users to PodSecurityAdmission

**Comment by HW-Owl** [comment]
@dibyom, we have also a strong interest to migrate to PodSecurityAdmission and are curious to see your solution.

Actually, we already tried some first steps. To achieve  ['restricted](https://kubernetes.io/docs/concepts/security/pod-security-standards/)' we just had to add 'runAsNonRoot = false' to 'securityContext' in various deployments.
Bigger problems are 'affinity-assistant' and 'eventlisteners', which are currently running with high privileges. We would be happy to see a solution where they could run in 'restricted' mode as default.

**Comment by vdemeester** [comment]
Closing this for the time being
/close

**Pull request closed without merging**
