### PR TITLE
Update comment on RunControllerName const

### PR DESCRIPTION
**Pull request by sbwsg**
# Changes

Prior to this commit the code comment for the `RunControllerName` const actually described the PipelineRun controller name.

This commit updates the code comment to correctly document the custom task controller name.

/kind documentation

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Release notes block below has been filled in or deleted (only if no user facing changes)

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
/retest

**Comment by pritidesai** [comment]
thanks @sbwsg 
/lgtm

**Pull request merged**
