### PR TITLE
Add versioned links to docs and examples for v0.9.0

### PR DESCRIPTION
**Pull request by afrittoli**
# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) to build and release this image.

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md) are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes) must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS) and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes) must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS), and they must first be added [in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

# Release Notes

```
Describe any user facing changes here, or delete this block.

Examples of user facing changes:
- API changes
- Bug fixes
- Any changes in behavior

```

### CODE REVIEW

**Comment by afrittoli** [comment]
I was hoping to merge this first and do the release right afterwards.
That means that for a few minutes those links will be broken, but in future, if someone checks out the tag, the link to the docs is there in the README.

**Comment by vdemeester** [comment]
@afrittoli make sense :angel: 
/hold cancel

**Comment by bobcatfish** [comment]
I think this was worth a shot but i just got pinged by someone who tried to follow the docs link for 0.9.0 and was confused why it was broken, so I think in the future it might be better to merge this after the release and tag are created?

**Comment by bobcatfish** [comment]
Or make sure we do it simultaneously! (With a Tekton Task maybe? :D)

**Comment by vdemeester** [comment]
> I think this was worth a shot but i just got pinged by someone who tried to follow the docs link for 0.9.0 and was confused why it was broken, so I think in the future it might be better to merge this after the release and tag are created?

Waw some people are quite quick then :thinking: To @afrittoli's point, "That means that for a few minutes those links will be broken, but in future, if someone checks out the tag, the link to the docs is there in the README.", I think this is worth merging before the release (aka having this commit in the release). Maybe we need to "automate" the commit in the release pipeline :angel:

**Pull request merged**
