### PR TITLE
Fix resolution getting started docs with correct parameters

### PR DESCRIPTION
**Pull request by ernesgonzalez33**
Change parameters in the resolver to the appropriate ones

# Changes

Fix resolution getting started docs with correct parameters

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [X] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [ ] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [X] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [X] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [X] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [X] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by lbernick — APPROVED** [review]
thanks @ernesgonzalez33! Can you please remove your release note? (there's not really anything actionable for people upgrading to a new release as a result of your change)

**Review by jerop — COMMENTED** [review]
/lgtm
/retest

**Pull request merged**
