### PR TITLE
Hygiene: enable additional linter presets.

### PR DESCRIPTION
**Pull request by bendory**
# Changes

This PR enables `golangci` presets format, import, metalinter, module, test, unused. 🧼 🧹

Code changes correspond to the issues found by linters -- specifically, the `goimports`
linter deterministically orders `import` statements for consistency.

There are no expected functional changes in this PR.

Context: https://github.com/tektoncd/pipeline/issues/5899

/kind cleanup

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [N/A] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [N/A] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [N/A] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [N/A] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by bendory** [comment]
I think the test failures are https://github.com/tektoncd/pipeline/issues/6228 -- waiting for that to resolve...

**Comment by JeromeJu** [comment]
> I think the test failures are #6228 -- waiting for that to resolve...
/retest
CI failures should be resolved by https://github.com/tektoncd/pipeline/pull/6239

**Review by lbernick — APPROVED** [review]

**Pull request merged**
