### PR TITLE
Fix typo in documentation

### PR DESCRIPTION
**Pull request by Areadrill**
# Changes

Quick fix of a typo in documentation.

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [x] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) if any changes are user facing, including updates to minimum requirements e.g. Kubernetes version bumps
- [ ] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [x] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings). See some examples of [good release notes](https://github.com/tektoncd/community/blob/main/standards.md#good-release-notes).
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

Release note:
```release-note
NONE
```

### CODE REVIEW

**Comment by JeromeJu** [comment]
Hi @Areadrill thanks for the fix.
Would you mind completing the required steps for CLA? And for doc changes like this we would not need release notes which are user facing.

**Comment by Areadrill** [comment]
Working on that

**Comment by JeromeJu** [comment]
Ahh just to clarify, we do not need release note but for the commit message format, we might still want to have release note None just like other PRs 😺  :
```release-note
NONE
```

**Comment by Areadrill** [comment]
Added

**Review by Yongxuanzhang — APPROVED** [review]

**Review by afrittoli — COMMENTED** [review]
Thank you for your contribution, much appreciated!
/lgtm

**Pull request merged**
