### PR TITLE
Use a subfolder in the release bucket

### PR DESCRIPTION
**Pull request by afrittoli**
The tekton release bucket shall host releases for all relevant
tekton projects. Pipeline should use its own dedicated subfolder.

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) to build and release this image.

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md) are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes) must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS) and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes) must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS), and they must first be added [in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

# Release Notes

```
Describe any user facing changes here, or delete this block.

Examples of user facing changes:
- API changes
- Bug fixes
- Any changes in behavior

```

### CODE REVIEW

**Comment by bobcatfish** [comment]
Just in time @afrittoli !! :laughing: 

@afrittoli can you also update our installation docs? https://github.com/tektoncd/pipeline/blob/master/docs/install.md#installing-tekton-pipelines-1

If we want to move the existing releases to this structure also i recommend we copy them (at least initially) so anyone trying to install based on the old location still can

**Comment by vdemeester** [comment]
@afrittoli can you add "Closes #57" in the description to closes the issue :angel:

**Comment by afrittoli** [comment]
> @afrittoli can you add "Closes #57" in the description to closes the issue 👼

uhm, that would point to pipeline #57

**Comment by vdemeester** [comment]
dang… "Closes tektoncd/plumbing#57" then :stuck_out_tongue_closed_eyes:

**Comment by afrittoli** [comment]
> Just in time @afrittoli !! 😆
> 
> @afrittoli can you also update our installation docs? https://github.com/tektoncd/pipeline/blob/master/docs/install.md#installing-tekton-pipelines-1
> 
> If we want to move the existing releases to this structure also i recommend we copy them (at least initially) so anyone trying to install based on the old location still can

Updated the docs, and created a copy of previous releases.

**Comment by afrittoli** [comment]
Can we cancel the hold now?

**Comment by vdemeester** [comment]
indeed :stuck_out_tongue_closed_eyes: 
/hold cancel

**Pull request merged**
