### PR TITLE
Add @jeromeJu as a pipelines maintainer

### PR DESCRIPTION
**Pull request by dibyom**
# Changes

Jerome has been consistently contributing to pipelines for a long while now. He drove much of the long and complicated v1 CRD migration in addition to his recent work around feature flags and software versioning. Along the way, he has racked up well over a 100+ reviews:

https://github.com/tektoncd/pipeline/pulls?q=is%3Apr++reviewed-by%3AJeromeJu+-author%3AJeromeJu+

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [x] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) if any changes are user facing, including updates to minimum requirements e.g. Kubernetes version bumps
- [x] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [x] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings). See some examples of [good release notes](https://github.com/tektoncd/community/blob/main/standards.md#good-release-notes).
- [x] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by Yongxuanzhang — APPROVED** [review]
🥳

**Review by jerop — APPROVED** [review]
Congratulations @JeromeJu 🎉 

/meow

**Review by vdemeester — APPROVED** [review]
🎉

**Review by afrittoli — COMMENTED** [review]
/approve
🎉

**Review by pritidesai — APPROVED** [review]
Welcome @JeromeJu, thank you for all the hard work 🙏

**Comment by jerop** [comment]
Congratulations @JeromeJu 👏🏾 

/lgtm
/woof

**Pull request merged**
