### PR TITLE
Adds Env to TaskRunSpec

### LINKED ISSUE #1606: Provide mechanism to set environment variables on TaskRuns
# Expected Behavior
Have similar API to knative-builds [TemplateInstantiationSpec](https://godoc.org/github.com/knative/build/pkg/apis/build/v1alpha1#TemplateInstantiationSpec) to provide environment variables to a TaskRun.

# Actual Behavior
Use work arounds.

# Steps to Reproduce the Problem

1.
2.
3.

# Additional Info

### PR DESCRIPTION
**Pull request by poy**
# Changes

Adds a `Env` field to `TaskRunSpec` to allow a user to set environment
variables on each step container. This mimics Knative-Build's
`TemplateInstantiationSpec`'s `Env` field.

Setting environment variables is useful for when a `TaskRun` author may
not know what variables are required ahead of time (e.g., Buildpacks).

fixes #1606

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [X] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [X] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [X] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) to build and release this image.

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md) are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes) must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS) and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes) must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS), and they must first be added [in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

# Release Notes

```
Describe any user facing changes here, or delete this block.

Examples of user facing changes:
- API changes
- Bug fixes
- Any changes in behavior

```

### CODE REVIEW

**Comment by ImJasonH** [comment]
/ok-to-test
/hold
(For 0.10)

I need to think about how this interacts with `task.spec.stepTemplate`. Probably the TaskRun should win any conflicts.

**Comment by poy** [comment]
@ImJasonH I followed the existing pattern established with implicitEnvVars hoping to do just that 😁

**Comment by bobcatfish** [comment]
Thanks for the contribution @poy! Before we merge this, we should discuss the design and make sure we want to add this - as mentioned in https://github.com/tektoncd/pipeline/issues/1606#issuecomment-558196354 this is something we have deliberately _not_ added support for in the past, so I'd like to dig a bit more into the use case you described in https://github.com/tektoncd/pipeline/issues/1606#issuecomment-558202941 so we can understand it a bit better before merging.

/hold

**Comment by cccfeng** [comment]
Hi everyone, it's nice to see some discussions and code changes on supporting dynamic environment variables. I would like to ask how can users support dynamic env through pipelineRun?

**Comment by poy** [comment]
Hey @cccfeng, I would recommend you join the discussion in #1606

**Comment by bobcatfish** [comment]
I'm assuming we can close this for now and continue the discussion in #1606 but plz reopen if I'm wrong @poy!

**Pull request closed without merging**
