### PR TITLE
Increase TaskTimeout in PipelineTaskTimout Test

### PR DESCRIPTION
**Pull request by nikhil-thomas**
Increase timeout to 60s from 20s.

The first task in this test pipeline takes more than 20s to start sometimes.
This makes the test flaky. 

ref:
 - Refactoring to use a lightweight image https://github.com/tektoncd/pipeline/pull/2118
 - Increase PipelineTask Timeout by 10s in e2e Test https://github.com/tektoncd/pipeline/pull/2101
 - PipelineTask Timeout e2e Test  https://github.com/tektoncd/pipeline/pull/2092

Signed-off-by: Nikhil Thomas <nikthoma@redhat.com>

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) to build and release this image.

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md) are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes) must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS) and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes) must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS), and they must first be added [in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

# Release Notes

```
Describe any user facing changes here, or delete this block.

Examples of user facing changes:
- API changes
- Bug fixes
- Any changes in behavior

```

### CODE REVIEW

**Comment by danielhelfand** [comment]
@nikhil-thomas Can you please show circumstances where this PipelineTask would take up to 60s? Or longer than 20s in general?

**Comment by nikhil-thomas** [comment]
> @nikhil-thomas Can you please show circumstances where this PipelineTask would take up to 60s? Or longer than 20s in general?

Sure, It takes `more than 20s` on a `fresh cluster`.
Fresh cluster
 - OpensShift on AWS
 - running this test right after `kind create cluster` (the test fails irregularly)

 I got consistent test passes for when I used `40s` timeout. I set `60s` as (40s + a margin)

In addition, as I understand the first task is supposed to complete (step: `sleep 1`, task timeout `60s`)
and the second task in the pipeline is supposed to hit the timeout (step: `sleep 10`,task timeout: `5s`)
so the higher timeout for the first task should not cause an issue.

**Comment by piyush-garg** [comment]
@danielhelfand On a fresh cluster, a pod needs to download the image before running and this is where the test fails, that's the reason I raised PR #2118 to use the lighter image.

**Comment by danielhelfand** [comment]
@piyush-garg I see, and thanks for further explaining and isolating it.

**Pull request merged**
