### PR TITLE
[release-v0.41.x] picking up latest changes in knative 1.8

### PR DESCRIPTION
**Pull request by pritidesai**
# Changes

This PR is a result of:

```
go get knative.dev/pkg@release-1.8
./hack/update-codegen.sh
```

`knative.dev/pkg` was recently updated to include a performance [fix](https://github.com/knative/pkg/pull/2687) which helped reduced the CPU usage by 61% and memory usage by 44% for huge pipelines. This PR is updating the tekton controllers to include that fix such that our LTS release can take advantage of this performance improvement.

The same fix was cherry picked in [knative.dev/pkg 1.9](https://github.com/knative/pkg/commits/release-1.9). Tekton pipeline was updated to use knative 1.9 post 0.45 in PR #6062. We have another PR https://github.com/tektoncd/pipeline/pull/6194 open to update pipeline controllers in the `main` branch.

/kind misc

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [ ] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [x] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
Bring the latest performance fix in knative/pkg which helps reduce CPU/Memory usage for huge pipelines.
```

### CODE REVIEW

**Comment by pritidesai** [comment]
the beta test failure is constant in all the attempts so far 😞:

```
Default change: During creation of nodepools or autoscaling configuration changes for cluster versions greater than 1.24.1-gke.800 a default location policy is applied. For Spot and PVM it defaults to ANY, and for all other VM kinds a BALANCED policy is used. To change the default values use the `--location-policy` flag.
Note: Your Pod address range (`--cluster-ipv4-cidr`) can accommodate at most 1008 node(s).
ERROR: (gcloud.beta.container.clusters.create) ResponseError: code=400, message=
	(1) Creation of node pools using node images based on Docker container runtimes is not supported in GKE v1.23. This is to prepare for the removal of Dockershim in Kubernetes v1.24. We recommend that you migrate to image types based on Containerd (examples). For more information, contact Cloud Support
	(2) Creation of node pools using node images based on Docker container runtimes is not supported in GKE v1.24+ clusters as Dockershim has been removed in Kubernetes v1.24.
2023/02/22 16:38:20 process.go:155: Step 'gcloud beta container clusters create --quiet --enable-autoscaling --min-nodes=1 --max-nodes=3 --scopes=cloud-platform --no-issue-client-certificate --project=tekton-prow-7 --region=us-central1 --machine-type=n1-standard-4 --image-type=cos --num-nodes=1 --network=tpipeline-e2e-net1628433604[252](https://prow.tekton.dev/view/gs/tekton-prow/pr-logs/pull/tektoncd_pipeline/6201/pull-tekton-pipeline-beta-integration-tests/1628433604252012544#1:build-log.txt%3A252)01[254](https://prow.tekton.dev/view/gs/tekton-prow/pr-logs/pull/tektoncd_pipeline/6201/pull-tekton-pipeline-beta-integration-tests/1628433604252012544#1:build-log.txt%3A254)4 --cluster-version=1.24.9-gke.2000 tpipeline-e2e-cls1628433604252012544' finished in 2.8496[255](https://prow.tekton.dev/view/gs/tekton-prow/pr-logs/pull/tektoncd_pipeline/6201/pull-tekton-pipeline-beta-integration-tests/1628433604252012544#1:build-log.txt%3A255)75s
2023/02/22 16:38:20 main.go:319: Something went wrong: starting e2e cluster: error creating cluster: error during gcloud beta container clusters create --quiet --enable-autoscaling --min-nodes=1 --max-nodes=3 --scopes=cloud-platform --no-issue-client-certificate --project=tekton-prow-7 --region=us-central1 --machine-type=n1-standard-4 --image-type=cos --num-nodes=1 --network=tpipeline-e2e-net1628433604252012544 --cluster-version=1.24.9-gke.2000 tpipeline-e2e-cls1628433604252012544: exit status 1
```

I am having hard time deciphering the failure but looks like a cluster is being created with 1.24, could that be an issue? 🤔 

Also, I checked two latest commits in [release-v0.41.x](https://github.com/tektoncd/pipeline/tree/release-v0.41.x) and noticed the `beta` tests were not part of the CI, wondering why? 

> @linux-foundation-easycla[bot]
> EasyCLA EasyCLA check passed. You are authorized to contribute.
> [Details](https://easycla.lfx.linuxfoundation.org/#/?version=2)
> @tekton-robot
> check-github-tasks-completed Job Successful.
> [Details](https://prow.tekton.dev/view/gs/tekton-prow/pr-logs/pull/tektoncd_pipeline/5960/check-github-tasks-completed/1611037801023803392)
> @tekton-robot
> check-pr-has-kind-label Job Successful.
> [Details](https://prow.tekton.dev/view/gs/tekton-prow/pr-logs/pull/tektoncd_pipeline/5960/check-pr-has-kind-label/1611039243600138240)
> @tekton-robot
> pull-tekton-pipeline-alpha-integration-tests Job succeeded.                     BaseSHA:9ee839025241dcaf1dc3b9086e3c5fdb0c4126c1
> [Details](https://prow.tekton.dev/view/gs/tekton-prow/pr-logs/pull/tektoncd_pipeline/5960/pull-tekton-pipeline-alpha-integration-tests/1611037802714107904)
> @tekton-robot
> pull-tekton-pipeline-build-tests Job succeeded.                     BaseSHA:9ee839025241dcaf1dc3b9086e3c5fdb0c4126c1
> [Details](https://prow.tekton.dev/view/gs/tekton-prow/pr-logs/pull/tektoncd_pipeline/5960/pull-tekton-pipeline-build-tests/1611037801594228736)
> @tekton-robot
> pull-tekton-pipeline-go-coverage Job succeeded.                     BaseSHA:9ee839025241dcaf1dc3b9086e3c5fdb0c4126c1
> [Details](https://prow.tekton.dev/view/gs/tekton-prow/pr-logs/pull/tektoncd_pipeline/5960/pull-tekton-pipeline-go-coverage/1611037802076573696)
> @tekton-robot
> pull-tekton-pipeline-integration-tests Job succeeded.                     BaseSHA:9ee839025241dcaf1dc3b9086e3c5fdb0c4126c1
> [Details](https://prow.tekton.dev/view/gs/tekton-prow/pr-logs/pull/tektoncd_pipeline/5960/pull-tekton-pipeline-integration-tests/1611037802097545216)
> @tekton-robot
> pull-tekton-pipeline-unit-tests Job succeeded.                     BaseSHA:9ee839025241dcaf1dc3b9086e3c5fdb0c4126c1
> [Details](https://prow.tekton.dev/view/gs/tekton-prow/pr-logs/pull/tektoncd_pipeline/5960/pull-tekton-pipeline-unit-tests/1611058557216624640)
> @tekton-robot
> tide In merge pool.

**Comment by JeromeJu** [comment]
> the beta test failure is constant in all the attempts so far 😞:
> 
> ```
> Default change: During creation of nodepools or autoscaling configuration changes for cluster versions greater than 1.24.1-gke.800 a default location policy is applied. For Spot and PVM it defaults to ANY, and for all other VM kinds a BALANCED policy is used. To change the default values use the `--location-policy` flag.
> Note: Your Pod address range (`--cluster-ipv4-cidr`) can accommodate at most 1008 node(s).
> ERROR: (gcloud.beta.container.clusters.create) ResponseError: code=400, message=
> 	(1) Creation of node pools using node images based on Docker container runtimes is not supported in GKE v1.23. This is to prepare for the removal of Dockershim in Kubernetes v1.24. We recommend that you migrate to image types based on Containerd (examples). For more information, contact Cloud Support
> 	(2) Creation of node pools using node images based on Docker container runtimes is not supported in GKE v1.24+ clusters as Dockershim has been removed in Kubernetes v1.24.
> 2023/02/22 16:38:20 process.go:155: Step 'gcloud beta container clusters create --quiet --enable-autoscaling --min-nodes=1 --max-nodes=3 --scopes=cloud-platform --no-issue-client-certificate --project=tekton-prow-7 --region=us-central1 --machine-type=n1-standard-4 --image-type=cos --num-nodes=1 --network=tpipeline-e2e-net1628433604[252](https://prow.tekton.dev/view/gs/tekton-prow/pr-logs/pull/tektoncd_pipeline/6201/pull-tekton-pipeline-beta-integration-tests/1628433604252012544#1:build-log.txt%3A252)01[254](https://prow.tekton.dev/view/gs/tekton-prow/pr-logs/pull/tektoncd_pipeline/6201/pull-tekton-pipeline-beta-integration-tests/1628433604252012544#1:build-log.txt%3A254)4 --cluster-version=1.24.9-gke.2000 tpipeline-e2e-cls1628433604252012544' finished in 2.8496[255](https://prow.tekton.dev/view/gs/tekton-prow/pr-logs/pull/tektoncd_pipeline/6201/pull-tekton-pipeline-beta-integration-tests/1628433604252012544#1:build-log.txt%3A255)75s
> 2023/02/22 16:38:20 main.go:319: Something went wrong: starting e2e cluster: error creating cluster: error during gcloud beta container clusters create --quiet --enable-autoscaling --min-nodes=1 --max-nodes=3 --scopes=cloud-platform --no-issue-client-certificate --project=tekton-prow-7 --region=us-central1 --machine-type=n1-standard-4 --image-type=cos --num-nodes=1 --network=tpipeline-e2e-net1628433604252012544 --cluster-version=1.24.9-gke.2000 tpipeline-e2e-cls1628433604252012544: exit status 1
> ```
> 
> I am having hard time deciphering the failure but looks like a cluster is being created with 1.24, could that be an issue? 🤔
> 
> Also, I checked two latest commits in [release-v0.41.x](https://github.com/tektoncd/pipeline/tree/release-v0.41.x) and noticed the `beta` tests were not part of the CI, wondering why?
> 
> > @linux-foundation-easycla[bot]
> > EasyCLA EasyCLA check passed. You are authorized to contribute.
> > [Details](https://easycla.lfx.linuxfoundation.org/#/?version=2)
> > @tekton-robot
> > check-github-tasks-completed Job Successful.
> > [Details](https://prow.tekton.dev/view/gs/tekton-prow/pr-logs/pull/tektoncd_pipeline/5960/check-github-tasks-completed/1611037801023803392)
> > @tekton-robot
> > check-pr-has-kind-label Job Successful.
> > [Details](https://prow.tekton.dev/view/gs/tekton-prow/pr-logs/pull/tektoncd_pipeline/5960/check-pr-has-kind-label/1611039243600138240)
> > @tekton-robot
> > pull-tekton-pipeline-alpha-integration-tests Job succeeded.                     BaseSHA:9ee839025241dcaf1dc3b9086e3c5fdb0c4126c1
> > [Details](https://prow.tekton.dev/view/gs/tekton-prow/pr-logs/pull/tektoncd_pipeline/5960/pull-tekton-pipeline-alpha-integration-tests/1611037802714107904)
> > @tekton-robot
> > pull-tekton-pipeline-build-tests Job succeeded.                     BaseSHA:9ee839025241dcaf1dc3b9086e3c5fdb0c4126c1
> > [Details](https://prow.tekton.dev/view/gs/tekton-prow/pr-logs/pull/tektoncd_pipeline/5960/pull-tekton-pipeline-build-tests/1611037801594228736)
> > @tekton-robot
> > pull-tekton-pipeline-go-coverage Job succeeded.                     BaseSHA:9ee839025241dcaf1dc3b9086e3c5fdb0c4126c1
> > [Details](https://prow.tekton.dev/view/gs/tekton-prow/pr-logs/pull/tektoncd_pipeline/5960/pull-tekton-pipeline-go-coverage/1611037802076573696)
> > @tekton-robot
> > pull-tekton-pipeline-integration-tests Job succeeded.                     BaseSHA:9ee839025241dcaf1dc3b9086e3c5fdb0c4126c1
> > [Details](https://prow.tekton.dev/view/gs/tekton-prow/pr-logs/pull/tektoncd_pipeline/5960/pull-tekton-pipeline-integration-tests/1611037802097545216)
> > @tekton-robot
> > pull-tekton-pipeline-unit-tests Job succeeded.                     BaseSHA:9ee839025241dcaf1dc3b9086e3c5fdb0c4126c1
> > [Details](https://prow.tekton.dev/view/gs/tekton-prow/pr-logs/pull/tektoncd_pipeline/5960/pull-tekton-pipeline-unit-tests/1611058557216624640)
> > @tekton-robot
> > tide In merge pool.

The beta integration test was[ introduced and held to be merged after V1 CRD release](https://github.com/tektoncd/plumbing/pull/1256), which could be the reason why it was not in v0.41.

**Comment by JeromeJu** [comment]
As for the cluster versioning https://github.com/tektoncd/plumbing/pull/1348 and https://github.com/tektoncd/plumbing/pull/1332 should be both in the last release, which I am not sure if that should be the case? cc @XinruZhang @vdemeester  🤔

**Comment by pritidesai** [comment]
One more thing I noticed, we are running [go 1.19](https://prow.tekton.dev/view/gs/tekton-prow/pr-logs/pull/tektoncd_pipeline/6201/pull-tekton-pipeline-beta-integration-tests/1628433604252012544#1:build-log.txt%3A121):

```
go version
go version go1.19 linux/amd64
```

This might not be causing issue here but our pipelines repo is compliant with 1.18 as par go.mod.

**Comment by pritidesai** [comment]
An interesting comparison of logs from beta tests in this PR and one of the recent PRs:

Screen Shot 2023-02-22 at 12 06 46 PM

Beta tests from this PR is missing setting up the KIND cluster and running `./test/presubmit-tests.sh --integration-tests` instead of running [test/e2e-tests.sh](https://github.com/tektoncd/pipeline/blob/d2f075aba67273ad7f216a6c35160825bcbd035a/test/e2e-tests.sh).

**Comment by XinruZhang** [comment]
@pritidesai 

```
ERROR: (gcloud.beta.container.clusters.create) ResponseError: code=400, message=
	(1) Creation of node pools using node images based on Docker container runtimes is not supported in GKE v1.23. This is to prepare for the removal of Dockershim in Kubernetes v1.24. We recommend that you migrate to image types based on Containerd (examples). For more information, contact Cloud Support
	(2) Creation of node pools using node images based on Docker container runtimes is not supported in GKE v1.24+ clusters as Dockershim has been removed in Kubernetes v1.24.
```

The error comes from the param we specified during the container creation `--image-type=cos` when creating the cluster using the following command, but not sure why the error only occurs in this PR

```
gcloud beta container clusters create --quiet --enable-autoscaling --min-nodes=1 --max-nodes=3 --scopes=cloud-platform --no-issue-client-certificate --project=tekton-prow-7 --region=us-central1 --machine-type=n1-standard-4 --num-nodes=1 --cluster-version=1.24.9-gke.2000 tpipeline-e2e
```

**Comment by pritidesai** [comment]
thanks @XinruZhang 👍 

I am also wondering why is the GKE being provisioned instead of KIND?

**Comment by pritidesai** [comment]
Could it be because this env. [setting](https://github.com/tektoncd/pipeline/blob/main/test/e2e-tests-kind-prow-beta.env) is missing from this branch (release-v0.41.x)?

**Comment by pritidesai** [comment]
Do we need to cherry pick this [PR](https://github.com/tektoncd/pipeline/pull/5737) which added prow env. for beta tests?

**Comment by pritidesai** [comment]
> Could it be because this beta env. [setting](https://github.com/tektoncd/pipeline/blob/main/test/e2e-tests-kind-prow-beta.env) is missing from this branch (release-v0.41.x)?

It was introduced in `0.45` and not part of branches from `release-v0.41.x` through `release-v0.44.x`. Just checked the latest [commit](https://github.com/tektoncd/pipeline/pull/6004) in `release-v0.44.x`, the beta test did not run on that branch.

**Comment by pritidesai** [comment]
One more follow up PR which we might have to cherry pick? https://github.com/tektoncd/pipeline/pull/6031 🤔

**Comment by XinruZhang** [comment]
Wondering if there's other modifications we need to cherrypick to ensure our CI works for previous releases. 🤔

**Comment by XinruZhang** [comment]
It looks llike we are good to go based on the comparison between this branch with the latest branch:  https://gist.github.com/XinruZhang/8a631aaa69457d53b96ce71ca1d5c428

**Comment by pritidesai** [comment]
> It looks llike we are good to go based on the comparison between this branch with the latest branch: https://gist.github.com/XinruZhang/8a631aaa69457d53b96ce71ca1d5c428

Cherrypick PR #6031 and #5737? Any other PRs I am missing to cherrypick?

**Comment by pritidesai** [comment]
> It looks llike we are good to go based on the comparison between this branch with the latest branch: https://gist.github.com/XinruZhang/8a631aaa69457d53b96ce71ca1d5c428

oh no, the gist has many more changes 😞 but the larger results was introduced in 0.43 which does not need to be cherrypicked. Also, we do need to cherrypick one more PR - https://github.com/tektoncd/pipeline/pull/5726

**Comment by pritidesai** [comment]
So to make 0.41 releasable, we need to cherrypick the following PRs:

- https://github.com/tektoncd/pipeline/pull/5726
- https://github.com/tektoncd/pipeline/pull/5737
- https://github.com/tektoncd/pipeline/pull/6031

Please correct me if I am wrong or add anything I am missing.

**Comment by XinruZhang** [comment]
I wonder do we need to run `pull-tekton-pipeline-beta-integration-tests` for the releases before v0.43.x

**Comment by JeromeJu** [comment]
> I wonder do we need to run `pull-tekton-pipeline-beta-integration-tests` for the releases before v0.43.x? Because this is introduced [tektoncd/plumbing#1256](https://github.com/tektoncd/plumbing/pull/1256) for testing beta features after V1 CRDs are released.
> 
> cc @tektoncd/core-collaborators @lbernick @JeromeJu

I think that we should not what it does should be only for those integration tests that require beta gates, so should not be a problem even if it is ran against them 🤔

**Comment by pritidesai** [comment]
Yup, I have been trying to see if it's possible to disable `beta` integration tests before 0.43 (or the release when `v1` CRDs were introduced). There should not be any harm in running `beta` but its equivalent to running `pull-tekton-pipeline-integration-tests` and does not add any value. `0.41` is LTS which makes it crucial to have a working CI for that branch. I will cherrypick those three PRs and we can take it from there. Thoughts?

**Comment by XinruZhang** [comment]
> Yup, I have been trying to see if it's possible to disable `beta` integration tests before 0.43 (or the release when `v1` CRDs were introduced). There should not be any harm in running `beta` but its equivalent to running `pull-tekton-pipeline-integration-tests` and does not add any value. `0.41` is LTS which makes it crucial to have a working CI for that branch. I will cherrypick those three PRs and we can take it from there. Thoughts?

SGTM! Thank you @pritidesai !

**Comment by pritidesai** [comment]
Hey @JeromeJu @XinruZhang @vdemeester @lbernick, I have a separate PR opened to fix the CI failure for the `release-v0.41.x` branch: https://github.com/tektoncd/pipeline/pull/6213 

The `beta` tests succeeded in that PR, hoping to see the rest of the checks succeed as well 🤞

**Pull request merged**
