### PR TITLE
[release-v0.43.x] Fix ci for 0.43

### PR DESCRIPTION
**Pull request by Yongxuanzhang**
# Changes

**End of Life for 0.43 is 2023-04-22, until then we need to keep the CI working for it 💓**

In PR https://github.com/tektoncd/pipeline/pull/6201, we identified a failure with our CI system. Beta integrations tests are failing in PR https://github.com/tektoncd/pipeline/pull/6201. Our CI system has been updated to run beta tests but the code base in release-v0.42.x was not updated with necessary changes to run beta tests successfully. We discovered a list of PRs which needs to be cherry picked into release-0.42.x branch for the tests to work.

Cherry picking the following PRs:

- Add prow env for beta integration test https://github.com/tektoncd/pipeline/pull/5737
- Beta Example Tests https://github.com/tektoncd/pipeline/pull/6031

This PR has these commits along with the changes after running ./hack/update-codegen.sh using Go 1.19.

Part of https://github.com/tektoncd/pipeline/issues/6220

/kind misc

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [ ] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [x] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by pritidesai** [comment]
The build is failing because of an update to `gofmt` in Go 1.19. Please run try to run `go fmt ./...` with Go >=1.19 and see if it resolves the failure. Thanks!

**Comment by Yongxuanzhang** [comment]
/retest
 
try again 🤔

**Comment by Yongxuanzhang** [comment]
Ah ci passes

**Review by pritidesai — APPROVED** [review]
thank you @Yongxuanzhang 👍

**Review by afrittoli — COMMENTED** [review]
/lgtm

**Pull request merged**
