### PR TITLE
Add Tracker to FakeClient

### PR DESCRIPTION
**Pull request by khrm**
Adding tracker to fake client similar to fake kube client.

Kubernetes Fake ClientSet Reference: 
https://github.com/kubernetes/client-go/blob/611184f7c43ae2d520727f01d49620c7ed33412d/kubernetes/fake/clientset_generated.go#L145

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) and [TaskRun](../tekton/publish-run.yaml) to build and release this image

### CODE REVIEW

**Comment by khrm** [comment]
I realised that this is a generated code. We will need to update k8s/code-generator to 1.15 version. ATM, we are at 1.12.6 . Should I update, @vdemeester  ? Or there's some schedule for this?

**Comment by vdemeester** [comment]
@khrm we need k8s.io  1.15 for this ? :scream_cat: I don't think we want to update to 1.15 right now for sure.

**Comment by bobcatfish** [comment]
> @khrm we need k8s.io 1.15 for this ? 🙀 We want to update to 1.15 right now for sure.

Will this mean that users of Tekton will also need their kube clusters to be 1.15 🤔 ? I would think that would be the case if we start using client libs that are for 1.15 😟 

My gut feeling would be to delay that if we can - unless we accept that the reality of kubernetes is that everyone needs to be upgrading constantly!

> Can you detail why is this needed ?

It seems like this particular PR doesn't include an actual usage of the new Tracker (maybe I'm missing something tho!) so I'd be inclined to not add this until we have to. But maybe you can explain more @khrm

**Comment by afrittoli** [comment]
> > @khrm we need k8s.io 1.15 for this ? 🙀 We want to update to 1.15 right now for sure.
> 
> Will this mean that users of Tekton will also need their kube clusters to be 1.15 🤔 ? I would think that would be the case if we start using client libs that are for 1.15 😟

I wonder what would change in Tekton to make it not compatible with earlier k8s.
I would expect the client libs to work with 1.15 and earlier versions too, so unless we start using a 1.15 specific feature we should be ok.

> 
> My gut feeling would be to delay that if we can - unless we accept that the reality of kubernetes is that everyone needs to be upgrading constantly!

+100, we shouldn't force our users to be on the very latest k8s unless we have a strict requirement for that.

> 
> > Can you detail why is this needed ?
> 
> It seems like this particular PR doesn't include an actual usage of the new Tracker (maybe I'm missing something tho!) so I'd be inclined to not add this until we have to. But maybe you can explain more @khrm

**Comment by khrm** [comment]
I was writing a test case where I have used PrependReactor to override default flow. For now, I wrote a function to return tracker along with fakeclient.
https://github.com/tektoncd/cli/pull/155/files#diff-f842055470551302221e6cb9566ae245R45

**Comment by bobcatfish** [comment]
> I would expect the client libs to work with 1.15 and earlier versions too, so unless we start using a 1.15 specific feature we should be ok.

If that's the case I'm all for it! Does anyone know for sure (@khrm ?)

> I was writing a test case where I have used PrependReactor to override default flow

Okay interesting! Could you explain in a bit more detail, maybe here and [in the commit message](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages) about what this means? I'm not sure what a `PrependReactor` is for or what the "default flow" is in this context or why it would need to be overridden, so a bit more detail would really help me out.

**Comment by khrm** [comment]
@bobcatfish 
PrependReactor adds a reactor to the beginning of chain which called for an action. And can also stop chain from propogating further.

In the example above, I pass a pipelinerun with GenerateName instead of name. A real service would generate the name but fake client doesn't. So to override the default behavior during creation of object, I need to call prepend reactor. And store it in tracker or store. 

Let's close this for now as I resolved this issue by instanting client outside the fake package. https://github.com/tektoncd/cli/blob/72224f4c7ea1498911d5107f00329ebcbf1d27d5/pkg/cmd/pipeline/start_test.go#L45
When we update the dependency, I would change that test.

**Pull request closed without merging**
