### PR TITLE
Fix links in `when` expressions migrations announcements

### PR DESCRIPTION
**Pull request by jerop**
# Changes

Today, those announcements link to https://github.com/tektoncd/pipeline/issues/1836 which is an unrelated issue. 

In this change, we add a link to the issue tracking that work - https://github.com/tektoncd/pipeline/issues/4461.

/kind cleanup

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [x] [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [n/a] [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Release notes block below has been filled in or deleted (only if no user facing changes)

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by sbwsg — APPROVED** [review]

**Comment by jerop** [comment]
/test pull-tekton-pipeline-alpha-integration-tests

sidecar test

**Comment by bobcatfish** [comment]
/approve

sidecar teeeeeesssst *fist shake*

**Comment by jerop** [comment]
/test pull-tekton-pipeline-integration-tests

known flake reported in https://github.com/tektoncd/pipeline/issues/4427

**Pull request merged**
