### PR TITLE
distinguish task dependencies: ordering vs resource

### PR DESCRIPTION
**Pull request by jerop**
# Changes

there are two types of dependencies between tasks:
- _resource-dependency_: based on resources needed from parent task,
which includes results, workspaces and resources
- _ordering-dependency_: based on runAfter which provides sequencing of
tasks when there may not be resource dependencies

however, it is currently difficult to distinguish between the two

this PR provides a way to know the dependency type and will be useful
for future work such as allowing execution of ordering-dependent tasks
when continueAfterSkip is set to true

/kind misc

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [x] Release notes block has been filled in or deleted (only if no user facing changes)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) to build and release this image.

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md) are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes) must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS) and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes) must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS), and they must first be added [in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by sbwsg — APPROVED** [review]
This looks good to me.  I do wonder if these need to be public funcs though?  If we keep them private I think we still get the benefit of their naming to help distinguish purpose but we can also consider them an "implementation detail" of `Deps()` and avoid testing them right now.  What do you think?

**Comment by jerop** [comment]
> This looks good to me. I do wonder if these need to be public funcs though? If we keep them private I think we still get the benefit of their naming to help distinguish purpose but we can also consider them an "implementation detail" of `Deps()` and avoid testing them right now. What do you think?

agreed, i need to use the functions in `pipeline_validation.go` only so that should work

**Pull request merged**
