### PR TITLE
Remove workflows/woke.yml

### PR DESCRIPTION
**Pull request by wlynch**
# Changes

Looking at recent PRs, this workflow appears to be broken with the error:

```
Error: The head commit for this pull_request event is not ahead of the base commit. Please submit an issue on this action's GitHub repo.
```

even though there's nothing special about the args going on. Reverting for the time being.

See https://github.com/tektoncd/pipeline/actions/runs/6869062223/job/18681015064?pr=7359, https://github.com/tektoncd/pipeline/actions/runs/6868035109/job/18677644144

Reverts https://github.com/tektoncd/pipeline/pull/7199

/cc @Yongxuanzhang @afrittoli 

/kind misc

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) if any changes are user facing, including updates to minimum requirements e.g. Kubernetes version bumps
- [ ] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [ ] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [ ] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including functionality, content, code)
- [ ] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [ ] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings). See some examples of [good release notes](https://github.com/tektoncd/community/blob/main/standards.md#good-release-notes).
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by Yongxuanzhang** [comment]
should we revert other changes? https://github.com/tektoncd/pipeline/commit/afd28ca147be85964b429aca0050dfb2c1b89080

**Review by Yongxuanzhang — APPROVED** [review]

**Comment by wlynch** [comment]
> should we revert other changes? [afd28ca](https://github.com/tektoncd/pipeline/commit/afd28ca147be85964b429aca0050dfb2c1b89080)

Done!

**Comment by Yongxuanzhang** [comment]
Thanks!

**Comment by JeromeJu** [comment]
/cherry-pick release-v0.53.x
We would also need this for the cherry-pick PR to work on v0.53 to pass the 'woke' tests now.

**Pull request closed without merging**
