### PR TITLE
Fix Workspaces in Sidecar to be serialized as workspaces not Workspaces

### LINKED ISSUE #3964: Sidecar struct field Workspaces has not JSON annotation
# Expected Behavior

Field should be annotated with json:"workspaces,omitempty"

# Actual Behavior

No annotation in source code.

### PR DESCRIPTION
**Pull request by jeffmaury**
Fixes #3964

Signed-off-by: Jeff MAURY <jmaury@redhat.com>

# Changes

Add JSON annotation in Workspaces field in Sidecar

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [ ] [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Release notes block below has been filled in or deleted (only if no user facing changes)

# Release Notes

NONE

### CODE REVIEW

**Review by sbwsg — APPROVED** [review]

**Comment by sbwsg** [comment]
running `./hack/update-openapigen.sh` and pushing the changes should fix the build tests.

/test pull-tekton-pipeline-alpha-integration-tests

**Comment by sbwsg** [comment]
Ah, apologies, a wrinkle in the way the hack scripts work: they need to be run from within a GOPATH otherwise they give relative references:

```
-										Ref:     ref("github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1.WhenExpression"),
+										Ref:     ref("./pkg/apis/pipeline/v1beta1.WhenExpression"),
```

The way I do this is to symlink my dev directory to `$GOPATH/src/github.com/tektoncd/pipeline`:

```bash
ln -s <path to pipeline source code> $GOPATH/src/github.com/tektoncd/pipeline
cd $GOPATH/src/github.com/tektoncd/pipeline
./hack/update-openapigen.sh
```

🤞 hopefully that should net us the updated openapi spec w/ absolute references.

**Comment by jerop** [comment]
we had [the same issue](https://github.com/tektoncd/pipeline/pull/3389) with WhenExpressions fields – we had to [support both cases](https://github.com/tektoncd/pipeline/pull/3923) for a while – we can avoid backwards incompatibility by patching 0.24

**Pull request merged**
