### PR TITLE
Update sdk-go to v2.0.0 and update-deps.

### PR DESCRIPTION
**Pull request by n3wscott**
# Changes

Updating the sdk-go package to v2.0.0, the latest release.

### CODE REVIEW

**Comment by n3wscott** [comment]
oh snapp... how do I add a kind label?

**Comment by afrittoli** [comment]
> oh snapp... how do I add a kind label?

/kind [kind]

The list of available kinds is in the comment from github :)

```
kind/bug: Categorizes issue or PR as related to a bug.
kind/flake: Categorizes issue or PR as related to a flakey test
kind/cleanup: Categorizes issue or PR as related to cleaning up code, process, or technical debt.
kind/design: Categorizes issue or PR as related to design.
kind/documentation: Categorizes issue or PR as related to documentation.
kind/feature: Categorizes issue or PR as related to a new feature.
kind/misc: Categorizes issue or PR as a miscellaneuous one.
```

**Comment by n3wscott** [comment]
/kind kind/misc

I guess? There should be a `kind/upgrade`

**Comment by n3wscott** [comment]
oh

I am dumb

/kind misc

**Comment by n3wscott** [comment]
/retest

those do not look like cloudevent errors

**Pull request merged**
