### PR TITLE
Add registry cert config map to support self-signed private registry

### PR DESCRIPTION
**Pull request by FogDong**
# Changes

I met the same problem as tektoncd/pipeline#1171 when I use self-signed private registry.
Use config map to configure users' cert and inject it as an env in the controller could be a good way to solve it.

This commit
- Add a config map to store users' cert.
- Add doc to explain it.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) to build and release this image.

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md) are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes) must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS) and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes) must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS), and they must first be added [in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

# Release Notes

```
Add registry cert config map to support self-signed private registry
```

### CODE REVIEW

**Comment by bobcatfish** [comment]
Hey @FogDong ! I'm wondering, do we also need to update the controller to use this configuration or is there something else in the cluster that uses it already?

Also adding this to the config/ dir would add it for all installations of Tekton - is this something we want by default always, or something that maybe users would want to optionally add?

**Comment by FogDong** [comment]
Hey @bobcatfish !
It's an optionally add, but I still think it should be added into the config dir to install it, otherwise users can not pull image from self-signed registry, they need to insert cert as an env manually in the controller deployment.
I also edit the install doc, it's an optional configuration if users are using self-signed registry

**Pull request closed without merging**
