### PR TITLE
Update to latest knative.dev/pkg

### PR DESCRIPTION
**Pull request by mattmoor**
# Changes

This is largely `go get knative.dev/pkg@main` and some changes to fix upstream breakages.

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [ ] [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [ ] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [ ] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [ ] Release notes block below has been filled in or deleted (only if no user facing changes)

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by mattmoor** [comment]
Need to run codegen, but I want one more change in PKG to avoid `InternalError` events when we use `NewRequeue*` methods. 😅

**Comment by mattmoor** [comment]
For the `test.KubeClient` changes, that was dropped here: https://github.com/knative/pkg/pull/2151

**Comment by mattmoor** [comment]
For the namespace RBAC changes, the OwnerRef logic was added here: https://github.com/knative/pkg/pull/2098

**Comment by mattmoor** [comment]
Ok, this seems to be passing tests, but some of the checks need a kick.

**Comment by mattmoor** [comment]
@vdemeester any idea how to kick the CLA bot?

For context, this is mostly to land: https://github.com/tektoncd/pipeline/pull/4131.

**Comment by vdemeester** [comment]
A good old close/reopen should do the trick (although it restarts all jobs 😹 )

**Comment by mattmoor** [comment]
Ok this should be RFAL.  Looks like we both did the close/open 😅

**Comment by jerop** [comment]
flagging that this change bumps the min k8s version to 1.19 so we need to add release notes for this (got some related errors developing on main) - bump in knative happened in https://github.com/knative/pkg/pull/2157

cc @sbwsg (release captain for v0.27)

**Comment by vdemeester** [comment]
Also this means we will release 0.27 based on a non released version of knative/pkg. Probably not a big deal 😇

**Pull request merged**
