### PR TITLE
Fix Hub Resolver doc typo

### PR DESCRIPTION
**Pull request by QuanZhang-William**
This commit fixes the Hub API endpoints configuration to `../config/resolvers/resolvers-deployment.yaml`

/kind documentation

# Changes

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [ ] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [ ] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [ ] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [ ] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [ ] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by chuangw6** [comment]
/lgtm

Thanks @QuanZhang-William

**Review by lbernick — APPROVED** [review]
@abayer maybe it would make sense for this configuration to move to the [hubresolver configmap](https://github.com/tektoncd/pipeline/blob/main/config/resolvers/hubresolver-config.yaml)?

**Comment by abayer** [comment]
Yeah, it definitely would!

/lgtm

**Review by vdemeester — APPROVED** [review]
/lgtm

**Pull request merged**
