### PR TITLE
Update docs with matrix csi workspace release number

### PR DESCRIPTION
**Pull request by JeromeJu**
# Changes

This commit adds the release number to the install.md according to 
https://github.com/tektoncd/pipeline/pull/5030#discussion_r916940460.

cc @dibyom 

/kind misc

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [n/a] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [n/a] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [n/a] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [n/a] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by lbernick — APPROVED** [review]
thanks Jerome, sorry I forgot to add this! could you also add this release link to matrix?

**Comment by JeromeJu** [comment]
Can we have another /lgtm? The previous one is removed due to rebase. 
Thanks

**Pull request merged**
