### PR TITLE
Replace google/cloud-sdk with GCR equivalent.

### PR DESCRIPTION
**Pull request by wlynch**
/cc @vdemeester 

# Changes

With the recent changes to DockerHub (https://www.docker.com/blog/scaling-docker-to-serve-millions-more-developers-network-egress/),
there will soon be quotas for image pulls.

While we're not sure how this will effect all of our dependencies,
for google/cloud-sdk Google maintains images in both DockerHub and GCR
(https://cloud.google.com/sdk/docs/downloads-docker), so we can use the
GCR version as a drop-in replacement and not worry about how the new
quota changes may affect us.

tl;dr replaces google/cloud-sdk => gcr.io/google.com/cloudsdktool/cloud-sdk

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [x] Release notes block has been filled in or deleted (only if no user facing changes)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) to build and release this image.

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md) are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes) must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS) and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes) must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS), and they must first be added [in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

# Release Notes

```release-note
gcloud images now use GCR hosted equivalent instead of DockerHub.
```

### CODE REVIEW

**Review by sbwsg — APPROVED** [review]

**Review by vdemeester — APPROVED** [review]
/meow

**Pull request merged**
