### PR TITLE
Issue 6670 add invalid pipeline for remote resolution

### PR DESCRIPTION
**Pull request by chitrangpatel**
# Changes

Prior to this, we skipped validation of propagated parameters and
workspaces was skipped in the reconciler until pod creation time.
As a result, validation of the pipeline spec from remote pipelines
was completely ignored. PR https://github.com/tektoncd/pipeline/pull/6693 has the actual fix.

This PR is assisting it and adding an example invalid pipeline spec for
validating the spec after remote resolution. Adding this to no-ci will skip example tests.
This PR fixes part of issue [#6670](https://github.com/tektoncd/pipeline/issues/6670).

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) if any changes are user facing, including updates to minimum requirements e.g. Kubernetes version bumps
- [ ] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [ ] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings). See some examples of [good release notes](https://github.com/tektoncd/community/blob/main/standards.md#good-release-notes).
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
NONE
```
/kind bug

### CODE REVIEW

**Comment by lbernick** [comment]
@chitrangpatel I think adding an invalid example to examples might be a bit confusing. I'm also not totally sure how this fits into https://github.com/tektoncd/pipeline/pull/6693; if it's needed for tests in that PR it should probably be part of that PR.

**Comment by chitrangpatel** [comment]
Hi @lbernick, I wanted to put this in the same PR as the original one. However, I needed to test with the remote resolver. For that, I need the example already in place to provide the url, pathInRepo and revision. 

All other examples that I looked at were using the catalog for remote resolution related tests. May be it could put it in the test folder under test data or something. That would be a lot cleaner I think.  But this PR will have to go in first I think since my e2e test needs something in place (unless there is a workaround there as well).

**Comment by lbernick** [comment]
> Hi @lbernick, I wanted to put this in the same PR as the original one. However, I needed to test with the remote resolver. For that, I need the example already in place to provide the url, pathInRepo and revision.

I think we have some unit tests that push to a fake image registry (e.g. using [this function](https://github.com/tektoncd/pipeline/blob/main/test/remote.go#L53)) or possibly a fake git repo? @Yongxuanzhang has added a few and might be able to give more info on how they work.

> This PR will have to go in first I think since my e2e test needs something in place (unless there is a workaround there as well).

This works the other way too though-- if someone deletes this example, their PR will pass tests, but break CI as soon as it's merged, so I'd prefer to avoid this route. Actually that's probably also going to be an issue for our tests relying on the catalog

**Review by jerop — COMMENTED** [review]
please squash the commits

**Comment by Yongxuanzhang** [comment]
I think @chitrangpatel wants to have this for e2e tests not the unit tests right? The fake registry only works for unit tests not the e2e tests. Does the [cluster-resolver](https://github.com/tektoncd/pipeline/blob/main/docs/cluster-resolver.md) work for your PR, if so we could use that instead of other resolvers.

**Comment by chuangw6** [comment]
> I think @chitrangpatel wants to have this for e2e tests not the unit tests right? The fake registry only works for unit tests not the e2e tests. Does the [cluster-resolver](https://github.com/tektoncd/pipeline/blob/main/docs/cluster-resolver.md) work for your PR? If so we could use that instead of other resolvers and you don't need to merge this example

+1 to this. Using cluster resolver might be more reliable for tests compared to git resolver.

**Comment by Yongxuanzhang** [comment]
> > I think @chitrangpatel wants to have this for e2e tests not the unit tests right? The fake registry only works for unit tests not the e2e tests.
> > Does the [cluster-resolver](https://github.com/tektoncd/pipeline/blob/main/docs/cluster-resolver.md) work for your PR? If so we could use that instead of other resolvers and you don't need to merge this example
> 
> @Yongxuanzhang the cluster-resolver does not work in my case. This is because when I create the pipeline, the web hook comes into play and rejects the invalid spec. I need this invalid spec in a remote location so that when the remote resolver gets it, I need to ensure that I validate it completely after that point.

Oh I see, sorry I don't have the full context, then maybe it should live in the [test](https://github.com/tektoncd/pipeline/tree/main/test) folder as you mentioned.

**Comment by chitrangpatel** [comment]
> > Hi @lbernick, I wanted to put this in the same PR as the original one. However, I needed to test with the remote resolver. For that, I need the example already in place to provide the url, pathInRepo and revision.
> 
> I think we have some unit tests that push to a fake image registry (e.g. using [this function](https://github.com/tektoncd/pipeline/blob/main/test/remote.go#L53)) or possibly a fake git repo? @Yongxuanzhang has added a few and might be able to give more info on how they work.
> 

@lbernick I tried this however the issue is that I run into connection issues for e2e tests. What happens is that when I run the e2e test on my laptop, the OCI server is created locally but the resolver is running on my GKE cluster so the bundle resolver runs into a connection error. For the unit tests, this is not an issue at all since it all happens locally.

Do you think that moving this invalid pipeline from `examples` to `test/testdata` will be ok? Also, I was able to add unit tests to check the other feature so I wonder if this e2e test is even necessary.

> > This PR will have to go in first I think since my e2e test needs something in place (unless there is a workaround there as well).
> 
> This works the other way too though-- if someone deletes this example, their PR will pass tests, but break CI as soon as it's merged, so I'd prefer to avoid this route. Actually that's probably also going to be an issue for our tests relying on the catalog

**Pull request closed without merging**
