### PR TITLE
Enabled `thelper` linter.

### PR DESCRIPTION
**Pull request by bendory**
# Changes

This linter cleans up our test output by omiting helper functions from test failure messages, instead labeling the failure with the calling function's details. This makes it easier to locate the true origin of the failure.

There are no expected functional changes in this PR.

The code changes in this PR are all changes to testing code to comply with Go style and best practices, specifically `t.Helper`:

- https://pkg.go.dev/testing#T.Helper
- https://goo.gle/go-style/best-practices#error-handling-in-test-helpers

Context: https://github.com/tektoncd/pipeline/issues/5899

/kind cleanup

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [N/A] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [x] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [N/A] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [N/A] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by wlynch — APPROVED** [review]
/lgtm

**Review by vdemeester — APPROVED** [review]
/lgtm

**Pull request merged**
