### PR TITLE
Add CRD OpenAPI validation for Pipeline, PipelineResource, Task

### PR DESCRIPTION
**Pull request by sbose78**
# Changes
Generated the OpenAPI validation schema for the
- Pipeline CRD
- PipelineResource CRD
- Task CRD

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) and [TaskRun](../tekton/publish-run.yaml) to build and release this image

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md)
are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes)
must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS)
and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes)
must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS),
and they must first be added
[in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

# Release Notes

```
OpenAPI Validation schema added for the Pipeline CRD.
```

### CODE REVIEW

**Comment by sbose78** [comment]
@googlebot I signed it!

**Comment by sbose78** [comment]
Thank you @bobcatfish for your thoughts on this proposal:

> did you generate these with a tool,
yes, using the [kubegen openapi generator via operator-sdk](url) .

> Since params can be either array type or string type, maybe OpenAPI validation can't handle that kind of syntax?

Yes, that scenario did need some manual fixing. 


I feel irrespective of whether generators can do a 100% good job - we should use some openapi validation in the CRD because
- It helps the user look at the API and understand what it needs
- It helps clients/servers validate the contract before creating the object. Today we could potentially create an object with any structure?
- Given that we have a pretty neat test suite now, we needn't have a full openapi validation spec for corner cases. We could leave out specific nested areas as `object`

**Comment by sbose78** [comment]
For attributes of `ArrayOrString` I removed the validation information from the spec from those fields because there's no good way to do so with the openapi validation spec today.

**Comment by bobcatfish** [comment]
Thanks for the detailed explanation @sbose78 ! 

I'm on board with this if you could also include in this PR a doc that explains how to update these (basically the description you already gave above) - probably https://github.com/tektoncd/pipeline/blob/master/DEVELOPMENT.md#adding-new-types would be a good place for it.

Also I think we should:
- Get some other OWNERS opinions + @sbwsg @dibyom @abayer @dlorenc @vdemeester @ImJasonH @afrittoli 
- Make a follow up issue to add some linting around this (so we can catch cases where it should be updated and isnt)

**Comment by vdemeester** [comment]
I am also onboard with this but I really wish we could tool a bit of it :angel:

**Comment by bobcatfish** [comment]
Quick ping: @sbose78 is this something you want to keep working on? (no worries if not!)

**Comment by sbose78** [comment]
I will clean this up later this week, sorry this had gone off my radar. If anyone wishes to take a look at it in the meantime, I'm good as well.

**Comment by vdemeester** [comment]
Closing in favor of #1776 

/close

**Pull request closed without merging**
