### PR TITLE
refactor TestReconcile_PipelineSpecTaskSpec objects

### PR DESCRIPTION
**Pull request by jbpratt**
# Changes

/kind cleanup

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [x] [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Release notes block below has been filled in or deleted (only if no user facing changes)

# Release Notes

```release-note
NONE
```

working on #4610

Signed-off-by: jbpratt <jbpratt78@gmail.com>

### CODE REVIEW

**Review by jbpratt — COMMENTED** [review]
Hi @jerop and @pritidesai

Curious if we should convert this expected object https://github.com/tektoncd/pipeline/pull/4622/files#diff-a64a19b939f791920d235cbf5bf2e4905d4814af06f21401b27af11351afbd0bL1013-L1028 My attempts to weren't exactly successful, anything omitted on the YAML side ends up as `nil` on the object so I'm not sure how to express some things.

**Review by vdemeester — APPROVED** [review]

**Comment by pritidesai** [comment]
> Hi @jerop and @pritidesai 😸 and @vdemeester !
> 
> Curious if we should convert this expected object
> 
> https://github.com/tektoncd/pipeline/blob/1f3b893548bb2414cbe60ac0cff74dc9adbb57f0/pkg/reconciler/pipelinerun/pipelinerun_test.go#L1015-L1030
> 
> My attempts to weren't exactly successful, anything omitted on the YAML side ends up as `nil` on the object so I'm not sure how to express some things.

Yes please, we should update and convert this object. Please refer to how its done here:

https://github.com/tektoncd/pipeline/pull/4609/files#diff-a64a19b939f791920d235cbf5bf2e4905d4814af06f21401b27af11351afbd0bR538

and

https://github.com/tektoncd/pipeline/pull/4609/files#diff-a64a19b939f791920d235cbf5bf2e4905d4814af06f21401b27af11351afbd0bR497

Also, if needed, you can add `ignoreTypeMeta` in the `diff`:

https://github.com/tektoncd/pipeline/pull/4609/files#diff-a64a19b939f791920d235cbf5bf2e4905d4814af06f21401b27af11351afbd0bR541

**Comment by jbpratt** [comment]
Pushed an update, the `ignoreTypeMeta` has helped, thank you @pritidesai . The test is currently failing, I'm seeing is resources wanting to be nil but I'm not sure how to fix this without another ignore compare option which may not be desirable. Thoughts? Sorry for the dumb question, still trying to figure things out :smiley_cat: 

```
    /home/jbpratt/git/tektoncd/pipeline/pkg/reconciler/pipelinerun/pipelinerun_test.go:1030: expected to see TaskRun &{{TaskRun tekton.dev/v1beta1} {test-pipeline-run-success-unit-test-task-spec  foo    0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[tekton.dev/memberOf:tasks tekton.dev/pipeline:test-pipeline tekton.dev/pipelineRun:test-pipeline-run-success tekton.dev/pipelineTask:unit-test-task-spec] map[] [{tekton.dev/v1beta1 PipelineRun test-pipeline-run-success  0x324c2b9 0x324c2b9}] []  []} {<nil> [] <nil> default <nil> 0xc000b34000  &Duration{Duration:1h0m0s,} <nil> [] [] []} {{0 [] map[]} { <nil> <nil> [] [] [] [] [] [] <nil>}}} created. Diff (-want, +got):   &v1beta1.TaskRun{
          	... // 1 ignored field
          	ObjectMeta: {Name: "test-pipeline-run-success-unit-test-task-spec", Namespace: "foo", Labels: {"tekton.dev/memberOf": "tasks", "tekton.dev/pipeline": "test-pipeline", "tekton.dev/pipelineRun": "test-pipeline-run-success", "tekton.dev/pipelineTask": "unit-test-task-spec"}, Annotations: {}, ...},
          	Spec: v1beta1.TaskRunSpec{
          		Debug:              nil,
          		Params:             nil,
        - 		Resources:          nil,
        + 		Resources:          &v1beta1.TaskRunResources{},
          		ServiceAccountName: "default",
          		TaskRef:            nil,
          		... // 7 identical fields
          	},
          	Status: {},
          }
```

**Review by jerop — APPROVED** [review]
thank you @jbpratt

/lgtm
/woof

**Comment by pritidesai** [comment]
> 

You can update the `expectedTaskRun` to set it to empty struct instead of nil:

```
	expectedTaskRun.Spec.Resources = &v1beta1.TaskRunResources{}
```

This should work!

**Comment by jbpratt** [comment]
I'll push another PR soon, my apologies. Should have marked this as draft :grin:

**Pull request merged**
