### PR TITLE
Remove test/logs helper binary in favor of tkn ⚓

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

`tkn` is already released and can display logs as much as this
helper. So let's remove this code and use a released version of tkn
instead.

/cc @bobcatfish @afrittoli 

How do you prefer to install `tkn` binary in the test image ?
- here, in the presubmit script, *curl*ing the binary from the release page
- in the image used in prow, so in `tektoncd/plumbing` ; this would make `tkn` available for all the projects :wink: 

Signed-off-by: Vincent Demeester <vdemeest@redhat.com>

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) to build and release this image.

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md) are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes) must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS) and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes) must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS), and they must first be added [in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

### CODE REVIEW

**Comment by chmouel** [comment]
/lgtm

niiiice

**Comment by vdemeester** [comment]
Depends on https://github.com/tektoncd/plumbing/pull/83

**Comment by vdemeester** [comment]
tektoncd/plumbing#83 is in, now needs to build, publish and update the image in prow :stuck_out_tongue:

**Pull request merged**
