### PR TITLE
Add almost-empty v1 package

### PR DESCRIPTION
**Pull request by lbernick**
# Changes
This commit adds a package for v1 and updates the hack directory to generate
code and OpenAPI spec for v1. The v1 package is left as minimal as possible;
however, the code does not build and pass tests without at least one generated client.
Therefore, a Task type is added with only a Description field, with the rest of the
Task spec to be added in a future commit.

/kind misc

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- n/a [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- n/a [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Release notes block below has been filled in
(if there are no user facing changes, use release note "NONE")

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by lbernick** [comment]
blocked on https://github.com/tektoncd/pipeline/pull/5066

**Comment by abayer** [comment]
Looks good in general, though I'm inherently a bit wary of adding a `v1` api without it being fully populated. But it should be harmless, I guess?

Would like to get thoughts from others from @tektoncd/core-maintainers

**Comment by vdemeester** [comment]
> Looks good in general, though I'm inherently a bit wary of adding a `v1` api without it being fully populated. But it should be harmless, I guess?
> 
> Would like to get thoughts from others from @tektoncd/core-maintainers

@abayer this is just the code and the package, it is not exported or exposed in any way. This is what we did for `v1beta1`.
I think it's fine, except *maybe* the openapi/swagger generation 👼🏼

**Comment by abayer** [comment]
> > Looks good in general, though I'm inherently a bit wary of adding a `v1` api without it being fully populated. But it should be harmless, I guess?
> > Would like to get thoughts from others from @tektoncd/core-maintainers
> 
> @abayer this is just the code and the package, it is not exported or exposed in any way. This is what we did for `v1beta1`. I think it's fine, except _maybe_ the openapi/swagger generation 👼🏼

@lbernick handled that bit nicely - generating `v1beta1` and `v1` OpenAPI and swagger separately from each other. So given that, I think this is good to go. =)

/approve

**Pull request merged**
