### PR TITLE
Cleanup unused arguments - mostly removing unused ctx 🧹

### PR DESCRIPTION
**Pull request by jerop**
# Changes

In this change, we cleanup unused arguments in functions, mostly removing unused "ctx".

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [n/a] [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [n/a] [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Release notes block below has been filled in (if there are no user facing changes, use release note "NONE")

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by vdemeester — COMMENTED** [review]
The main reason it exists on `SetDefaults` for example, is to make is `Defaultable`. This is not necessary useful for non CRD types though, but I tend to like the consistency. But.. I also do not like when there is function param that are not used 😛

**Comment by jerop** [comment]
> The main reason it exists on `SetDefaults` for example, is to make is `Defaultable`. This is not necessary useful for non CRD types though, but I tend to like the consistency. But.. I also do not like when there is function param that are not used 😛

@vdemeester `SetDefaults` still has `context.Context` - it's just that it's not named because it's not used -- did the same thing for `Validate` to make it `Validatable`

**Pull request merged**
