### PR TITLE
Add variable expansion in the workspaces.mountPath field of Tasks #3152

### PR DESCRIPTION
**Pull request by khalkie**
# Changes

* included Workspace in ApplyReplacements logic so any variables will be expanded

* added another Task Validation operation in createPod, which runs after the variable expansion - it may be possible that the Workspaces are no longer valid (i.e. have duplicate names) after the variable expansion

Fixes: #3786

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [X] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [X] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [X] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [X] Release notes block has been filled in or deleted (only if no user facing changes)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) to build and release this image.

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md) are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes) must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS) and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes) must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS), and they must first be added [in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

# Release Notes

```release-note
Users are able to use variable substitution in the mountPath field of a Workspace within a Task
```

### CODE REVIEW

**Comment by sbwsg** [comment]
Commits should be squashed into 1 using `git rebase -i HEAD^^^^^` or something similar.

Suggest also updating [`docs/variables.md`](https://github.com/tektoncd/pipeline/blob/master/docs/variables.md#fields-that-accept-variable-substitutions) to include `workspaces[].mountPath` in the list of places variables can be used.

I have to confess I'm still a tad uneasy allowing a field to accept variables when the field itself can also be used as a variable elsewhere.  However I pulled down the branch and couldn't get anything to break except when doing something really silly like introducing a cycle by using a workspace path variable in a param that I then also used inside the workspace's mountPath field so I am ok with this going in 👍.

**Comment by sbwsg** [comment]
Thinking about this some more yesterday evening:

- it might also be worth including a description of this variable support to our [`workspaces.md`](https://github.com/tektoncd/pipeline/blob/master/docs/workspaces.md) doc.
- We should probably add a code comment above the new call to Validate with something like, "perform another validation pass because...".

I also wonder if there's some kind of test we can construct that codifies the accepted/supported ordering of variable applications. This might be a little out of scope for this specific PR but I wonder if we could build a table of variables with various dependencies on each other and check that they replace in the right way.  This would be try and catch errors introduced if another dev ever comes along and reorders the variable Apply sequencing.

**Comment by vdemeester** [comment]
> I have to confess I'm still a tad uneasy allowing a field to accept variables when the field itself can also be used as a variable elsewhere. However I pulled down the branch and couldn't get anything to break except when doing something really silly like introducing a cycle by using a workspace path variable in a param that I then also used inside the workspace's mountPath field so I am ok with this going in +1.

I am not sure I follow, the variable for workspaces is `workspaces.<workspaceName>.path`, which is not _really_ `mountPath`. It "derives" from `mountPath` but is not directly the same variable. That said, I do agree that we need to make sure this doesn't break the variable interpolation "work".

**Comment by bobcatfish** [comment]
i think we'd want to update https://github.com/tektoncd/pipeline/blob/master/docs/variables.md#fields-that-accept-variable-substitutions as well

**Comment by afrittoli** [comment]
@khalkie are you still working on this? 
I think it would be a really useful feature to have, some `go` tasks in the catalog might benefit from it.

**Comment by khalkie** [comment]
Sorry so much for the delay!  I recreated this fix in another PR - https://github.com/tektoncd/pipeline/pull/3934

**Pull request closed without merging**
