### PR TITLE
Fix pipelinerun_taskrun_duration_seconds metric

### PR DESCRIPTION
**Pull request by NavidZ**
# Changes

This CL changes reporting taskrun duration as
part of pipelinerun metric to use knative
metrics Record API to match with the rest of the
existing metrics.

We have been using opensensus stats Record API for
reporting pipelinerun_taskrun_duration_seconds metric
as oppose to other metrics that we used knative metrics
API to report them. At this point only the metrics
that are reported with knative metrics are being
correctly plumbed to metrics backend. So as a result
pipelinerun_taskrun_duration_seconds was missing on
the metrics backend.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) to build and release this image.

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md) are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes) must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS) and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes) must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS), and they must first be added [in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

### CODE REVIEW

**Comment by NavidZ** [comment]
@hrishin do you happen to remember why we were using stats.Record in this instance? I can see the unittests are passing either way but I wasn't able to see the metric on StackDriver in the current state and using knative metrics.Record fixed it.

**Comment by hrishin** [comment]
>@hrishin do you happen to remember why we were using stats.Record in this instance? I can see the unittests are passing either way but I wasn't able to see the metric on StackDriver in the current state and using knative metrics.Record fixed it.

Wow, thats good catch @NavidZ, thank you! 
I guess it bug and mistake happen during implementation :thinking: .(why its left as stats.record() instead of metrics.record()? )

**Comment by NavidZ** [comment]
@vdemeester the test failures seem weird. I wasn't able to reproduce them locally. I'm still looking into it.

> I guess it bug and mistake happen during implementation 🤔 .(why its left as stats.record() instead of metrics.record()? )
@hrishin Alrighty. Good to know that it is safe to do have it used metrics.Record.

**Comment by vdemeester** [comment]
/retest
@NavidZ yeah, lot's of flake these days on pipeline, we need to fix that..

**Comment by NavidZ** [comment]
Just to link the issues. This change is related to #2814

**Pull request merged**
