### PR TITLE
Bump k8schain dep to avoid some log spam

### PR DESCRIPTION
**Pull request by imjasonh**
This should reduce some log spam stemming from the ecr-login credential
helper being used by k8schain, which previously would log a warning any
time it was asked to resolve creds for a non-ECR registry -- which we
regularly do...

go-containerregistry bumped its k8s.io deps to v0.23.X, so we need to
replace them back to v0.22.5 to maintain compatibility with Knative
packages.

/kind cleanup

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [x] [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [x] [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Release notes block below has been filled in or deleted (only if no user facing changes)

# Release Notes

```release-note
Reduce some spammy logs when resolving images not on ECR.
```

/assign @sbwsg 
/assign @vdemeester 
/assign @dlorenc

### CODE REVIEW

**Comment by imjasonh** [comment]
We should probably also bump pkg/authn/kubernetes to pick up https://github.com/google/go-containerregistry/pull/1299 then cherrypick it into the release. @afrittoli

**Comment by imjasonh** [comment]
And https://github.com/google/go-containerregistry/pull/1300

**Review by vdemeester — APPROVED** [review]

**Pull request merged**
