### PR TITLE
Fix ./hack/update-codegen.sh script

### PR DESCRIPTION
**Pull request by dprotaso**
The change allows the codegen script to work when the repo's directory
is not checked out as 'pipeline'

# Changes

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [x] [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [x] [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [X] Release notes block below has been filled in
(if there are no user facing changes, use release note "NONE")

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by dprotaso** [comment]
related: https://github.com/knative/pkg/issues/2499

doing some cleanup: https://github.com/knative/pkg/pull/2509

**Review by vdemeester — APPROVED** [review]
cc @sbwsg

**Pull request merged**
