### PR TITLE
TEP-0058: Graceful Termination - `PipelineRunCancelled` is deprecated

### PR DESCRIPTION
**Pull request by jerop**
# Changes

In [TEP-0058: Graceful Termination][tep-0058], we deprecated `PipelineRunCancelled` and added:
- `StoppedRunFinally` - To "stop" (i.e. let the tasks complete, then execute finally tasks) a Pipeline
- `CancelledRunFinally` - To "cancel" (i.e. interrupt any executing non finally tasks, then execute finally tasks)
- `Cancelled` - Same as today's `PipelineRunCancelled` - i.e. interrupt any executing tasks without running finally tasks

The above was released in [v0.25][v25] in June 2021.

This change adds the deprecated field - `PipelineRunCancelled` - to the deprecation table.

Issue: https://github.com/tektoncd/pipeline/issues/4611
Pull Requests:
- https://github.com/tektoncd/pipeline/pull/3915
- https://github.com/tektoncd/pipeline/pull/4246
- https://github.com/tektoncd/community/pull/638

[tep-0058]: https://github.com/tektoncd/community/blob/main/teps/0058-graceful-pipeline-run-termination.md
[v25]: https://github.com/tektoncd/pipeline/releases/tag/v0.25.0

/kind cleanup
# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [x] [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [n/a] [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Release notes block below has been filled in or deleted (only if no user facing changes)

# Release Notes

```release-note
Reminder that `PipelineRunCancelled` was deprecated in v0.25. Earliest removal date is March 2022.
```

### CODE REVIEW

**Comment by lbernick** [comment]
/lgtm
Thanks Jerop!

**Comment by pritidesai** [comment]
thank you @jerop, please add this announcement in the release notes 🙏

**Comment by jerop** [comment]
@pritidesai it was already announced in [v0.25](https://github.com/tektoncd/pipeline/releases/tag/v0.25.0), just not added to the deprecations table - do you think we need to announce again?

**Comment by pritidesai** [comment]
thank you @jerop, its my misunderstanding, I thought we are removing the flag in the next release (0.34 - March 2022). This is just an update the the deprecation table. When are we removing the flag then? with V1? or after promoting graceful termination to beta?

**Review by pritidesai — APPROVED** [review]

**Pull request merged**
