### PR TITLE
[master] Upgrade to latest dependencies

### PR DESCRIPTION
**Pull request by mattmoor**
Produced via:
```shell
./hack/update-deps.sh --upgrade
./hack/update-codegen.sh
```
/cc vdemeester ImJasonH
/assign vdemeester ImJasonH

### CODE REVIEW

**Comment by ImJasonH** [comment]
This deleted [third_party/LICENSE](https://github.com/tektoncd/pipeline/blob/master/third_party/LICENSE), presumably because it also removed our dependency on some golang.org/x/ packages. Just making sure to call this out in case this was unexpected.

**Comment by mattmoor** [comment]
@ImJasonH I think this is a sign that someone needs to update:
```
go get github.com/google/go-licenses
```

The actions do a fresh `go get` each run, so they should reflect the latest.

**Comment by mattmoor** [comment]
switching bots

**Pull request closed without merging**
