### PR TITLE
Bump to K8s 23 libs.

### PR DESCRIPTION
**Pull request by mattmoor**
`knative.dev/pkg` just bumped to 23 libs as part of 1.4 prep (The min version at this commit is still 1.21, so no change there).

I wanted to get this bumped so that the downstream test leg there is unbroken.

Sigstore also picked this up already, so if we don't get pipelines updated then bumping that dep in chains will become problematic. 

/kind cleanup

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [x] [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [x] [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Release notes block below has been filled in or deleted (only if no user facing changes)

# Release Notes

```release-note
Tekton Pipelines now uses k8s 23 libs
```

### CODE REVIEW

**Comment by mattmoor** [comment]
Once this lands, I will bump things in Chains to make sure things are good everywhere.

**Comment by vdemeester** [comment]
@afrittoli we need to bump to go 1.17 for this to be green 🙏🏼

**Comment by afrittoli** [comment]
This change bumps the golang version for the unit and build jobs https://github.com/tektoncd/plumbing/pull/1038

**Comment by afrittoli** [comment]
@mattmoor Just to make sure, does this new version knative/pkg increase the minimum required k8s version?

**Comment by mattmoor** [comment]
> knative.dev/pkg just bumped to 23 libs as part of 1.4 prep (The min version at this commit is still 1.21, so no change there).

Not yet.

**Comment by afrittoli** [comment]
/test pull-tekton-pipeline-build-tests

> /test pull-tekton-pipeline-integration-tests /test pull-tekton-pipeline-alpha-integration-tests

I've only updated build and unit tests for now as I wanted to fix them before changing more.
I can update the integrations ones too now.

**Comment by afrittoli** [comment]
https://github.com/tektoncd/plumbing/pull/1042

**Comment by afrittoli** [comment]
```
    status_test.go:55: Failed to create Task: Internal error occurred: failed calling webhook "webhook.pipeline.tekton.dev": Post "https://tekton-pipelines-webhook.tekton-pipelines.svc:443/defaulting?timeout=10s": EOF
```

**Review by afrittoli — COMMENTED** [review]
/approve

**Comment by vdemeester** [comment]
It's green 🎉 
/meow
/lgtm

**Pull request merged**
