### PR TITLE
[release-v0.42.x] Fixing CI for 0.42

### PR DESCRIPTION
**Pull request by pritidesai**
# Changes

**End of Life for 0.42 is 2023-03-22, until then we need to keep the CI working for it 💓** 

In PR #6201, we identified a failure with our CI system. Beta integrations tests are failing in PR #6201. Our CI system has been updated to run beta tests but the code base in release-v0.42.x was not updated with necessary changes to run beta tests successfully. We discovered a list of PRs which needs to be cherry picked into release-0.42.x branch for the tests to work.

Cherry picking the following PRs:                                               

- Add prow env for beta integration test #5737                                    
- Beta Example Tests #6031        

This PR has these commits along with the changes after running  `./hack/update-codegen.sh` using Go 1.19.

Part of https://github.com/tektoncd/pipeline/issues/6220

/kind misc

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [ ] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [x] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by pritidesai** [comment]
The tests are failing with:

```
        Error: error processing import paths in "./config/controller.yaml": error resolving image references: Get "https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:611d9a8745f756da77a759a2d0160df98e1768833886726456f4556bf90cfbb5?se=2023-02-24T17%3A10%3A00Z&sig=geLM%2B3icj5kO6cNZ%2BmWsSaE8CI3Ny4kSm8fhf8fbocY%3D&sp=r&spr=https&sr=b&sv=2019-12-12": read tcp 10.53.64.3:44780->185.199.110.154:443: read: connection reset by peer
        2023/02/24 17:00:20 error during command execution:error processing import paths in "./config/controller.yaml": error resolving image references: Get "https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:611d9a8745f756da77a759a2d0160df98e1768833886726456f4556bf90cfbb5?se=2023-02-24T17%3A10%3A00Z&sig=geLM%2B3icj5kO6cNZ%2BmWsSaE8CI3Ny4kSm8fhf8fbocY%3D&sp=r&spr=https&sr=b&sv=2019-12-12": read tcp 10.53.64.3:44780->185.199.110.154:443: read: connection reset by peer
```

**Comment by JeromeJu** [comment]
> The tests are failing with:
> 
> ```
>         Error: error processing import paths in "./config/controller.yaml": error resolving image references: Get "https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:611d9a8745f756da77a759a2d0160df98e1768833886726456f4556bf90cfbb5?se=2023-02-24T17%3A10%3A00Z&sig=geLM%2B3icj5kO6cNZ%2BmWsSaE8CI3Ny4kSm8fhf8fbocY%3D&sp=r&spr=https&sr=b&sv=2019-12-12": read tcp 10.53.64.3:44780->185.199.110.154:443: read: connection reset by peer
>         2023/02/24 17:00:20 error during command execution:error processing import paths in "./config/controller.yaml": error resolving image references: Get "https://pkg-containers.githubusercontent.com/ghcr1/blobs/sha256:611d9a8745f756da77a759a2d0160df98e1768833886726456f4556bf90cfbb5?se=2023-02-24T17%3A10%3A00Z&sig=geLM%2B3icj5kO6cNZ%2BmWsSaE8CI3Ny4kSm8fhf8fbocY%3D&sp=r&spr=https&sr=b&sv=2019-12-12": read tcp 10.53.64.3:44780->185.199.110.154:443: read: connection reset by peer
> ```

/retest
The registry issue seems to be connection issue at ghcr

**Review by lbernick — APPROVED** [review]

**Pull request merged**
