### PR TITLE
Bump to release-1.0 of knative.dev/pkg

### PR DESCRIPTION
**Pull request by mattmoor**
Last week Knative cut 1.0, this bumps the knative.dev/pkg dependency to the `release-1.0` branch.

/kind misc

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [N/A] [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [N/A] [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [N/A] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Release notes block below has been filled in or deleted (only if no user facing changes)

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by mattmoor** [comment]
Oh god, I forgot that Go 1.17 adds directives that make Tekton's verify-codegen explode 🤦

**Review by vdemeester — APPROVED** [review]
/meow

**Review by JohnNiang — COMMENTED** [review]
Hi @mattmoor, I found that there was an important change made in `knative.dev/pkg v0.0.0-20211101212339-96c0204a70dc`, which `defaultMinimumVersion` value was changed from `1.19.0` to `1.20.0`. 

https://github.com/tektoncd/pipeline/blob/17439c01768f734468ba1ed69a333238615e568b/vendor/knative.dev/pkg/version/version.go#L28-L37

So that we cannot run Tekton pipeline controller and webhook into Kubernetes 1.19.x correctly.

But installation document still claim to support Kubernetes 1.19.

https://github.com/tektoncd/pipeline/blob/123c78a33857f79e95a93b628aadde9aab60b7d2/docs/install.md#L33-L37

**Comment by vdemeester** [comment]
@bobcatfish  @jerop we need to add this requirement to the release not of v0.30 👼🏼 
@JohnNiang yes, we need to update the `install.md` doc too 😓, sorry this "slipped" under our nose.

Note that I think setting `KUBERNETES_MIN_VERSION` environment variable to the deployment pod template spec should work fine (I don't think there is anything specific to 1.20 in pipeline).

**Comment by mattmoor** [comment]
I missed this skimming the changes, my bad!

In some of the higher traffic knative repos, we are running KinD presubmit legs for ~all of the supported versions, so this is very evident presubmit.  This isn't really practical with GKE clusters, but I'm happy to share pointers if this is interesting to Tekton?

Sorry for the missed release note 😅

**Comment by imjasonh** [comment]
There have been some attempts to add KinD e2e tests in the past (https://github.com/tektoncd/plumbing/issues/631, #3544), I'd love to move that forward to test exactly these kinds of scenarios.

**Comment by mattmoor** [comment]
I've been running the Tekton e2e tests this way downstream in `mink` for over a year without any real issues.  It's actions, so the reception when I offered previously was pretty chilly, but It would take me an hour and it would have caught this...

**Comment by afrittoli** [comment]
@jerop Would you like to update the release notes for v0.30.0? I was going to update dogfooding and realised that our robocat cluster is broken because of this. If we had service monitoring on the clusters we would have detected this the day after the PR was merged 😅

**Comment by jerop** [comment]
@afrittoli good catch, just updated the release - https://github.com/tektoncd/pipeline/releases/tag/v0.30.0

**Pull request merged**
