### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by gsaslis**
# Changes

fixes typo

# Submitter Checklist

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

## Reviewer Notes

N/A

### CODE REVIEW

**Comment by danielhelfand** [comment]
Thanks @gsaslis! Could please sign the CLA?

**Comment by gsaslis** [comment]
@danielhelfand so I tried to check if Red Hat has signed the corporate CLA, but [this page](https://opensource.google/docs/cla/#troubleshoot) mentions: 

> If the contributor is covered by a corporate CLA, make sure that the corporation is listed at http://linkremoved/. 

any idea what that linkremoved is, so I can check whether we're already on that list?

**Comment by danielhelfand** [comment]
> @danielhelfand so I tried to check if Red Hat has signed the corporate CLA, but [this page](https://opensource.google/docs/cla/#troubleshoot) mentions:
> 
> > If the contributor is covered by a corporate CLA, make sure that the corporation is listed at http://linkremoved/.
> 
> any idea what that linkremoved is, so I can check whether we're already on that list?

/cc @bobcatfish @vdemeester

**Comment by vdemeester** [comment]
> @danielhelfand so I tried to check if Red Hat has signed the corporate CLA, but [this page](https://opensource.google/docs/cla/#troubleshoot) mentions:
> 
> > If the contributor is covered by a corporate CLA, make sure that the corporation is listed at http://linkremoved/.
> 
> any idea what that linkremoved is, so I can check whether we're already on that list?

yeah, ping me by mail vdemeest@redhat.com for the corporate CLA.
The other solution is to way monday as we will switch from `cla/goole` to easycla which will be a individual cla (at least for us at Red Hat)

**Comment by bobcatfish** [comment]
Looks like we just need the CLA check to get signed and we'd be ready to go @gsaslis !

**Comment by gsaslis** [comment]
@bobcatfish thanks for the reminder! 😅 

I have started an internal process to hopefully get this CLA signed at the corporate level for Red Hat, so that the onboarding process for others is easier and we can hopefully start attracting more contributors here. 

Would you mind if we left this open a short while longer, to see how fast that internal process moves along?

**Comment by bobcatfish** [comment]
kk no problem @gsaslis !

**Comment by sbwsg** [comment]
Just checking in here, @gsaslis is the EasyCLA approval still in-progress on your side?

**Comment by vdemeester** [comment]
ping @gsaslis :bow:

**Comment by sbwsg** [comment]
Thanks for taking the time to push a fix for this @gsaslis.  It's since been resolved in a61c2156ac87d3eeadcffa226667bf74bbcaf10f so I'm going to close this PR now.

**Comment by gsaslis** [comment]
sorry folks - was terrible with replies here... 😞  

thanks for taking care of it nonetheless! 🙏 👍

**Pull request closed without merging**
