### PR TITLE
Aggregate pipeline roles to built-in clusterroles

### PR DESCRIPTION
**Pull request by richardmarshall**
# Changes

Create clusterroles for the purpose of providing namespace scoped
access to pipeline resources via the built-in admin, edit, and view
clusterroles.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

# Release Notes

```
release-note
```

### CODE REVIEW

**Comment by afrittoli** [comment]
Thanks for this, this helps with https://github.com/tektoncd/pipeline/issues/439.

**Comment by afrittoli** [comment]
Thanks for this, this helps with https://github.com/tektoncd/pipeline/issues/439.

**Comment by bobcatfish** [comment]
hey @richardmarshall !! I'm not very familiar with clusterroles unfortunately :( could you possibly update the commit message (and maybe even [the install docs if it makes sense](https://github.com/tektoncd/pipeline/blob/master/docs/install.md)?) to describe a bit more about how to use these new roles, and when you'd want to? (even if its just a matter of linking to some external docs)

:pray: :heart:

**Comment by dlorenc** [comment]
> hey @richardmarshall !! I'm not very familiar with clusterroles unfortunately :( could you possibly update the commit message (and maybe even [the install docs if it makes sense](https://github.com/tektoncd/pipeline/blob/master/docs/install.md)?) to describe a bit more about how to use these new roles, and when you'd want to? (even if its just a matter of linking to some external docs)

So my understanding is that these roles are not meant to be used directly. They just "aggregate" our existing roles so that they automatically get applied to cluster "editors", "viewers", etc.

**Pull request merged**
