### PR TITLE
Determine changeset from build information

### PR DESCRIPTION
**Pull request by imjasonh**
This updates knative.dev/pkg to @main to pick up a recent change to make
`changeset.Get()` determine the built version from information embedded in
the binary, and no longer return an error.

This also lets us remove symlinks for HEAD and refs in kodata, since
they were only there to enable the previous `changeset.Get()`
implementation.

https://github.com/tektoncd/pipeline/pull/4928 recently bumped our knative/pkg dep to release-1.6 (which was the real hard part, thanks @vdemeester!). Here's the diff between release-1.6 and what we'll import now: https://github.com/knative/pkg/compare/release-1.6...7b8b06028e4faf966147049c807781d8363a7b88

The relevant changes are https://github.com/knative/pkg/pull/2548 and https://github.com/knative/pkg/pull/2549

Similar change to knative/serving to drop HEAD and refs: https://github.com/knative/serving/pull/13130

cc @dprotaso 

/kind cleanup

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [ ] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [x] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [x] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
Version informaiton added to workload labels is determined from information embedded by Go, instead of relying on symlinks to Git information in our build process.
```

### CODE REVIEW

**Comment by imjasonh** [comment]
Oh, looks like tests still run with go 1.17:

```
go version go1.17.11 linux/amd64
```

We'll need to bump this to 1.18 to get this to work. Since Go only officially supports the last two versions, and 1.19 just came out, we should bump to 1.18 anyway.

**Comment by abayer** [comment]
...I forgot that https://github.com/tektoncd/pipeline/pull/5134 hadn't merged yet. d'oh.

**Review by vdemeester — APPROVED** [review]
/lgtm

**Pull request merged**
