### PR TITLE
[TEP-114] Remove the feature flag custom-task-version to stop supporting v1alpha1 Run

### LINKED ISSUE #5837: TEP-0114: Remove the feature flag `custom-task-version` in release v0.47.0
Remove the feature flag `custom-task-version` in release `v0.47.0`, which means we stop supporting `v1alpha1.Run` anymore.

**Background**

As proposed in [TEP-0114](https://github.com/tektoncd/community/blob/main/teps/0114-custom-tasks-beta.md#new-feature-flag-custom-task-version), the default value of `custom-task-version` is set to `v1alpha1` in the first release, approximately v0.43.0, then we switch it to `v1beta1` in v0.44.0 (which is tracked by https://github.com/tektoncd/pipeline/issues/5836), then eventually remove it in release v0.47.0.

cc @jerop @abayer

### PR DESCRIPTION
**Pull request by Yongxuanzhang**
# Changes

This commit closes #5837. It removes the feature flag custom-task-version to stop supporting v1alpha1.Run as planed in TEP-114. There will be a separate PR to remove the v1alpha1.Run tracking by #6498.

/kind feature

Signed-off-by: Yongxuan Zhang yongxuanzhang@google.com

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [x] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) if any changes are user facing, including updates to minimum requirements e.g. Kubernetes version bumps
- [x] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [ ] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [x] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
action required: Feature flag custom-task-version is removed, tekton pipeline will stop supporting v1alpha1 Run and only use v1beta1 CustomRun. 
```

### CODE REVIEW

**Review by jerop — APPROVED** [review]
Thank you @Yongxuanzhang!

I suppose there's a follow up PR removing v1alpha1.Run?

**Review by lbernick — COMMENTED** [review]
do we also need to remove the alpha custom task controller? or would that be in the follow-up PR removing v1alpha1 custom task? https://github.com/tektoncd/pipeline/tree/main/test/custom-task-ctrls/wait-task-alpha

**Comment by Yongxuanzhang** [comment]
> do we also need to remove the alpha custom task controller? or would that be in the follow-up PR removing v1alpha1 custom task? https://github.com/tektoncd/pipeline/tree/main/test/custom-task-ctrls/wait-task-alpha

Yes I will remove it in next PR.

**Pull request merged**
