### PR TITLE
Add some switches to the e2e script ⚙️

### PR DESCRIPTION
**Pull request by afrittoli**
# Changes

Add three switches (env variables) in the main e2e script, that
can be used to:
- skip setting up the test environment
- skip running the YAML based tests
- set the feature gate (this is also available as ENV var

They are useful for setting up the E2E tests in KinD clusters, as
well as generally useful for development purposes.

Add an env file which is used by the kind e2e script, see
https://github.com/tektoncd/plumbing/pull/927 for reference

Signed-off-by: Andrea Frittoli <andrea.frittoli@uk.ibm.com>

/kind misc

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [x] [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [x] [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Release notes block below has been filled in or deleted (only if no user facing changes)

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
We discussed this a little bit for the operator as well but, shouldn't we, most likely invert those flags ? 
My rational is : as a contributor, what is the main use case I will have when running e2e tests ? Most likely, exercising what I just wrote and deploy on my cluster right ? So most of the time I will want to skip the installation (and cluster provisionning, …). That part is mainly useful for CI, thus I tend to think it is better to make the CI have some environment variable than making the contributor write those each time he wants to try and run e2e tests on his work-in-progress.

**Comment by afrittoli** [comment]
> We discussed this a little bit for the operator as well but, shouldn't we, most likely invert those flags ? My rational is : as a contributor, what is the main use case I will have when running e2e tests ? Most likely, exercising what I just wrote and deploy on my cluster right ? So most of the time I will want to skip the installation (and cluster provisionning, …). That part is mainly useful for CI, thus I tend to think it is better to make the CI have some environment variable than making the contributor write those each time he wants to try and run e2e tests on his work-in-progress.

Yeah, I think in development use cases one would like to deploy Tekton (including the code changes) and run tests.
Running `initialize` won't be needed then and not doing that could be the default, but that will require then updating all existing e2e prow jobs.

**Comment by vdemeester** [comment]
> Yeah, I think in development use cases one would like to deploy Tekton (including the code changes) and run tests. Running `initialize` won't be needed then and not doing that could be the default, but that will require then updating all existing e2e prow jobs.

Yes agreed, hence me approving. I think we can do this as follow-ups but not need to it now, at once.

**Comment by afrittoli** [comment]
@imjasonh @bobcatfish can I get a second review on this - I'd love to move forward with kind testing for pipeline asap - so hopefully we can get it up and running before the holidays

**Comment by nikhil-thomas** [comment]
👍 lgtm

**Comment by imjasonh** [comment]
Looks good to me. If @bobcatfish doesn't have comments I can give it the official slash-lgtm.

**Comment by afrittoli** [comment]
Added https://github.com/tektoncd/plumbing/pull/942 to plumbing to that the job does not skip

**Comment by afrittoli** [comment]
Some env variable must be missing which breaks the generation of the junit report, but apart from that, the E2E tests in kind are now passing 🎉 👍 
```
PASS
Using kubeconfig at `` with cluster ``
ok  	github.com/tektoncd/pipeline/test/v1alpha1	457.717s
Finished run, return code is 0
mktemp: (null): Invalid argument
/workspace/source/vendor/github.com/tektoncd/plumbing/scripts/library.sh: line 262: ${xml}: ambiguous redirect
XML report written to 
BusyBox v1.34.1 (2021-11-23 00:57:35 UTC) multi-call binary.

Usage: cp [-arPLHpfinlsTu] SOURCE DEST
or: cp [-arPLHpfinlsu] SOURCE... { -t DIRECTORY | DIRECTORY }

Copy SOURCEs to DEST

	-a	Same as -dpR
	-R,-r	Recurse
	-d,-P	Preserve symlinks (default if -R)
	-L	Follow all symlinks
	-H	Follow symlinks on command line
	-p	Preserve file attributes if possible
	-f	Overwrite
	-i	Prompt before overwrite
	-n	Don't overwrite
	-l,-s	Create (sym)links
	-T	Refuse to copy if DEST is a directory
	-t DIR	Copy all SOURCEs into DIR
	-u	Copy only newer files
Test log written to 
test/e2e-tests.sh: line 61: [: missing `]'
**************************************
***        E2E TESTS PASSED        ***
**************************************
```

This does not include the examples yet - I'll add them in a second PR.

**Comment by bobcatfish** [comment]
not blocking the PR but a request and a thought:

* making our already complicated bash based testing logic more complicated feels a bit 😞  but we've been talking about migrating it to tekton for this long and still havent so i dont want to get in the way of adding functionality we need
* could there be some comments in the script that explain what each of the flags are for?

**Comment by pritidesai** [comment]
hey @afrittoli is this ready to merge? Looks like this is stuck with some of the checks `pull-pipeline-kind-k8s-v1-20-e2e` and `check-pr-has-kind-label `. 

Also, do you want to address @bobcatfish's [comments](https://github.com/tektoncd/pipeline/pull/4400#issuecomment-1011524355) in this PR?

**Comment by afrittoli** [comment]
k8s v1.20 is not supported by Tekton anymore, so updating the CI job to use v1.21 https://github.com/tektoncd/plumbing/pull/1034

**Pull request merged**
