### PR TITLE
Indicate minimum cluster version is now 1.15 🚗

### LINKED ISSUE #2197: Broken release on v0.11.0-rc1
# Expected Behavior
After upgrading to the official release v0.110-rc1, pods in namespace tekton-pipelines should run successfully 

# Actual Behavior
```bash
$ kubectl apply --filename https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml
$ kubectl get -n tekton-pipelines pods
NAME                                           READY   STATUS             RESTARTS   AGE
tekton-pipelines-controller-65c64786c8-kmfxh   0/1     CrashLoopBackOff   4          2m38s
tekton-pipelines-webhook-75c699fff9-7c6pt      0/1     CrashLoopBackOff   4          2m38s
```

# Steps to Reproduce the Problem

Step 1: reset
```bash
$ kubectl delete namespace tekton-pipelines
namespace "tekton-pipelines" deleted
```

Step 2: install latest offical release as shown [here](https://github.com/tektoncd/pipeline/blob/master/docs/install.md#installing-tekton-pipelines-on-kubernetes)
```bash
$ kubectl apply --filename https://storage.googleapis.com/tekton-releases/pipeline/latest/release.yaml
$ kubectl get -n tekton-pipelines pods
NAME                                           READY   STATUS             RESTARTS   AGE
tekton-pipelines-controller-65c64786c8-kmfxh   0/1     CrashLoopBackOff   4          2m38s
tekton-pipelines-webhook-75c699fff9-7c6pt      0/1     CrashLoopBackOff   4          2m38s
```

Step 3: Rollback to previous version 0.9.0 and approve it works.
``` bash
$ kubectl delete namespace tekton-pipelines
namespace "tekton-pipelines" deleted
$ kubectl apply --filename https://storage.googleapis.com/tekton-releases/pipeline/previous/v0.9.0/release.yaml
$ kubectl get -n tekton-pipelines pods
NAME                                           READY   STATUS    RESTARTS   AGE
tekton-pipelines-controller-754c496f57-xm9gp   1/1     Running   0          7s
tekton-pipelines-webhook-6664fb8c56-t2c4z      1/1     Running   0          7s
```
      
# Additional Info
See here for the two pods (controller and webhook) output

```bash
kubectl get -n tekton-pipelines pods/tekton-pipelines-controller-65c64786c8-kmfxh -o json
``` 
```json  
{
    "apiVersion": "v1",
    "kind": "Pod",
    "metadata": {
        "annotations": {
            "cluster-autoscaler.kubernetes.io/safe-to-evict": "false"
        },
        "creationTimestamp": "2020-03-09T22:10:25Z",
        "generateName": "tekton-pipelines-controller-65c64786c8-",
        "labels": {
            "app": "tekton-pipelines-controller",
            "app.kubernetes.io/component": "controller",
            "app.kubernetes.io/name": "tekton-pipelines",
            "pipeline.tekton.dev/release": "v0.11.0-rc1",
            "pod-template-hash": "65c64786c8",
            "version": "v0.11.0-rc1"
        },
        "name": "tekton-pipelines-controller-65c64786c8-kmfxh",
        "namespace": "tekton-pipelines",
        "ownerReferences": [
            {
                "apiVersion": "apps/v1",
                "blockOwnerDeletion": true,
                "controller": true,
                "kind": "ReplicaSet",
                "name": "tekton-pipelines-controller-65c64786c8",
                "uid": "c717e023-6252-11ea-a334-42010a800156"
            }
        ],
        "resourceVersion": "14585",
        "selfLink": "/api/v1/namespaces/tekton-pipelines/pods/tekton-pipelines-controller-65c64786c8-kmfxh",
        "uid": "c71d1a95-6252-11ea-a334-42010a800156"
    },
    "spec": {
        "containers": [
            {
                "args": [
                    "-kubeconfig-writer-image",
                    "gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/kubeconfigwriter:v0.11.0-rc1@sha256:66ff7dd82f77a9e7a5f5fbc6783baf5af732bb4428e0c7293ce7c285bd06f90e",
                    "-creds-image",
                    "gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/creds-init:v0.11.0-rc1@sha256:d1251c017ad8db911f6b459f9cbe94328c962b619b5a6e4ef57524254c1dc30d",
                    "-git-image",
                    "gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:v0.11.0-rc1@sha256:90bab5bf608890d086942890681d84faf82c1cc766c97ad95e309c50bdac3121",
                    "-nop-image",
                    "tianon/true",
                    "-shell-image",
                    "busybox",
                    "-gsutil-image",
                    "google/cloud-sdk",
                    "-entrypoint-image",
                    "gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/entrypoint:v0.11.0-rc1@sha256:4c6b3559819aa9e32b8b6b506140115a93e66fd513036c1d20f3426f5e405be1",
                    "-imagedigest-exporter-image",
                    "gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/imagedigestexporter:v0.11.0-rc1@sha256:8b339a57f2080c6d017636317e368cca3c9124f0fe14af98e53d1dc446bb897e",
                    "-pr-image",
                    "gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/pullrequest-init:v0.11.0-rc1@sha256:62388b0dd5fd3b12444e454cdb6ec967afb557dd2131a9f94bb7bb98761b5f35",
                    "-build-gcs-fetcher-image",
                    "gcr.io/tekton-releases/github.com/tektoncd/pipeline/vendor/github.com/googlecloudplatform/cloud-builders/gcs-fetcher/cmd/gcs-fetcher:v0.11.0-rc1@sha256:74fd88bb0c4810483bdbbfb779d9ad01324145d5e3e63c4c9271c61ae0d4e1c7"
                ],
                "env": [
                    {
                        "name": "SYSTEM_NAMESPACE",
                        "valueFrom": {
                            "fieldRef": {
                                "apiVersion": "v1",
                                "fieldPath": "metadata.namespace"
                            }
                        }
                    },
                    {
                        "name": "CONFIG_LOGGING_NAME",
                        "value": "config-logging"
                    },
                    {
                        "name": "CONFIG_OBSERVABILITY_NAME",
                        "value": "config-observability"
                    },
                    {
                        "name": "CONFIG_ARTIFACT_BUCKET_NAME",
                        "value": "config-artifact-bucket"
                    },
                    {
                        "name": "CONFIG_ARTIFACT_PVC_NAME",
                        "value": "config-artifact-pvc"
                    },
                    {
                        "name": "METRICS_DOMAIN",
                        "value": "tekton.dev/pipeline"
                    }
                ],
                "image": "gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/controller:v0.11.0-rc1@sha256:786a306a2645186ad2c547db2cfc3e1987cd31962166dc320c908d10ebe903b9",
                "imagePullPolicy": "IfNotPresent",
                "name": "tekton-pipelines-controller",
                "resources": {},
                "terminationMessagePath": "/dev/termination-log",
                "terminationMessagePolicy": "File",
                "volumeMounts": [
                    {
                        "mountPath": "/etc/config-logging",
                        "name": "config-logging"
                    },
                    {
                        "mountPath": "/var/run/secrets/kubernetes.io/serviceaccount",
                        "name": "tekton-pipelines-controller-token-xwl7c",
                        "readOnly": true
                    }
                ]
            }
        ],
        "dnsPolicy": "ClusterFirst",
        "enableServiceLinks": true,
        "nodeName": "gke-ci-test2-default-pool-eaeff9be-4djb",
        "priority": 0,
        "restartPolicy": "Always",
        "schedulerName": "default-scheduler",
        "securityContext": {},
        "serviceAccount": "tekton-pipelines-controller",
        "serviceAccountName": "tekton-pipelines-controller",
        "terminationGracePeriodSeconds": 30,
        "tolerations": [
            {
                "effect": "NoExecute",
                "key": "node.kubernetes.io/not-ready",
                "operator": "Exists",
                "tolerationSeconds": 300
            },
            {
                "effect": "NoExecute",
                "key": "node.kubernetes.io/unreachable",
                "operator": "Exists",
                "tolerationSeconds": 300
            }
        ],
        "volumes": [
            {
                "configMap": {
                    "defaultMode": 420,
                    "name": "config-logging"
                },
                "name": "config-logging"
            },
            {
                "name": "tekton-pipelines-controller-token-xwl7c",
                "secret": {
                    "defaultMode": 420,
                    "secretName": "tekton-pipelines-controller-token-xwl7c"
                }
            }
        ]
    },
    "status": {
        "conditions": [
            {
                "lastProbeTime": null,
                "lastTransitionTime": "2020-03-09T22:10:25Z",
                "status": "True",
                "type": "Initialized"
            },
            {
                "lastProbeTime": null,
                "lastTransitionTime": "2020-03-09T22:10:25Z",
                "message": "containers with unready status: [tekton-pipelines-controller]",
                "reason": "ContainersNotReady",
                "status": "False",
                "type": "Ready"
            },
            {
                "lastProbeTime": null,
                "lastTransitionTime": "2020-03-09T22:10:25Z",
                "message": "containers with unready status: [tekton-pipelines-controller]",
                "reason": "ContainersNotReady",
                "status": "False",
                "type": "ContainersReady"
            },
            {
                "lastProbeTime": null,
                "lastTransitionTime": "2020-03-09T22:10:25Z",
                "status": "True",
                "type": "PodScheduled"
            }
        ],
        "containerStatuses": [
            {
                "containerID": "docker://eccb17fe216980ec89c6f2b092609151d734f4872bc64319bc3671832bf954ee",
                "image": "sha256:31300f939d2c427b3caee8280ec2a7ddaa2d13832b97375f8f484cae6d36a716",
                "imageID": "docker-pullable://gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/controller@sha256:786a306a2645186ad2c547db2cfc3e1987cd31962166dc320c908d10ebe903b9",
                "lastState": {
                    "terminated": {
                        "containerID": "docker://eccb17fe216980ec89c6f2b092609151d734f4872bc64319bc3671832bf954ee",
                        "exitCode": 1,
                        "finishedAt": "2020-03-09T22:13:27Z",
                        "reason": "Error",
                        "startedAt": "2020-03-09T22:13:27Z"
                    }
                },
                "name": "tekton-pipelines-controller",
                "ready": false,
                "restartCount": 5,
                "state": {
                    "waiting": {
                        "message": "Back-off 2m40s restarting failed container=tekton-pipelines-controller pod=tekton-pipelines-controller-65c64786c8-kmfxh_tekton-pipelines(c71d1a95-6252-11ea-a334-42010a800156)",
                        "reason": "CrashLoopBackOff"
                    }
                }
            }
        ],
        "hostIP": "10.128.0.75",
        "phase": "Running",
        "podIP": "10.76.2.11",
        "qosClass": "BestEffort",
        "startTime": "2020-03-09T22:10:25Z"
    }
}
```

```bash
kubectl get -n tekton-pipelines pods/tekton-pipelines-webhook-75c699fff9-7c6pt -o json
```

```json
{
    "apiVersion": "v1",
    "kind": "Pod",
    "metadata": {
        "annotations": {
            "cluster-autoscaler.kubernetes.io/safe-to-evict": "false"
        },
        "creationTimestamp": "2020-03-09T22:10:25Z",
        "generateName": "tekton-pipelines-webhook-75c699fff9-",
        "labels": {
            "app": "tekton-pipelines-webhook",
            "app.kubernetes.io/component": "webhook-controller",
            "app.kubernetes.io/name": "tekton-pipelines",
            "pipeline.tekton.dev/release": "v0.11.0-rc1",
            "pod-template-hash": "75c699fff9",
            "role": "webhook",
            "version": "v0.11.0-rc1"
        },
        "name": "tekton-pipelines-webhook-75c699fff9-7c6pt",
        "namespace": "tekton-pipelines",
        "ownerReferences": [
            {
                "apiVersion": "apps/v1",
                "blockOwnerDeletion": true,
                "controller": true,
                "kind": "ReplicaSet",
                "name": "tekton-pipelines-webhook-75c699fff9",
                "uid": "c7504daf-6252-11ea-a334-42010a800156"
            }
        ],
        "resourceVersion": "14629",
        "selfLink": "/api/v1/namespaces/tekton-pipelines/pods/tekton-pipelines-webhook-75c699fff9-7c6pt",
        "uid": "c753b9bf-6252-11ea-a334-42010a800156"
    },
    "spec": {
        "containers": [
            {
                "env": [
                    {
                        "name": "SYSTEM_NAMESPACE",
                        "valueFrom": {
                            "fieldRef": {
                                "apiVersion": "v1",
                                "fieldPath": "metadata.namespace"
                            }
                        }
                    },
                    {
                        "name": "CONFIG_LOGGING_NAME",
                        "value": "config-logging"
                    },
                    {
                        "name": "CONFIG_OBSERVABILITY_NAME",
                        "value": "config-observability"
                    },
                    {
                        "name": "WEBHOOK_SERVICE_NAME",
                        "value": "tekton-pipelines-webhook"
                    },
                    {
                        "name": "METRICS_DOMAIN",
                        "value": "tekton.dev/pipeline"
                    }
                ],
                "image": "gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/webhook:v0.11.0-rc1@sha256:06d797f5456bfcd2c0bf50d701d899c6ad286dddf4d334c554c8e3e0c6949ca8",
                "imagePullPolicy": "IfNotPresent",
                "name": "webhook",
                "ports": [
                    {
                        "containerPort": 9090,
                        "name": "metrics",
                        "protocol": "TCP"
                    },
                    {
                        "containerPort": 8008,
                        "name": "profiling",
                        "protocol": "TCP"
                    },
                    {
                        "containerPort": 8443,
                        "name": "https-webhook",
                        "protocol": "TCP"
                    }
                ],
                "resources": {},
                "securityContext": {
                    "allowPrivilegeEscalation": false
                },
                "terminationMessagePath": "/dev/termination-log",
                "terminationMessagePolicy": "File",
                "volumeMounts": [
                    {
                        "mountPath": "/var/run/secrets/kubernetes.io/serviceaccount",
                        "name": "tekton-pipelines-controller-token-xwl7c",
                        "readOnly": true
                    }
                ]
            }
        ],
        "dnsPolicy": "ClusterFirst",
        "enableServiceLinks": true,
        "nodeName": "gke-ci-test2-default-pool-eaeff9be-4djb",
        "priority": 0,
        "restartPolicy": "Always",
        "schedulerName": "default-scheduler",
        "securityContext": {},
        "serviceAccount": "tekton-pipelines-controller",
        "serviceAccountName": "tekton-pipelines-controller",
        "terminationGracePeriodSeconds": 30,
        "tolerations": [
            {
                "effect": "NoExecute",
                "key": "node.kubernetes.io/not-ready",
                "operator": "Exists",
                "tolerationSeconds": 300
            },
            {
                "effect": "NoExecute",
                "key": "node.kubernetes.io/unreachable",
                "operator": "Exists",
                "tolerationSeconds": 300
            }
        ],
        "volumes": [
            {
                "name": "tekton-pipelines-controller-token-xwl7c",
                "secret": {
                    "defaultMode": 420,
                    "secretName": "tekton-pipelines-controller-token-xwl7c"
                }
            }
        ]
    },
    "status": {
        "conditions": [
            {
                "lastProbeTime": null,
                "lastTransitionTime": "2020-03-09T22:10:25Z",
                "status": "True",
                "type": "Initialized"
            },
            {
                "lastProbeTime": null,
                "lastTransitionTime": "2020-03-09T22:10:25Z",
                "message": "containers with unready status: [webhook]",
                "reason": "ContainersNotReady",
                "status": "False",
                "type": "Ready"
            },
            {
                "lastProbeTime": null,
                "lastTransitionTime": "2020-03-09T22:10:25Z",
                "message": "containers with unready status: [webhook]",
                "reason": "ContainersNotReady",
                "status": "False",
                "type": "ContainersReady"
            },
            {
                "lastProbeTime": null,
                "lastTransitionTime": "2020-03-09T22:10:25Z",
                "status": "True",
                "type": "PodScheduled"
            }
        ],
        "containerStatuses": [
            {
                "containerID": "docker://8c13625907cecfd41f5c4ee278bf1931f96ac339e0d95938f85ff61ae602e18a",
                "image": "sha256:00b46864a1c443738089a729a7542af0034b973eb6a42112f264ab9da99a32b4",
                "imageID": "docker-pullable://gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/webhook@sha256:06d797f5456bfcd2c0bf50d701d899c6ad286dddf4d334c554c8e3e0c6949ca8",
                "lastState": {
                    "terminated": {
                        "containerID": "docker://8c13625907cecfd41f5c4ee278bf1931f96ac339e0d95938f85ff61ae602e18a",
                        "exitCode": 1,
                        "finishedAt": "2020-03-09T22:13:40Z",
                        "reason": "Error",
                        "startedAt": "2020-03-09T22:13:40Z"
                    }
                },
                "name": "webhook",
                "ready": false,
                "restartCount": 5,
                "state": {
                    "waiting": {
                        "message": "Back-off 2m40s restarting failed container=webhook pod=tekton-pipelines-webhook-75c699fff9-7c6pt_tekton-pipelines(c753b9bf-6252-11ea-a334-42010a800156)",
                        "reason": "CrashLoopBackOff"
                    }
                }
            }
        ],
        "hostIP": "10.128.0.75",
        "phase": "Running",
        "podIP": "10.76.2.10",
        "qosClass": "BestEffort",
        "startTime": "2020-03-09T22:10:25Z"
    }
}
```

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

In #1894 we bumped our k8s dependencies such that a cluster must now
be running at least 1.15. This adds it to the README.md, to make sure
user know it too.

Closes #2197 

Signed-off-by: Vincent Demeester <vdemeest@redhat.com>

/kind documentation

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) to build and release this image.

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md) are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes) must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS) and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes) must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS), and they must first be added [in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

### CODE REVIEW

**Comment by afrittoli** [comment]
I like the cherry colour of the needs-cherry-pick label ^_^

**Comment by vdemeester** [comment]
oh boy I broke the README !

**Comment by sbwsg** [comment]
needs unit test.

**Pull request merged**
