### PR TITLE
Temporary disable yaml linting 😓

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

So that the CI is unblocked while we fix those python issues.

Signed-off-by: Vincent Demeester <vdemeest@redhat.com>

/cc @chmouel @afrittoli @bobcatfish @sbwsg 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) to build and release this image.

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md) are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes) must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS) and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes) must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS), and they must first be added [in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

### CODE REVIEW

**Comment by bobcatfish** [comment]
Thanks for jumping on this @vdemeester !

/lgtm

> So that the CI is unblocked while we fix those python issues.

I'm not sure what python issues we're talking about, do you have a an issue or link? (Particularly to make sure we remember to turn this back on!)

**Comment by vdemeester** [comment]
`test-runner` was previously using Python 2, which is bad at handling unicode and stuff… Now `test-runner` is using Python 3 so it should be safer.

The weird thing about this error though, we don't have any of those on plumbing. One of my guess, is how we use `CHANGED_FILES` for this — it might try to lint files that do not exists anymore and fail :sweat_smile: .

**Comment by bobcatfish** [comment]
Thanks for explaining @vdemeester ! Do you have an issue or something that is tracking this work to make sure it's not all on your shoulders to remember to turn it back on?

**Pull request merged**
