### PR TITLE
add example for CloudNativeBuildpacks

### PR DESCRIPTION
**Pull request by pyama86**
# Changes

Hi Team!
Cloudnative buildpacks were supported for [knative build](https://github.com/knative/build-templates/blob/master/buildpacks/cnb.yaml).
I want to do the same with pipeline, so I added it to the example.
Thanks!

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) and [TaskRun](../tekton/publish-run.yaml) to build and release this image

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md)
are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes)
must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS)
and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes)
must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS),
and they must first be added
[in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

# Release Notes

```
Describe any user facing changes here, or delete this block.

Examples of user facing changes:
- API changes
- Bug fixes
- Any changes in behavior

```

### CODE REVIEW

**Comment by pyama86** [comment]
@googlebot I signed it!

**Comment by dibyom** [comment]
Nice! I wonder if the [catalog](https://github.com/tektoncd/catalog) would be a even better place for this?

/ok-to-test

**Comment by vdemeester** [comment]
I think I agree with @dibyom, there should be cloudnativebuildpacks in the catalog. That said, doesn't stop us to have those example runing here :angel: (as long as they are not too long)

**Comment by dibyom** [comment]
Yeah, putting it in the examples/ ensures that it runs as part of the YAML tests. 
But at the moment, this PR only contains the `Task` and not a `TaskRun`, so maybe we add a `TaskRun` to this PR to exercise the `Task`?

**Comment by vdemeester** [comment]
@dibyom oh very good point :sweat_smile:

**Comment by pyama86** [comment]
Thanks for response.
I couldn't find this.
https://github.com/tektoncd/catalog/blob/master/buildpacks/buildpacks-v3.yaml
Since this catalog has the same definition, this PR is closed.

Thanks!

**Pull request closed without merging**
