### PR TITLE
docs: fix links to Matrix examples

### PR DESCRIPTION
**Pull request by AverageMarcus**
# Changes

Fixed the links on the Matrix docs page to point to the examples on GitHub instead of relative URLs.

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [x] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) if any changes are user facing, including updates to minimum requirements e.g. Kubernetes version bumps
- [ ] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [ ] [pre-commit](https://github.com/tektoncd/pipeline/blob/main/DEVELOPMENT.md#install-tools) Passed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [ ] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings). See some examples of [good release notes](https://github.com/tektoncd/community/blob/main/standards.md#good-release-notes).
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
NONE
```

/kind documentation

### CODE REVIEW

**Comment by afrittoli** [comment]
Thanks for this PR @AverageMarcus - I think the problem with this approach is that the GitHub links are not versioned, so all the versioned published docs on https://tekton.dev/docs will point the variable version on `main` for those files.
I think an alternative solution may be to change the [sync/publishing scripts](https://github.com/tektoncd/website/blob/main/sync/) on the website to point those URLs to GitHub at publishing time, using a version specific link.

**Comment by AverageMarcus** [comment]
Does that support pulling things from the `examples` directory though? Is there an existing place this is being done that I could copy?

**Pull request merged**
