### PR TITLE
an attempt to fix integration tests

### PR DESCRIPTION
**Pull request by pritidesai**
# Changes

Check if event already exists before adding them - the same events are generated multiple times and lately its causing very frequent build system failures. This is an attempt to unblock PR reviews until we fix it the right way (not generating duplicate events).

Hoping to avoid commenting `/test pull-tekton-pipeline-integration-tests` in the PR for this particular failure:

```
Expected 2 number of successful events from pipelinerun and taskrun but got 3; list of received events ...
```

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [x] Release notes block has been filled in or deleted (only if no user facing changes)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) to build and release this image.

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md) are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes) must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS) and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes) must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS), and they must first be added [in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

### CODE REVIEW

**Comment by afrittoli** [comment]
Thanks for this! Hopefully this was already fixed by https://github.com/tektoncd/pipeline/pull/2860

**Comment by pritidesai** [comment]
@afrittoli looks like we are good with the events generation, should we close this PR? I will move the typo fix to separate PR.

**Comment by afrittoli** [comment]
Yes, thank you!

**Comment by vdemeester** [comment]
/close
thanks @pritidesai :wink:

**Pull request closed without merging**
