### PR TITLE
Sort pod container statuses based on Step order in taskSpec

### PR DESCRIPTION
**Pull request by Peaorl**
# Changes

This commit closes tektoncd#3239

Tekton determines the `TaskRun` status message of a failed `TaskRun` based on the results of the first terminated `Step` (pod container). Until now, Tekton sorted pod container statuses based on the _FinishedAt_ and _StartedAt_ timestamps set by Kubernetes. 
Occasionally, a `Step` terminated in response to the first terminated `Step` could have the same timestamps as the first terminated Step. 
Therefore, Tekton was not always able to correctly determine what the first terminated `Step` was, and as a result, Tekton may set an incorrect `TaskRun` status message.

In this commit, pod container statuses are sorted based on the container order as specified by Tekton in the podSpec. 
Tekton bases this order on the user provided taskSpec and `Steps` added internally by Tekton. Therefore, Tekton accounts for internally added `Steps` when sorting pod container statuses.
# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [X] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [X] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [X] Release notes block has been filled in or deleted (only if no user facing changes)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) to build and release this image.

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md) are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes) must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS) and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes) must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS), and they must first be added [in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

# Release Notes
```release-note
Steps in the TaskRun status field are now sorted according to the Step order specified in the taskSpec
```

### CODE REVIEW

**Comment by vdemeester** [comment]
/kind bug
/ok-to-test
@Peaorl this might need a release note (other than `NONE`) :stuck_out_tongue:

**Comment by GregDritschler** [comment]
> In this commit, pod container statuses are sorted based on the Step order set in the taskSpec. This order ought to be correct as Tektonenforces Steps to be scheduled in this order. In case Tekton adds extra Steps (such as for pipelineresources), Tekton already updates the taskSpec with these Steps. Therefore, Tekton accounts for these internally added Steps when sorting.

The taskSpec passed to MakeTaskRunStatus does not have the internal steps.  It is the user's taskSpec.

Perhaps you are looking at the steps in the TaskRun's status?  Those do have the internal steps because the code fabricates steps for them from the container statuses.  You'll notice those steps are not in order relative to the user's steps.

I suggest testing a TaskRun with a PipelineResource that has an error (e.g. a git resource with a repo that doesn't exist), to confirm the behavior.

Also this change needs to be separated from your other PR #3138 (or, if it depends on it, you need to hold this one until that one is approved and merged).

**Comment by Peaorl** [comment]
Thanks Greg! Good catch, I made sure the updated taskSpec is passed on to the appropriate function (MakeTaskRunStatus).

/hold

**Comment by GregDritschler** [comment]
> Thanks @GregDritschler ! Good catch, I made sure the updated taskSpec is passed on to the appropriate function (MakeTaskRunStatus).
> 

So now the updated taskSpec is passed to MakeTaskRunStatus when the pod is created, but what happens on subsequent reconcile calls when the pod exists?

**Comment by Peaorl** [comment]
I changed it such that the container order in the `podSpec` is used. Tekton sets this container order when the pod is created and bases the order on the `taskSpec` and the internally added `Steps`.

**Review by sbwsg — APPROVED** [review]

**Pull request merged**
