### PR TITLE
chore: change the boilerplate  in copyright from 2020 to 2023

### PR DESCRIPTION
**Pull request by kycheng**
# Changes

Change copyright in boilerplate from 2020 to 2023.

refs: #6232

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [x] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [x] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [x] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [x] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```
NONE
```

### CODE REVIEW

**Comment by wlynch** [comment]
Generally LGTM, though I'm tempted to follow https://www.linuxfoundation.org/blog/blog/copyright-notices-in-open-source-software-projects and just omit the year altogether so we don't have to do this again next year.

@tektoncd/core-maintainers any objections?

**Comment by pritidesai** [comment]
> Generally LGTM, though I'm tempted to follow https://www.linuxfoundation.org/blog/blog/copyright-notices-in-open-source-software-projects and just omit the year altogether so we don't have to do this again next year.
> 
> @tektoncd/core-maintainers wdyt? (👍 for yes, 👎 for no)

Thanks @wlynch, I did not find specific information on the year in the linked blog article.

Generally, the foundation describes best practice on what to include in such licenses, for example, does all files need a license header? What kind of license header is necessary in each file? etc. We are part of cdFoundation, do you or anybody has any insight into if cdFounation has any guidelines?

Our [license](https://github.com/tektoncd/pipeline/blob/main/LICENSE) file explains how we should apply the Apache license and what is the standard header. This license file represents the standard SPDX License Data - https://spdx.org/licenses/Apache-2.0.html

There is an [alternative](https://spdx.dev/ids/) available to only include a short identifiers instead of the entire license header. 

I would recommend to include such identifier if we want to avoid including the license header which in turn avoids updating source files every year:

```
SPDX-License-Identifier: Apache-2.0
```

**Comment by wlynch** [comment]
@pritidesai in particular:

> Instead, many LF project communities recommend using a more general statement in a form similar to the following (where XYZ is the project’s name):
> 
> - Copyright The XYZ Authors.
> - Copyright The XYZ Contributors.
> - Copyright Contributors to the XYZ project.
> 
> ...
> 
> By using a common format, **the project avoids having to maintain** lists of names of the authors or copyright holders, **years or ranges of years**, and variations on the (c) symbol. This aims to minimize the burden on developers and maintainers as well as redistributors of the code, particularly where compliance with the license requires that further distributions retain or reproduce copyright notices.

paging @afrittoli @fdegir who may know who to talk to on the CDF side.

---

Re SPDX headers - I'm indifferent, though where I've seen it used the copyright notice is also included. My understanding is that it only replaces the Apache 2.0 bits.

**Comment by pritidesai** [comment]
> By using a common format, the project avoids having to maintain lists of names of the authors or copyright holders, years or ranges of years, and variations on the (c) symbol.

Aah, found it, thanks @wlynch. I don't think so it's ideal to tweak Copyright this way which can have a cascading impact on adhering to the standards. Such license and copyright info is an integral part of SBOM and many organizations have legal implications. 

> Re SPDX headers - I'm indifferent, though where I've seen it used the copyright notice is also included. My understanding is that it only replaces the Apache 2.0 bits.

It could potentially replace the entire license header.

> What are SPDX IDs?
An easy way to label your source code’s licenses
Needs only one new comment line per file
Human-readable and machine readable

Yup, for an existing projects, the recommendation is not to drop `Copyright`:

> Copyright notices
SPDX IDs are intending to express information about licenses. Copyright notices ‐ statements about who owns the copyright in a file or project ‐ are outside the scope of SPDX short-form IDs.
Therefore, you should not remove or modify existing copyright notices in files when adding an SPDX ID.

A  simple example of such usage (SPDX short identifier with copyright):

https://github.com/zephyrproject-rtos/zephyr/blob/main/zephyr-env.sh

**Comment by kycheng** [comment]
> > By using a common format, the project avoids having to maintain lists of names of the authors or copyright holders, years or ranges of years, and variations on the (c) symbol.
> 
> Aah, found it, thanks @wlynch. I don't think so it's ideal to tweak Copyright this way which can have a cascading impact on adhering to the standards. Such license and copyright info is an integral part of SBOM and many organizations have legal implications.
> 
> > Re SPDX headers - I'm indifferent, though where I've seen it used the copyright notice is also included. My understanding is that it only replaces the Apache 2.0 bits.
> 
> It could potentially replace the entire license header.
> 
> > What are SPDX IDs?
> > An easy way to label your source code’s licenses
> > Needs only one new comment line per file
> > Human-readable and machine readable
> 
> Yup, for an existing projects, the recommendation is not to drop `Copyright`:
> 
> > Copyright notices
> > SPDX IDs are intending to express information about licenses. Copyright notices ‐ statements about who owns the copyright in a file or project ‐ are outside the scope of SPDX short-form IDs.
> > Therefore, you should not remove or modify existing copyright notices in files when adding an SPDX ID.
> 
> A simple example of such usage (SPDX short identifier with copyright):
> 
> https://github.com/zephyrproject-rtos/zephyr/blob/main/zephyr-env.sh

@pritidesai Do we need to update to this format now? 

```
#
# Copyright (c) 2023 The Tekton Authors, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
```

but I don't think it addresses the year issue.

**Pull request closed without merging**
