### PR TITLE
Inline the `ResourceDeclaration` struct in `TaskResource`

### PR DESCRIPTION
**Pull request by nlewo**
Before the commit 92d5bcca31a690282179bae74a9b995c9e6337c5, attributes
of `ResourceDeclaration` belong to `TaskResource`.

This avoids generated JSON structures to contain the useless
`ResourceDeclaration` attribute.

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) to build and release this image.

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md) are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes) must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS) and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes) must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS), and they must first be added [in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

# Release Notes

```
Describe any user facing changes here, or delete this block.

Examples of user facing changes:
- API changes
- Bug fixes
- Any changes in behavior

```

### CODE REVIEW

**Comment by nlewo** [comment]
@googlebot I signed it!

**Comment by nlewo** [comment]
@bobcatfish I ran into this issue because I tried to generate `cue` files from your `go` sources: the objective is to extract a schema as the[ `cue` kubernetes tutorial ](https://github.com/cuelang/cue/tree/master/doc/tutorial/kubernetes#extract-cue-templates-directly-from-kubernetes-go-source) does. 
Without the `inline` tag, `cue` generates this struct (a piece of the struct):
```
spec:
  inputs:
    resources:
    - ResourceDeclaration:
        name: "source"
        type: "git"
```
while with the `inline` tag it generates:
```

spec:
  inputs:
    resources:
    -  name: "source"
        type: "git"
```

This is also explained in the `cue get go --help` message:
```
	- embedded structs marked with a json inline tag unify with struct
	  definition. For instance, the Go struct

	    struct MyStruct {
			Common  json:",inline"
			Field string
		 }

	  translates to the CUE struct

		 MyStruct: Common & {
			 Field: string
		 }

```

The Go json marshaller, by default, inlines embedded structs (i didn't try before you asked for).I tried to find some documentation about this tag, but I wasn't able to:/ That's really strange!
Note that you are already using such kind of tag [here](https://github.com/tektoncd/pipeline/blob/master/pkg/apis/pipeline/v1alpha1/task_types.go#L91) for instance.

**Comment by nlewo** [comment]
So, this `inline` flag  is recognized by the `go-yaml` package (https://github.com/go-yaml/yaml/commit/8691640bc70f3d96128a809341d850b550a3abb9) but I have not been able to find it in the `go-json` package!

**Comment by dibyom** [comment]
Thanks for the thorough explanation @nlewo ! 
/hold cancel

**Pull request merged**
