### PR TITLE
Use PipelineWorkspaceDeclaration instead of WorkspacePipelineDeclaration 👷‍♀️

### PR DESCRIPTION
**Pull request by bobcatfish**
# Changes

This is a super minor change to rename WorkspacePipelineDeclaration to
PipelineWorkspaceDeclaration. WorkspacePipelineDeclaration sounds like
it's a pipeline declaration inside of a workspace, but actually its
meant to be a workspace declaration inside of a pipeline!

I'm trying to pickup some of the work started in https://github.com/tektoncd/pipeline/pull/1936
and this seemed like a reasonable improvement to carve off and merge on
its own :D

co-authored with @sbwsg 

/kind cleanup

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [n/a] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [n/a] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) to build and release this image.

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md) are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes) must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS) and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes) must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS), and they must first be added [in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

# Release Notes

```
The field WorkspacePipelineDeclaration in the API go library is now called PipelineWorkspaceDeclaration
```

### CODE REVIEW

**Comment by jlpettersson** [comment]
> Possibly silly question but: Does renaming things count as API changes to someone writing code against a Pipeline client?

I was thinking about this too. This is just a change of the Go-client API, but no changes in the Yaml API or REST API - so I would not count it as an "api change" ?

**Comment by pritidesai** [comment]
> > Possibly silly question but: Does renaming things count as API changes to someone writing code against a Pipeline client?
> 
> I was thinking about this too. This is just a change of the Go-client API, but no changes in the Yaml API or REST API - so I would not count it as an "api change" ?

Ditto, would not count as an `API Change` 👍  but CLI repo has a reference here:

https://github.com/tektoncd/cli/blob/85e53f79d71f9373b22a9ed62c0dd06b4e9f54f7/pkg/cmd/pipeline/start_test.go#L3152

How does this change impact CLI? /lgtm if its not breaking CLI 😲

**Comment by bobcatfish** [comment]
Added the alias like you suggested @vdemeester , PTAL!

I also opened https://github.com/tektoncd/pipeline/issues/2748 to create more clarity around our policy for client lib changes.

**Comment by pritidesai** [comment]
thanks @bobcatfish 
/lgtm

**Pull request merged**
