### PR TITLE
pkg/apis: export more `Task` validation functions 🤹

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

The reason to export those is mainly to be able to validate
Tasks *ahead* of time in clients (such as `tkn`) and/or to re-use
those function in Custom Tasks if possible.

The current use case I have for those is `TaskGroup`, that *wraps* a
Task, and thus tries to perform the same set of validation.

Signed-off-by: Vincent Demeester <vdemeest@redhat.com>

/kind cleanup

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [ ] [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [X] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [X] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [X] Release notes block below has been filled in
(if there are no user facing changes, use release note "NONE")

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by afrittoli — COMMENTED** [review]
A comment in the code would help understand why these are exposed, since they are not consumed anywhere within `pipeline`.  Else you risk the next maintainer changing this back at some point.

**Comment by imjasonh** [comment]
Re: ahead-of-time validation, what should clients like `tkn` do when their vendored/linked-in validation code doesn't match with the installed Tekton version's? It's potentially a problem if either `tkn` is stricter (valid Tasks get rejected) or if `tkn` is looser (invalid Tasks get sent, disjoint error experience).

Not saying we shouldn't do it, just wondering if there are any big issues with validation version skew we anticipate.

**Comment by vdemeester** [comment]
> Re: ahead-of-time validation, what should clients like `tkn` do when their vendored/linked-in validation code doesn't match with the installed Tekton version's? It's potentially a problem if either `tkn` is stricter (valid Tasks get rejected) or if `tkn` is looser (invalid Tasks get sent, disjoint error experience).
> 
> Not saying we shouldn't do it, just wondering if there are any big issues with validation version skew we anticipate.

I agree but I think it's not necessarily only for clients but also extensions and/or alternative implementation. For example, with `buildkit-tekton` I probably want to add validation very similar to the version I support — today, without this, I need to duplicate code a bit (and that code might be wrong later on). It could also be true for remote resolver or custom task that might "wrap" existing Tekton objects. An example is the [TaskGroup](https://github.com/openshift-pipelines/tekton-task-group) custom task.
Maybe giving the example of `tkn` here was the wrong one 😛

**Pull request closed without merging**
