### PR TITLE
move tep75 tep76 and tep 107 examples from alpha to beta

### PR DESCRIPTION
**Pull request by Yongxuanzhang**
# Changes

Tep [75](https://github.com/tektoncd/pipeline/pull/6211), [76](https://github.com/tektoncd/pipeline/pull/6103) and [107](https://github.com/tektoncd/pipeline/issues/4955) have been promoted from alpha to beta. So we should have those examples in beta. This would benefit users if they want to search for related examples.

/kind cleanup

Signed-off-by: Yongxuan Zhang yongxuanzhang@google.com

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) if any changes are user facing, including updates to minimum requirements e.g. Kubernetes version bumps
- [ ] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [ ] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [ ] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including functionality, content, code)
- [ ] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [ ] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings). See some examples of [good release notes](https://github.com/tektoncd/community/blob/main/standards.md#good-release-notes).
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by lbernick — APPROVED** [review]
just a heads up propagated params are stable

**Comment by Yongxuanzhang** [comment]
> just a heads up propagated params are stable

Oh thanks! That's why it isn't in the beta table list. I only saw the promo to beta issue and thought it is in beta. Will move examples out of beta now.

**Comment by lbernick** [comment]
> > just a heads up propagated params are stable
> 
> Oh thanks! That's why it isn't in the beta table list. I only saw the promo to beta issue and thought it is in beta. Will move examples out of beta now.

I don't think it impacts this PR, since object params and array indexing are still in beta

**Pull request merged**
