### PR TITLE
Upgrade knative -> 0.18

### PR DESCRIPTION
**Pull request by eddie4941**
# Changes

The newest knative/pkg release has released some change to how metrics
are generated. In particular, the new code stops generating a metrics
for every resource that is reconciled. This dramatically reduces the
metrics cardinality for the webhook. This ultimately
reduces amount of memory required by the webhook daemons and
greatly improves the usability of the /metrics endpoint as it will not
longer return a metrics for every resource that is reconciled.

fixes: #2872

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [x] Release notes block has been filled in or deleted (only if no user facing changes)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) to build and release this image.

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md) are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes) must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS) and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes) must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS), and they must first be added [in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

# Release Notes

```release-note
This release will drop the `resource_name` label from `webhook_request_(count, latencies_bucket)` metrics. This this breaking change with no replacement for those relying on these metrics. The omission of these metrics will improve the overall memory usage of the webhook and the stability of the /metrics endpoint.

```

### CODE REVIEW

**Comment by eddie4941** [comment]
I tested this with older clusters to make sure the new changes didn't break anything. The results:

version info:
```shell
$ kb version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.6", GitCommit:"dff82dc0de47299ab66c83c626e08b245ab19037", GitTreeState:"clean", BuildDate:"2020-07-16T00:04:31Z", GoVersion:"go1.14.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```

Tekton off of master (8ecaa2974dbcc5d09e4309ecf91aa97ff6b0cf4d) includes the `resource_name` label:
```shell
$ http :9090/metrics | grep webhook_request_latencies_bucket | wc -l
      85

$ http :9090/metrics | grep webhook_request_latencies_bucket | grep 'resource_name=' | wc -l
      85
```

Tekton with new changes doesn't include the `resource_name` label.
```shell
$ http :9090/metrics | grep webhook_request_latencies_bucket | wc -l
      85

$ http :9090/metrics | grep webhook_request_latencies_bucket | grep 'resource_name=' | wc -l
       0
```

**Comment by vdemeester** [comment]
/hold
Let's make sure we wait for 0.17 to be release to get this in

**Comment by mattmoor** [comment]
FWIW:
/lgtm

I was literally just about to start this and my spidey sense prompted me to go look for a PR 🎉 

Looking over this I am actually really glad someone else did this as it looks like it required a lot of changes, so thanks for picking up this particularly nasty change 😅 

@vdemeester is there a date for 17?

**Comment by mattmoor** [comment]
I bumped triggers here (imports this): https://github.com/tektoncd/triggers/pull/784

**Comment by vdemeester** [comment]
> @vdemeester is there a date for 17?

Tomorrow :wink:

**Comment by eddie4941** [comment]
Let me know when this is all good to go. In the meantime, Ill try my best to keep it rebased and up to date.

**Comment by vdemeester** [comment]
It should also fix #3237 if I am not wrong.

**Comment by mattmoor** [comment]
If we can land this, then I will try to fix up my triggers and CLI PRs today/tomorrow

**Comment by mattmoor** [comment]
@eddie4941 looks like a merge conflict
```
test/workspace_test.go:253:24: cannot use t (variable of type *\"testing\".T) as context.Context value in argument to setup: missing method Deadline /home/prow/go/src/github.com/tektoncd/pipeline/test/workspace_test.go:253:25: too few arguments in call to setup
```

**Comment by afrittoli** [comment]
I thought the fix for this was in knative/pkg v0.17 which is already in tektoncd/pipeline v0.17.... but it looks like it is not.... I just tried on my v0.17 cluster. 
So we'll fix this in tektoncd/pipeline v0.18 using knative/pkg v0.18 :D

**Comment by mattmoor** [comment]
/lgtm

thanks again! 🎉

**Pull request merged**
