### PR TITLE
Add runtime params to pipeline resource

### PR DESCRIPTION
**Pull request by Mikedu1988**
Currently, a pipeline resource is defined and created before a taskrun or a pipelinerun. Users can't change the pipeline resource params after it's created. If we want to change then branch of a git resource when I start a new pipeline run, I have to created a new resource or update the current resource before I start the pipeline run.
By adding runtime params to pipeline resource, user can declare run time params when creating a pipeline run and then the params will be injected into pipeline resource.

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) and [TaskRun](../tekton/publish-run.yaml) to build and release this image

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md)
are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes)
must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS)
and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes)
must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS),
and they must first be added
[in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

# Release Notes

```
User can now inject runtime params into resources referred in a taskrun or a piplinerun. And change the resource created accordingly.

A pipelinerun example below:
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: some-service-git
spec:
  type: git
  params:
  - name: url
    value: https://gitlab.local.com/mike/some-service
  - name: revision
    value: dev
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: pipelinerun-some-service-sit
spec:
  pipelineRef:
    name: maven-project-pipeline
  serviceAccount: 'tekton-git-and-registry'
  params:
    - name: branch
      value: sit
    - name: project_name
      value: some-service
  resources:
  - name: source-repo
    resourceRef:
      name: some-service-git
      runtimeParams:
      - name: revision
        value: sit
  - name: image
    resourceRef:
      name: some-service-docker

The runtime param revision will be injected into resource some-service-git when the resource get created.
User don't have to create another resource pointing to another branch, user can build any git revision with the same resource.
```

### CODE REVIEW

**Comment by Mikedu1988** [comment]
@googlebot I signed it!

**Comment by vdemeester** [comment]
/hold
@Mikedu1988 thanks for the pull-request :angel: There is active discussion on the PipelineResource models and I feel we should hold a bit on adding feature related to PipelineResource until those discussion leads to somewhere "stable".

- [Tekton Pipeline Resource Extensibility](https://docs.google.com/document/d/1rcMG1cIFhhixMSmrT734MBxvH3Ghre9-4S2wbzodPiU/edit?ts=5d512593#)
- [Reduce PipelineResource Waste](https://docs.google.com/document/d/1fF2vWMs12d3FwkqkNuzS7FzQFQSFz1ZKUe6CHqkIg0c/edit#)

**Comment by Mikedu1988** [comment]
@vdemeester understand. I don't have right permission to the documents you share. 
We've been using tekton for a little while, the pipeline resource is somehow painful as there are too many projects to many branches to build. So I come up with the runtime parameter solution.
I also have some some idea regarding pv and resource management, if it's ok, please have someone approve my request to access these discussion.

**Comment by vdemeester** [comment]
> @vdemeester understand. I don't have right permission to the documents you share.

You need to subscribe to the tekton-dev google groups and you will have automatic access to the doc :angel: (see [here](https://github.com/tektoncd/community/blob/master/contact.md#mailing-list))

**Comment by bobcatfish** [comment]
> By adding runtime params to pipeline resource, user can declare run time params when creating a pipeline run and then the params will be injected into pipeline resource.

@Mikedu1988 this is a cool idea! I think this is addressing some of the same problems we're trying to tackle in the design doc @vdemeester linked ([Reduce PipelineResource Waste](https://docs.google.com/document/d/1fF2vWMs12d3FwkqkNuzS7FzQFQSFz1ZKUe6CHqkIg0c/edit#) - the issue is #544 .

In that proposal we would make it so that you can embed `PipelineResources` in `PipelineRuns`, so your example above would instead look like:

```
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: some-service-git
spec:
  type: git
  params:
  - name: url
    value: https://gitlab.local.com/mike/some-service
  - name: revision
    value: dev
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: pipelinerun-some-service-sit
spec:
  pipelineRef:
    name: maven-project-pipeline
  serviceAccount: 'tekton-git-and-registry'
  params:
    - name: branch
      value: sit
    - name: project_name
      value: some-service
  resources:
  - name: source-repo
    type: git
    params:
    - name: url
      value: https://gitlab.local.com/mike/some-service
    - name: revision
      value: sit
    - name: image
      resourceRef:
        name: some-service-docker
```

btw we'll probably be discussing this more in our working group meeting this week if you are interested in joining or want to watch the recordings / read the notes afterward: https://github.com/tektoncd/community/blob/master/contact.md#working-group

**Comment by afrittoli** [comment]
Thank you for this, I think it's a nice idea and a potential alternative approach to creating a new resource or specifying the resource inline in the PipelineRun. 
As @vdemeester and @bobcatfish already mentioned this will have to be discussed as part of the general PipelineResources revamp.

One use case where I believe the option "creating a new resource" does not help, is when one of the parameters of the resource is generated during the execution of a previous step or task.

**Comment by bobcatfish** [comment]
@Mikedu1988 how do you want to go forward with this? I think we'd want to do some more design and discussion before merging, do you mind if we close the PR in the meantime?

**Comment by Mikedu1988** [comment]
> @Mikedu1988 how do you want to go forward with this? I think we'd want to do some more design and discussion before merging, do you mind if we close the PR in the meantime?

please proceed

**Pull request closed without merging**
