### PR TITLE
use tagged images to take advantage of the least expensive default image pull policy

### PR DESCRIPTION
**Pull request by pritidesai**
# Changes

Replace the `latest` tag with the latest version and tag the image to take advantage of the least expensive k8s default image pull policy. The current policy is:

* if you omit the `imagePullPolicy` field, and the tag for the container image is `:latest`, `imagePullPolicy` is automatically set to `Always`
* if you omit the `imagePullPolicy` field, and you don't specify the tag for the container image, `imagePullPolicy` is automatically set to `Always`

With this change, we are relying on the following policy:

* if you omit the `imagePullPolicy` field, and you specify the tag for the container image that isn't `:latest`, the `imagePullPolicy` is automatically set to `IfNotPresent`.

Part of https://github.com/tektoncd/pipeline/issues/4551

/kind misc

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) if any changes are user facing, including updates to minimum requirements e.g. Kubernetes version bumps
- [x] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] [pre-commit](https://github.com/tektoncd/pipeline/blob/main/DEVELOPMENT.md#install-tools) Passed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [x] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings). See some examples of [good release notes](https://github.com/tektoncd/community/blob/main/standards.md#good-release-notes).
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by chitrangpatel — APPROVED** [review]
/lgtm

**Review by chitrangpatel — COMMENTED** [review]
Approving for now but my only fear with this is maintaining the version tags every once in a while. I think thats an ok compromise.

**Comment by pritidesai** [comment]
> Approving for now but my only fear with this is maintaining the version tags every once in a while. I think thats an ok compromise.

Yes, this is an additional maintenance until we find a permanent solution. However, it only requires infrequent updates.

**Pull request merged**
