### PR TITLE
Cleanup: Remove "substituted context" task validation

### PR DESCRIPTION
**Pull request by lbernick**
Prior to this commit, when a sentinel value was injected into the context, TaskSpec.Validate skipped most validation. This logic was introduced in https://github.com/tektoncd/pipeline/pull/4835. However, there are no longer places in the codebase, other than tests, where this sentinel value was used. This commit removes this logic. No functional changes.

/kind cleanup

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- n/a Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) if any changes are user facing, including updates to minimum requirements e.g. Kubernetes version bumps
- [x] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- n/a Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings). See some examples of [good release notes](https://github.com/tektoncd/community/blob/main/standards.md#good-release-notes).
- n/a Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by dibyom — APPROVED** [review]

**Comment by lbernick** [comment]
It looks like all these test failures are actually flakes-- all are related to git clone failures that I think are transient and definitely aren't related to this PR. The alpha integration tests failed due to https://github.com/tektoncd/pipeline/issues/6626.
/retest

**Review by JeromeJu — APPROVED** [review]

**Comment by lbernick** [comment]
/retest

everything seems to be failures fetching/cloning git 🤔

**Comment by lbernick** [comment]
/retest

I think things are working again based on the prow dashboard

**Pull request merged**
