### PR TITLE
Some code improvements

### PR DESCRIPTION
**Pull request by sosiska**
# Changes

* Rewrite if-else chain as a switch.
* Rewrite some switch statements with only one case as if.
* Assignments simplified by using assignment operators.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md#principles) (if user facing)
- [X] Commit messages follow [commit message best practices](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md#commit-messages)

# Release Notes

These changes do not affect the current behavior.

### CODE REVIEW

**Comment by pivotal-nader-ziada** [comment]
@sosiska can you please take a look at the conflict? Thanks

**Comment by vdemeester** [comment]
@sosiska can you squash those 2 commits ? :angel: :pray:

**Comment by sosiska** [comment]
> @sosiska can you squash those 2 commits ? angel pray

Done in 9a0261b785f0b009065e524643484e026f04f9d9.

**Comment by sosiska** [comment]
1 moment, I must correct commit message, because now it is not:
"Assignments simplified by using assignment operators."

**Comment by sosiska** [comment]
> 1 moment, I must correct commit message, because now it is not:
> "Assignments simplified by using assignment operators."

Done in 2f4cea2cc97926d31b297fdf83da026a37572cde.

**Comment by bobcatfish** [comment]
niiiice thanks for the improvements @sosiska !! :heart_eyes_cat:

**Pull request merged**
