### PR TITLE
Reserve /tekton/ paths and "tekton-internal-" volume names

### LINKED ISSUE #1304: Reserve "tekton/" folder in taskrun filesystem
We should consider reserving the `tekton/` folder in the taskrun filesystem and perhaps even move stuff from the current `builder/` folder to `tekton/`. 
The tekton folder could contain internal tools as well as things like the proposed JSON file containing the [pipelinerun context](https://docs.google.com/document/d/1eJBb2VHuSTbrIWfPE3TGdRRfdbJsRCOBIqfTwx9M3H8/edit#) and any other filesystem based standards we add in the future

 @ahpook [pointed](https://docs.google.com/document/d/1eJBb2VHuSTbrIWfPE3TGdRRfdbJsRCOBIqfTwx9M3H8/edit?disco=AAAADn5iEJ0) out that Github actions does something similar by reserving the /github folder i.e. the `/github/workflow/event.json` contains the request payload.

### PR DESCRIPTION
**Pull request by ImJasonH**
Reserve /tekton/ paths and "tekton-internal-" volume names

This prevents collisions between user-specified volumes and
Tekton-internal volumes used to support execution.

Some validation changes:
- volume names starting with "tekton-internal-" are not valid
- volumeMounts that mount at /tekton/* are not valid -- _except_ for `/tekton/home`, which we allow users to mount over, for instance if they want a PVC volume to persist the default home directory.

Tekton's own internal volume mounts are already mounted at /tekton/*,
and now all volume names start with "tekton-internal-"

Some Tekton-internal volume names were previously randomized to prevent
collisions, which is no longer necessary, so they're no longer
randomized.

creds-init mounts annotated K8s secrets into the creds-init process.
Previously those were mounted at /var/build-secrets/* (a relic of
knative/build times). Now those are mounted at /tekton/creds-secrets/*

Some init container names were also randomly generated, which is
unnecessary, so that's gone too.

/hold 
dependent of #1700

Fixes #1304

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) to build and release this image.

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md) are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes) must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS) and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes) must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS), and they must first be added [in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

# Release Notes

```
Reject volune names starting with "tekton-internal-" and volume mounts mounting under /tekton/* -- these are reserved for Tekton internal implementation details.
```

### CODE REVIEW

**Comment by vdemeester** [comment]
@ImJasonH needs a rebase :angel: :pray:

**Comment by vdemeester** [comment]
#1700 is merged, so I think we can remove the hold

/hold cancel
/retest

**Comment by ImJasonH** [comment]
Tests currently fail because we had previously allowed users to define their own `/workspace` and `HOME` volume, in case they wanted those to be persistent for instance.

I think that just means we need to keep allowing _those_ to be mounted over, but not fully-internal paths like `/tekton/scripts`.

I'll try to fix this up today or tomorrow.

**Pull request merged**
