### PR TITLE
Added condition Resource E2E Test and also updated Clients structure to make it exportable

### PR DESCRIPTION
**Pull request by praveen4g0**
Added condition Resource E2E tests and also updated "clients" structure to "Client" make it exportable 

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) to build and release this image.

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md) are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes) must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS) and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes) must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS), and they must first be added [in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

# Release Notes

```
Describe any user facing changes here, or delete this block.

Examples of user facing changes:
- API changes
- Bug fixes
- Any changes in behavior

```

### CODE REVIEW

**Comment by praveen4g0** [comment]
@dibyom  It's better to be exportable as it has many common/Reusable functions associated with it, which can be used in another components, reason I came up with struct name as Client insted of Clients is we have already used that name under controller.go, any suggestions on naming convention of Clients?

**Comment by dibyom** [comment]
These are just test clients right? So, are they being used in any package that is not `test`? Also maybe `TestClients` as the name?

**Comment by vdemeester** [comment]
> These are just test clients right? So, are they being used in any package that is not `test`? Also maybe `TestClients` as the name?

Definitely not `TestClients`, `golint` won't be happy about it anyway. It's in a `test` package, so `Clients` is fine (as it gets used as `test.Clients`)

**Comment by dibyom** [comment]
@vdemeester The are two exported  `test.Clients` if we use `Clients` -- one in pipeline/test/clients.go and the other in pipeline/test/controller.go

**Comment by sbwsg** [comment]
@praveen4g0 given that this client is only used in the test package, why does it need to be exported?  I can understand making it public if you have a specific use case as part of this change that requires it but I don't think we should make it public just because it might be useful in future.  We can instead make that change when we need it.

Do you still intend to work on this PR or should we close it for now?

**Comment by vdemeester** [comment]
I think we can either close or just have the conditionnals test in this PR @praveen4g0.
For cli we are duplicating part of those code (`Clients`), but I think it make sense for now

**Comment by praveen4g0** [comment]
So @vdemeester , should I go ahead close this pr, raise new one only for conditional tests??

**Comment by vdemeester** [comment]
@praveen4g0 yeah :+1: thanks :hugs:

**Pull request closed without merging**
