### PR TITLE
Add some tests for pkg/git/git.go

### PR DESCRIPTION
**Pull request by chmouel**
# Changes

Add some more tests for pkg/git/git.go

We are creating a fake local git repo where to clone from to avoid
network flakiness.

/kind misc

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [X] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [NA] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [X] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [NA] Release notes block has been filled in or deleted (only if no user facing changes)

```release-note
NONE
```

### CODE REVIEW

**Comment by chmouel** [comment]
Weird unit-tests definitively pass under my VM, let's see why it's failing on CI,

**Comment by chmouel** [comment]
/hold cancel


Tested (and fixed it) locally with gcr.io/tekton-releases/dogfooding/test-runner let's see if it works now

**Review by vdemeester — APPROVED** [review]

**Pull request merged**
