### PR TITLE
Switch `test/*.go` to using YAML rather than structs

### LINKED ISSUE #4276: start using `YAMLParsers` in `/test/*_test.go`
@imjasonh added `YAML` helpers in https://github.com/tektoncd/pipeline/blob/main/test/yaml.go which takes a `YAML` in a string and returns respective desearlized objects including:

* Task
* TaskRun
* Pipeline
* PipelineRun

These helpers can help simplify the way we have implemented the integration tests. Most of the integration tests under `/test` initialize objects directly or have implemented functions to create such objects. The integration tests also serves as a great reference after `/examples` for the users to learn how to implement task/pipeline specifications. It will be beneficial to our users and contributors, if we can simplify the tests i.e instead of initializing these objects, add `YAML` specifications in the tests.

A huge thank you to @abayer for undertaking this cleanup 🙏 

/kind cleanup

### PR DESCRIPTION
**Pull request by abayer**
# Changes

fixes #4276

/kind cleanup

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [x] [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Release notes block below has been filled in or deleted (only if no user facing changes)

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by abayer** [comment]
@pritidesai Yeah, `pipelinefinally_test.go` is just a fair amount of work to change to not being so parameterized, and I wanted to get the bulk of the work done first, at least. I'll probably refactor it in a followup PR.

**Comment by pritidesai** [comment]
thanks @abayer for all the hard work on this, I finally finished reviewing all the changes 😓  I have left a few comments. I doubt any of them are blocking since the tests are running fine unless those changes are not necessary or adding any value in terms of validating the functionality 😜 

let me know your thoughts ...

I am ready to merge this 💯

**Pull request merged**
