### PR TITLE
Fix the xml report generation for kind e2e jobs

### PR DESCRIPTION
**Pull request by afrittoli**
# Changes

The generation of the junitxml test results file fails because mktemp
accepts a slighlty different syntax on alpine. Pull in a fix to that
from the plumbing repo.

The ARTIFACTS varible is usually set by prow for prow jobs configs.
Set it to the mount point of the workspace used by the e2e kind
test task.

Signed-off-by: Andrea Frittoli <andrea.frittoli@uk.ibm.com>

/kind misc

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [x] [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [x] [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Release notes block below has been filled in or deleted (only if no user facing changes)

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
/lgtm

**Comment by afrittoli** [comment]
@lbernick The [Kind based CI job](https://dashboard.dogfooding.tekton.dev/#/namespaces/tekton-ci/pipelineruns/pull-pipeline-kind-k8s-v1-21-e2e-v9qv9?pipelineTask=e2e-tests&step=kind) I'm tweaking in this PR could be handy to split the main integration tests in multiple jobs without running out of clusters from boskos in our CI.
This PR helps in getting some results uploaded to a GCS bucket but there are still a few more things missing before we have similar functionality as with prow:

- requiring ok-to-tests for PRs coming from outside the org
- displaying comments with help on how to re-run the tests
- mark jobs as required in the branch protection - this could be done manually for now. One gotcha there is that notifications are configured today so that if a job is skipped then no notifications are sent, but we could change that to always send the notifications and mark skipped jobs as passed. 

In terms of displaying / storing logs, today we use the Tekton Dashboard, but that is short lived. Some ideas on how to improve on that: https://github.com/tektoncd/plumbing/issues/1046

**Pull request merged**
