### PR TITLE
Migrate some test builder references to structs

### PR DESCRIPTION
**Pull request by ImJasonH**
Also delete `test/builder/` since it appears to be unused.

Before:
```
$ git grep "tb\." | wc -l
    3579
```

After:

```
$ git grep "tb\." | wc -l
    3023
```

/kind cleanup

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [y] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [n/a] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [y] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [y] Release notes block has been filled in or deleted (only if no user facing changes)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) to build and release this image.

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md) are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes) must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS) and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes) must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS), and they must first be added [in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

# Release Notes

```release-note
NONE
```

/assign @vdemeester

### CODE REVIEW

**Review by vdemeester — COMMENTED** [review]
Overall seems good to me.

> Also delete `test/builder/` since it appears to be unused.

Yes, it was kept here to not break *downstream* consumer of this package. I think it should be ok to remove it now (cc @piyush-garg @pradeepitm12 @dibyom for cli and triggers)

**Comment by dibyom** [comment]
Thanks for flagging @vdemeester I think triggers still might be using some pipeline builders but I'll try to get rid of them. In any case, I think this PR can be merged -- won't break us until we update pipeline dependency

**Comment by ImJasonH** [comment]
ping @piyush-garg @pradeepitm12 any concerrns with this change?

**Comment by pradeepitm12** [comment]
> ping @piyush-garg @pradeepitm12 any concerrns with this change?



> ping @piyush-garg @pradeepitm12 any concerrns with this change?

This may require some changes in the tests of cli, but that can be handled.

**Comment by piyush-garg** [comment]
@ImJasonH This may break CLI tests whenever the next bump happens. We are not using the internal pkg, but are dependent on test/builder for CLI tests. I have created an issue in CLI to move to structs. https://github.com/tektoncd/cli/issues/1145

**Comment by ImJasonH** [comment]
So it sounds like people are generally okay with removing `test/builders/` and they'll remove references when they bump their dependency to pick up this change. Is that correct? Any other concerns before merging this?

**Pull request merged**
