### PR TITLE
Emit pipelinerun event when it is cancelled

### LINKED ISSUE #1229: cancel pipelinerun should emit pipelinerun event
# Expected Behavior
when cancel a pipelinerun by edit status, pipelinerun should emit a fail event.

# Actual Behavior
No event.
# Steps to Reproduce the Problem

1.
2.
3.

# Additional Info

### PR DESCRIPTION
**Pull request by Letty5411**
Fixes #1229

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) and [TaskRun](../tekton/publish-run.yaml) to build and release this image

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md)
are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes)
must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS)
and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes)
must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS),
and they must first be added
[in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

# Release Notes

```
Describe any user facing changes here, or delete this block.

Examples of user facing changes:
- API changes
- Bug fixes
- Any changes in behavior

```

### CODE REVIEW

**Comment by Letty5411** [comment]
> @googlebot I signed it!

**Comment by bobcatfish** [comment]
Thanks for finding this problem and fixing it this @Letty5411 ! 

Would you mind adding a test for this as well?

It looks like the best place to add it would be in our cancel tests: https://github.com/tektoncd/pipeline/blob/master/test/cancel_test.go

You can see an example of another end to end test that tests the events in https://github.com/tektoncd/pipeline/blob/master/test/pipelinerun_test.go#L203

**Comment by Letty5411** [comment]
> Thanks for finding this problem and fixing it this @Letty5411 !
> 
> Would you mind adding a test for this as well?
> 
> It looks like the best place to add it would be in our cancel tests: https://github.com/tektoncd/pipeline/blob/master/test/cancel_test.go
> 
> You can see an example of another end to end test that tests the events in https://github.com/tektoncd/pipeline/blob/master/test/pipelinerun_test.go#L203

Thanks for your suggestion, I have added the test. Could you help trigger the test?

**Comment by dibyom** [comment]
hey @Letty5411 looks like the build test is failing with a lint error:

> I0905 22:16:49.542] test/cancel_test.go:190: File is not `gofmt`-ed with `-s` (gofmt)

Could you run `gofmt -s -w test/cancel_test.go`? Otherwise, this change looks good :+1:

**Comment by Letty5411** [comment]
> hey @Letty5411 looks like the build test is failing with a lint error:
> 
> > I0905 22:16:49.542] test/cancel_test.go:190: File is not `gofmt`-ed with `-s` (gofmt)
> 
> Could you run `gofmt -s -w test/cancel_test.go`? Otherwise, this change looks good 👍

Thanks for your review, I have fixed it.

**Comment by Letty5411** [comment]
hi @dibyom , if this PR is OK, could you help merge it, thanks~

**Pull request merged**
