### PR TITLE
Add Git LFS Support to build-base image used by git-init to solve #2997

### PR DESCRIPTION
**Pull request by eqqe**
# Changes

Add git-lfs Alpine package to support Git LFS (https://git-lfs.github.com/) when cloning repositories.
/kind feature

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [ ] Release notes block has been filled in or deleted (only if no user facing changes)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) to build and release this image.

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md) are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes) must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS) and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes) must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS), and they must first be added [in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

# Release Notes

```release-note
Adding support for git-lfs repositories in git-init by adding the package in the git-init image
```

### CODE REVIEW

**Comment by vdemeester** [comment]
@eqqe this is gonna need a release-note entry, like "Adding support for git-lfs repositories in git-init by adding the package in the git-init image".

**Comment by eqqe** [comment]
@vdemeester I have updated the release note but the PR labels are not updated

**Comment by vdemeester** [comment]
> @vdemeester I have updated the release note but the PR labels are not updated

Ah right, it needs `release-note` after the three backtick (`) to be taken into account, I've update the desc :wink:

**Comment by pritidesai** [comment]
Should we add any tests? 🤔

**Comment by dlorenc** [comment]
> Should we add any tests? 🤔

The only meaningful test I can think of would be an e2e test of cloning a repo that uses Git LFS.

**Comment by sbwsg** [comment]
Yeah I think it would be useful to add a test around this, which I think could be most easily achieved by adding a YAML to our examples directory that uses a git server sidecar running git-lfs.  It looks like there's a test server available as part of the git lfs project: https://github.com/git-lfs/lfs-test-server

For an example of creating an example YAML that uses a sidecar as a git server see https://github.com/tektoncd/pipeline/blob/38455ba42c39233ec4abd6b078649a4e3b12a7c7/examples/v1beta1/taskruns/authenticating-git-commands.yaml#L64

**Comment by pritidesai** [comment]
This has five commits, please squash them into one.

**Pull request merged**
