### PR TITLE
Revamp compute resources documentation

### PR DESCRIPTION
**Pull request by lbernick**
# Changes
This commit updates Tekton documentation on compute resources.
It separates Kubernetes background into a separate section, describes how
resource requests differ in Tekton and in Kubernetes, adds examples for
LimitRange, and adds details for ResourceQuotas.

/kind  documentation

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [x] [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- n/a [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Release notes block below has been filled in
(if there are no user facing changes, use release note "NONE")

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by lbernick** [comment]
This PR describes the behavior of LimitRange support as modified in #4769

**Review by leeonlee — APPROVED** [review]
LGTM!

**Comment by vdemeester** [comment]
/hold
Let's wait for https://github.com/tektoncd/pipeline/pull/4769 to be merged then 🙃

**Review by vdemeester — APPROVED** [review]
/lgtm

**Pull request merged**
