### PR TITLE
Drop the tracker.

### PR DESCRIPTION
**Pull request by mattmoor**
# Changes

Tekton's use of the `tracker` is redundant with the informer events it already has configured, and the tracker lease the pipeline run controller is using is probably too small to actually be effective for long-running pipelines.

The tracker is built around the premise that resyncs happen to "refresh" things, and so to be safe the tracker lease should be a multiple of the resync period.  The pipeline controller is currently hardcoding `30m`, but the default resync period is `10h`, so anything taking longer than `30m` via the tracker will actually drop events.  The controller also seems to track a `TaskRun` with the name of the `PipelineRun`, which also feels wrong...  🤔 

Fortunately, I believe that both usages of the tracker are wholly redundant with informer events on owned resources anyhow, so this change should just remove unneeded complexity.

For additional background, the purpose of the tracked isn't to track owned resources, but rather to track resources referenced via `corev1.ObjectReference` (or equivalent).  We use this in Knative to track changes to Addressable resources that some resource might be delivering events to (e.g. maybe the address changed, or it is no longer Ready).

/kind cleanup

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [ ] [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [ ] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [ ] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [ ] Release notes block below has been filled in or deleted (only if no user facing changes)

# Release Notes

```release-note
NONE
```

cc @dlorenc @imjasonh @vdemeester @afrittoli

### CODE REVIEW

**Comment by mattmoor** [comment]
Rebased this on #4110 which just landed.

**Review by vdemeester — APPROVED** [review]
Seems good to me 😉

**Review by afrittoli — COMMENTED** [review]
Thanks!
Going back all the way to https://github.com/tektoncd/pipeline/pull/757, this is the first reference of the tracker that I see, but it was in a different place in the code, and it does not seem to be applicable anymore - today a Pipeline is not marked as done until all associated TaskRun have finished execution in some way.

/lgtm

**Pull request merged**
