### PR TITLE
Add resolvers deployment, with release and e2e integration

### LINKED ISSUE #4710: Promote Remote Resolution to beta
### Feature request

Remote resolution is currently behind the alpha feature gate in Tekton Pipelines. This issue is intended to track the work required to promote resolution into beta, removing the feature gate.

### Use case

Platforms and users would like to access Tekton resources in locations other than OCI registries or the cluster their taskruns and pipelineruns execute in.

### Criteria for Promotion

- [ ] Poll Pipeline maintainers for their preferred direction with resolution: integrate with pipelines + add out-of-box resolvers, keep entirely separate, go a different direction entirely.
- [ ] Once ^ is done, document the rest of the criteria for promotion here.

### PR DESCRIPTION
**Pull request by abayer**
# Changes

Closes #4710

/kind feature

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [x] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [x] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [x] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [x] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
action required: The separate Resolutions project has been folded into Pipeline. If currently using Resolution, remove the tekton-remote-resolution namespace before upgrading and installing the new "resolvers.yaml".
```

### CODE REVIEW

**Comment by abayer** [comment]
...I swear that the tests in `test/resolvers_test.go` all passed when I initially wrote this commit, but then I screwed myself up by not re-running those tests after incorporating https://github.com/tektoncd/resolution/pull/75. Whoops. =)

**Comment by abayer** [comment]
/retest

Hrm. The build tests keep failing and I can't figure out why...

**Comment by abayer** [comment]
I can't reproduce the `pull-tekton-pipeline-build-tests` failure locally, and it's not exactly a helpful failure:
```
./test/presubmit-tests.sh: line 60: 79368 Killed                  KO_DOCKER_REPO=example.com ko resolve --platform=all --push=false -R -f config > /dev/null
```
...right as it gets to the end of the `ko resolve` call. For giggles, I've broken up the `ko resolve` into two calls, one for everything but `config/resolvers`, and one just for `config/resolvers`. Maybe that'll help?

**Comment by abayer** [comment]
/retest

Well, splitting up the `ko resolve` calls _did_ work. I don't know why, but 🤷. Some flakiness on the e2e tests, but that just came out of nowhere, so I'm retrying...

**Comment by abayer** [comment]
Ok, the failure is legit - see #5396 for details and (hopefully) a solution.

**Review by vdemeester — APPROVED** [review]
😻

**Pull request merged**
