### PR TITLE
[Carry #3238] Cancel taskrun using entrypoint binary

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

This is a carry-over from #4618.

The cancellation of taskruns is now done through the entrypoint binary
through a new flag called 'cancel_file'. This removes the need for
deleting the pods to cancel a taskrun, allowing examination of the logs
on the pods from cancelled taskruns. Part of work on issue #3238

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [x] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [x] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
Taskrun can now be cancelled using the entrypoint, which results of Pods from these TaskRun to be no longer deleted: they are stopped instead.
```

### CODE REVIEW

**Comment by lbernick** [comment]
It looks like this is copied from #4618 without changes? I left a few comments on that PR, would you mind addressing them?

**Comment by kubasikus** [comment]
@vdemeester Hi, why did this get closed?

**Comment by vdemeester** [comment]
> @vdemeester Hi, why did this get closed?

Didn't have time to keep up-to-date, it's getting carried in https://github.com/tektoncd/pipeline/pull/6511

**Pull request closed without merging**
