### PR TITLE
Remove Results Field for PipelineRuns and TaskRuns

### LINKED ISSUE #1243: Remove unused Results field
# Expected Behavior

Our API should only contain fields we actually use.

# Actual Behavior

[The results field](https://github.com/tektoncd/pipeline/blob/dbd2e69ca91af93943e16d4beb9e12d72f1c60f7/pkg/apis/pipeline/v1alpha1/pipelinerun_types.go#L57) was part of our very first design and was imagine to contain info like links to logs and test results, but we have since not done anything with it. When we choose to revisit these topics we can add in fields as needed safely, but we should remove this field for now b/c it does nothing at all and the longer we leave it in, the greater the chances that someone will come to rely on it for some reason.

### PR DESCRIPTION
**Pull request by danielhelfand**
Closes #1243 

This pull request removes the `Results` field for `pipelineruns` and `taskruns` from the Tekton pipeline API. 

I also touched up some language in `api_compatibility_policy.md` after noticing some typos when reading it over.

# Changes

Removes all `Results *Results` references throughout the project.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md)
are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes)
must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS)
and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes)
must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS),
and they must first be added
[in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

# Release Notes

```
Removes Results field from API for PipelineRuns and TaskRuns
```

### CODE REVIEW

**Comment by danielhelfand** [comment]
Addressed issues build/test issues. Should be ready for a review. Thanks!

**Comment by sbwsg** [comment]
Is this a backwards compatible change?  Or has it already been placed into deprecated state for some number of releases?

Removal of fields has tripped us up a little bit before - thinking of the "Trigger" field that got removed from TaskRuns at the same time as the validation webhook started rejecting resources with unknown fields.

**Comment by danielhelfand** [comment]
@sbwsg I am unaware if the field has been deprecated and if there has been notice given, but this will break users who are using the `Results` field and some notice should be given. 

According to your policy, it looks like you like to give a full release notice. I saw the issue was targeted for 0.7.0.

**Comment by danielhelfand** [comment]
However, judging by the writing in the issue, it seems as if this field doesn't really have much of a purpose other than to be a placeholder. Digging through the code that I removed in this pr, it doesn't appear like `Results` was really used for anything. So, unless I am mistaken, I believe this would be backwards compatible as it doesn't appear to do anything at this point. I think it's reasonable to assume this is not being used.

**Comment by sbwsg** [comment]
I wonder if a good approach here might be to log a warning to indicate that the field is deprecated as of 0.7.0, document it as part of the 0.7.0 release notes, and then remove it completely in 0.8.0?  I'm not sure if the warning part is possible though - @vdemeester @bobcatfish any thoughts on this?

**Comment by dibyom** [comment]
Yeah, we can definitely call it out in the release notes, and maybe log a warning in the controller logs though I'm not sure how useful that will be.

**Comment by danielhelfand** [comment]
I can agree with the idea that logging, at least in the ways we could, would probably not be the best way to communicate this. What if we announced the 0.7.0 release notes this field will be deprecated and also add in code comments to `Results` for both `TaskRunSpec` and `PipelineRunSpec` that these fields will be deprecated in 0.8.0?

**Comment by sbwsg** [comment]
sounds good to me

**Comment by danielhelfand** [comment]
@sbwsg Thanks for your help. I'll close this now and we can revisit it in 0.8.0. I can open a pr comments announcing the deprecation in 0.8.0.

**Pull request closed without merging**
