### PR TITLE
[master] Fix spelling errors

### PR DESCRIPTION
**Pull request by mattmoor**
Produced via:
  `github.com/client9/misspell`
/assign ImJasonH vdemeester
/cc ImJasonH vdemeester

### CODE REVIEW

**Comment by vdemeester** [comment]
@mattmoor you need to sign the cla :stuck_out_tongue:

**Comment by mattmoor** [comment]
> you need to sign the cla

I don't sign CLAs, VMware does. 😉 

I kicked the machine last week when this new bot got turned on, and it is working its way through the red tape 🤞

Glad to see you finally dropped the googlebot 😂

**Comment by afrittoli** [comment]
Holding off lgtm until CLA is green

**Comment by mattmoor** [comment]
I pinged the ticket this morning 😞

**Comment by mattmoor** [comment]
With some luck the CLA stuff has been resolved.  IDK how to poke this bot, so I'm going to wait for the force push tomorrow morning 🤞

**Comment by vdemeester** [comment]
@mattmoor you might need to re-push :sweat_smile:

**Pull request merged**
