### PR TITLE
Define new types for Cloud Events

### PR DESCRIPTION
**Pull request by afrittoli**
# Changes

Define new types in TaskRun to hold the information and status
about cloud events to be delivered once a TaskRun is complete.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [n/a] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) and [TaskRun](../tekton/publish-run.yaml) to build and release this image

### CODE REVIEW

**Comment by afrittoli** [comment]
@vdemeester my idea here was to have a simple solution for a CloudEvent base type of notification; but yeah we still need to tackle the topic of notifications more in general. This implementation gives you a nice way to do notifications that works well with triggers so we can soon start chaining tasks asynchronously. 
I'm not opposed to the idea of introducing a NotificationResource that would be specialized into CloudEventResource but I feel that's something we could do as a follow-up?

**Comment by vdemeester** [comment]
> I'm not opposed to the idea of introducing a NotificationResource that would be specialized into CloudEventResource but I feel that's something we could do as a follow-up?

Yeah, I was thinking outloud :angel:

**Pull request merged**
