### PR TITLE
cleaning up provenance from pipelineRun

### PR DESCRIPTION
**Pull request by pritidesai**
# Changes

The tests are intended to not validate provenance fields and hence deleting those fields from the status and adding `ignoreProvenance` while comparing actual and expected `pipelineRun`.

Deleting provenace from:

- https://github.com/tektoncd/pipeline/blob/main/pkg/reconciler/pipelinerun/pipelinerun_test.go#L1200
- https://github.com/tektoncd/pipeline/blob/main/pkg/reconciler/pipelinerun/pipelinerun_test.go#L4821
- And all the instances from `matrix` tests

/kind cleanup

@dibyom as mentioned in the earlier PR - https://github.com/tektoncd/pipeline/pull/7064#discussion_r1313405792

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) if any changes are user facing, including updates to minimum requirements e.g. Kubernetes version bumps
- [x] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [x] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings). See some examples of [good release notes](https://github.com/tektoncd/community/blob/main/standards.md#good-release-notes).
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by jerop — APPROVED** [review]
/test check-pr-has-kind-label

**Comment by Yongxuanzhang** [comment]
Thanks! 
/lgtm

**Comment by jerop** [comment]
retriggering CLA

**Pull request merged**
