### PR TITLE
Can I reproduce it with just the timeout test alone? 🎵

### PR DESCRIPTION
**Pull request by bobcatfish**
One is the loneliest number
One is the loneliest number
One is the loneliest number that you'll ever do
One is the loneliest
One is the loneliest
One is the loneliest number that you'll ever do

Investigating #731

### CODE REVIEW

**Comment by bobcatfish** [comment]
lol maybe not...

AGAIN

/test pull-tekton-pipeline-integration-tests

**Comment by bobcatfish** [comment]
```
--- PASS: TestTaskRunTimeout (31.24s)
```

ಠ_ಠ

**Comment by bobcatfish** [comment]
```
I0417 23:21:39.521] === PAUSE TestTaskRunTimeout
I0417 23:21:39.521] === CONT  TestTaskRunTimeout
I0417 23:22:09.642] --- PASS: TestTaskRunTimeout (31.21s)
```

😩

/test pull-tekton-pipeline-integration-tests

**Comment by bobcatfish** [comment]
I mean its really seeming like just the one test on its own is never hitting this, I say, based on my sample set of 5.

/test pull-tekton-pipeline-integration-tests

**Comment by vdemeester** [comment]
> I mean its really seeming like just the one test on its own is never hitting this, I say, based on my sample set of 5.

Yes that was kind of my assumption too… when run alone (without any load), it seems to hold on… I think timeout is flakey under medium to heavy load on the controller, somehow

**Comment by bobcatfish** [comment]
>  I think timeout is flakey under medium to heavy load on the controller, somehow

I'm wondering if it's something load related too :thinking::thinking: :thinking:  which will be harder to figure out probably. It's weird tho cuz it _never_ seems to happen locally, even using (what I think is) the same cluster setup.

**Comment by bobcatfish** [comment]
via https://github.com/tektoncd/pipeline/pull/771 i have a strong theory about what's going on, will update #731 :dancing_women:

**Pull request closed without merging**
