### PR TITLE
ref: prompt for specific error fields

### PR DESCRIPTION
**Pull request by cugykw**
# Changes

We encountered an error, but the error message does not match.

```
Error from server (BadRequest): error when creating "pipeline_scan.yml": admission webhook "validation.webhook.pipeline.tekton.dev" denied the request: validation failed: invalid value: name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]'): spec.tasks[0].name
```

# Steps to Reproduce the Problem
```
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
...
  - name: scan
    params:
    - name: git_reponame
      value: $(params.git_reponame)
    runAfter:
    - git-clone
    taskRef:
      kind: ClusterTask
      name: scan-security.  // invalid taskRef.name
    workspaces:
    - name: repo
      workspace: repo
...
```

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [x] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [x] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [ ] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]

**Review by jerop — COMMENTED** [review]
thank you @cugykw! 

/lgtm

**Pull request merged**
