### PR TITLE
Google/ko 5.0+ requires images to be prefixed by ko:// .

### PR DESCRIPTION
**Pull request by akram**
# Changes

Adds ko:// scheme to images used by ko

See https://github.com/google/ko/issues/158

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) to build and release this image.

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md) are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes) must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS) and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes) must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS), and they must first be added [in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

# Release Notes

```release-note
Adds ko:// scheme to images used by ko (dev only)
```

### CODE REVIEW

**Comment by afrittoli** [comment]
Thanks for this. 

We tried this before (https://github.com/tektoncd/pipeline/pull/2216, https://github.com/tektoncd/pipeline/pull/2216) but we reverted it (https://github.com/tektoncd/pipeline/pull/2561, https://github.com/tektoncd/pipeline/pull/2624, https://github.com/tektoncd/pipeline/pull/2624) because it broke our release process, there is an issue (https://github.com/google/ko/issues/164) with `ko` when using `ko://` and the `-P` (preserve path) flag. 

As far as I can see the issue on `ko` side is still open. I would prefer once the issue is solved on `ko` side to revert the reverts and get the `ko://` back in that way.

**Comment by akram** [comment]
note @afrittoli 
I will keep it up to you close the PR if it is a dup or let it open if it could be helpful in a close future.

**Comment by bobcatfish** [comment]
@vdemeester afaik someone needs to experiment with changing the yamls back to using ko:// and possibly bumping the pinned version of ko we are building into the gcloud images

as a bonus it would be great to understand more about how the version pinning actually works since it doesnt seem to guarantee that we get the pinned version at all

**Comment by mattmoor** [comment]
I linked what we're doing in the Knative prow images from the linked issue above.

As far as I know 0.5.1 (what we pin) fixes what you are seeing and HEAD has a further fix for "local" mode, which we've been using successfully with KinD for weeks now.

**Comment by vdemeester** [comment]
/kind misc
Rebased and updated the release-note part.

/lgtm

**Comment by bobcatfish** [comment]
let's give it a shot

/approve

**Comment by bobcatfish** [comment]
Looks like #2850 should have fixed the cancel tests, however it did get merged 4 hours ago and the latest flake was 1 hour ago so maybe we should keep an eye on it.

**Comment by vdemeester** [comment]
`test TestPipelineLevelFinally_OneDAGTaskFailed_Failure 1m26s`.. a new one…
/retest

**Pull request merged**
