### PR TITLE
Non terminal pod exists

### PR DESCRIPTION
**Pull request by vaikas**
# Changes
If for some reason the pod fails to be created because it already exists, do not treat it as a
terminal failure. More background in #4741

/kind bug

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [ ] [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [ ] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [ ] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [ ] Release notes block below has been filled in
(if there are no user facing changes, use release note "NONE")

# Release Notes

```release-note
If for some reason between getting the pod with a list and creation it already exists, do not
treat it as a terminal failure.
```

### CODE REVIEW

**Comment by vdemeester** [comment]
ping @vaikas

**Comment by vaikas** [comment]
@vdemeester this one builds on top of #4740 so I'd rather rebase after/if that gets merged.

**Review by afrittoli — COMMENTED** [review]
Thanks for this!
It would be great to have test coverage for this new case.

**Comment by vaikas** [comment]
Fantastic, thanks. I was out on PTO so I'll be taking a look this week.

**Pull request merged**
