### PR TITLE
Add a PipelineResourceBase struct that implements some stub versions …

### PR DESCRIPTION
**Pull request by dlorenc**
…of the interfaces.

# Changes

This struct can be embedded to simplify and reduce boilerplate across the different resource
types, making further refactors easier.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [X] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [X] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [X] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

### CODE REVIEW

**Comment by dlorenc** [comment]
> My personal feeling is that a slight reduction in the amount of code that needs to be written and faster refactoring are not worth introducing inheritance.

I don't think embedding in this fashion is really inheritance: https://medium.com/@simplyianm/why-gos-structs-are-superior-to-class-based-inheritance-b661ba897c67

but don't feel strongly enough about this to argue it. I think that criticism could basically apply to any form of struct or interface embedding, which we (and most Go programs) make heavy use of.

**Comment by dlorenc** [comment]
> I wonder if there is another way we can tackle this - if we're finding that the interface our resources are implementing contains functions which frequently aren't needed for resources, maybe we should change the interface - maybe we should have a separate object for UploadVolume + DownloadVolume specs for example, with no implementation for types that don't need it.

One idea I was kicking around is to remove most of these methods and give resources *one* method with a signature something like:

```golang
func ModifyTaskSpec(spec TaskSpec) (TaskSpec, error)
```

which would be more flexible, but harder to unit test and provide less well-defined lifecycle hooks. Any thoughts on that approach?

**Comment by bobcatfish** [comment]
> I don't think embedding in this fashion is really inheritance: https://medium.com/@simplyianm/why-gos-structs-are-superior-to-class-based-inheritance-b661ba897c67

Thanks for the link! Unfortunately I'm still not completely convinced, but I'd really like to be :( Like you said, struct embedding is used all over the place, and I find it makes reasoning about the code very difficult.

The article suggests that the main downside of inheritance is that "changing a base class can cause unwanted side effects all over a code base" and I don't see how that's any different when the "base" class is embedded vs. inherited.

```go
type Foo struct {}
type Bar struct {
  Foo
}
type Baz struct {
  Bar
}

func (Foo) A() {
   fmt.Println("Foo A")
}

func (Foo) B() {
   fmt.Println("Foo B")
}

func (Bar) B() {
   fmt.Println("Bar B")
}

func (Baz) C() {
   fmt.Println("Baz C")
}


func main() {
	f := Baz{}
	f.A()
	f.B()
	f.C()
}
```

Output:

```
Foo A
Bar B
Baz C
```

Seems nearly as confusing as conventional inheritance to me!

>  I think that criticism could basically apply to any form of struct or interface embedding, which we (and most Go programs) make heavy use of.

I totally agree that this applies to all embedding, not just this particular case!

On a similar note - Python programs use inheritance and polymorphism like crazy, but I'd still maintain that it should be avoided as much as possible.

> func ModifyTaskSpec(spec TaskSpec) (TaskSpec, error)

hmm interesting! this gave me some more ideas (im not super convinced by any of them either tho, and in fact I'm leaning toward going along with what you proposed in the meantime XD - i mention in idea 2 tho that im wondering how this will work with resource extensibility)

### idea 1 - embedding & modifying TaskSpec

What do you think about this compromise, which does use struct embedding but I think limits the blast radius a bit more:

- Each Resource type has two functions, e.g.:
  -  `func (s GitResource) GetTaskSpecInputUpdates() TaskSpecUpdates`
  -  `func (s GitResource) GetTaskSpecOutputUpdates() TaskSpecUpdates`
- `TaskSpecUpdates` is an interface with functions for each type we know we want to update, in this case `Volumes` and `Steps`
- We have an implementation `TaskSpecNoUpdates` for which `Volumes` and `Steps` return empty lists
- Each Resource type can have its down Updater, e.g. `GitInputUpdates` which can embed `TaskSpecNoUpdates` if it wants, to default to updating nothing, or the function can simply return `TaskSpecNoUpdates` if there are none.

What I like about this:
- TaskSpecNoUpdates is a bit more descriptive than PipelineResourceBase
- We can expand TaskSpecUpdates with other parts of a `TaskSpec` that need to be updated (probably wouldnt ever happen tho??)
- The existing types don't start inheriting from a base class; we limit this to only the functionality we want to control this way (the TaskSpec modification) vs. the entrity of each Resource type

### idea 2 - pod spec

I was trying to think what other parts of the TaskSpec a PipelineResource might need to modify, and I realized it was totally news to me that they needed to add `Volume`s as well (thanks for #1139 btw!!)

The proposed contract in [the resource extensibility proposal](https://docs.google.com/document/d/1rcMG1cIFhhixMSmrT734MBxvH3Ghre9-4S2wbzodPiU/edit?ts=5d512593#heading=h.2ux1nabff3w3) has `beforecontainers` and `aftercontainers` but nothing about volumes at all, however I think they are required. So a couple ways to handle that:

- Add `Volumes` to the contract as well (which assumes we only ever need to update steps + volumes to make PipelineResources happen)
- Make each of the `beforecontainers` and `aftercontainers` a pod spec which the Pipeline controller would have to introspect and somehow merge with the pod it wants to make (similar probably to [how we merge `stepTemplate`](https://github.com/tektoncd/pipeline/blob/7a0454b27e9966ac6063b4c5320c46864fe33fc6//pkg/apis/pipeline/v1alpha1/merge.go#L29:6))

**Comment by bobcatfish** [comment]
wow

**Pull request closed without merging**
