### PR TITLE
chore: change the boilerplate in copyright from 2020 to 2023 

### PR DESCRIPTION
**Pull request by kycheng**
# Changes

Change copyright in boilerplate from 2020 to 2023.

refs: #6232

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [x] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [x] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [x] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [x] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```
NONE
```

### CODE REVIEW

**Comment by kycheng** [comment]
The wrong operation caused the pr https://github.com/tektoncd/pipeline/pull/6292 to be closed, and a pr was reopened.

**Comment by kycheng** [comment]
> There were a bunch of questions that popped up from this around our obligations for license headers. We have an open ticket with the CDF asking how to best move forward here. Until we get a response, we'll need to put this on hold. 😢

Well, I'm willing to work on this if need be.

**Comment by pritidesai** [comment]
thanks @kycheng for working on this!

thanks @wlynch, do we have a ticket or issue that we can link with CDF? apologies in advance if I have missed it.

**Pull request closed without merging**
