### PR TITLE
Describe Runtime Envs of E2E Tests

### PR DESCRIPTION
**Pull request by XinruZhang**
# Changes

Prior to this PR, it is unclear that where the local tests run and the difference between local tests and presubmit/CI tests. It can be hard for people to understand/debug test failures, especially for people who start to contribute to Tekton.

This PR enriches the test doc to clarify the difference mentioned above.

/kind documentation

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [x] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [x] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [x] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [x] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

``` release-note
NONE
```

### CODE REVIEW

**Comment by abayer** [comment]
/approve

Could you change the commit message/PR title to reflect that this is just describing the environment for e2e tests?

**Comment by XinruZhang** [comment]
@abayer  Oh good catch!! updated. Thx!

**Review by jerop — APPROVED** [review]
/lgtm

**Pull request merged**
