### PR TITLE
Bump TestSidecarTaskSupport test timeout to 2m.

### PR DESCRIPTION
**Pull request by wlynch**
# Changes

The sidecar tests have been fairly flaky. :(
While in upstream we've added more compute at the prow clusters to
help, this has still been noticable in other CI environments.

Bumping this for the time being to help the pain. It'd probably be worth
looking into if there's room for improvement for why these are taking so
long to schedule.

/kind flake

Related: https://github.com/tektoncd/pipeline/issues/2656

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [n/a] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [ n/a] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [x] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [x] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by wlynch** [comment]
Hmmmmm not sure why the release notes none aren't being picked up. Docs say this should be okay...

/release-note-none

**Comment by imjasonh** [comment]
/lgtm

Is there a space between the ` and the release-note? That's tripped me up in the past.

**Comment by wlynch** [comment]
> Is there a space between the ` and the release-note? That's tripped me up in the past.

That was it! Looks like https://github.com/tektoncd/pipeline/pull/5105 should fix. 😎

**Comment by wlynch** [comment]
unit tests failing due to https://github.com/tektoncd/pipeline/issues/5254

**Comment by wlynch** [comment]
unit tests failing due to https://github.com/tektoncd/pipeline/issues/5152

**Comment by abayer** [comment]
/approve

For what it's worth, I think I tried tweaking this timeout earlier and it didn't solve the problem. But I could be confusing memories of failed attempts to get the various `PipelineRun` timeout tests to pass consistently (which ended up leading to me writing #5134, which itself is waiting on #5224).

**Pull request merged**
