### PR TITLE
Move namespace.yaml to avoid unintended deletion of other components

### PR DESCRIPTION
**Pull request by hidehitof**
related: #4064
# Changes
Move namespace.yaml to avoid unintended deletion of other components.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [x] Release notes block has been filled in or deleted (only if no user facing changes)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) to build and release this image.

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md) are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes) must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS) and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes) must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS), and they must first be added [in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

# Release Notes

```release-note
Moved namespace.yaml in order to avoid unintended deletion of other tekton components. 
```

### CODE REVIEW

**Comment by hidehitof** [comment]
The test seems to fail.
I will investigate the cause, then rerun the test.

**Comment by kobaji** [comment]
This is @kobaji , working with @hidehitof .

I found the following command (installing pipeline) also need to be executed with `-R` option.

https://github.com/tektoncd/pipeline/blob/main/DEVELOPMENT.md#install-pipeline

```
ko apply -f config/
```
We will be also updating this.

**Comment by vdemeester** [comment]
Right we need to update the e2e tests to do this too

**Review by afrittoli — COMMENTED** [review]
Thanks for this change.

This has an impact on our releases too, we should update the release task as well so that the namespace is included in the release yaml like today.

I think this may be useful for the development workflow but I'd prefer not to alter the shape of the release file.

**Comment by hidehitof** [comment]
> Thanks for this change.
> 
> This has an impact on our releases too, we should update the release task as well so that the namespace is included in the release yaml like today.
> 
> I think this may be useful for the development workflow but I'd prefer not to alter the shape of the release file.

@afrittoli 
Thank you very much for your comment.

We should NOT change the config folder, just we should note in DEVELOPMENT.md, right?

**Comment by vdemeester** [comment]
> We should NOT change the config folder, just we should note in DEVELOPMENT.md, right?

No I think we should change the config folder, but we also need to update the release "scripts" and tasks (in `tekton/` folder) to take this change into account (and include the `namespace` as part of the release).

**Comment by kobaji** [comment]
/kind documentation

Checking the following URL, I found the above label is required.
https://dashboard.dogfooding.tekton.dev/#/namespaces/tektonci/pipelineruns/check-pr-labels-96r4f?pipelineTask=kind-label&step=check-labels

**Comment by hidehitof** [comment]
Now we have changed the structure of config folder. The test seems to be successful.
But we have not touched the tasks which is to update the release "scripts" and tasks (in tekton/ folder) regarding [this comment](https://github.com/tektoncd/pipeline/pull/4093#issuecomment-889796269).
Next, we will touch those tasks.

**Comment by kobaji** [comment]
Hi @vdemeester Thank you very much for your kind advice.

> we also need to update the release "scripts" and tasks (in tekton/ folder) to take this change into account (and include the namespace as part of the release).

Our survey revealed that L143 and L147 in the following file should be updated. (I apologize for not taking much time to this PR)
Is it enough update? Or do we need something more?

https://github.com/tektoncd/pipeline/blob/caa619b8d14999e8599f7ea86a7521e421d20c3e/tekton/publish.yaml#L143

↓ (adding `-R`)

```
       ko resolve --platform=$(params.platforms) --preserve-import-paths -t $(params.versionTag) -R -f ${PROJECT_ROOT}/config/ > $OUTPUT_RELEASE_DIR/release.yaml 
```

https://github.com/tektoncd/pipeline/blob/caa619b8d14999e8599f7ea86a7521e421d20c3e/tekton/publish.yaml#L147

↓ (adding `-R`)

```
      ko resolve --platform=$(params.platforms) --preserve-import-paths -R -f ${PROJECT_ROOT}/config/ > $OUTPUT_RELEASE_DIR/release.notags.yaml
```

Thank you very much for your kind help!!

**Review by vdemeester — APPROVED** [review]

**Comment by hidehitof** [comment]
@afrittoli @imjasonh 
I'm so sorry for the late fix.
Now I have changed the structure of config folder and updated release "scripts" and tasks (in tekton/ folder), 
which is commented [at here](https://github.com/tektoncd/pipeline/pull/4093#issuecomment-889796269),
 with [these changes](https://github.com/tektoncd/pipeline/pull/4093#issuecomment-905442339).
I would like you to check my fixes.

**Comment by jerop** [comment]
thank you @hidehitof and @kobaji for the contributions and your patience! 

looks good to me, please the `-R` to the test guide as well:

https://github.com/tektoncd/pipeline/blob/76cb481f504c48a1c110a8d6e670ede5fe5ef0ca/test/README.md#L1-L8

/approve

**Comment by hidehitof** [comment]
@jerop 
Thank you very much for your kind advice.
I will change the it and search if there is similar problem or not in the sources.

**Comment by hidehitof** [comment]
@jerop
I searched if there is similar problem or not in the sources.
Should we change following parts?


https://github.com/tektoncd/pipeline/blob/46d332c2aedef45a0c4b4d3d30f2f44cbb071709/DEVELOPMENT.md?plain=1#L382-L384
https://github.com/tektoncd/pipeline/blob/46d332c2aedef45a0c4b4d3d30f2f44cbb071709/DEVELOPMENT.md?plain=1#L384-L386
https://github.com/tektoncd/pipeline/blob/46d332c2aedef45a0c4b4d3d30f2f44cbb071709/test/e2e-common.sh#L26-L28
https://github.com/tektoncd/pipeline/blob/46d332c2aedef45a0c4b4d3d30f2f44cbb071709/test/e2e-common.sh#L49-L51
https://github.com/tektoncd/pipeline/blob/46d332c2aedef45a0c4b4d3d30f2f44cbb071709/test/e2e-common.sh#L65-L67
https://github.com/tektoncd/pipeline/blob/46d332c2aedef45a0c4b4d3d30f2f44cbb071709/Makefile#L67-L69
https://github.com/tektoncd/pipeline/blob/46d332c2aedef45a0c4b4d3d30f2f44cbb071709/Makefile#L71-L73
https://github.com/tektoncd/pipeline/blob/46d332c2aedef45a0c4b4d3d30f2f44cbb071709/tekton/publish.yaml#L157-L159
https://github.com/tektoncd/pipeline/blob/46d332c2aedef45a0c4b4d3d30f2f44cbb071709/tekton/publish.yaml#L161-L163
https://github.com/tektoncd/pipeline/blob/46d332c2aedef45a0c4b4d3d30f2f44cbb071709/test/presubmit-tests.sh#L61-L63

**Comment by jerop** [comment]
@hidehitof thanks for being so thorough! yes, that's right and would maintain the current behavior of those functions :) 

/closes https://github.com/tektoncd/pipeline/issues/4064

**Comment by hidehitof** [comment]
@jerop
I'm so sorry for the late fix.
Now I have changed some points which needs ```-R``` option based on [this](https://github.com/tektoncd/pipeline/pull/4093#issuecomment-969974587) comment.

In addition these change, I found more problem and I added -R to these.

https://github.com/tektoncd/pipeline/blob/e6327c869317f83d52f59932542d06269993b075/Makefile#L67-L69
https://github.com/tektoncd/pipeline/blob/e6327c869317f83d52f59932542d06269993b075/Makefile#L71-L73
And I didn't change this source because it will delete all resources regardless ```-R``` option
https://github.com/tektoncd/pipeline/blob/e6327c869317f83d52f59932542d06269993b075/test/e2e-common.sh#L49-L51

**Comment by hidehitof** [comment]
> @jerop I'm so sorry for the late fix. Now I have changed some points which needs `-R` option based on [this](https://github.com/tektoncd/pipeline/pull/4093#issuecomment-969974587) comment.
> 
> In addition these change, I found more two problems and I added `-R` to these.
> 
> https://github.com/tektoncd/pipeline/blob/e6327c869317f83d52f59932542d06269993b075/Makefile#L67-L69
> 
> 
> https://github.com/tektoncd/pipeline/blob/e6327c869317f83d52f59932542d06269993b075/Makefile#L71-L73
> 
> 
> And I didn't change this source because it will delete all resources regardless `-R` option
> https://github.com/tektoncd/pipeline/blob/e6327c869317f83d52f59932542d06269993b075/test/e2e-common.sh#L49-L51

**Comment by hidehitof** [comment]
@afrittoli @imjasonh 
If you have time, I'd really appreciate it if you could check our changes. The detail of changes is written [here](https://github.com/tektoncd/pipeline/pull/4093#issuecomment-969974587) and [here](https://github.com/tektoncd/pipeline/pull/4093#issuecomment-1009605999)

**Comment by jerop** [comment]
@kobaji @hidehitof apologies for the delay and thank you for the patience 😁 

/lgtm

**Pull request merged**
