### PR TITLE
Have the timeout handler decorate log lines with "key".

### PR DESCRIPTION
**Pull request by mattmoor**
Several of the methods in the timeout handler deal with specific keys, and log information about them; however, they do not decorate these log lines with the key they are acting on, so when filtering by key (e.g. logstream) they don't show up.  This decorates the logger with these keys in contexts where they are available.

I am hoping this will narrow down some of the timeout_test flakes I've been hunting.

/kind cleanup

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [ ] Release notes block has been filled in or deleted (only if no user facing changes)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) to build and release this image.

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md) are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes) must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS) and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes) must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS), and they must first be added [in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

# Release Notes

```release-note
Log statements from the timeout handler will now be decorate with the key of the resource they are acting on.
```

cc @bobcatfish

### CODE REVIEW

**Comment by mattmoor** [comment]
/retest

Helm test failed with:
```
error building image: Get https://index.docker.io/v2/library/golang/manifests/latest: EOF
```

I saw a similar flake yesterday downstream, I wonder if it's worth picking a different image 🤔   Maybe one on GCR so this test isn't predicated on the availability of two registries (since kaniko already has to be pulled from there).

**Review by vdemeester — APPROVED** [review]
/meow

**Review by jerop — COMMENTED** [review]
> Log statements from the timeout handler will not be decorate with the key of the resource they are acting on.

in the release note above, did you mean "will be" instead of "will not be"? 🤔

**Comment by mattmoor** [comment]
@jerop good catch.  I often typo `now` as `not` 🤦

**Pull request merged**
