### PR TITLE
Updated clock to use k8s.io/utils/clock

### PR DESCRIPTION
**Pull request by perithompson**
# Changes

This PR updates clock to use k8s.io/utils/clock

When importing tekton libraries into other projects that uitilise the
k8s.io/apimachinary modules, the import will fail as this has now been
removed in favour of k8s.io/utils/clock.clock. This Commit moves to use
this new package.

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [x] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [x] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [x] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [x] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

/kind cleanup

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by lbernick — APPROVED** [review]
thanks @perithompson!

**Comment by abayer** [comment]
/lgtm

@perithompson Looks like you need a CLA filed - see https://github.com/tektoncd/pipeline/pull/5413#issuecomment-1234395779

**Comment by perithompson** [comment]
Thanks @abayer! I have requested this internally, I will follow up next week

**Comment by abayer** [comment]
Hooray! =)

**Pull request merged**
