### PR TITLE
Fix sample yaml

### PR DESCRIPTION
**Pull request by piyush-garg**
Yaml provided as a sample have missing property
and are confusing the users

Fix them to avoid confusions and also used the
consistent naming

Fixes https://github.com/tektoncd/pipeline/issues/755

### CODE REVIEW

**Comment by chmouel** [comment]
awesome 👍

**Comment by bobcatfish** [comment]
This is great, thanks so much for catching and fixing this @piyush-garg !!! :heart::heart::heart:

/approve
/meow space

**Pull request merged**
