### PR TITLE
Run enhancements

### PR DESCRIPTION
**Pull request by GregDritschler**
# Changes

This PR contains a number of small enhancements related to the new `Run` type. I am building a custom controller to handle `Run`s. I found these enhancements to be helpful in building it.

* Add a status field to the `Run` spec to support requesting cancellation of the `Run`
* Add helper functions (`MarkRunFailed`, etc.) to update the Run status condition, similar to ones in `pipelinerun_types.go` and `taskrun_types.go`
* Add helper functions to serialize and deserialize a `Run`'s `extraFields`
* Add a filter function that can be used when creating an event handler to notify your custom controller when an object owned by a `Run` is modified

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [ ] Release notes block has been filled in or deleted (only if no user facing changes)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) to build and release this image.

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md) are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes) must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS) and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes) must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS), and they must first be added [in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

# Release Notes

### CODE REVIEW

**Comment by GregDritschler** [comment]
@ImJasonH new PR with just the runtime changes

**Comment by GregDritschler** [comment]
TestExamples failed trying to access github

        {"level":"error","ts":1601390535.111976,"caller":"git/git.go:53","msg":"Error running git [fetch --recurse-submodules=yes --depth=1 origin --update-head-ok --force master]: exit status 128\nfatal: unable to access 'https://github.com/tektoncd/pipeline/': Could not resolve host: github.com\n","stacktrace":"github.com/tektoncd/pipeline/pkg/git.run\n\tgithub.com/tektoncd/pipeline/pkg/git/git.go:53\ngithub.com/tektoncd/pipeline/pkg/git.Fetch\n\tgithub.com/tektoncd/pipeline/pkg/git/git.go:144\nmain.main\n\tgithub.com/tektoncd/pipeline/cmd/git-init/main.go:52\nruntime.main\n\truntime/proc.go:203"}
        {"level":"fatal","ts":1601390535.1121497,"caller":"git-init/main.go:53","msg":"Error fetching git repository: failed to fetch [master]: exit status 128","stacktrace":"main.main\n\tgithub.com/tektoncd/pipeline/cmd/git-init/main.go:53\nruntime.main\n\truntime/proc.go:203"}

**Review by ImJasonH — COMMENTED** [review]
/lgtm

**Review by vdemeester — CHANGES_REQUESTED** [review]
@GregDritschler can you write a more informative commit messages ? It looks like we are adding a status and support "cancel" for runs (passing the status) in one commit, and a new helper function `FilterOwnerRunRef` in the other. It's worth having a better commit message than just "Run enhancements" :wink:

**Comment by GregDritschler** [comment]
I fixed the commit message.

**Pull request closed without merging**
