### PR TITLE
Add Condition to v1alpha2 🎋

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

This port Condition from v1alpha1 as is to v1alpha2.

This depends on #1841 and #1725 (as it is based on those two)

/hold
/cc @bobcatfish 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) to build and release this image.

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md) are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes) must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS) and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes) must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS), and they must first be added [in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

### CODE REVIEW

**Comment by bobcatfish** [comment]
mentioned this is slack also but I'd rather hold off on making Condition part of beta since a) it's pretty new b) i'm not sure we've actually completed the epic yet (@dibyom correct me if I'm wrong) and c) in my own experience I haven't been able to use it the way I've wanted to (that's just me tho - and I think @dlorenc has had similar experiences). so personally I'd rather give it a bit of a revisit first

**Comment by dibyom** [comment]
I think the missing features are mostly going to be in the PipelineTask side rather than in the Condition CRD (e.g. chaining conditions, or #1684). That being said, I'm for waiting on making Conditions Beta (do we even need a extra CRD...can we just reuse some "kinds" of tasks/steps instead?)

**Comment by vdemeester** [comment]
I guess I can close this for now :angel: 
/close

**Pull request closed without merging**
