### PR TITLE
Use script mode in the cloud-event example

### PR DESCRIPTION
**Pull request by afrittoli**
@ImJasonH 

# Changes

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) to build and release this image.

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md) are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes) must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS) and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes) must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS), and they must first be added [in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

# Release Notes

```
Describe any user facing changes here, or delete this block.

Examples of user facing changes:
- API changes
- Bug fixes
- Any changes in behavior

```

### CODE REVIEW

**Comment by dibyom** [comment]
> I1115 15:16:48.884] ERROR: tests timed out
I1115 15:16:48.885] >> Checking test results for taskrun
I1115 15:16:49.719] ERROR: test poll-for-content-run=SucceededUnknown but should be succeededtrue
I1115 15:16:49.719] ERROR: one or more YAML tests failed


> I1115 15:16:51.708]   spec:
I1115 15:16:51.709]     inputs: {}
I1115 15:16:51.709]     outputs:
I1115 15:16:51.709]       resources:
I1115 15:16:51.709]       - name: myimage
I1115 15:16:51.709]         resourceSpec:
I1115 15:16:51.710]           params:
I1115 15:16:51.710]           - name: url
I1115 15:16:51.710]             value: fake-registry/test/fake-image
I1115 15:16:51.710]           type: image
I1115 15:16:51.710]       - name: notification
I1115 15:16:51.711]         resourceSpec:
I1115 15:16:51.711]           params:
I1115 15:16:51.711]           - name: targetURI
I1115 15:16:51.711]             value: http://sink:8080
I1115 15:16:51.711]           type: cloudEvent
I1115 15:16:51.712]     podTemplate: {}
I1115 15:16:51.712]     serviceAccountName: ""
I1115 15:16:51.712]     taskRef:
I1115 15:16:51.712]       kind: Task
I1115 15:16:51.713]       name: send-cloud-event-task
I1115 15:16:51.713]     timeout: 1h0m0s
I1115 15:16:51.713]   status:
I1115 15:16:51.713]     cloudEvents:
I1115 15:16:51.713]     - status:
I1115 15:16:51.714]         condition: Failed
I1115 15:16:51.714]         message: "1 error occurred:\n\t* Post http://sink:8080: dial tcp: lookup sink
I1115 15:16:51.714]           on 10.11.240.10:53: no such host\n\n"
I1115 15:16:51.714]         retryCount: 1

**Comment by vdemeester** [comment]
@dibyom yeah, a rebase should fix that race :sweat_smile:

**Comment by afrittoli** [comment]
Script mode has been added to the this test already in 1bfd9794422204f77d76f4c5a796824fa0cc21ae, so this can be closed.

**Pull request closed without merging**
