### PR TITLE
Release v0.24.3

### PR DESCRIPTION
**Pull request by afrittoli**
# Changes

This is a minor release to fix the delta between v0.24.1 and v0.24.2.

Release v0.24.1 included by mistake three extra commits.
The next minor release v0.24.2 did not include them, but the difference is problematic: https://github.com/tektoncd/pipeline/issues/4017

Release v0.24.3 builds on top of v0.24.2 and restores the three extra commits:

* https://github.com/tektoncd/pipeline/commit/d3666c263237a88bb02f68d9173a9fff7b5fd50e
* https://github.com/tektoncd/pipeline/commit/bf511ddbb8392e3be8036ef697315f7d36089f7f
* https://github.com/tektoncd/pipeline/commit/b31327bd83512658fdcc61f12806dfad41353a40

/kind misc

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [ ] [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [ ] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [ ] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [ ] Release notes block below has been filled in or deleted (only if no user facing changes)

# Release Notes

```release-notes
This is a minor release to fix the delta between v0.24.1 and v0.24.2.

Release v0.24.1 included by mistake three extra commits.
The next minor release v0.24.2 did not include them, but the difference is problematic: https://github.com/tektoncd/pipeline/issues/4017

Release v0.24.3 builds on top of v0.24.2 and restores the three extra commits:

* https://github.com/tektoncd/pipeline/commit/d3666c263237a88bb02f68d9173a9fff7b5fd50e
* https://github.com/tektoncd/pipeline/commit/bf511ddbb8392e3be8036ef697315f7d36089f7f
* https://github.com/tektoncd/pipeline/commit/b31327bd83512658fdcc61f12806dfad41353a40
```

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
/cc @sbwsg @jerop

**Comment by sbwsg** [comment]
Would it be worthwhile to cherry-pick https://github.com/tektoncd/pipeline/pull/3979 as part of this patch release as well?  It fixes a bug with the `workingDir` default removal on s390x (also I think the problem described in this bug report: https://github.com/tektoncd/pipeline/issues/4007)

Otherwise +1 ! 

/approve

**Comment by afrittoli** [comment]
> Would it be worthwhile to cherry-pick #3979 as part of this patch release as well? It fixes a bug with the `workingDir` default removal on s390x (also I think the problem described in this bug report: #4007)

It sounds like a good idea to me, but I'd add that one as a separate PR then 🙏 

> 
> Otherwise +1 !
> 
> /approve

**Comment by jerop** [comment]
thanks for the quick fix @afrittoli! 

/lgtm

**Pull request merged**
