### PR TITLE
Remove the Trigger field from TaskRun/PipelineRun.

### PR DESCRIPTION
**Pull request by dlorenc**
# Changes

This field is not currently used, and it's usage should be replaced
with labels/annotations. This commit removes it now, before anyone
takes a dependency on it.

At a later time we can decide on the correct label/annotation usage
for this information and start writing that data.

Ref https://github.com/tektoncd/pipeline/issues/833

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [X] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [X] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

# Release Notes

```
The trigger field has been removed from TaskRun.
Its usage will be replaced with labels and annotations at a later time.
```

### CODE REVIEW

**Comment by nader-ziada** [comment]
`trigger` field  should also be removed from the yaml examples

**Comment by bobcatfish** [comment]
> This field is not currently used, 

Hmm... it's not completely unused in that the PipelineRun controller sets the field on TaskRuns, and I think @iancoffey was saying that the event implementation sets it.

I don't mind removing it, but it seems odd to remove it now before we decide how to replace it.

Maybe bring it up at the WG meeting this week @dlorenc ?

**Comment by dlorenc** [comment]
> `trigger` field should also be removed from the yaml examples

Fixed!

**Comment by dlorenc** [comment]
> I don't mind removing it, but it seems odd to remove it now before we decide how to replace it.

If we know we want to remove it, I'd rather remove it ASAP before other things start using it. I added it to the agenda for tomorrow.

**Comment by iancoffey** [comment]
Indeed, I had tried to implement this for the eventbinding things, but am fine just using labels instead 👍

**Comment by abayer** [comment]
/hold
/lgtm

LGTMing but also putting on hold until after WG tomorrow. =)

**Comment by abayer** [comment]
ah, it added the label but I didn't see it.

**Comment by dlorenc** [comment]
> Hmm... it's not completely unused in that the PipelineRun controller sets the field on TaskRuns, and I think @iancoffey was saying that the event implementation sets it.

I would also argue that merely writing a field doesn't count as using it :)

**Comment by bobcatfish** [comment]
> I would also argue that merely writing a field doesn't count as using it :)

Yeah that's a good point - I guess it only matters if someone is consuming it!

**Comment by afrittoli** [comment]
I think an annotation would be more fitting, the spec should contain information for the controller to reconciliate the resource, while "trigger" is not used/needed by the controller at all.

**Comment by vdemeester** [comment]
Discussed it (real quick) during the working group, as nobody raise any flag for keeping it, let's get rid of the field :angel: 
/hold cancel

**Pull request merged**
