### PR TITLE
subcommands_test: Group command tests with t.Run.

### PR DESCRIPTION
**Pull request by wlynch**
# Changes

Simple clean up to help display/group command tests together and cut
down on some of the repetition.

/kind cleanup

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [x] [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [x] [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Release notes block below has been filled in or deleted (only if no user facing changes)

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by wlynch** [comment]
/hold 

To be submitted after #4352

/cc @sbwsg

**Review by dibyom — APPROVED** [review]

**Pull request merged**
