### PR TITLE
Remove deprecated serviceAccount field from *Run 🌳

### LINKED ISSUE #1219: Change serviceAccount to serviceAccountName to be consistent with k8s
The `serviceAccount` field name should probably be renamed to `serviceAccountName` to match more closely with the normal k8s API. See `serviceAccountName` under pod [here](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.12/). 

This stems from @bobcatfish 's comment here: https://github.com/tektoncd/triggers/pull/63/files#r314863023

> ugh but it's called `serviceAccountName` in the rest of kubernetes isn't it :S
> 
> image
> 
> maybe we should leave this and change pipelines after all

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

This removes the deprecated `serviceAccount` field from TaskRun and
PipelineRun in favor of the newly added `serviceAccountName` (in
previous release) to match more closely the kubernetes API.

Closes #1219

Signed-off-by: Vincent Demeester <vdemeest@redhat.com>

/cc @bobcatfish @afrittoli 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) to build and release this image.

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md) are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes) must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS) and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes) must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS), and they must first be added [in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

# Release Notes

```
Remove deprecated serviceAccount field from TaskRun/PipelineRun in favor of serviceAccountName
```

### CODE REVIEW

**Comment by afrittoli** [comment]
@vdemeester rebase? 👼

**Comment by vdemeester** [comment]
oh boy.. I need to rebase indeed :joy:

**Comment by bobcatfish** [comment]
woot thanks @vdemeester !!

**Pull request merged**
