### PR TITLE
Don't modify the lister cache's copy.

### PR DESCRIPTION
**Pull request by mattmoor**
/kind bug

Fixes: https://github.com/tektoncd/pipeline/issues/4179

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [ ] [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [ ] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [ ] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [ ] Release notes block below has been filled in or deleted (only if no user facing changes)

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by mattmoor** [comment]
I'm not thrilled at the idea of discarding the error here either, but I figured it was worth leaving that alone for this change...

**Comment by mattmoor** [comment]
Ok, if I'm being really honest, I'm not a fan of any aspect of how the pipeline is handling retries by messing with another controller's resource's status to recycle it instead of just creating new taskruns 😂

**Review by imjasonh — APPROVED** [review]
I'd love some more systematic way to avoid this fwiw, identifying and fixing these by hand isn't going to scale. 🤔

**Comment by mattmoor** [comment]
@imjasonh There is one! 😉  The knative table testing framework checks for this, which I think has effectively eliminated this from our controllers, but Tekton never adopted that because it landed around/after the split 😞 

It'd be a pretty big undertaking, which I probably can't sign up for, but I'd be happy to consult, and I'm sure the Knative folks would be willing to field questions, since most of Knative is using it.

**Comment by mattmoor** [comment]
Here's where we do it, fwiw: https://github.com/knative/pkg/blob/b558677ab03404ed118ba3e179a7438fe2d8509a/reconciler/testing/table.go#L390-L394

**Pull request merged**
