### PR TITLE
skip helm test on s390x arch

### PR DESCRIPTION
**Pull request by Basavaraju-G**
# Changes
Skip helm test on s390x platform. it uses unsecure docker registry in the testcase. s390x dogfooding cluster is having https based docker registry. due to http based registry testcase failing.
`run-ltzmxyos-gn266": creating push check transport for s390x-cluster.bastion-z.svc.cluster.local:443 failed: GET http://s390x-cluster.bastion-z.svc.cluster.local:443/v2/: unsupported status code 400; body: <html>
        <head><title>400 The plain HTTP request was sent to HTTPS port</title></head>
        <body>
        <center><h1>400 Bad Request</h1></center>
        <center>The plain HTTP request was sent to HTTPS port</center>
        <hr><center>nginx/1.22.0</center>
        </body>
        </html>`

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [ ] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [X] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [X] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [X] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [ ] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by afrittoli — APPROVED** [review]
/approve

**Comment by Basavaraju-G** [comment]
Hi @jerop @lbernick would you please review this PR?

**Comment by lbernick** [comment]
Curious why this is only an issue on s390x? Can this test be rewritten, or should it be removed entirely? It looks like it depends on the image pipelineresource, and removing it would help resolve https://github.com/tektoncd/pipeline/pull/6002

**Comment by Basavaraju-G** [comment]
> Curious why this is only an issue on s390x? Can this test be rewritten, or should it be removed entirely? It looks like it depends on the image pipelineresource, and removing it would help resolve #6002

Thanks @lbernick We configured s390x based k8s cluster differently on dogfooding CI. nightly CI runs link: https://dashboard.dogfooding.tekton.dev/#/namespaces/bastion-z/pipelineruns

More details about s390x testing CI https://github.com/tektoncd/plumbing/issues/1192
we configured secure docker registry(i.e KO_DOCKER_REPO) for security reasons. but tests failed due to this. so we want skip this test only on dogfooding setup. it works fine on local s390x kind cluster. 

`cile succeeded
    stream.go:254: I 06:04:33.698 tekton-pipelines-controller-d6c87556b-lfrrd [github.com.tektoncd.pipeline.pkg.reconciler.pipelinerun.Reconciler] [arendelle-hzh8w/helm-deploy-pipeline-run-vzqlxrwd] All TaskRuns have finished for PipelineRun helm-deploy-pipeline-run-vzqlxrwd so it has finished
    stream.go:254: I 06:04:33.698 tekton-pipelines-controller-d6c87556b-lfrrd [github.com.tektoncd.pipeline.pkg.reconciler.pipelinerun.Reconciler] [arendelle-hzh8w/helm-deploy-pipeline-run-vzqlxrwd] PipelineRun helm-deploy-pipeline-run-vzqlxrwd status is being set to &{Succeeded True  {2023-01-24 06:04:33.698859243 +0000 UTC m=+428.236507952} Succeeded Tasks Completed: 3 (Failed: 0, Cancelled 0), Skipped: 0}
    stream.go:254: W 06:04:33.717 tekton-pipelines-controller-d6c87556b-lfrrd [github.com.tektoncd.pipeline.pkg.reconciler.pipelinerun.Reconciler] [arendelle-hzh8w/helm-deploy-pipeline-run-vzqlxrwd] the configmap key "location" is empty
    stream.go:254: I 06:04:33.719 tekton-pipelines-controller-d6c87556b-lfrrd [github.com.tektoncd.pipeline.pkg.reconciler.pipelinerun.Reconciler] [arendelle-hzh8w/helm-deploy-pipeline-run-vzqlxrwd] Reconcile succeeded
    helm_task_test.go:107: Cleaning up helm from cluster...
    helm_task_test.go:107: Creating Task helm-remove-all-task
    helm_task_test.go:107: Creating TaskRun helm-remove-all-taskrun
    helm_task_test.go:107: Waiting for TaskRun helm-remove-all-taskrun in namespace arendelle-hzh8w to complete
    stream.go:254: I 06:04:35.690 tekton-pipelines-controller-d6c87556b-lfrrd [github.com.tektoncd.pipeline.pkg.reconciler.taskrun.Reconciler] [arendelle-hzh8w/helm-deploy-pipeline-run-vzqlxrwd-check-service] taskrun done : helm-deploy-pipeline-run-vzqlxrwd-check-service
    stream.go:254: I 06:04:35.691 tekton-pipelines-controller-d6c87556b-lfrrd [github.com.tektoncd.pipeline.pkg.reconciler.taskrun.Reconciler] [arendelle-hzh8w/helm-deploy-pipeline-run-vzqlxrwd-check-service] Reconcile succeeded
    helm_task_test.go:107: Deleting Cluster Role binding default-tiller-rn94j for helm
    helm_task_test.go:107: Deleting namespace arendelle-hzh8w
--- PASS: TestHelmDeployPipelineRun (176.13s)
PASS
Using kubeconfig at `` with cluster ``
ok  	github.com/tektoncd/pipeline/test	176.176s`

sure i will try to remove it.

**Comment by lbernick** [comment]
> > Curious why this is only an issue on s390x? Can this test be rewritten, or should it be removed entirely? It looks like it depends on the image pipelineresource, and removing it would help resolve #6002
> 
> Thanks @lbernick We configured s390x based k8s cluster differently on dogfooding CI.
> 
> nightly CI runs link: https://dashboard.dogfooding.tekton.dev/#/namespaces/bastion-z/pipelineruns
> 
> More details about s390x testing CI [tektoncd/plumbing#1192](https://github.com/tektoncd/plumbing/issues/1192) we configured secure docker registry(i.e KO_DOCKER_REPO) for security reasons. but tests failed due to this. so we want skip this test only on dogfooding setup. it works perfectly fine on local s390x kind cluster.
> 
> Screenshot 2023-01-24 at 11 39 32 AM
> 
> sure i will try to remove it.

Got it! I think we should either remove it (not sure why we need tests for pushing to an image registry) or if you can add a bit more context (i.e. what you said in your last comment) to the comments in the code here that's also fine

**Comment by Basavaraju-G** [comment]
similar pr to remove helm test is removed. https://github.com/tektoncd/pipeline/pull/6002 so closing this.

**Pull request closed without merging**
