### PR TITLE
fix:inconsistent 'retries' document example fields in customrun

### PR DESCRIPTION
**Pull request by cugykw**
# Changes

The customrun example docs do not match.

```
  params:
    - name: searching
      value: the purpose of my existence
  #  customRef
  ref:
    apiVersion: custom.tekton.dev/v1alpha1
```

/kind documentation

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [x] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [ ] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [ ] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [ ] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [ ] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by jerop — APPROVED** [review]
@cugykw thanks for fixing the documentation, please update the commit message with more details

```
fix: inconsistent 'retries' document example fields in customrun

this change fixes the docs for using 'retries' in customruns from using 'ref' field to 'customref' field
```

cc @XinruZhang

**Comment by XinruZhang** [comment]
Ops, thank you for the fix @cugykw!

/lgtm

**Pull request merged**
