### PR TITLE
clean up TestReconcile_CloudEvents YAML parsing

### PR DESCRIPTION
**Pull request by jbpratt**
# Changes

Replace Pipeline, PipelineRun, and Task object initialization to use YAMLParser

/kind cleanup

working on #4610

:D picking this up to do a bit of learning. Thank you all for the awesomeness
that is Tekton!!

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [x] [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Release notes block below has been filled in or deleted (only if no user facing changes)

# Release Notes

```release-note
NONE
```

Signed-off-by: jbpratt <jbpratt78@gmail.com>

### CODE REVIEW

**Comment by pritidesai** [comment]
thank you @jbpratt for helping out 👍 Welcome to the community!
/ok-to-test

**Review by pritidesai — APPROVED** [review]
thank you @jbpratt 👍

**Comment by pritidesai** [comment]
@jbpratt please update the commit message to include a brief description 🙏

**Comment by jbpratt** [comment]
@pritidesai updated!

**Review by vdemeester — APPROVED** [review]
/lgtm

**Comment by jbpratt** [comment]
/retest

I don't think my changes are related to the failures but I'm investigating now

**Pull request merged**
