### PR TITLE
Use tektoncd/plumbing instead of knative/test-infra

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

As Pipeline graduated from `knative`, we're trying, with `plumbing` to
make remove our dependency on knative `test-infra` scripts. Those
scripts have been migrated to `tektoncd/plumbing`, so let's start use those.

The end goal being to reduce even more the use of those script and
only use pipeline to build pipeline 👼.

Marking this as `wip` for now, as I expect some breaking

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ :no_good_man: ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ :no_good_man: ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

### CODE REVIEW

**Comment by vdemeester** [comment]
Oh my god it's green :man_dancing:

**Comment by vdemeester** [comment]
/hold
cc @bobcatfish @abayer @dlorenc

**Comment by abayer** [comment]
/lgtm

yay! =)

**Comment by vdemeester** [comment]
/hold
Need to do a small fix

**Comment by bobcatfish** [comment]
This is awesome! Good call @vdemeester , I love this incremental approach :heart_eyes:

**Pull request merged**
