### PR TITLE
Fix links to Why Aren't PipelineResources in Beta?

### PR DESCRIPTION
**Pull request by AlanGreene**
# Changes

Resolves https://github.com/tektoncd/website/issues/333

Links to the "Why Aren't PipelineResources in Beta?" section in the docs
should have `aren-t` in the fragment instead of `arent`. This can be
confirmed by clicking the link icon beside the heading and checking the
browser address bar.

/kind documentation

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [x] [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [ ] [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Release notes block below has been filled in or deleted (only if no user facing changes)

# Release Notes

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]

**Comment by afrittoli** [comment]
Thanks @AlanGreene ! This will have to be backported to fix the branch where it was discovered.

**Review by afrittoli — COMMENTED** [review]
/lgtm

**Comment by AlanGreene** [comment]
> This will have to be backported to fix the branch where it was discovered.

Good point, I'll try to take a look at previous releases later today 👍

**Pull request merged**
