### PR TITLE
Move nopImage and entrypointImage from pkg/… package to cmd/controller

### LINKED ISSUE #1309: importing the pipeline api pollutes flags
Importing the pipeline api causes a bunch of global flags to get introduced, for example:

https://github.com/tektoncd/pipeline/blob/5e3276d3df90c4d9b7c8d42c16c058a8d2348809/pkg/apis/pipeline/v1alpha1/git_resource.go#L33-L35

Ideally people should be able to consume this api definition without polluting their flag namespace. 
Can we move these flags into the pipeline controller and/or move them inside an optionally called function rather than global vars / init statements which everyone has to run?

ref https://github.com/kubernetes/test-infra/issues/14320

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

This is part of a set of changes to make sure we don't define CLI
flags in our `pkg/…` packages… so that importing packages from there
do not pollute the cli flags.

Follow-up of #1348, Closes #1309

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) to build and release this image.

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md) are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes) must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS) and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes) must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS), and they must first be added [in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

### CODE REVIEW

**Comment by chmouel** [comment]
😻

**Comment by vdemeester** [comment]
/cc @sbwsg @ImJasonH 
(as you reviewed the first one too)

**Pull request merged**
