### PR TITLE
Add Priti as an owner 🎉

### PR DESCRIPTION
**Pull request by bobcatfish**
# Changes

@pritidesai has been a reviewer on many PRs (37 by the count at
https://github.com/tektoncd/pipeline/pulls?q=is%3Apr+is%3Aopen+reviewed-by%3Apritidesai)
and she has been the author of several PRs (27 at https://github.com/tektoncd/pipeline/pulls/pritidesai)
including finally (#2661) which was one of the most substantial changes
to pipeline execution since we implemented DAGs (not to mention that she
patiently worked with the evolution of this feature over several months
from the runOn feature which evolved into this one).

Thanks so much @pritidesai!!!! So excited that you want to become even
more involved in pipelines :D :D :D

p.s. @vdemeester I'm assuming that our intention at least at the moment was to have a 1:1 mapping b/w approvers and `apis-approvers`

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [n/a] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [x] Release notes block has been filled in or deleted (only if no user facing changes)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) to build and release this image.

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md) are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes) must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS) and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes) must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS), and they must first be added [in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

# Release Notes
```release-note
NONE
 ```

### CODE REVIEW

**Comment by bobcatfish** [comment]
/hold

PTAL current OWNERS @sbwsg @dibyom @dlorenc @vdemeester @afrittoli @ImJasonH

**Comment by ImJasonH** [comment]
/lgtm

🎉🎉🎉

**Comment by vdemeester** [comment]
/approve
/lgtm
/meow
🙌🏼🙌🏼🙌🏼

**Comment by afrittoli** [comment]
:tada: :tada: :tada:
/approve
/lgtm

**Comment by sbwsg** [comment]
/lgtm
/approve

😸 🎉 🙌 🎉 🙌 🎉 🙌 🎉 🙌 🎉 😸

**Comment by bobcatfish** [comment]
Welcome @pritidesai !!!!! :tada::tada::tada::tada:

image

**Pull request merged**
