### PR TITLE
Remove nader ziada and shashwathi from owners

### PR DESCRIPTION
**Pull request by pivotal-nader-ziada**
# Changes

Remove @pivotal-nader-ziada and @shashwathi from OWNERS file since we will both be dedicating less time to the tekton project in the near future

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [NA ] Includes [tests](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md#principles) (if functionality changed/added)
- [NA] Includes [docs](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md#principles) (if user facing)
- [NA] Commit messages follow [commit message best practices](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md)
for more details._

# Release Notes

```

```

/cc @bobcatfish

### CODE REVIEW

**Comment by bobcatfish** [comment]
Thanks for all your super high quality work! And for your great attitude, it's been super fun @pivotal-nader-ziada @shashwathi 

cat with headphones rocking out and saying "thank you"

Just say the word if you want to come back and we'll add you right back in ;)

**Comment by vdemeester** [comment]
Same thing that @bobcatfish said, we're gonna miss you :hugs:

**Pull request merged**
