### PR TITLE
docs: Update references to examples from v1beta1 to v1

### PR DESCRIPTION
**Pull request by HamzaMateen**
In response to the cleanup effort aimed at deduplicating tests between v1 and v1beta1, this commit addresses broken links in our documentation. The changes involve updating references to examples under the v1beta1 API version to instead point to the v1 API version. Additionally, certain features that transitioned from alpha to beta within the v1 API required corresponding updates to their references.

This change ensures that the documentation accurately reflects the current state of the project, eliminating broken links and inconsistencies. The goal is to improve the overall user experience and provide accurate information.

Fixes #6908

# Changes
- Updated references to examples from v1beta1 to v1 in the following documentation files:
  - docs/api-spec.md
  - docs/auth.md
  - docs/developers/api-versioning.md
  - docs/matrix.md
  - docs/pipelineruns.md
  - docs/pipelines.md
  - docs/taskruns.md
  - docs/tasks.md
  - docs/workspaces.md
  

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ x] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) if any changes are user facing, including updates to minimum requirements e.g. Kubernetes version bumps
- [ ] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [ x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [ x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including functionality, content, code)
- [ x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [ ] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings). See some examples of [good release notes](https://github.com/tektoncd/community/blob/main/standards.md#good-release-notes).
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by HamzaMateen** [comment]
kind/documentation

**Review by khrm — COMMENTED** [review]
/ok-to-test

**Review by vdemeester — APPROVED** [review]

**Pull request merged**
