### PR TITLE
Add UID label to PipelineRun and TaskRun

### LINKED ISSUE #8165: TaskRun pod should have UUID label of Taskrun
### Feature request
TaskRun pod should have the UUID label of Taskrun

### Use case

* Currently, we only have the name of Taskrun in the pod labels but we can't filter the pod logs based on this when a log forwarder like vector or fluentd stores logs. Names aren't unique. Only UUIDs are unique and can help determine which Run the logs belong to.

### PR DESCRIPTION
**Pull request by khrm**
# Changes
Fixes #8165 

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [x] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) if any changes are user facing, including updates to minimum requirements e.g. Kubernetes version bumps
- [x] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [ ] [pre-commit](https://github.com/tektoncd/pipeline/blob/main/DEVELOPMENT.md#install-tools) Passed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [ ] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings). See some examples of [good release notes](https://github.com/tektoncd/community/blob/main/standards.md#good-release-notes).
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
TaskRun pods have tekton.dev/taskRunUID and tekton.dev/pipelineRunUID labels
```

### CODE REVIEW

**Review by khrm — COMMENTED** [review]
/kind feature

**Review by vdemeester — APPROVED** [review]

**Review by khrm — COMMENTED** [review]
/assign @afrittoli @piyush-garg 
Can we get this merge for v0.63.x ?

**Pull request merged**
