### PR TITLE
Bump knative/pkg to 1.13 and k8s.io to 0.28.5

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

This updates core dependencies of knative/pkg to it's latest release,
1.13. And it updates the k8s.io dependencies according to it.

Note: this moves the min kubernetes version to 1.27 for tektoncd/pipeline.

Signed-off-by: Vincent Demeester <vdemeest@redhat.com>

/kind misc

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) if any changes are user facing, including updates to minimum requirements e.g. Kubernetes version bumps
- [ ] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] [pre-commit](https://github.com/tektoncd/pipeline/blob/main/DEVELOPMENT.md#install-tools) Passed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [x] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings). See some examples of [good release notes](https://github.com/tektoncd/community/blob/main/standards.md#good-release-notes).
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
knative/pkg dependency is now 1.13 and k8s.io dependencies are 0.28.x.
In addition, this make the minimum kubernetes version supported by tektoncd/pipeline to be 1.27.
```

### CODE REVIEW

**Comment by vdemeester** [comment]
I need to update the kind version we use here.

**Comment by vdemeester** [comment]
https://github.com/tektoncd/plumbing/pull/1907 for bumping kind version

**Comment by JeromeJu** [comment]
> [tektoncd/plumbing#1907](https://github.com/tektoncd/plumbing/pull/1907) for bumping kind version

/retest
now that plumbing 1907 is merged

**Comment by vdemeester** [comment]
```
 [clone-coverage-upload : clone] {"level":"error","ts":1711581650.6748326,"caller":"git/git.go:54","msg":"Error running git [fetch --recurse-submodules=yes origin --update-head-ok --force refs/heads/main:refs/heads/main refs/pull/7808/head:refs/batch/refs/pull/7808/head]: exit status 128\nremote: Repository not found.\nfatal: repository 'https://github.com/$(tasks.split-full-repo-name.results.repoOwner)/$(tasks.split-full-repo-name.results.repoName).git/' not found\n","stacktrace":"github.com/tektoncd/pipeline/pkg/git.run\n\tgithub.com/tektoncd/pipeline/pkg/git/git.go:54\ngithub.com/tektoncd/pipeline/pkg/git.Fetch\n\tgithub.com/tektoncd/pipeline/pkg/git/git.go:145\nmain.main\n\tgithub.com/tektoncd/pipeline/cmd/git-init/main.go:52\nruntime.main\n\truntime/proc.go:204"}
[clone-coverage-upload : clone] {"level":"fatal","ts":1711581650.6749718,"caller":"git-init/main.go:53","msg":"Error fetching git repository: failed to fetch [refs/heads/main:refs/heads/main refs/pull/7808/head:refs/batch/refs/pull/7808/head]: exit status 128","stacktrace":"main.main\n\tgithub.com/tektoncd/pipeline/cmd/git-init/main.go:53\nruntime.main\n\truntime/proc.go:204"} 
```
🤔 I don't understand why `pull-tekton-pipeline-go-coverage-df` fails with this sometimes…

**Pull request merged**
