### PR TITLE
Deduplicate examples tests between v1 and v1beta1

### PR DESCRIPTION
**Pull request by lbernick**
Currently, we run a large number of examples tests that are duplicated in v1 and v1beta1. These tests are meant to test specific features, such as params and workspaces, that have the same syntax and implementation in v1 and v1beta1. Since we have conversion integration tests, these duplicated examples tests are likely adding little value.

In addition, examples tests are the flakiest set of tests in the repo and often time out. Removing redundant examples tests should make our CI less flaky.

This commit moves any examples tests that were solely present in v1beta1 to v1, leaving only those that use features that weren't migrated to v1. It deletes any examples that were duplicated between v1 and v1beta1.

/kind cleanup
Partially addresses https://github.com/tektoncd/pipeline/issues/6906

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- n/a Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) if any changes are user facing, including updates to minimum requirements e.g. Kubernetes version bumps
- n/a Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- n/a Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings). See some examples of [good release notes](https://github.com/tektoncd/community/blob/main/standards.md#good-release-notes).
- n/a Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by jerop — COMMENTED** [review]
examples are not only used for tests but also as samples for users (with some of them even being referenced in the docs) -- instead of removing them, can we move them to the folder where they are not tested so that they can still be used as samples? the concern here though is that they may go out of date if they are not tested :/

**Comment by jerop** [comment]
reading the description of this PR again, you are not actually removing any tests because there are integration tests for the same functionality, you are only deduplicating v1 and v1beta1 -- is that correct? if so, I suggest updating the title to "deduplicate example tests in v1beta1 and v1"

reading https://github.com/tektoncd/pipeline/issues/6906 and the title made me think that you were actually removing tests -- thought the redundancy is with integration tests

please clarify

**Comment by lbernick** [comment]
Thanks for the feedback, updated the PR title and commit message!

**Review by jerop — APPROVED** [review]

**Comment by Yongxuanzhang** [comment]
/lgtm

Thanks! Not sure if in docs we linked to examples moved in this PR, but should be easy to fix if there is any

**Pull request merged**
