### PR TITLE
Aggregate taskRun/pipelineRun duration metrics by task/pipeline

### LINKED ISSUE #1786: Measure taskRun/pipelineRun aggregate by task/pipeline template
# Expected Behavior
From v0.8.0, Tekton Pipeline supports the Metrics feature. We can't wait to deploy the prometheus server and grafana dashboard service to make statistics on the operation of the tekton pipeline. 

**We want to query pipeline metrics quickly and stably always.** 

# Actual Behavior
With the increase in the number of historical taskrun/pipelineruns, we find that the `tekton-pipelines-controller.tekton-pipelines:9090/metrics`  is getting slower and slower, and prometheus queries sometimes timeout.

Aggregation in the dimension of task / pipeline is sufficient, instead of detailed data for each taskrun / pipelinerun which should be recorded in somewhere like [Result Metadata Api Service](https://docs.google.com/document/d/1-XBYQ4kBlCHIHSVoYAAf_iC01_by_KoK2aRVO0t8ZQ0/edit#)

# Steps to Reproduce the Problem

1.  Deploy tektoncd / pipeline of version no less than v0.8.0.
2. Taskruns / pipelineruns with different names (online services will introduce an uuid as isolation) are continuously submitted to run and released after they finish.
3. `curl -s tekton-pipelines-controller.tekton-pipelines:9090/metrics` , you will find a large number of tekton_pipelinerun_duration_seconds_bucket and tekton_pipelinerun_taskrun_duration_seconds_bucket indicators.  The metrics interface will slow linearly over time.

# Additional Info

-  In prometheus now , the P50 / P90 time of pipelinerun 
`
histogram_quantile(0.5, sum(tekton_pipelinerun_duration_seconds_bucket{job="tektoncd_metrics",status="success"}) 
by (le,pipeline))
`
or average time
`
avg(tekton_pipelinerun_duration_seconds_sum{job="tektoncd_metrics",status="success"} / tekton_pipelinerun_duration_seconds_count{job="tektoncd_metrics",status="success"}) by (pipeline)
`
will slow down as the amount of data increases.

- If the taskrun / pipelinerun tag is removed, we can use
`
histogram_quantile(0.5, 
  sum(rate(tekton_pipelinerun_duration_seconds_bucket{job="tektoncd_metrics",status="success"}[10m])) by (le,pipeline)
) 
`
which keep query efficiency forever.

### PR DESCRIPTION
**Pull request by cccfeng**
Detailed data for each taskrun/pipelinerun  lead to a sharp increase in the amount of metrics data. So aggregation in the dimension of task / pipeline is sufficient.

fixes #1786 

# Changes

Remove pipelinerun tag from github.com/tektoncd/pipeline/pkg/reconciler/pipelinerun/metrics.go.
Remove taskrun/pipelinerun tag from github.com/tektoncd/pipeline/pkg/reconciler/taskrun/metrics.go

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [ ] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) to build and release this image.

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md) are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes) must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS) and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes) must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS), and they must first be added [in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

# Release Notes

Examples of user facing changes:
pipeline metrics change: 
from
`tekton_pipelinerun_duration_seconds_bucket{instance="xxxx",job="tektoncd_metrics",le="+Inf",namespace="tekton-pipelines",pipeline="xxxx",pipelinerun="yyyy",status="failed"}`
to
`tekton_pipelinerun_duration_seconds_bucket{instance="xxxx",job="tektoncd_metrics",le="+Inf",namespace="tekton-pipelines",pipeline="xxxx",status="failed"}`

from
`tekton_pipelinerun_taskrun_duration_seconds_bucket{instance="xxxx",job="tektoncd_metrics",le="+Inf",namespace="tekton-pipelines",pipeline="xxxx",pipelinerun="xxxx",status="success",task="sofa-apiparser",taskrun="xxxx"}`
to
`
tekton_pipelinerun_taskrun_duration_seconds_bucket{instance="xxxx",job="tektoncd_metrics",le="+Inf",namespace="tekton-pipelines",pipeline="xxxx",status="success",task="xxxx"}
`

### CODE REVIEW

**Comment by hrishin** [comment]
/lgtm

However, we need those metrics(cardinalities) PipelineRun/TaskRun wise. Is there any other way we can optimized metrics data?

**Comment by cccfeng** [comment]
> /lgtm
> 
> Thank you for the patch @cccfeng 🙇
> 
> However, we need those metrics(cardinalities) PipelineRun/TaskRun wise. Is there any other way we can optimized metrics data?

Glad to receive a reply from the author of the metrics module. 

As a supplement I mentioned in #1786 , we tend to count the change, average or quantile over a period of time rather than data specific to each running instance. In tektoncd / pipeline, it is meaningful to aggregate the quantity or time by a certain task or pipeline.  On the other hand, prometheus is good at tracking changes in the value of fixed indicators rather than changing indicators which will cause performance problems sooner or later.

Currently we use tektoncd / dashboard and tektoncd / cli to observe at the granularity of each instance. But it is not enough because etcd data is not persistent. In my personal opinion, the data of each running instance should be considered in the [Tekton Execution History API](https://docs.google.com/document/d/1-XBYQ4kBlCHIHSVoYAAf_iC01_by_KoK2aRVO0t8ZQ0/edit#heading=h.xgjl2srtytjt), not in the metrics module.

**Comment by cccfeng** [comment]
It seems that e2e tests are not stable...

**Comment by hrishin** [comment]
@cccfeng thank you for  comprehensive explanation. Whatever you've mentioned in the sounds reasonable and make sense. Retaining the each PipelineRun/TaskRun instance data may be expensive for Prometehus. Now about history API it sounds reasonable to store Run(s) data.

However right away its has come into place. Unless history API fall into place its better to retain instances information? Eventually we can make this transition? 

Meanwhile how about changing the type of `x_run_duration` type from `histogram` to `count`? although personally I dont feel its a right move.

**Comment by cccfeng** [comment]
> @cccfeng thank you for comprehensive explanation. Whatever you've mentioned in the sounds reasonable and make sense. Retaining the each PipelineRun/TaskRun instance data may be expensive for Prometehus. Now about history API it sounds reasonable to store Run(s) data.
> 
> However right away its has come into place. Unless history API fall into place its better to retain instances information? Eventually we can make this transition?
> 
> Meanwhile how about changing the type of `x_run_duration` type from `histogram` to `count`? although personally I dont feel its a right move.

I think the metrics module is more for monitoring services, the most important of which is to show the trend changes in real time, followed by relatively old historical data for comparison. Currently, all running instance data is stored at the granularity of pipelinerun and taskrun. This effect is not significant, but it affects the return time of the controller's metric interface. After running for about two to three weeks, the prometheus query cannot be successful. And then we must restart the controller instance.

In the real usage scenario inside Ant Financial, we configure the statistics of the p50 / p90 time of the pipeline and task, instead of caring about the running time of each specific pipelinerun and taskrun.
And prometheus use bucket to record the duration, it is not an exact value. I think very few people will use prometheus to query precise data.

Finally, one more thing,  x_run_duration is a histogram type in order to use the histogram_quantile method that comes with prometheus. A counter is a cumulative metric that represents a single monotonically increasing counter whose value can only increase or be reset to zero on restart. It is indeed inappropriate in the scenario of statistics duration

**Comment by cccfeng** [comment]
Hi @hrishin . Prometheus use bucket to record the duration, it is not an exact value. Even if each instance records one piece of data, it loses precision at the beginning. Dimensional aggregation through the pipeline / task template does not make things worse.  🙂

**Comment by hrishin** [comment]
Hi @cccfeng 

Well to some extent I agree what are we discussing here. However I'm really not sure how such volume of metrics taking toll on Prometheus scraping (its not able scrape or getting timeout). Would you mind sharing more details on this part? (please forgive me, but I remember testing this data for around 900 PipelineRun - 1600 TaskRun instances, I didin't see the issue with Prometheus status for the pipeline target)

> Finally, one more thing, x_run_duration is a histogram type in order to use the histogram_quantile method that comes with prometheus. A counter is a cumulative metric that represents a single monotonically increasing counter whose value can only increase or be reset to zero on restart. It is indeed inappropriate in the scenario of statistics duration

Let's not add the the bandage :+1:

**Comment by cccfeng** [comment]
> Hi @cccfeng
> 
> Well to some extent I agree what are we discussing here. However I'm really not sure how such volume of metrics taking toll on Prometheus scraping (its not able scrape or getting timeout). Would you mind sharing more details on this part? (please forgive me, but I remember testing this data for around 900 PipelineRun - 1600 TaskRun instances, I didin't see the issue with Prometheus status for the pipeline target)

We use Tekton's pipeline and task templates to arrange different logic, such as Java, golang app build or test, docker image build, etc. When the user submits code or system triggers, different task ids can also be understood as a brand new pipelinerun will be pulled up. When pipelinerun runs successfully or fails, it will be released for a period of time.  As of now, we use Tekton to run tens of thousands different pipelineRun every day.

So in the current code implementation, each pipelinerun will generate N Prometheus data. Within 2~3 weeks, the time for the `9090/metrics` interface to return will be very slow. There will also be a lot of data stored on the Prometheus server, which takes longer to calculate

**Comment by hrishin** [comment]
@cccfeng thank you for sharing those insights :bowing_man: . Feels bad for the issues you're facing there.

Whatever we are discussing here sounds legit for the problem you're facing. Question is shall we accept this change or not for 2 reasons.
1) For our(OpenShift pipelines) use case we are planning to use each `PipelineRun` and `TaskRuns` data. So further we have to figure other way to get that data.
2) If we accept this, not sure if other people or integrators are already leverage on those metrics and this could break their metrics support.

Could you please help here?
@bobcatfish @ImJasonH @vdemeester  @afrittoli

**Comment by vdemeester** [comment]
> @cccfeng thank you for sharing those insights bowing_man . Feels bad for the issues you're facing there.
> 
> Whatever we are discussing here sounds legit for the problem you're facing. Question is shall we accept this change or not for 2 reasons.
> 
>     1. For our(OpenShift pipelines) use case we are planning to use each `PipelineRun` and `TaskRuns` data. So further we have to figure other way to get that data.
> 
>     2. If we accept this, not sure if other people or integrators are already leverage on those metrics and this could break their metrics support.
> 
> 
> Could you please help here?
> @bobcatfish @ImJasonH @vdemeester @afrittoli

Maybe we should have an option in the configuration allowing to modify this behavior somehow (aka doing the aggregation or not). This would help cover both use cases ?

/cc @afrittoli @abayer

**Comment by afrittoli** [comment]
> > @cccfeng thank you for sharing those insights bowing_man . Feels bad for the issues you're facing there.
> > Whatever we are discussing here sounds legit for the problem you're facing. Question is shall we accept this change or not for 2 reasons.
> > ```
> > 1. For our(OpenShift pipelines) use case we are planning to use each `PipelineRun` and `TaskRuns` data. So further we have to figure other way to get that data.
> > 
> > 2. If we accept this, not sure if other people or integrators are already leverage on those metrics and this could break their metrics support.
> > ```
> > 
> > 
> > Could you please help here?
> > @bobcatfish @ImJasonH @vdemeester @afrittoli
> 
> Maybe we should have an option in the configuration allowing to modify this behavior somehow (aka doing the aggregation or not). This would help cover both use cases ?
> 
> /cc @afrittoli @abayer

I'm not familiar enough with Prometheus to comment on this properly - but I would expect that the metric receiving system should be able to decide which metrics to receive and which do discard, have regular cleanup tasks and data aggregation strategies.

**Comment by bobcatfish** [comment]
Since this PR has been open since December, @cccfeng would you mind opening an issue to keep discussing this? Please feel free to reopen once we're ready to review!

**Pull request closed without merging**
