### PR TITLE
Move PodStatus->TaskRunStatus code to pkg/pod

### PR DESCRIPTION
**Pull request by ImJasonH**
This allows us to unexport more helper functions, and centralizes the other half of Pod<->TaskRun conversion into pkg/pod.

Some consts are still exported, but I think those might be useful to
some callers anyway.

#1605 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [y] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [n] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [y] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

### CODE REVIEW

**Comment by bobcatfish** [comment]
> LGTM :)

not sure if ironic or waiting to be picked up by cool new tekton dogfooding automation

image

**Comment by vdemeester** [comment]
/lgtm
/meow

:stuck_out_tongue_closed_eyes:

**Pull request merged**
