### PR TITLE
Disable Webhook PDB by default, document enabling it

### LINKED ISSUE #3654: PodDisruptionBudget causing inability to gracefully drain a node with tekton-pipelines-webhook pod
# Expected Behavior

Gracefully draining nodes which contains tekton pods are possible.

# Actual Behavior

With single running `tekton-pipelines-webhook` pod (which is possible due to `tekton-pipelines-webhook`: `HorizontalPodAutoscaler.spec.minReplicas: 1`) it's impossible to gracefully drain a node because `PodDisruptionBudget` is set to `minAvailable: 80%`.

# Steps to Reproduce the Problem

1. Run tekton-pipeline: kubectl apply -f https://storage.googleapis.com/tekton-releases/pipeline/previous/v0.19.0/release.yaml
2. Make sure there is single `tekton-pipelines-webhook` pod (scaled down)
3. Try to drain node with `tekton-pipelines-webhook` pod

# Additional Info

- Kubernetes version:

 ```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

- Tekton Pipeline version:
```
Client version: 0.15.0
Pipeline version: v0.19.0
Triggers version: v0.10.0
```

### PR DESCRIPTION
**Pull request by ImJasonH**
Fixes #3654 

# Changes

This change disables PodDisruptionBudget for the webhook deployment, and documents how to re-enable it in docs/enabling-ha. It also makes some edits to enabling-ha.md to streamline and recommend best practices.

/kind bug

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [n] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [y] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [y] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)
- [y] Release notes block has been filled in or deleted (only if no user facing changes)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) to build and release this image.

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md) are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes) must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS) and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes) must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS), and they must first be added [in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

# Release Notes

```release-note
Disable PodDisruptionBudget for the webhook deployment by default
```

cc @vdemeester @nikhil-thomas @bobcatfish

### CODE REVIEW

**Comment by ImJasonH** [comment]
cc @raballew as well, who added the PDB in #3391

**Review by vdemeester — APPROVED** [review]
/meow
Thanks for doing this @ImJasonH (and @nikhil-thomas for the exploration)

**Comment by zhangtbj** [comment]
Hi Jason,

A quick question, is that possible to remove the PDB setting from Tekton deployment and document how to configure it in the document? :)

Then the user can choose enable or disable it by themselves.

We enable PDB in our Tekton on production env. If it is set `MinAvailable` as 0 or other values by default, I am afraid it may override the existing settings or maybe to other users.

**Comment by sbose78** [comment]
I see @zhangtbj 's point here. Shipping the hpa manifests might override existing values. We may consider skipping the hpa manifests altogether and instead include documentation on it ?

**Comment by vdemeester** [comment]
> I see @zhangtbj 's point here. Shipping the hpa manifests might override existing values. We may consider skipping the hpa manifests altogether and instead include documentation on it ?

And move that knowledge/management to the [operator](https://github.com/tektoncd/operator) 👼🏼

**Comment by ImJasonH** [comment]
Sorry for letting this PR slip through the cracks. Let's get this in before 0.22.

To clarify, the specific ask is to remove the PDB from `webhook-hpa.yaml` from the default Tekton installation bundle, and instead _document_ how to enable it, with example YAML in the docs. Does that sound right to you @zhangtbj @sbose78 ?

**Comment by sbose78** [comment]
That's right, Jason.

**Comment by ImJasonH** [comment]
> That's right, Jason.

Done. 👍

**Comment by pritidesai** [comment]
@sbose78 please help review the changes 🙏 (looking for `/lgtm` 😉 )

**Comment by pritidesai** [comment]
Thanks @sbose78, we will have to add you to the org. I will create a separate PR in the community repo.

**Comment by pritidesai** [comment]
You should get the `/lgtm` privilege after [this](https://github.com/tektoncd/community/pull/376) PR in community repo is merged 😄  Until then,

/lgtm

**Comment by sbose78** [comment]
Thank you very much, Priti!

**Comment by zhangtbj** [comment]
Cool, thank you Jason! :)

**Pull request merged**
