### PR TITLE
Remove the pkg/jsonpath library.

### PR DESCRIPTION
**Pull request by dlorenc**
# Changes

This was originally added as part of #1951 and #1493 in January 2020,
but the work was never finished and the package isn't used anywhere.

It's a non-trivial amount of code and maintenance to keep up to date as we
bump linters and scanners, so we should delete it until there's a clear use
case.

I'm not aware of anyone using this now, so another reason to remove it now is to
prevent someone from taking a dependency on it.

Signed-off-by: Dan Lorenc <dlorenc@google.com>

/kind cleanup

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [X] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [X] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [X] Release notes block below has been filled in or deleted (only if no user facing changes)

# Release Notes

```release-note
The package `pkg/jsonpath` has been removed. This does not effect anyone using tektoncd/pipeline directly, but may break users importing this code as a library during an update. We're unaware of any usage of this package right now.
```

### CODE REVIEW

**Comment by skaegi** [comment]
Thanks Dan. This is the right call and can always be resurrected later.

**Review by afrittoli — COMMENTED** [review]
/lgtm

**Pull request merged**
