### PR TITLE
Add doc links for 0.29.1, 0.30.1, 0.31.1 and 0.32.1

### PR DESCRIPTION
**Pull request by sbwsg**
# Changes
Patch releases have just gone out for 0.29, 0.30, 0.31 and 0.32.

This commit adds doc links to our readme for each of the newly minted
versions.

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [x] [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Release notes block below has been filled in or deleted (only if no user facing changes)

# Release Notes
```release-note
NONE
```

### CODE REVIEW

**Review by jerop — APPROVED** [review]

**Comment by bobcatfish** [comment]
/me shakes fist at sidecar test https://github.com/tektoncd/pipeline/issues/4169 (segue: i wonder if there's something else we could do to make it more reliable - we can't seem to figure out how to make the current logic reliable, maybe we could make it simpler while we keep a bug open about the underlying problem?)

/lgtm

**Pull request merged**
