### PR TITLE
Complete implementation of image pull failure handling

### PR DESCRIPTION
**Pull request by SaschaSchwarze0**
Signed-off-by: Sascha Schwarze <schwarzs@de.ibm.com>

# Changes

I was a little confused by the code flow from https://github.com/tektoncd/pipeline/pull/4921. A `checkPodFailed` function that then always set `TaskRunReasonImagePullFailed` in case of an error looked incorrect.

So, I am doing what I think @abayer referred to in https://github.com/tektoncd/pipeline/pull/4921#discussion_r891592039 = adding the reason to the return values of the function.

Also putting in what @imjasonh asked for in https://github.com/tektoncd/pipeline/pull/4921#discussion_r885797241 = the step name and the image into the message.

Finally, I am adding the missing sidecar handling.

/kind feature

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [x] [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Release notes block below has been filled in
(if there are no user facing changes, use release note "NONE")

# Release Notes

```release-note
The TaskRunImagePullFailed logic now covers sidecars, and the error message includes the step name and the image
```

### CODE REVIEW

**Comment by SaschaSchwarze0** [comment]
> @SaschaSchwarze0 you need to remove the space between the backticks and release-note

Thanks, no idea how that could have gotten in there. lol

**Review by jerop — APPROVED** [review]
Thanks @SaschaSchwarze0 🎉 

Please add the context that you have in the pull request description to the commit message as well: https://github.com/tektoncd/community/blob/main/standards.md#commits

**Comment by dibyom** [comment]
Thank you @SaschaSchwarze0 This looks good to me.
/lgtm

**Pull request merged**
