### PR TITLE
Rename imports from knative/build-pipeline to tektoncd/pipeline.

### PR DESCRIPTION
**Pull request by dlorenc**
This change should make the repository build correctly in the new repository location.

This should not be merged until the repository has been moved.

### CODE REVIEW

**Comment by abayer** [comment]
Looks like the CI env is a bit busted?

**Comment by dlorenc** [comment]
OK, this should be ready for a review and a test of the new tide instance!

I still need to disable the other knative prow, but we should be able to see this go in first.

**Pull request merged**
