### PR TITLE
Create codeql-analysis.yml

### PR DESCRIPTION
**Pull request by afrittoli**
# Changes

Enable the standard codeql analysis from GitHub.
This runs as a GitHub action. The configuration is the vanilla one proposed by GitHub.

/kind misc

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [-] [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [-] [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Release notes block below has been filled in or deleted (only if no user facing changes)

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by afrittoli** [comment]
@vdemeester @dibyom @bobcatfish This didn't find any issue - only a couple in test code which I dismissed as not relevant.
What do you think about keeping this action around i.e. merge the PR?

**Comment by dlorenc** [comment]
> What do you think about keeping this action around i.e. merge the PR?

Just my 2c - I've never seen this find a relevant issue. It takes a long time and it's only ever noticed 2-3 things for me that weren't valid. I think codeql is better in native non-memory safe code. It's not really that annoying since false positives are rare, but any findings at all are very rare.

**Review by vdemeester — APPROVED** [review]
It doesn't take more time than any of our current jobs, so.. I am fine having it there.

**Pull request merged**
