### PR TITLE
Setup WorkingDir for place-tools init container to avoid permission error

### PR DESCRIPTION
**Pull request by afrittoli**
Cherry-picked from https://github.com/tektoncd/pipeline/pull/3979

# Changes

With 1001 user `run-steps-as-non-root` test can fail because of missing access permissions, see https://github.com/tektoncd/pipeline/issues/3978

Possible solutions are to use 65532 user, which is configured one for gcr.io/distroless/static:nonroot base image or to change working directory to "/" from the default "/home/nonroot" 

"/" working directory allows to use not only 65532 user, so this path is chosen.

/kind misc

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [x] [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Release notes block below has been filled in or deleted (only if no user facing changes)

# Release Notes

```release-note
Fixes bug #3978
```

### CODE REVIEW

**Comment by sbwsg** [comment]
Awesome, cheers @afrittoli !

/approve

**Review by vdemeester — APPROVED** [review]

**Review by jerop — APPROVED** [review]
/test pull-tekton-pipeline-integration-tests

**Pull request merged**
