### PR TITLE
TEP-0114: Remove enable-custom-task and alpha feature flag

### PR DESCRIPTION
**Pull request by JeromeJu**
# Changes

This commits remove the `enable-custom-task` and alpha feature flag for the
custom task feature gates.

/kind feature
Fixes: #5155 

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [n/a] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [n/a] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [n/a] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [n/a] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by jerop** [comment]
/hold

@JeromeJu this will be one of the last steps in implementing TEP-0114 - let's follow the ordering in https://github.com/tektoncd/pipeline/issues/4313 🙏🏾

**Comment by JeromeJu** [comment]
> /hold
> 
> @JeromeJu thank for for this PR - this will be one of the last steps in implementing TEP-0114 - let's follow the ordering in #4313 🙏🏾

Thanks @jerop  for the pointer. Will be following #4313

**Comment by vdemeester** [comment]
I think prior to removing, we should change the default value (to true) and deprecate the option so that we remove it in a couple of releases. This will give time for our users to upgrade at their pace.

**Pull request closed without merging**
