### PR TITLE
TEP-0127: Larger Results via Sidecar Logs - Cleanup

### PR DESCRIPTION
**Pull request by chitrangpatel**
# Changes

This PR addresses some changes in https://github.com/tektoncd/pipeline/pull/5828.

Moved config to enable access to sidecar logs into a different folder so that it is not installed by default. Also removed docs for installation (will be added in the final PR) so that it does not suggest that the feature is ready for use.

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [x] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [x] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [x] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [x] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
Moved config to enable access to sidecar logs into a different folder.
```
/kind feature

### CODE REVIEW

**Comment by chitrangpatel** [comment]
@afrittoli this PR addresses your comments in https://github.com/tektoncd/pipeline/pull/5828. I hope I haven't missed anything 😄

**Review by jerop — APPROVED** [review]

**Comment by Yongxuanzhang** [comment]
sorry I don't understand the relationship between PR title Larger Results via Sidecar Logs - Feature flags and the changes. It looks like we mainly remove the installation docs and move config files (roles related config). Why the PR naming is feature flags?

**Comment by chitrangpatel** [comment]
it's trying to address comments that were left after the feature flags PR was merged.I could rename it a bit to reflect that this is a bit of a cleanup to the merged PR.

**Comment by Yongxuanzhang** [comment]
> it's trying to address comments that were left after the feature flags PR was merged.I could rename it a bit to reflect that this is a bit of a cleanup to the merged PR.
I think rename it would be better. 
btw this PR is labeled as feature yet it looks more like a cleanup

**Comment by chitrangpatel** [comment]
> > it's trying to address comments that were left after the feature flags PR was merged.I could rename it a bit to reflect that this is a bit of a cleanup to the merged PR.
> 
> I think rename it would be better. btw this PR is labeled as feature yet it looks more like a cleanup

Done

**Review by Yongxuanzhang — APPROVED** [review]

**Pull request merged**
