### PR TITLE
[TEP074] Remove git-ssh Examples

### PR DESCRIPTION
**Pull request by JeromeJu**
# Changes
This commit removes the git-ssh examples, which are flakey in CI while these are going to be removed along with the 
git resources removal in the upcoming release.
And https://github.com/tektoncd/pipeline/issues/6240 was opened to track for the replacement of the git credential usage.

fixes: https://github.com/tektoncd/pipeline/issues/6228
/kind misc

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [x] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [x] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [n/a] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [n/a] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by pritidesai** [comment]
It could be possible the keys might have expired on 02/24 🤔 I am on board to drop these two tests which started causing outages in our CI and given that the `git` resources are going away but at the same time, @JeromeJu please create an issue to re-introduce such examples (if they don't exists already) either using git resolver or git clone task.

/approve

**Comment by JeromeJu** [comment]
> It could be possible the keys might have expired on 02/24 🤔 I am on board to drop these two tests which started causing outages in our CI and given that the `git` resources are going away but at the same time, @JeromeJu please create an issue to re-introduce such examples (if they don't exists already) either using git resolver or git clone task.
> 
> /approve

Thanks @pritidesai https://github.com/tektoncd/pipeline/issues/6240 is opened to track the replacement of such git-ssh example.

**Comment by Yongxuanzhang** [comment]
/lgtm

Thanks!

**Comment by pritidesai** [comment]
This fixes `main` but the branches CI are still broken with this failure 😭 We should cherry this into the branches `0.41` through `0.45`: 

/cherry-pick releasev0.41.x
/cherry-pick releasev0.42.x
/cherry-pick releasev0.43.x
/cherry-pick releasev0.44.x
/cherry-pick releasev0.45.x

**Comment by pritidesai** [comment]
I am sorry tekton-robot, I misspelled branch name 😞 Please try again:

/cherry-pick release-v0.41.x
/cherry-pick release-v0.42.x
/cherry-pick release-v0.43.x
/cherry-pick release-v0.44.x
/cherry-pick release-v0.45.x

**Comment by pritidesai** [comment]
Let's try cherry picking one branch at a time:

/cherry-pick release-v0.42.x

**Pull request merged**
