### PR TITLE
Refactor version.ValidateEnabledAPIFields to config pkg

### PR DESCRIPTION
**Pull request by JeromeJu**
# Changes
This commit refactors the ValidateEnabledAPIFields function to the config package. The validation previously lived in v1beta1 and it was moved to the version pkg which functions as API version conversion utils rather than for feature versions. This commit moves it to the config pkg since it is actually more tied with featureflags config validation of the `enabled-api-fields` feature flag. 
~~A future work for this might be renaming the filename to stability-level after the implementations of TEP0138 where glossaries have been planned to be updated for the API compatibility policy.~~

/kind misc

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [x] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) if any changes are user facing, including updates to minimum requirements e.g. Kubernetes version bumps
- [x] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [x] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings). See some examples of [good release notes](https://github.com/tektoncd/community/blob/main/standards.md#good-release-notes).
- [x] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
refactor: version.ValidateEnabledAPIFields has been moved to the config package
```

### CODE REVIEW

**Review by pritidesai — APPROVED** [review]
Can I please request renaming this to `featureflags_validation.go` instead of `version_validation.go`. I see this as more of validating configuration specified in `config-feature-flags.yaml`. Thoughts?

**Comment by JeromeJu** [comment]
> Can I please request renaming this to `featureflags_validation.go` instead of `version_validation.go`. I see this as more of validating configuration specified in `config-feature-flags.yaml`. Thoughts?

Thanks Priti!
Done. Makes perfect sense, I was just thinking this might be done later but sounds good to complete in the same step.
Just completed this in this PR and removed "A future work for this might be renaming the filename to stability-level after the implementations of TEP0138 where glossaries have been planned to be updated for the API compatibility policy." from the commit message.

**Review by vdemeester — APPROVED** [review]
So, we don't really have this in our "guidelines", but this will break "go code" consumer, as the package is removed. We could keep the old package, *alias* the function and mark them as deprecated to be removed in a later release, but that's probably fine.

**Comment by JeromeJu** [comment]
> So, we don't really have this in our "guidelines", but this will break "go code" consumer, as the package is removed. We could keep the old package, _alias_ the function and mark them as deprecated to be removed in a later release, but that's probably fine.

Thanks @vdemeester 
That's a solid point given it is a LTS coming up. I've restored it as deprecated and aliased.

Meanwhile I'm double-checking if https://github.com/tektoncd/pipeline/blob/main/docs/developers/api-changes.md is the right place for such guideline updates? I'm happy to add such refactor case if that sounds good.

**Comment by vdemeester** [comment]
> Meanwhile I'm double-checking if https://github.com/tektoncd/pipeline/blob/main/docs/developers/api-changes.md is the right place for such guideline updates? I'm happy to add such refactor case if that sounds good.

Probably *but* maybe we should have one document for Go 🙃

**Review by Yongxuanzhang — COMMENTED** [review]
/lgtm

**Comment by JeromeJu** [comment]
/test pull-tekton-pipeline-beta-integration-tests
flake: image pull issue

**Comment by JeromeJu** [comment]
/retest
ErrImagePull

**Pull request merged**
