### PR TITLE
Promoting `onError` to beta 🎓

### PR DESCRIPTION
**Pull request by pritidesai**
# Changes

Pipeline [0.27](https://github.com/tektoncd/pipeline/releases/tag/v0.27.0) was released in August 2021 which introduced an alpha feature to specify `onError` in a `step`. This feature was implemented in the PR #4106.

To enable this feature, the Tekton Pipeline deployment had to set `enable-api-fields` to `alpha`.

After discussing this in the API WG:
https://docs.google.com/document/d/17PodAxG8hV351fBhSu7Y_OIPhGTVgj6OJ2lPphYYRpU/edit#heading=h.ig94pf1w10xc
I have sent an email out to collect the feedback from the users.  @skaegi is looking forward to this promotion.

Following the promotion [guidelines](https://github.com/tektoncd/community/blob/main/teps/0033-tekton-feature-gates.md#promoting-a-field-from-alpha-to-the-highest-stable-level), this commit includes:
* Updating task validation to no longer require `enable-api-fields` set to `alpha`.
* The documentation is updated to move it out of the alpha [section](https://github.com/tektoncd/pipeline/blob/main/docs/install.md#alpha-features).
* Moved the example `yaml`s out of `alpha`.

/kind feature

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [x] [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [x] [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Release notes block below has been filled in or deleted (only if no user facing changes)

# Release Notes

```release-note
Announcement: onError in a step is now stable and available to include in your task definition without any flag. 
```

### CODE REVIEW

**Comment by bobcatfish** [comment]
Sounds good to me!!

/approve

**Comment by jerop** [comment]
re-lgtming now that tide is unblocked and other prs have merged

/lgtm

**Pull request merged**
