### PR TITLE
[cherry-pick] Fix Workspaces in Sidecar to be serialized as workspaces not Workspaces

### LINKED ISSUE #3964: Sidecar struct field Workspaces has not JSON annotation
# Expected Behavior

Field should be annotated with json:"workspaces,omitempty"

# Actual Behavior

No annotation in source code.

### PR DESCRIPTION
**Pull request by jerop**
# Changes

Workspaces field in Sidecar does not have a JSON annotation, therefore it defaults to pascalcase. This is inconsistent with other fields that are all lowercase. We need to dd the annotations to ensure that json schema generators work correctly. 

This change annotates the Workspaces field in Sidecar with `json:"workspaces,omitempty"`. 

Fixes #3964

(cherry picked from commits 7f2eafa659f12a4e3678dc42b711eccdf35d0b69, 0b8006348e917505cb71fa3186ce524cdb4c3ac4, a9b729b9e83959dbc0f00baeb83b9c8b46780f17)

We need to cherry pick this change into v0.24 to avoid backwards incompatibility and regressed behavior when we release v0.25.

/kind bug

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [ ] [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Release notes block below has been filled in or deleted (only if no user facing changes)

# Release Notes

```release-note
sidecar workspaces field is annotated in lowercase instead of pascalcase
```

### CODE REVIEW

**Review by sbwsg — APPROVED** [review]

**Comment by jerop** [comment]
`ERROR: (gcloud.beta.container.clusters.create) ResponseError: code=400, message=Basic authentication was removed for GKE cluster versions >= 1.19. The cluster cannot be created with basic authentication enabled. Instructions for choosing an alternative authentication method can be found at: https://cloud.google.com/kubernetes-engine/docs/how-to/api-server-authentication.` 

do we need to update auth for testing clusters? cc @afrittoli

**Comment by vdemeester** [comment]
@jerop I think we need to update the plumbing "vendor" files in the branch too 😅

**Comment by jerop** [comment]
> @jerop I think we need to update the plumbing "vendor" files in the branch too 😅

thanks @vdemeester!!

cherry picked the plumbing updates in https://github.com/tektoncd/pipeline/pull/4009

**Pull request closed without merging**
