### PR TITLE
[pkg/reconciler] clean up io/ioutil package

### PR DESCRIPTION
**Pull request by my-git9**
[pkg/reconciler] clean up io/ioutil package
Ref: https://github.com/tektoncd/pipeline/issues/5874

# Release Notes
```release-note
NONE
```

### CODE REVIEW

**Comment by JeromeJu** [comment]
/kind cleanup
/retest
test: TestPipelineRun/fan-in_and_fan-out times out

**Review by lbernick — APPROVED** [review]
thanks @my-git9! could you please add a commit message, and add release note "NONE" to your PR description?

**Comment by vdemeester** [comment]
I think the PR needs a rebase ? 🤔

**Comment by my-git9** [comment]
Updated. Thanks for all

**Review by jerop — COMMENTED** [review]
/lgtm

**Pull request merged**
