### PR TITLE
Update docs for ResourceQuota and QoS

### LINKED ISSUE #4533: How to make a pod to have QoS guaranteed?
### Feature request

I made a `Task`  with specified resources (same requests/limit) and expected the pod would have guaranteed QoS, but as default init-containers injected by Tekton itself like `place-tools`, `step-init` have no resources parameters, the pod had Burstable QoS.

I'd like to have a way to make my Pod guaranteed. I think it may be possible to have such feature using LimitRange but it may be nicer and more intuitive to have the feature in Tekton.

### Use case

We have several tasks which requires high cpu/memory resources. We don't want to make them be killed as it also takes a long time to finish.

### PR DESCRIPTION
**Pull request by lbernick**
# Changes

This commit updates compute resources documentation to reflect how Tekton
currently works with ResourceQuotas and how to achieve different levels of
quality of service for Tekton pods.
Closes #4533.

/kind documentation

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [x] [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- n/a [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Release notes block below has been filled in
(if there are no user facing changes, use release note "NONE")

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by dibyom — APPROVED** [review]

**Comment by abayer** [comment]
@lbernick fyi, `/test all` won't stop kicking off the `pull-tekton-pipeline-kind-*` jobs for another ~40 minutes, when the cronjob updating the Prow config runs.

**Comment by lbernick** [comment]
> fyi, `/test all` won't stop kicking off the `pull-tekton-pipeline-kind-*` jobs for another ~40 minutes, when the cronjob updating the Prow config runs.

ah got it thanks Andrew!

**Pull request merged**
