### PR TITLE
minor consistency fixes

### PR DESCRIPTION
**Pull request by EliZucker**
# Changes
1. Attempt to make bracket usage consistent across testing. To give some background, in [an earlier PR](https://github.com/tektoncd/pipeline/pull/1074), I wrote some validation tests, and kept the additional tests in line with the existing tests in that file. However, I got [feedback](https://github.com/tektoncd/pipeline/pull/1074#discussion_r303121620) that I should collapse the brackets, so I had to change the existing tests in that file as well to match that formatting. I'm not sure if Tekton has decided on that type of styling rule, but IMO it's probably a good idea to keep them consistent so that users aren't forced to either arbitrarily follow one of the existing styles (increasing the project inconsistency), or refactor the entire existing test file themselves.

2. Adjust taskrunpod files to match gofmt results. When runnning gofmt, those 3 files are the only ones that need adjustment. It's interesting that build-tests didn't see that (I assumed it checked linting but I'm probably wrong). It's possible that that it only checks for differences in the generated files or my computer somehow has a different gofmt version.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added) - **No functionality changed**
- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing) **No user facing changes**
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages) 

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

# Release Notes

### CODE REVIEW

**Comment by afrittoli** [comment]
Thanks for this. I think it's a good idea to keep the style consistent; I feel however that unless we enforce it via CI there will more PR like this one needed in the future. 
Is there a way to enforce the test formatting automatically?

**Comment by bobcatfish** [comment]
hahaha take that @dlorenc 😜

**Comment by EliZucker** [comment]
> Thanks for this. I think it's a good idea to keep the style consistent; I feel however that unless we enforce it via CI there will more PR like this one needed in the future.
> Is there a way to enforce the test formatting automatically?

Not sure about the brackets, but I think the tests can be modified to at least verify that gofmt doesn't suggest something different; the logic would be similar to the current codegen enforcement.

**Comment by bobcatfish** [comment]
> Thanks for this. I think it's a good idea to keep the style consistent; I feel however that unless we enforce it via CI there will more PR like this one needed in the future.
> Is there a way to enforce the test formatting automatically?

If someone can find a tool that'll check for this that we can add to our linting then I'm all for it! This feels to me like a minor enough thing that it's not worth putting too much time into tho.

( @EliZucker would probably be worth writing up an issue in our dogfooding epic #267 about making sure we are running `go fmt` !)

/approve
/meow space

**Pull request merged**
