### PR TITLE
Bump github.com/knative/pkg dependency and deps…

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

… and update import path as it is now `knative.dev/pkg` (as all
knative projects)

It has to be done at some point :angel: I'll follow-up with PR in the other tekton repositories :angel: 

Signed-off-by: Vincent Demeester <vdemeest@redhat.com>

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [ ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [ ] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) and [TaskRun](../tekton/publish-run.yaml) to build and release this image

### CODE REVIEW

**Comment by vdemeester** [comment]
Bumped kubernetes to 1.12.9 too
cc @tejal29

**Comment by afrittoli** [comment]
This looks pretty straight forward - thanks for doing it! /lgtm

**Comment by bobcatfish** [comment]
( @afrittoli i think /lgtm has to be on its own line! and also recently it looked like if there was any text following it, e.g. "/lgtm i love cats" it wouldnt work either XD)

/lgtm

**Comment by bobcatfish** [comment]
ruh roh

**Comment by tejal29** [comment]
Thanks a bunch!!!

**Pull request merged**
