### PR TITLE
[Deprecated] PodSecurityPolicy

### PR DESCRIPTION
**Pull request by JeromeJu**
# Changes

This commit removes the deprecated PodSeucrityPolicy and provide a guide moving forward for users.

Fixes: https://github.com/tektoncd/pipeline/issues/4112
/kind bug

TODO:
Apply PSA & OPA that could cover what previously PSP has achieved.

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [x] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [n/a] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [x] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings)
- [x] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
PodSecurityPolicy is deprecated.
```

### CODE REVIEW

**Comment by dibyom** [comment]
> How are we going to test the PSA implementation against PSP?

I'm not sure if I fully understand the question but from reading your doc, it looks like we'd have to use PSA level "privileged" . You also provide the [3 policies](https://github.com/tektoncd/pipeline/pull/5528/files#diff-b0def43104df1bd58421e6db6aeec42dae7eb1d24a1e089d1604c18e2dafb266R57-R65) that one would have to implement using an external policy engine like OPA. I think that's sufficient

**Comment by JeromeJu** [comment]
> > How are we going to test the PSA implementation against PSP?
> 
> I'm not sure if I fully understand the question but from reading your doc, it looks like we'd have to use PSA level "privileged" . You also provide the [3 policies](https://github.com/tektoncd/pipeline/pull/5528/files#diff-b0def43104df1bd58421e6db6aeec42dae7eb1d24a1e089d1604c18e2dafb266R57-R65) that one would have to implement using an external policy engine like OPA. I think that's sufficient

Yes I would like to ask as pointed in the WG, do I need to provide the implementation of a PSA controller as an example, which should be an equivalence of 101-podsecuritypolicy.yaml as we are currently removing from pipeline in this PR?
If that is the case, do we need to have test cases that compares each specification between those two?

**Comment by JeromeJu** [comment]
Goal: When we remove psp, the security specs should be the same for webhooks and controllers service account.

**Pull request closed without merging**
