### PR TITLE
[cherry-pick] Update tektoncd/plumbing.

### PR DESCRIPTION
**Pull request by jerop**
# Changes

This is pulls in tektoncd/plumbing@3c5af40 to fix integration tests.

(cherry picked from commit 55ae8563be29a76bb43b9577c8d6072ae7110d78)

We need to cherry pick this change into v0.24 to run integration tests for a Workspaces in Sidecars fix. We need to fix the Workspaces in Sidecars to be serialized as workspaces not Workspaces. This is change is made in https://github.com/tektoncd/pipeline/pull/4008. Its integration tests are failing because basic authentication was removed for GKE cluster versions >= 1.19 so clusters cannot be created with basic authentication enabled. So we need to cherry pick this change to disable basic auth and create clusters to run the tests for the Workspaces in Sidecars fix.

/kind bug 
# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [x] [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Release notes block below has been filled in or deleted (only if no user facing changes)

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by sbwsg — APPROVED** [review]

**Comment by bobcatfish** [comment]
hey @jerop! tiny pedantic request: could you explain a bit more (ideally in the commit message) about why this is needed and how it fixes things? you linked to https://github.com/tektoncd/plumbing/commit/3c5af40 and the explanation there makes this sound like a cleanup that maybe will in the future be relevant

the commit said:

> Additionally, this feature is going away in GKE 1.19, so we're better off disabling it ASAP in preparation.

so im guessing the situation might be that we are now using 1.19 so this is a problem? or is it something else?

Thanks!! 🙏

**Comment by jerop** [comment]
thanks for the reviews!!

@bobcatfish I've added more detail to the commit messages and PR description

**Comment by vdemeester** [comment]
> hey @jerop! tiny pedantic request: could you explain a bit more (ideally in the commit message) about why this is needed and how it fixes things? you linked to [tektoncd/plumbing@3c5af40](https://github.com/tektoncd/plumbing/commit/3c5af40) and the explanation there makes this sound like a cleanup that maybe will in the future be relevant
> 
> the commit said:
> 
> > Additionally, this feature is going away in GKE 1.19, so we're better off disabling it ASAP in preparation.
> 
> so im guessing the situation might be that we are now using 1.19 so this is a problem? or is it something else?
> 
> Thanks!!

Note that this is also due to the fact that, the version of k8s we use for a given release is not tied to the release (aka if we were to release 0.10 today, we would run against a 1.19, whereas at the time of the release we were using 1.15 or something). 

/lgtm
/meow

**Pull request merged**
