### PR TITLE
updating readme to include 0.26

### PR DESCRIPTION
**Pull request by pritidesai**
# Changes

Updating readme to include 0.26 links

/kind documentation

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [x] [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [ ] [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [x] Release notes block below has been filled in or deleted (only if no user facing changes)

# Release Notes

```release-note
Updating readme to include links to the latest release- 0.26
```

### CODE REVIEW

**Review by jerop — APPROVED** [review]
/test pull-tekton-pipeline-integration-tests

**Review by afrittoli — COMMENTED** [review]
/lgtm

**Pull request merged**
