### PR TITLE
Test `isRunning`

### PR DESCRIPTION
**Pull request by jerop**
# Changes

`isRunning` is an unexported function, so it did not have tests
per the in [guidelines][guidelines]. The recommendation is to not
test unexported function, and if needed to move the function into
a package, test it then export the function. However, this is hard
to do for the resources package because of cyclic dependencies. We
already have tests for another unexported function - `isFailure` -
and discussions to make exceptions for that guideline are ongoing.

In this change, we add tests for `isRunning` to ensure it works
as expected, as we prepare to make changes to the function to support
`Matrix`.

[guidelines]: https://github.com/tektoncd/community/blob/ac0ae1b304ef515e8099f772f42b91aac1b26e6b/standards.md#tests

/kind misc

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [n/a] [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [x] [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including functionality, content, code)
- [x] Release notes block below has been filled in (if there are no user facing changes, use release note "NONE")

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by dibyom — APPROVED** [review]

**Comment by jerop** [comment]
@abayer @dibyom rebased to fix merge conflict, please take a look

**Pull request merged**
