### PR TITLE
Skip sidecar deletion logic for canceled or timed-out TaskRun

### PR DESCRIPTION
**Pull request by SaschaSchwarze0**
# Changes

While a TaskRun timed out, I noticed some errors in Tekton's controller log:

```
{"level":"info","ts":"2021-04-13T09:37:55.166Z","logger":"tekton-pipelines-controller","caller":"controller/controller.go:530","msg":"Reconcile succeeded","commit":"5dc24d2","knative.dev/controller":"github.com.tektoncd.pipeline.pkg.reconciler.taskrun.Reconciler","knative.dev/kind":"tekton.dev.TaskRun","knative.dev/traceid":"abf578f1-be99-4b31-88dd-92394dfafa90","knative.dev/key":"build-test/sascha-dev-zsmk6-kppc8","duration":0.0070604}
{"level":"warn","ts":"2021-04-13T09:38:07.000Z","logger":"tekton-pipelines-controller","caller":"taskrun/taskrun.go:563","msg":"stopping task run \"sascha-dev-zsmk6-kppc8\" because of \"TaskRunTimeout\"","commit":"5dc24d2","knative.dev/controller":"github.com.tektoncd.pipeline.pkg.reconciler.taskrun.Reconciler","knative.dev/kind":"tekton.dev.TaskRun","knative.dev/traceid":"40a1100e-ecab-49f7-8ac9-4a783851d790","knative.dev/key":"build-test/sascha-dev-zsmk6-kppc8"}
{"level":"info","ts":"2021-04-13T09:38:07.009Z","logger":"tekton-pipelines-controller.event-broadcaster","caller":"record/event.go:282","msg":"Event(v1.ObjectReference{Kind:\"TaskRun\", Namespace:\"build-test\", Name:\"sascha-dev-zsmk6-kppc8\", UID:\"922dfc0c-770f-4b91-b5d6-6f917fce7110\", APIVersion:\"tekton.dev/v1beta1\", ResourceVersion:\"4090\", FieldPath:\"\"}): type: 'Warning' reason: 'Failed' TaskRun \"sascha-dev-zsmk6-kppc8\" failed to finish within \"15s\"","commit":"5dc24d2"}
{"level":"info","ts":"2021-04-13T09:38:07.061Z","logger":"tekton-pipelines-controller","caller":"controller/controller.go:530","msg":"Reconcile succeeded","commit":"5dc24d2","knative.dev/controller":"github.com.tektoncd.pipeline.pkg.reconciler.taskrun.Reconciler","knative.dev/kind":"tekton.dev.TaskRun","knative.dev/traceid":"40a1100e-ecab-49f7-8ac9-4a783851d790","knative.dev/key":"build-test/sascha-dev-zsmk6-kppc8","duration":0.0611236}
{"level":"warn","ts":"2021-04-13T09:38:07.061Z","logger":"tekton-pipelines-controller","caller":"taskrun/taskrun.go:563","msg":"stopping task run \"sascha-dev-zsmk6-kppc8\" because of \"TaskRunTimeout\"","commit":"5dc24d2","knative.dev/controller":"github.com.tektoncd.pipeline.pkg.reconciler.taskrun.Reconciler","knative.dev/kind":"tekton.dev.TaskRun","knative.dev/traceid":"28550396-ba40-4108-bcf0-00da57dd2e59","knative.dev/key":"build-test/sascha-dev-zsmk6-kppc8"}
{"level":"info","ts":"2021-04-13T09:38:07.068Z","logger":"tekton-pipelines-controller","caller":"controller/controller.go:530","msg":"Reconcile succeeded","commit":"5dc24d2","knative.dev/controller":"github.com.tektoncd.pipeline.pkg.reconciler.pipelinerun.Reconciler","knative.dev/kind":"tekton.dev.PipelineRun","knative.dev/traceid":"69852f31-53cb-4756-b64d-d5597b6205f4","knative.dev/key":"build-test/sascha-dev-zsmk6","duration":0.0000779}
{"level":"info","ts":"2021-04-13T09:38:07.238Z","logger":"tekton-pipelines-controller.event-broadcaster","caller":"record/event.go:282","msg":"Event(v1.ObjectReference{Kind:\"TaskRun\", Namespace:\"build-test\", Name:\"sascha-dev-zsmk6-kppc8\", UID:\"922dfc0c-770f-4b91-b5d6-6f917fce7110\", APIVersion:\"tekton.dev/v1beta1\", ResourceVersion:\"4090\", FieldPath:\"\"}): type: 'Warning' reason: 'Failed' TaskRun \"sascha-dev-zsmk6-kppc8\" failed to finish within \"15s\"","commit":"5dc24d2"}
{"level":"info","ts":"2021-04-13T09:38:07.347Z","logger":"tekton-pipelines-controller","caller":"controller/controller.go:530","msg":"Reconcile succeeded","commit":"5dc24d2","knative.dev/controller":"github.com.tektoncd.pipeline.pkg.reconciler.taskrun.Reconciler","knative.dev/kind":"tekton.dev.TaskRun","knative.dev/traceid":"28550396-ba40-4108-bcf0-00da57dd2e59","knative.dev/key":"build-test/sascha-dev-zsmk6-kppc8","duration":0.2856071}
{"level":"info","ts":"2021-04-13T09:38:07.347Z","logger":"tekton-pipelines-controller","caller":"taskrun/taskrun.go:114","msg":"taskrun done : sascha-dev-zsmk6-kppc8 \n","commit":"5dc24d2","knative.dev/controller":"github.com.tektoncd.pipeline.pkg.reconciler.taskrun.Reconciler","knative.dev/kind":"tekton.dev.TaskRun","knative.dev/traceid":"844e896c-fd6f-4538-9451-7169ed78d2f0","knative.dev/key":"build-test/sascha-dev-zsmk6-kppc8"}
{"level":"info","ts":"2021-04-13T09:38:07.354Z","logger":"tekton-pipelines-controller","caller":"controller/controller.go:530","msg":"Reconcile succeeded","commit":"5dc24d2","knative.dev/controller":"github.com.tektoncd.pipeline.pkg.reconciler.taskrun.Reconciler","knative.dev/kind":"tekton.dev.TaskRun","knative.dev/traceid":"844e896c-fd6f-4538-9451-7169ed78d2f0","knative.dev/key":"build-test/sascha-dev-zsmk6-kppc8","duration":0.0065659}
{"level":"info","ts":"2021-04-13T09:38:10.395Z","logger":"tekton-pipelines-controller","caller":"taskrun/taskrun.go:114","msg":"taskrun done : sascha-dev-zsmk6-kppc8 \n","commit":"5dc24d2","knative.dev/controller":"github.com.tektoncd.pipeline.pkg.reconciler.taskrun.Reconciler","knative.dev/kind":"tekton.dev.TaskRun","knative.dev/traceid":"7b58afe1-4af6-4e22-a358-f3bc6ee4734f","knative.dev/key":"build-test/sascha-dev-zsmk6-kppc8"}
{"level":"error","ts":"2021-04-13T09:38:10.418Z","logger":"tekton-pipelines-controller","caller":"taskrun/reconciler.go:291","msg":"Returned an error","commit":"5dc24d2","knative.dev/controller":"github.com.tektoncd.pipeline.pkg.reconciler.taskrun.Reconciler","knative.dev/kind":"tekton.dev.TaskRun","knative.dev/traceid":"7b58afe1-4af6-4e22-a358-f3bc6ee4734f","knative.dev/key":"build-test/sascha-dev-zsmk6-kppc8","targetMethod":"ReconcileKind","error":"pods \"sascha-dev-zsmk6-kppc8-pod-xhmhr\" not found","stacktrace":"github.com/tektoncd/pipeline/pkg/client/injection/reconciler/pipeline/v1beta1/taskrun.(*reconcilerImpl).Reconcile\n\tgithub.com/tektoncd/pipeline/pkg/client/injection/reconciler/pipeline/v1beta1/taskrun/reconciler.go:291\nknative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tknative.dev/pkg@v0.0.0-20210127163530-0d31134d5f4e/controller/controller.go:522\nknative.dev/pkg/controller.(*Impl).RunContext.func3\n\tknative.dev/pkg@v0.0.0-20210127163530-0d31134d5f4e/controller/controller.go:460"}
{"level":"error","ts":"2021-04-13T09:38:10.418Z","logger":"tekton-pipelines-controller","caller":"controller/controller.go:540","msg":"Reconcile error","commit":"5dc24d2","knative.dev/controller":"github.com.tektoncd.pipeline.pkg.reconciler.taskrun.Reconciler","knative.dev/kind":"tekton.dev.TaskRun","duration":0.0234892,"error":"pods \"sascha-dev-zsmk6-kppc8-pod-xhmhr\" not found","stacktrace":"knative.dev/pkg/controller.(*Impl).handleErr\n\tknative.dev/pkg@v0.0.0-20210127163530-0d31134d5f4e/controller/controller.go:540\nknative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tknative.dev/pkg@v0.0.0-20210127163530-0d31134d5f4e/controller/controller.go:523\nknative.dev/pkg/controller.(*Impl).RunContext.func3\n\tknative.dev/pkg@v0.0.0-20210127163530-0d31134d5f4e/controller/controller.go:460"}
{"level":"info","ts":"2021-04-13T09:38:10.418Z","logger":"tekton-pipelines-controller","caller":"taskrun/taskrun.go:114","msg":"taskrun done : sascha-dev-zsmk6-kppc8 \n","commit":"5dc24d2","knative.dev/controller":"github.com.tektoncd.pipeline.pkg.reconciler.taskrun.Reconciler","knative.dev/kind":"tekton.dev.TaskRun","knative.dev/traceid":"b0558064-a16c-4279-9e45-091e91d81ffe","knative.dev/key":"build-test/sascha-dev-zsmk6-kppc8"}
{"level":"info","ts":"2021-04-13T09:38:10.419Z","logger":"tekton-pipelines-controller.event-broadcaster","caller":"record/event.go:282","msg":"Event(v1.ObjectReference{Kind:\"TaskRun\", Namespace:\"build-test\", Name:\"sascha-dev-zsmk6-kppc8\", UID:\"922dfc0c-770f-4b91-b5d6-6f917fce7110\", APIVersion:\"tekton.dev/v1beta1\", ResourceVersion:\"4175\", FieldPath:\"\"}): type: 'Warning' reason: 'InternalError' pods \"sascha-dev-zsmk6-kppc8-pod-xhmhr\" not found","commit":"5dc24d2"}
{"level":"error","ts":"2021-04-13T09:38:10.430Z","logger":"tekton-pipelines-controller","caller":"taskrun/reconciler.go:291","msg":"Returned an error","commit":"5dc24d2","knative.dev/controller":"github.com.tektoncd.pipeline.pkg.reconciler.taskrun.Reconciler","knative.dev/kind":"tekton.dev.TaskRun","knative.dev/traceid":"b0558064-a16c-4279-9e45-091e91d81ffe","knative.dev/key":"build-test/sascha-dev-zsmk6-kppc8","targetMethod":"ReconcileKind","error":"pods \"sascha-dev-zsmk6-kppc8-pod-xhmhr\" not found","stacktrace":"github.com/tektoncd/pipeline/pkg/client/injection/reconciler/pipeline/v1beta1/taskrun.(*reconcilerImpl).Reconcile\n\tgithub.com/tektoncd/pipeline/pkg/client/injection/reconciler/pipeline/v1beta1/taskrun/reconciler.go:291\nknative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tknative.dev/pkg@v0.0.0-20210127163530-0d31134d5f4e/controller/controller.go:522\nknative.dev/pkg/controller.(*Impl).RunContext.func3\n\tknative.dev/pkg@v0.0.0-20210127163530-0d31134d5f4e/controller/controller.go:460"}
{"level":"error","ts":"2021-04-13T09:38:10.430Z","logger":"tekton-pipelines-controller","caller":"controller/controller.go:540","msg":"Reconcile error","commit":"5dc24d2","knative.dev/controller":"github.com.tektoncd.pipeline.pkg.reconciler.taskrun.Reconciler","knative.dev/kind":"tekton.dev.TaskRun","duration":0.0120727,"error":"pods \"sascha-dev-zsmk6-kppc8-pod-xhmhr\" not found","stacktrace":"knative.dev/pkg/controller.(*Impl).handleErr\n\tknative.dev/pkg@v0.0.0-20210127163530-0d31134d5f4e/controller/controller.go:540\nknative.dev/pkg/controller.(*Impl).processNextWorkItem\n\tknative.dev/pkg@v0.0.0-20210127163530-0d31134d5f4e/controller/controller.go:523\nknative.dev/pkg/controller.(*Impl).RunContext.func3\n\tknative.dev/pkg@v0.0.0-20210127163530-0d31134d5f4e/controller/controller.go:460"}
{"level":"info","ts":"2021-04-13T09:38:10.430Z","logger":"tekton-pipelines-controller.event-broadcaster","caller":"record/event.go:282","msg":"Event(v1.ObjectReference{Kind:\"TaskRun\", Namespace:\"build-test\", Name:\"sascha-dev-zsmk6-kppc8\", UID:\"922dfc0c-770f-4b91-b5d6-6f917fce7110\", APIVersion:\"tekton.dev/v1beta1\", ResourceVersion:\"4175\", FieldPath:\"\"}): type: 'Warning' reason: 'InternalError' pods \"sascha-dev-zsmk6-kppc8-pod-xhmhr\" not found","commit":"5dc24d2"} 
```

They complain a non-existing pod which is reasonable as a timed out TaskRun deletes the pod. The code is inside the `stopSidecars` function that imo should not try to stop a sidecar from a pod that was deleted. I am therefore extending the logic inside that function to not do something if the TaskRun is canceled or timed out.

/kind bug

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [X] [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [X] [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [X] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [X] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [X] Release notes block below has been filled in or deleted (only if no user facing changes)

# Release Notes

```release-note
Do not run sidecar deletion logic for canceled or timed-out taskrun where pod was deleted
```

### CODE REVIEW

**Comment by sbwsg** [comment]
Interesting!  Thanks for this.  I guess this must be racing because the sidecar stopping code does check if the Pod is NotFound before continuing.

/approve

**Comment by pritidesai** [comment]
> The code is inside the stopSidecars function that imo should not try to stop a sidecar from a pod that was deleted. I am therefore extending the logic inside that function to not do something if the TaskRun is canceled or timed out.

Does the sidecar exist at this point? If we extend the logic to not attempt to delete, how will the sidecar be deleted before ending the run?

**Comment by SaschaSchwarze0** [comment]
> > The code is inside the stopSidecars function that imo should not try to stop a sidecar from a pod that was deleted. I am therefore extending the logic inside that function to not do something if the TaskRun is canceled or timed out.
> 
> Does the sidecar exist at this point? If we extend the logic to not attempt to delete, how will the sidecar be deleted before ending the run?

Sidecars are containers that run in the same pod. The pod is deleted, so is the sidecar.

**Comment by pritidesai** [comment]
> Sidecars are containers that run in the same pod. The pod is deleted, so is the sidecar.

Yup, my bad, for some reason I interpreted side car running as a separate Pod 🙃 , thanks for the clarification @SaschaSchwarze0 👍 

so in case of cancellation and timeout, we do delete the pod so adding these checks here are reasonable and help avoid unwanted error message.

/lgtm

**Comment by sbwsg** [comment]
You'll need to rebase on top of `main` to get the integration tests passing.

1. `git fetch upstream`
2. `git rebase upstream/main`
3. `git push --force <your remote> <branch name>`

**Comment by SaschaSchwarze0** [comment]
> 
> 
> You'll need to rebase on top of `main` to get the integration tests passing.
> 
>     1. `git fetch upstream`
> 
>     2. `git rebase upstream/main`
> 
>     3. `git push --force <your remote> <branch name>`

Done @sbwsg

**Comment by sbwsg** [comment]
Awesome, thank you!  Re-adding Priti's lgtm as there haven't been any other code changes:

/lgtm

**Pull request merged**
