### PR TITLE
migrate yaml package to sigs.k8s.io/yaml

### PR DESCRIPTION
**Pull request by timonwong**
# Changes

Update `github.com/ghodss/yaml` package to its permanent fork `sigs.k8s.io/yaml`, since the former releasing any new version for a long time, on the other hand, the latter is still under active development (fix CVEs, etc).

Besides, `default-pod-template` and `default-affinity-assistant-pod-template` in `config-defaults` are now deserialized using `UnmarshalStrict` first, print a warning message, and try again with `Unmarshal`, in order to keep the compatibility.

/kind misc

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [x] [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) included if any changes are user facing
- [X] [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [X] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [X] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including
  functionality, content, code)
- [X] Release notes block below has been filled in
(if there are no user facing changes, use release note "NONE")

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Comment by timonwong** [comment]
Since `UnmarshalStrict()` may introduce incompatibility, should we keep using `Unmarshal` instead?

**Comment by vdemeester** [comment]
> Since `UnmarshalStrict()` may introduce incompatibility, should we keep using `Unmarshal` instead?

That's a good point and I think we should indeed, but maybe with a plan (and communication) to move to `UnmarshalStrict()` (with warnings of what types of incompatibility it would bring, and when *according to plan*).

**Comment by timonwong** [comment]
> That's a good point and I think we should indeed, but maybe with a plan (and communication) to move to `UnmarshalStrict()` (with warnings of what types of incompatibility it would bring, and when _according to plan_).

Now the old behavior is preserved. (with a warning message)

**Review by vdemeester — APPROVED** [review]

**Comment by vdemeester** [comment]
I think the error comes from `pkg/reconciler/pipelinerun/pipelinerun_updatestatus_test.go` that still calls `github.com/ghodss/yaml` 😅 
@timonwong if you don't have time to fix it, I can fix it in the PR 😉

**Comment by timonwong** [comment]
> I think the error comes from `pkg/reconciler/pipelinerun/pipelinerun_updatestatus_test.go` that still calls `github.com/ghodss/yaml` 😅
> @timonwong if you don't have time to fix it, I can fix it in the PR 😉

@vdemeester thanks, I've submitted a new commit which address that :)

**Comment by vdemeester** [comment]
/hold
@timonwong can you squash your commits ? 
(Also, the UI is telling "cannot be rebased due to conflicts)

**Comment by abayer** [comment]
/retest

One of the sidecar tests flaking, yet again,.

**Comment by vdemeester** [comment]
Thanks @timonwong 🎉

**Pull request merged**
