### PR TITLE
Add @Yongxuanzhang as a pipelines maintainer

### PR DESCRIPTION
**Pull request by dibyom**
# Changes

@Yongxuanzhang has been a consistent contributor to pipelines for a long time now and has worked on a number of big features such as trusted resources and array parameters. He has also reviewed 130+ PRs and meets all the other criteria for being a maintainer.

Reviews: https://github.com/search?q=-author%3Ayongxuanzhang+repo%3Atektoncd%2Fpipeline+reviewed-by%3Ayongxuanzhang+type%3Apr&type=pullrequests

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [x] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) if any changes are user facing, including updates to minimum requirements e.g. Kubernetes version bumps
- [x] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [x] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings). See some examples of [good release notes](https://github.com/tektoncd/community/blob/main/standards.md#good-release-notes).
- [x] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by vdemeester — APPROVED** [review]
🎉 🎉 🎉

**Review by jerop — APPROVED** [review]
/meow

**Comment by pritidesai** [comment]
Thank you @Yongxuanzhang for all your hard work and very excited to have you join the maintainer squad 🎉

**Review by pritidesai — APPROVED** [review]

**Comment by Yongxuanzhang** [comment]
Thank you all!! ❤️

**Comment by chuangw6** [comment]
/lgtm

Thank you @Yongxuanzhang for all your contributions!!!

**Pull request merged**
