### PR TITLE
Clean up non-functional CloudEvents Metrics in Reconciler for Deprecated CloudEvents

### PR DESCRIPTION
**Pull request by JeromeJu**
# Changes
This commit cleans up the CloudEvents Metrics which are no longer functional with the removal of CloudEvents PipelineResources, and also the CloudEvents field of the TaskRun Status API is also deprecated and not moved to v1.

/kind cleanup
fixes: https://github.com/tektoncd/pipeline/issues/6826

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [ ] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) if any changes are user facing, including updates to minimum requirements e.g. Kubernetes version bumps
- [ ] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [ ] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [ ] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including functionality, content, code)
- [ ] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [ ] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings). See some examples of [good release notes](https://github.com/tektoncd/community/blob/main/standards.md#good-release-notes).
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by dibyom — APPROVED** [review]

**Comment by lbernick** [comment]
/lgtm

I think we could also remove some of the unused cloudevents code: https://github.com/tektoncd/pipeline/blob/f0f5646fffccbcdb836363105b636b294fd51a65/pkg/reconciler/events/cloudevent/cloud_event_controller.go#L38-L52

**Comment by JeromeJu** [comment]
> /lgtm
> 
> I think we could also remove some of the unused cloudevents code:
> 
> https://github.com/tektoncd/pipeline/blob/f0f5646fffccbcdb836363105b636b294fd51a65/pkg/reconciler/events/cloudevent/cloud_event_controller.go#L38-L52

Agreed! as put at https://github.com/tektoncd/pipeline/issues/6826#issuecomment-1591578643, this current PR is opened to unblock v1 swap and as pointed these could also be removed in a followup PR.

**Comment by JeromeJu** [comment]
/retest
test: TestExamples/v1/taskruns/steptemplate-env-merge with 
`Could not get logs for pod steptemplate-env-merge-756np-pod: container "step-foo" in pod "steptemplate-env-merge-756np-pod" is waiting to start: image can't be pulled`

**Comment by dibyom** [comment]
>      message: 'The step "unnamed-0" in TaskRun "retry-example-lqdlp-hello-world" failed
              to pull the image "". The pod errored with the message: "Back-off pulling image
              "busybox"."'

**Comment by JeromeJu** [comment]
/test pull-tekton-pipeline-alpha-integration-tests
potential flake: TestExamples/v1/pipelineruns/using-retries-and-retry-count-variables, reached retries count limit which should not be related to the current chagnes.

**Pull request merged**
