### PR TITLE
Make sure all alpine packages are updated to their latest versions.

### PR DESCRIPTION
**Pull request by othomann**
# Changes

Make sure all alpine packages are updated to their latest versions.

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [n/a ] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [n/a] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [n/a] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) to build and release this image.

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md) are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes) must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS) and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes) must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS), and they must first be added [in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

# Release Notes

```
Future releases won't include vulnerabilities fixed in the alpine packages but not yet built into the alpine:latest docker image.
```

### CODE REVIEW

**Comment by bobcatfish** [comment]
To expand on @vdemeester 's request, a few more things:

- Usually the title of the PullRequest will describe the change, e.g. in this case maybe "Make sure all alpine packages are updated to their latest versions."
- These are the commit message guidelines, as he mentioned the commit message should be descriptive: https://github.com/tektoncd/community/blob/master/standards.md#commit-messages
- The "release notes" section is intended for you to fill in with anything that is relevant in future releases - in this case you might say something about how future releases won't include such and such vulnerabilities

**Comment by othomann** [comment]
@vdemeester I added a new line at the end of the Dockerfile. I cannot explain why the integration tests are failing with only this change.

**Comment by vdemeester** [comment]
@othomann might be flakyness :sweat:

**Comment by othomann** [comment]
the lgtm flag has been removed because of my latest change (addition of an empty line at the end of the Dockerfile).

**Comment by othomann** [comment]
@vdemeester all tests are green now.

**Comment by othomann** [comment]
Not sure why the pipeline build tests now reports:
```
I0109 19:19:45.108] ===============================
I0109 19:20:32.325] pkg/client/resource/informers/externalversions/generic.go:54:2: singleCaseSwitch: should rewrite switch statement to if statement (gocritic)
I0109 19:20:32.326] 	switch resource {
I0109 19:20:32.326] 	^
I0109 19:20:32.429] ============================
```

**Pull request merged**
