### PR TITLE
[master] Auto-update dependencies

### PR DESCRIPTION
**Pull request by mattmoor**
Produced via:
  `./hack/update-deps.sh --upgrade && ./hack/update-codegen.sh`
/assign ImJasonH vdemeester
/cc ImJasonH vdemeester

### CODE REVIEW

**Comment by mattmoor** [comment]
Ignore this.  I need to add `vendor/modules.txt` to the list of files to ignore when considering whether a PR has any meaningful changes.

This is up, though, so as you want to start floating deps forward tweak `./hack/update-deps.sh`.  We plan to freeze `release-0.14` of knative/pkg today.

cc @vdemeester

**Comment by vdemeester** [comment]
@mattmoor also, it should add the diff in `vendor` :angel: I wasn't sure if that was the case or not :stuck_out_tongue:

**Comment by mattmoor** [comment]
@vdemeester Right, but there are times when only `go.mod` changes because of `replace` rules, which wouldn't touch vendor.

**Comment by vdemeester** [comment]
ah :sweat_smile:

**Pull request closed without merging**
