### PR TITLE
Remove deprecated fields from PipelineResourceResult 🍠

### PR DESCRIPTION
**Pull request by vdemeester**
# Changes

The `Name` and `Digest` field have been deprecated in a previous
release. This removes the fields from the struct. See
https://github.com/tektoncd/pipeline/issues/1392 for the inital issue.

It also reduce code duplication by aliasing some types between
v1alpha1 and v1alpha2.

Signed-off-by: Vincent Demeester <vdemeest@redhat.com>

/cc @bobcatfish @othomann @dlorenc @sbwsg 

# Submitter Checklist

These are the criteria that every PR should meet, please check them off as you
review them:

- [x] Includes [tests](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if functionality changed/added)
- [x] Includes [docs](https://github.com/tektoncd/community/blob/master/standards.md#principles) (if user facing)
- [x] Commit messages follow [commit message best practices](https://github.com/tektoncd/community/blob/master/standards.md#commit-messages)

_See [the contribution guide](https://github.com/tektoncd/pipeline/blob/master/CONTRIBUTING.md) for more details._

Double check this list of stuff that's easy to miss:

- If you are adding [a new binary/image to the `cmd` dir](../cmd), please update
  [the release Task](../tekton/publish.yaml) to build and release this image.

## Reviewer Notes

If [API changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md) are included, [additive changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#additive-changes) must be approved by at least two [OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS) and [backwards incompatible changes](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-incompatible-changes) must be approved by [more than 50% of the OWNERS](https://github.com/tektoncd/pipeline/blob/master/OWNERS), and they must first be added [in a backwards compatible way](https://github.com/tektoncd/pipeline/blob/master/api_compatibility_policy.md#backwards-compatible-changes-first).

# Release Notes

```
Remove Name and Digest deprecated fields from PipelineResourceResult
```

### CODE REVIEW

**Comment by bobcatfish** [comment]
```
I0206 17:34:58.721] 2020/02/06 17:34:58 main.go:734: provider gke, will acquire project type gke-project from boskos
I0206 17:39:58.721] 2020/02/06 17:39:58 main.go:316: Something went wrong: failed to prepare test environment: --provider=gke boskos failed to acquire project: resources not found
I0206 17:39:58.730] Test subprocess exited with code 0
```

uh oh

it's like boskos knows im build cop

**Comment by bobcatfish** [comment]
/test pull-tekton-pipeline-integration-tests
--

**Comment by bobcatfish** [comment]
phew it's just flakey.... "Just" 😅

**Comment by vdemeester** [comment]
/test pull-tekton-pipeline-integration-tests

two flakes in a row :thinking: :sweat:

**Comment by afrittoli** [comment]
According to the review notes, this must be approved by 50% of the owners, so here's my 
/lgtm 
Thanks for fixing this!

**Pull request merged**
