### PR TITLE
[TEP-0094] Promote taskrun.spec's stepSpecs and sidecarSpecs to beta

### PR DESCRIPTION
**Pull request by khrm**
Configuring of stepSpecs and sideCarSpecs was introduced in v0.34.0. This is a crucial feature required by our customers when running Pipelines at large scale. This promotes TEP-0094 to beta such that these features can be used by the task authors and pipeline authors in a cluster when enable-api-fields is either set to beta or alpha.

# Changes

# Submitter Checklist

As the author of this PR, please check off the items in this checklist:

- [x] Has [Docs](https://github.com/tektoncd/community/blob/main/standards.md#docs) if any changes are user facing, including updates to minimum requirements e.g. Kubernetes version bumps
- [x] Has [Tests](https://github.com/tektoncd/community/blob/main/standards.md#tests) included if any functionality added or changed
- [ ] [pre-commit](https://github.com/tektoncd/pipeline/blob/main/DEVELOPMENT.md#install-tools) Passed
- [x] Follows the [commit message standard](https://github.com/tektoncd/community/blob/main/standards.md#commits)
- [x] Meets the [Tekton contributor standards](https://github.com/tektoncd/community/blob/main/standards.md) (including functionality, content, code)
- [x] Has a kind label. You can add one by adding a comment on this PR that contains `/kind <type>`. Valid types are bug, cleanup, design, documentation, feature, flake, misc, question, tep
- [ ] Release notes block below has been updated with any user facing changes (API changes, bug fixes, changes requiring upgrade notices or deprecation warnings). See some examples of [good release notes](https://github.com/tektoncd/community/blob/main/standards.md#good-release-notes).
- [ ] Release notes contains the string "action required" if the change requires additional action from users switching to the new release

# Release Notes

```release-note
NONE
```

### CODE REVIEW

**Review by khrm — COMMENTED** [review]
/kind feature

**Review by vdemeester — APPROVED** [review]

**Comment by vdemeester** [comment]
@khrm needs a rebase 🙏🏼 
@afrittoli @chitrangpatel can you take a look ?

**Comment by khrm** [comment]
I have rebased this PR. Somehow tide is still saying can't be rebased.

**Comment by khrm** [comment]
I have finished testing this.
/hold cancel

**Comment by khrm** [comment]
This can be verified using this manifest:

```
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: side-step
spec:
  steps:
    - name: test
      image: docker.io//alpine:latest
  sidecars:
    - name: side
      image: docker.io/linuxcontainers/alpine:latest
---
apiVersion: tekton.dev/v1
kind: TaskRun
metadata:
  name: test-sidestep
spec:
  taskRef:
    name: side-step
  stepSpecs:
    - name: test
      computeResources:
        requests:
          memory: 1Gi
  sidecarSpecs:
    - name: side
      computeResources:
        requests:
          cpu: 100m
        limits:
          cpu: 500m
```

**Review by chitrangpatel — APPROVED** [review]

**Review by chitrangpatel — APPROVED** [review]

**Review by afrittoli — COMMENTED** [review]
Thank you @khrm 
/lgtm

**Pull request merged**
